### ISSUE TITLE
low priority | command "/plot generatebiome help" generates a biome when "help" isn't an actual biome

### ISSUE THREAD

**Issue by Dad3** [IntellectualSites/FastAsyncWorldEdit#107]
# Bug report template 

**Debug paste link:** 

**Description of the problem:** 
/plot generatebiome help 
generates a biome but "help" is not an actual biome, very wierd 

**How to replicate:** 

stand on plot and type /plot generatebiome help 
**Checklist**:

- [-] I included a `/plot debugpaste` link
not working for some reason 
`[22:29:14 WARN]: java.io.IOException: Server returned HTTP response code: 503 for URL: https://hastebin.com/documents
[22:29:14 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
[22:29:14 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
[22:29:14 WARN]:        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
[22:29:14 WARN]:        at com.intellectualcrafters.plot.util.HastebinUtility.upload(HastebinUtility.java:30)
[22:29:14 WARN]:        at com.intellectualcrafters.plot.util.HastebinUtility.upload(HastebinUtility.java:60)
[22:29:14 WARN]:        at com.intellectualcrafters.plot.commands.DebugPaste$1.run(DebugPaste.java:29)
[22:29:14 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63)
[22:29:14 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[22:29:14 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[22:29:14 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[22:29:14 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[22:29:14 WARN]:        at java.lang.Thread.run(Unknown Source)`
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by MattBDev** [comment]
Moved to appropriate project since it is implemented by FAWE

**Comment by MattBDev** [comment]
I believe the issue still occurs in 1.13 otherwise, please close.

**Comment by aurorasmiles** [comment]
Wasn't able to replicate this issue anymore, so assuming this is fixed
