### ISSUE TITLE
InaccessibleObjectException on player leave

### ISSUE THREAD

**Issue by greysilly7** [IntellectualSites/FastAsyncWorldEdit#1076]
### Server Implementation

Tuinity

### Server Version

1.16.5

### Describe the bug

Gives an ``InaccessibleObjectException`` on player leave

### To Reproduce

Join and leave with latest 9aa25ce

### Expected behaviour

No error

### Error log (if applicable)

[17:05:18] [Server thread/INFO]: Chibisuke lost connection: Tiempo de espera para inicio de sesiÃ³n excedido [17:05:18] [Server thread/WARN]: java.lang.reflect.InaccessibleObjectException: Unable to make field java.lang.ThreadLocal$ThreadLocalMap java.lang.Thread.threadLocals accessible: module java.base does not "opens java.lang" to unnamed module @3420af52 [17:05:18] [Server thread/WARN]: 	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357) [17:05:18] [Server thread/WARN]: 	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297) [17:05:18] [Server thread/WARN]: 	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:177) [17:05:18] [Server thread/WARN]: 	at java.base/java.lang.reflect.Field.setAccessible(Field.java:171) [17:05:18] [Server thread/WARN]: 	at com.boydti.fawe.object.collection.CleanableThreadLocal.iterate(CleanableThreadLocal.java:94) [17:05:18] [Server thread/WARN]: 	at com.boydti.fawe.object.collection.CleanableThreadLocal.getAll(CleanableThreadLocal.java:61) [17:05:18] [Server thread/WARN]: 	at com.sk89q.worldedit.session.request.Request.getAll(Request.java:55) [17:05:18] [Server thread/WARN]: 	at com.sk89q.worldedit.extension.platform.Actor.cancel(Actor.java:235) [17:05:18] [Server thread/WARN]: 	at com.sk89q.worldedit.entity.Player.unregister(Player.java:403) [17:05:18] [Server thread/WARN]: 	at com.sk89q.worldedit.bukkit.BukkitPlayer.unregister(BukkitPlayer.java:417) [17:05:18] [Server thread/WARN]: 	at com.boydti.fawe.bukkit.FaweBukkit.onPlayerQuit(FaweBukkit.java:267) [17:05:18] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor514.execute(Unknown Source) [17:05:18] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) [17:05:18] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) [17:05:18] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) [17:05:18] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:623) [17:05:18] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerList.disconnect(PlayerList.java:605) [17:05:18] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1981) [17:05:18] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnection.disconnect(PlayerConnection.java:483) [17:05:18] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnection.disconnect(PlayerConnection.java:450) [17:05:18] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.entity.CraftPlayer.kickPlayer(CraftPlayer.java:503) [17:05:18] [Server thread/WARN]: 	at fr.xephi.authme.task.TimeoutTask.run(TimeoutTask.java:31) [17:05:18] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) [17:05:18] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:469) [17:05:18] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1539) [17:05:18] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:429) [17:05:18] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1446) [17:05:18] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1147) [17:05:18] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:286) [17:05:18] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831) [17:05:18] [Server thread/INFO]: Chibisuke left the game

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/ee8bd11234df49f1901afd34c7838211

### Fawe Version

FastAsyncWorldEdit-Bukkit-1.16-9aa25ce

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.16/ and the issue still persists.

### Anything else?

I built the jar myself, also I am useing an unsupported server jar its called ``hyalus`` . I put tunity cause I also tested on it and got same error

**Comment by NotMyFault** [comment]
If your platform is not listed, it is not supported. Don't tick something else.

**Comment by greysilly7** [comment]
> If your platform is not listed, it is not supported. Don't tick something else.

I said I tested on tunity and got same thing

**Comment by NotMyFault** [comment]
> @NotMyFault I said I tested on tunity and got same thing

Then provide the information requested on the platform using rather on something else.

**Comment by greysilly7** [comment]
ok I will get the error but on tunity, using same flags and everythign, let me just start my tunity test server up again

**Comment by NotMyFault** [comment]
Anyway, duplicate of https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/396

**Comment by greysilly7** [comment]
ok
