### ISSUE TITLE
Error on startup?

### ISSUE THREAD

**Issue by greysilly7** [IntellectualSites/FastAsyncWorldEdit#1077]
### Server Implementation

Tuinity

### Server Version

1.16.5

### Describe the bug

Errors on startup

### To Reproduce

Start server with FAWE

### Expected behaviour

No Error

### Error log (if applicable)

[13:21:03 INFO]: [FastAsyncWorldEdit] Enabling FastAsyncWorldEdit v1.16-9aa25ce [13:21:04 WARN]: java.lang.NumberFormatException: For input string: "9aa25ce" [13:21:04 WARN]: 	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:68) [13:21:04 WARN]: 	at java.base/java.lang.Integer.parseInt(Integer.java:652) [13:21:04 WARN]: 	at java.base/java.lang.Integer.parseInt(Integer.java:770) [13:21:04 WARN]: 	at com.boydti.fawe.FaweVersion.<init>(FaweVersion.java:21) [13:21:04 WARN]: 	at com.boydti.fawe.FaweVersion.tryParse(FaweVersion.java:31) [13:21:04 WARN]: 	at com.boydti.fawe.Fawe.setupConfigs(Fawe.java:244) [13:21:04 WARN]: 	at com.boydti.fawe.Fawe.<init>(Fawe.java:132) [13:21:04 WARN]: 	at com.boydti.fawe.Fawe.set(Fawe.java:116) [13:21:04 WARN]: 	at com.boydti.fawe.bukkit.FaweBukkit.<init>(FaweBukkit.java:69) [13:21:04 WARN]: 	at com.sk89q.worldedit.bukkit.WorldEditPlugin.onEnable(WorldEditPlugin.java:140) [13:21:04 WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) [13:21:04 WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) [13:21:04 WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) [13:21:04 WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) [13:21:04 WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) [13:21:04 WARN]: 	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:254) [13:21:04 WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1067) [13:21:04 WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290) [13:21:04 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:832)

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/a9581b4564734c228ecc6d2abb75224d

### Fawe Version

FastAsyncWorldEdit-Bukkit-1.16-9aa25ce

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.16/ and the issue still persists.

### Anything else?

FAWE is my only plugin

**Comment by NotMyFault** [comment]
That is the indicator of a locally built jar.
