### ISSUE TITLE
FAWE not keeping orientation for chest, stairs & more

### ISSUE THREAD

**Issue by markaabo** [IntellectualSites/FastAsyncWorldEdit#1081]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

if i try and replace all chests in a selection to trapped chests it resets their orientation and ALL of them then points towards the same direction, the same goes for anything that has orientation like stairs, furnaces and so on.

### To Reproduce

Place 4 chests where they all have a different orientation, and select the area they're in.
then do `//replace chest trapped_chest` puff now all of them points towards the same direction.

### Expected behaviour

When using any command like `//copy`, `//paste`, `//replace`, `//replacenear`, or anything else where their is a block orientation before your do the edit it should then remember that orientation and replace/paste and so on, while keeping the individual orientation of the blocks that are affected.

### Screenshots / Videos

Before:
![Before](https://user-images.githubusercontent.com/68380434/118815444-89780b00-b8b1-11eb-97ae-9964448bea65.png)

Command i do: `//replace chest ender_chest`

After:
![After](https://user-images.githubusercontent.com/68380434/118815482-90068280-b8b1-11eb-804d-84d2ab334087.png)

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/b469262e51a34c6bb99f504ec2ab8036

### Fawe Version

FastAsyncWorldEdit-Bukkit-1.16-688

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.16/ and the issue still persists.

**Comment by LaurenceBarnes** [comment]
Read the docs next time :p

try `//replace chest ^trapped_chest`

**Comment by LaurenceBarnes** [comment]
@NotMyFault however I noticed (just tested it) that chests become invisible and require to be opened and a re-login to become visible again. Is that a known issue?

**Comment by markaabo** [comment]
> 
> 
> Read the docs next time :p
> 
> try `//replace chest ^trapped_chest`

I have not tested your solution but i will when i can. i tried googling and googling have to look thru alot of posts i tried looking in the doc but i cannot find it, could you link me to where you find it in the docs? :)

Also i also noticed the invisible bug thought it was just my shaders

**Comment by LaurenceBarnes** [comment]
https://worldedit.enginehub.org/en/latest/usage/general/patterns/

:D

**Comment by markaabo** [comment]
> 
> 
> https://worldedit.enginehub.org/en/latest/usage/general/patterns/
> 
> :D
> 
> > **[Patterns — WorldEdit 7.2 documentation](https://worldedit.enginehub.org/en/latest/usage/general/patterns/)**

Thank you, idk why this didnt come up in google or when i searched around the docs earlier :D

Also how do you apply the "^" when your pasting something?, its still not remebering pasting orientation sometimes

**Comment by LaurenceBarnes** [comment]
how are you using/combining the commands?

**Comment by markaabo** [comment]
> 
> 
> how are you using/combining the commands?

How do you mean?, im just selecting something doing `//copy` then move where i want it to paste it in and do `//paste` :)

**Comment by LaurenceBarnes** [comment]
the "^" is for replace commands, as you described in the issue. In the link I sent you is an example of that. //copy and //paste are two different things. Do you rotate or flip the clipboards?

**Comment by markaabo** [comment]
Sometimes i do rotate the clipboards, also i said it in exspected behavior that `//copy` and `//pasta` should behave identical to the original model

**Comment by LaurenceBarnes** [comment]
they do behave identical, which is why I am wondering. I do notice that there is an issue when first flipping and then rotating a clipboard, but not when just plain copying and pasting. It would be helpful if you made a video with all steps to show us how to reproduce, then we might be able to open an issue.

**Comment by markaabo** [comment]
> 
> 
> Read the docs next time :p
> 
> try `//replace chest ^trapped_chest`

I have now tested it and it doesn't work, when using `//replace trapped_chest ^ender_chest` it replys with `(FAWE) 0 blocks have been replaced.` but if i run the same command without the `^` it works but now the oriantation is not working, and the problem is their with all of them looking at north.

If i do `//replace trapped_chest ^chest` it works like you said but i need to replace trapped with enderchests also which somehow doesnt work

**Comment by LaurenceBarnes** [comment]
you are right, chests and trapped chests cannot be replaced by enderchests. I don't know if that has something to do with enderchests not being able to become double chests. I would consider this a bug @NotMyFault 

Also when trying to just //replace trapped_chest ender_chest it works (with the ender_chest being invisible first), but when doing //replace trapped_chest ^ender_chest I get this error https://pastebin.com/PJJj9KWu

Note that I am using the StarlightBuild-19, as I am currently investigating another bug with newer versions on the main branch.

**Comment by markaabo** [comment]
If you do it the other way around `//replace ender_chest ^trapped_chest` it looks like this:
![2021-05-22_12 58 12](https://user-images.githubusercontent.com/68380434/119224233-c3d5e800-bafd-11eb-8ed2-2a65e8061439.png)

But if i do //replace ender_chest ^trapped_chest[type=single]` it works backwards but trying the same with trapped_chests to ender_chests just results in an error:

`[12:59:49 INFO]: K4bb issued server command: //replace trapped_chest[type=single] ^ender_chest
[12:59:49 ERROR]: An unexpected error while handling a WorldEdit command
java.lang.ArrayIndexOutOfBoundsException: null
        at com.sk89q.worldedit.world.block.BlockType.withPropertyId(BlockType.java:142) ~[?:?]
        at com.sk89q.worldedit.world.block.BlockType.withStateId(BlockType.java:147) ~[?:?]
        at com.sk89q.worldedit.world.block.BlockState.with(BlockState.java:269) ~[?:?]
        at com.sk89q.worldedit.function.pattern.TypeApplyingPattern.apply(TypeApplyingPattern.java:48) ~[?:?]
        at com.sk89q.worldedit.function.pattern.Pattern.apply(Pattern.java:48) ~[?:?]
        at com.sk89q.worldedit.function.pattern.Pattern.applyBlock(Pattern.java:53) ~[?:?]
        at com.boydti.fawe.beta.implementation.filter.MaskFilter.applyBlock(MaskFilter.java:45) ~[?:?]
        at com.boydti.fawe.beta.implementation.filter.block.CharFilterBlock.filter(CharFilterBlock.java:141) ~[?:?]
        at com.sk89q.worldedit.regions.Region.filter(Region.java:284) ~[?:?]
        at com.sk89q.worldedit.regions.CuboidRegion.filter(CuboidRegion.java:683) ~[?:?]
        at com.boydti.fawe.beta.implementation.filter.block.ChunkFilterBlock.filter(ChunkFilterBlock.java:84) ~[?:?]
        at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.filterBlocks(ChunkHolder.java:823) ~[?:?]
        at com.boydti.fawe.beta.IQueueExtent.apply(IQueueExtent.java:158) ~[?:?]
        at com.boydti.fawe.beta.implementation.queue.ParallelQueueExtent.apply(ParallelQueueExtent.java:96) ~[?:?]
        at com.boydti.fawe.beta.implementation.queue.ParallelQueueExtent.replaceBlocks(ParallelQueueExtent.java:176) ~[?:?]
        at com.sk89q.worldedit.extent.PassthroughExtent.replaceBlocks(PassthroughExtent.java:165) ~[?:?]
        at com.sk89q.worldedit.EditSession.replaceBlocks(EditSession.java:1183) ~[?:?]
        at com.sk89q.worldedit.command.RegionCommands.replace(RegionCommands.java:307) ~[?:?]
        at com.sk89q.worldedit.command.RegionCommandsRegistration.cmd$_replace(RegionCommandsRegistration.java:722) ~[?:?]
        at com.sk89q.worldedit.command.RegionCommandsRegistration$$Lambda$3590/0x0000000000000000.run(Unknown Source) ~[?:?]
        at org.enginehub.piston.CommandManager.execute(CommandManager.java:157) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommandOnCurrentThread$16(PlatformCommandManager.java:695) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager$$Lambda$6105/0x0000000000000000.get(Unknown Source) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandTask(PlatformCommandManager.java:711) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandOnCurrentThread(PlatformCommandManager.java:697) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommand$13(PlatformCommandManager.java:667) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager$$Lambda$6086/0x0000000000000000.run(Unknown Source) ~[?:?]
        at com.sk89q.worldedit.extension.platform.AbstractPlayerActor.lambda$runAction$1(AbstractPlayerActor.java:698) ~[?:?]
        at com.sk89q.worldedit.extension.platform.AbstractPlayerActor$$Lambda$6081/0x0000000000000000.run(Unknown Source) ~[?:?]
        at com.boydti.fawe.object.task.AsyncNotifyQueue.lambda$run$0(AsyncNotifyQueue.java:27) ~[?:?]
        at com.boydti.fawe.object.task.AsyncNotifyQueue$$Lambda$6082/0x0000000000000000.call(Unknown Source) ~[?:?]
        at com.boydti.fawe.object.task.AsyncNotifyQueue.lambda$call$1(AsyncNotifyQueue.java:44) ~[?:?]
        at com.boydti.fawe.object.task.AsyncNotifyQueue$$Lambda$6083/0x0000000000000000.call(Unknown Source) ~[?:?]
        at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1448) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?]`

**Comment by markaabo** [comment]
@LaurenceBarnes should i make a new issue for the invisble chests, and enderchest thing?, also the invisble chest thing doesnt fix on my server for anyone if you relog they stay invisble untill you open them

**Comment by LaurenceBarnes** [comment]
yes, but make one for either. Check if someone else made an issue before and link it.
