### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by TheArmagan** [IntellectualSites/FastAsyncWorldEdit#1083]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

```
[19:27:34 WARN]: java.lang.NullPointerException
[19:27:34 WARN]: java.lang.NullPointerException
[19:27:34 WARN]: java.lang.NullPointerException
[19:27:34 WARN]: java.util.concurrent.ExecutionException: java.lang.NullPointerException
[19:27:34 WARN]:        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
[19:27:34 WARN]:        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
[19:27:34 WARN]:        at com.boydti.fawe.beta.implementation.queue.SingleThreadQueueExtent.pollSubmissions(SingleThreadQueueExtent.java:341)
[19:27:34 WARN]:        at com.boydti.fawe.beta.implementation.queue.SingleThreadQueueExtent.getOrCreateChunk(SingleThreadQueueExtent.java:271)
[19:27:34 WARN]:        at com.boydti.fawe.beta.implementation.queue.SingleThreadQueueExtent.getOrCreateChunk(SingleThreadQueueExtent.java:39)
[19:27:34 WARN]:        at com.boydti.fawe.beta.implementation.lighting.NMSRelighter.smoothSkyLight(NMSRelighter.java:1102)
[19:27:34 WARN]:        at com.boydti.fawe.beta.implementation.lighting.NMSRelighter.fixSkyLighting(NMSRelighter.java:1040)
[19:27:34 WARN]:        at com.boydti.fawe.beta.implementation.lighting.NMSRelighter.fixSkyLighting(NMSRelighter.java:900)
[19:27:34 WARN]:        at com.boydti.fawe.beta.implementation.lighting.NMSRelighter.fixLightingSafe(NMSRelighter.java:781)
[19:27:34 WARN]:        at com.boydti.fawe.beta.implementation.lighting.NMSRelighter.removeAndRelight(NMSRelighter.java:102)
[19:27:34 WARN]:        at com.sk89q.worldedit.EditSession.flushQueue(EditSession.java:1113)
[19:27:34 WARN]:        at com.sk89q.worldedit.EditSession.setBlocks(EditSession.java:1034)
[19:27:34 WARN]:        at com.sk89q.worldedit.LocalSession.undo(LocalSession.java:578)
[19:27:34 WARN]:        at com.sk89q.worldedit.command.HistoryCommands.undo(HistoryCommands.java:86)
[19:27:34 WARN]:        at com.sk89q.worldedit.command.HistoryCommandsRegistration.cmd$undo(HistoryCommandsRegistration.java:146)
[19:27:34 WARN]:        at org.enginehub.piston.CommandManager.execute(CommandManager.java:157)
[19:27:34 WARN]:        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommandOnCurrentThread$16(PlatformCommandManager.java:695)
[19:27:34 WARN]:        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandTask(PlatformCommandManager.java:711)
[19:27:34 WARN]:        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandOnCurrentThread(PlatformCommandManager.java:697)
[19:27:34 WARN]:        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$null$13(PlatformCommandManager.java:667)
[19:27:34 WARN]:        at com.sk89q.worldedit.extension.platform.AbstractPlayerActor.lambda$runAction$1(AbstractPlayerActor.java:698)
[19:27:34 WARN]:        at com.boydti.fawe.object.task.AsyncNotifyQueue.lambda$run$0(AsyncNotifyQueue.java:27)
[19:27:34 WARN]:        at com.boydti.fawe.object.task.AsyncNotifyQueue.lambda$call$1(AsyncNotifyQueue.java:44)
[19:27:34 WARN]:        at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1448)
[19:27:34 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[19:27:34 WARN]:        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
[19:27:34 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
[19:27:34 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
[19:27:34 WARN]:        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
[19:27:34 WARN]: Caused by: java.lang.NullPointerException

```
### To Reproduce

//replacenear 50 air 1%glowstone,200%air

### Expected behaviour

no errors

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/ebf39dd56147468e8177381ba5326216

### Fawe Version

FastAsyncWorldEdit version 1.16.685;9aa25ce

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.16/ and the issue still persists.

### Anything else?

Nope thats it, a quick bug report. :

**Comment by MattBDev** [comment]
@dordsor21 Is this linked to one of the issues you have been tracking/working on?

**Comment by SirYwell** [comment]
Yes, althought the PR doesn't fix it (yet)

**Comment by dordsor21** [comment]
Fixed in https://github.com/IntellectualSites/FastAsyncWorldEdit/commit/f6af9925e8366ee7055a7dd95515c09021a152b4
