### ISSUE TITLE
Java 16 not supported on 1.8 server

### ISSUE THREAD

**Issue by andreasdc** [IntellectualSites/FastAsyncWorldEdit#1131]
### Server Implementation

Paper

### Server Version

1.15.2

### Describe the bug

not working

### To Reproduce

[05:28:26] [Server thread/WARN]: java.lang.NoSuchFieldException: modifiers

[05:28:26] [Server thread/WARN]:        at java.base/java.lang.Class.getDeclaredField(Unknown Source)

[05:28:26] [Server thread/WARN]:        at com.boydti.fawe.config.Config.setAccessible(Config.java:451)

[05:28:26] [Server thread/WARN]:        at com.boydti.fawe.config.Config.save(Config.java:288)

[05:28:26] [Server thread/WARN]:        at com.boydti.fawe.config.Config.<init>(Config.java:27)

[05:28:26] [Server thread/WARN]:        at com.boydti.fawe.config.Settings.<init>(Settings.java:8)

[05:28:26] [Server thread/WARN]:        at com.boydti.fawe.config.Settings.<clinit>(Settings.java:10)

[05:28:26] [Server thread/WARN]:        at com.boydti.fawe.bukkit.FaweBukkit.<init>(FaweBukkit.java:94)

[05:28:26] [Server thread/WARN]:        at com.boydti.fawe.bukkit.BukkitMain.onEnable(BukkitMain.java:76)

[05:28:26] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)

[05:28:26] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)

[05:28:26] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)

[05:28:26] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:375)

[05:28:26] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:332)

[05:28:26] [Server thread/WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:209)

[05:28:26] [Server thread/WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:601)

[05:28:26] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Unknown Source)

[05:28:26] [Server thread/WARN]: java.lang.NullPointerException: Cannot assign field "ENABLED" because "com.boydti.fawe.config.Settings.IMP.TICK_LIMITER" is null

### Expected behaviour

work

### Fawe Debugpaste

0

### Fawe Version

0

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.16/ and the issue still persists.

**Comment by dordsor21** [comment]
Don't use 1.8.

**Comment by andreasdc** [comment]
> Don't use 1.8.

Umm, just fix your plugin? What if I want 1.7-1.16 and 1.8 mechanics?

**Comment by NotMyFault** [comment]
Then you use tools porting old 1.8 mechanics to modern Minecraft versions like everyone else does.

**Comment by MattBDev** [comment]
I think it's funny that this person reported their server version as "1.15.2" and yet proceeded to complain about 1.8
