### ISSUE TITLE
StackOverflow during startup running mcpaper 1.17-43

### ISSUE THREAD

**Issue by ericmartineau** [IntellectualSites/FastAsyncWorldEdit#1136]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

During startup, a stackoverflow occurs
```
	at com.sk89q.worldedit.world.registry.LegacyMapper.<init>(LegacyMapper.java:80) ~[?:?]
	at com.sk89q.worldedit.world.registry.LegacyMapper.getInstance(LegacyMapper.java:309) ~[?:?]
	at com.sk89q.worldedit.world.block.BlockTypes.parse(BlockTypes.java:849) ~[?:?]
	at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseLogic(DefaultBlockParser.java:360) ~[?:?]
	at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseFromInput(DefaultBlockParser.java:104) ~[?:?]
	at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseFromInput(DefaultBlockParser.java:74) ~[?:?]
	at com.sk89q.worldedit.internal.registry.AbstractFactory.parseFromInput(AbstractFactory.java:77) ~[?:?]
	at com.sk89q.worldedit.world.registry.LegacyMapper.loadFromResource(LegacyMapper.java:136) ~[?:?]
	at com.sk89q.worldedit.world.registry.LegacyMapper.<init>(LegacyMapper.java:80) ~[?:?]
	at com.sk89q.worldedit.world.registry.LegacyMapper.getInstance(LegacyMapper.java:309) ~[?:?]
	at com.sk89q.worldedit.world.block.BlockTypes.parse(BlockTypes.java:849) ~[?:?]
	at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseLogic(DefaultBlockParser.java:360) ~[?:?]
	at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseFromInput(DefaultBlockParser.java:104) ~[?:?]
	at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseFromInput(DefaultBlockParser.java:74) ~[?:?]
	at com.sk89q.worldedit.internal.registry.AbstractFactory.parseFromInput(AbstractFactory.java:77) ~[?:?]
	at com.sk89q.worldedit.world.registry.LegacyMapper.loadFromResource(LegacyMapper.java:136) ~[?:?]
	at com.sk89q.worldedit.world.registry.LegacyMapper.<init>(LegacyMapper.java:80) ~[?:?]
	at com.sk89q.worldedit.world.registry.LegacyMapper.getInstance(LegacyMapper.java:309) ~[?:?]
	at com.sk89q.worldedit.world.block.BlockTypes.parse(BlockTypes.java:849) ~[?:?]
	at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseLogic(DefaultBlockParser.java:360) ~[?:?]
	at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseFromInput(DefaultBlockParser.java:104) ~[?:?]
	at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseFromInput(DefaultBlockParser.java:74) ~[?:?]
	at com.sk89q.worldedit.internal.registry.AbstractFactory.parseFromInput(AbstractFactory.java:77) ~[?:?]
	at com.sk89q.worldedit.world.registry.LegacyMapper.loadFromResource(LegacyMapper.java:136) ~[?:?]
	at com.sk89q.worldedit.world.registry.LegacyMapper.<init>(LegacyMapper.java:80) ~[?:?]
	at com.sk89q.worldedit.world.registry.LegacyMapper.getInstance(LegacyMapper.java:309) ~[?:?]
	at com.sk89q.worldedit.world.block.BlockTypes.parse(BlockTypes.java:849) ~[?:?]
	at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseLogic(DefaultBlockParser.java:360) ~[?:?]
	at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseFromInput(DefaultBlockParser.java:104) ~[?:?]
	at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseFromInput(DefaultBlockParser.java:74) ~[?:?]
	at com.sk89q.worldedit.internal.registry.AbstractFactory.parseFromInput(AbstractFactory.java:77) ~[?:?]
	at com.sk89q.worldedit.world.registry.LegacyMapper.loadFromResource(LegacyMapper.java:136) ~[?:?]
	at com.sk89q.worldedit.world.registry.LegacyMapper.<init>(LegacyMapper.java:80) ~[?:?]
	at com.sk89q.worldedit.world.registry.LegacyMapper.getInstance(LegacyMapper.java:309) ~[?:?]
	at com.sk89q.worldedit.world.block.BlockTypes.parse(BlockTypes.java:849) ~[?:?]
	at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseLogic(DefaultBlockParser.java:360) ~[?:?]
	at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseFromInput(DefaultBlockParser.java:104) ~[?:?]
	at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseFromInput(DefaultBlockParser.java:74) ~[?:?]
	at com.sk89q.worldedit.internal.registry.AbstractFactory.parseFromInput(AbstractFactory.java:77) ~[?:?]
	at com.sk89q.worldedit.world.registry.LegacyMapper.loadFromResource(LegacyMapper.java:136) ~[?:?]
	at com.sk89q.worldedit.world.registry.LegacyMapper.<init>(LegacyMapper.java:80) ~[?:?]
	at com.sk89q.worldedit.world.registry.LegacyMapper.getInstance(LegacyMapper.java:309) ~[?:?]
	at com.sk89q.worldedit.world.block.BlockTypes.parse(BlockTypes.java:849) ~[?:?]
	at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseLogic(DefaultBlockParser.java:360) ~[?:?]
	at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseFromInput(DefaultBlockParser.java:104) ~[?:?]
	at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseFromInput(DefaultBlockParser.java:74) ~[?:?]
	at com.sk89q.worldedit.internal.registry.AbstractFactory.parseFromInput(AbstractFactory.java:77) ~[?:?]
	at com.sk89q.worldedit.world.registry.LegacyMapper.loadFromResource(LegacyMapper.java:136) ~[?:?]
	at com.sk89q.worldedit.world.registry.LegacyMapper.<init>(LegacyMapper.java:80) ~[?:?]
	at com.sk89q.worldedit.world.registry.LegacyMapper.getInstance(LegacyMapper.java:309) ~[?:?]
	at com.sk89q.worldedit.world.block.BlockTypes.parse(BlockTypes.java:849) ~[?:?]
	at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseLogic(DefaultBlockParser.java:360) ~[?:?]
	at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseFromInput(DefaultBlockParser.java:104) ~[?:?]
	at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseFromInput(DefaultBlockParser.java:74) ~[?:?]
	at com.sk89q.worldedit.internal.registry.AbstractFactory.parseFromInput(AbstractFactory.java:77) ~[?:?]
	at com.sk89q.worldedit.world.registry.LegacyMapper.loadFromResource(LegacyMapper.java:136) ~[?:?]
	at com.sk89q.worldedit.world.registry.LegacyMapper.<init>(LegacyMapper.java:80) ~[?:?]
	at com.sk89q.worldedit.world.registry.LegacyMapper.getInstance(LegacyMapper.java:309) ~[?:?]
	at com.sk89q.worldedit.world.block.BlockTypes.parse(BlockTypes.java:849) ~[?:?]
	at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseLogic(DefaultBlockParser.java:360)
```

### To Reproduce

 Get 1.17-43 build of mcpaper
Install FAWE
Start server

### Expected behaviour

Server to startup

### Fawe Debugpaste

FastAsyncWorldEdit v1.16-734;78acb85

### Fawe Version

FastAsyncWorldEdit v1.16-734;78acb85

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.16/ and the issue still persists.

**Comment by MattBDev** [comment]
No debug paste provided. Please do not ignore the template.

**Comment by NotMyFault** [comment]
Please attach a `/fawe debugpaste` and provide the full exception on a paste service like https://paste.gg/

**Comment by ericmartineau** [comment]
I'm not trying to be obstinate here, but I've provided you everything you need.  I can't produce a `/fawe debugpaste` because the server never starts up far enough to be able to log in to run the command.  Yes, I should've included the bottom of the stacktrace, but at this point, I'd have to redownload the broken version of FAWE, install it, and restart the server just to get 8 lines of the stacktrace.  Instead, I spent my time trying to fix the problem and put up a PR.
