### ISSUE TITLE
ConcurrentModificationException in EditSession close()/flushQueue()

### ISSUE THREAD

**Issue by Combustible** [IntellectualSites/FastAsyncWorldEdit#1139]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

We use FAWE to regularly paste in a *lot* of schematics to generate procedural structures, respawn dungeons, etc. Like, thousands a week. Sometimes when many schematics are loaded very close to each other we get the following error in the log: 

```
 java.util.concurrent.ExecutionException: java.util.ConcurrentModificationException: java.util.ConcurrentModificationException
    at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1006)
    at com.boydti.fawe.beta.implementation.queue.SingleThreadQueueExtent.pollSubmissions(SingleThreadQueueExtent.java:301)
    at com.boydti.fawe.beta.implementation.queue.SingleThreadQueueExtent.flush(SingleThreadQueueExtent.java:394)
    at com.boydti.fawe.beta.IQueueExtent.commit(IQueueExtent.java:112)
    at com.sk89q.worldedit.extent.PassthroughExtent.commit(PassthroughExtent.java:207)
    at com.sk89q.worldedit.extent.AbstractDelegateExtent.commit(AbstractDelegateExtent.java:265)
    at com.sk89q.worldedit.extent.PassthroughExtent.commit(PassthroughExtent.java:207)
    at com.sk89q.worldedit.EditSession.flushQueue(EditSession.java:1089)
    at com.sk89q.worldedit.EditSession.flushSession(EditSession.java:1082)
    at com.sk89q.worldedit.EditSession.close(EditSession.java:1071)
    at com.playmonumenta.structures.utils.StructureUtils$1.lambda$run$5(StructureUtils.java:215)
    at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
    at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
    at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:829)
 Caused by: java.util.ConcurrentModificationException: java.util.ConcurrentModificationException
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
    at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:600)
    ... 17 more
 Caused by: java.util.ConcurrentModificationException
    at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1493)
    at java.base/java.util.HashMap$EntryIterator.next(HashMap.java:1526)
    at net.minecraft.server.v1_16_R3.PacketPlayOutMapChunk.<init>(PacketPlayOutMapChunk.java:92)
    at com.boydti.fawe.bukkit.adapter.mc1_16_5.BukkitAdapter_1_16_5.sendChunk(BukkitAdapter_1_16_5.java:190)
    at com.boydti.fawe.bukkit.adapter.mc1_16_5.BukkitGetBlocks_1_16_5.send(BukkitGetBlocks_1_16_5.java:702)
    at com.boydti.fawe.bukkit.adapter.mc1_16_5.BukkitGetBlocks_1_16_5.lambda$call$7(BukkitGetBlocks_1_16_5.java:637)
    at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnable.exec(ForkJoinTask.java:1387)
    at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
    at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
    at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
    at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
    at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

This results in part of the schematic not loading, usually a chunk section like in the following picture (this room is supposed to be a dome, but a rectangular section failed to load). 

![room missing section](https://user-images.githubusercontent.com/2737074/123182114-9c977100-d443-11eb-881a-f0b929c3a3b1.png)

### To Reproduce

I don't have an easy way to reproduce this consistently - but it happens to us every week, usually when scheduling many paste operations at the same time / close to each other in time. I am hoping it will be possible to track down from the stack trace. 

### Expected behaviour

Schematic should load and exception not be thrown. 

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/dd07f2b274a140d7be98b479bdcd3ef9

### Fawe Version

FastAsyncWorldEdit Version: 1.16-730;96ed367

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.16/ and the issue still persists.

**Comment by MattBDev** [comment]
When you say "loaded very close to each other" do you mean that schematics are being loaded very fast or are you referring to the distance between the schematics?

**Comment by Combustible** [comment]
Both I guess - we are loading schematics adjacent to each other both in time and space. 

Where this shows up the most is our system that generates procedural dungeons - which paste rectangular areas adjacent/touching each other. Generation happens over many ticks, making one EditSession/paste request at a time, then waiting a few ticks, and repeating.

**Comment by NickNackGus** [comment]
If it helps, one of those procedural dungeons pastes up to five structures at once - one for a room, one on the top of the dungeon for a map, and four hall icon structures that overlap with the room icon by a block (though the overlapping blocks are skipped in the paste).
