### ISSUE TITLE
There is no registered PlotPlayer converter for type CraftPlayer for non-opped players

### ISSUE THREAD

**Issue by SecretlyJealous** [IntellectualSites/FastAsyncWorldEdit#1140]
### Server Implementation

Tuinity

### Server Version

1.16.5

### Describe the bug

When using FastAsyncWorldEdit-Bukkit-p2v6-16 with PlotSquared-Bukkit-6.0.1-Premium worldedit commands refuse to work for players that are not OP and prints this error in console: 
```
[16:06:57 WARN]: java.lang.IllegalArgumentException: There is no registered PlotPlayer converter for type CraftPlayer
[16:06:57 WARN]:        at com.plotsquared.core.player.PlotPlayer.from(PlotPlayer.java:131)
[16:06:57 WARN]:        at com.boydti.fawe.bukkit.regions.plotsquared.PlotSquaredFeature.getMask(PlotSquaredFeature.java:79)
[16:06:57 WARN]:        at com.boydti.fawe.util.WEManager.getMask(WEManager.java:112)
[16:06:57 WARN]:        at com.sk89q.worldedit.extension.platform.AbstractPlayerActor.getCurrentRegions(AbstractPlayerActor.java:534)
[16:06:57 WARN]:        at com.sk89q.worldedit.extension.platform.AbstractPlayerActor.getCurrentRegions(AbstractPlayerActor.java:530)
[16:06:57 WARN]:        at com.boydti.fawe.util.EditSessionBuilder.compile(EditSessionBuilder.java:386)
[16:06:57 WARN]:        at com.sk89q.worldedit.EditSession.<init>(EditSession.java:258)
[16:06:57 WARN]:        at com.boydti.fawe.util.EditSessionBuilder.build(EditSessionBuilder.java:431)
[16:06:57 WARN]:        at com.sk89q.worldedit.LocalSession.createEditSession(LocalSession.java:1527)
[16:06:57 WARN]:        at com.sk89q.worldedit.extension.platform.binding.ProvideBindings.editSession(ProvideBindings.java:56)
[16:06:57 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:06:57 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[16:06:57 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:06:57 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[16:06:57 WARN]:        at com.sk89q.worldedit.extension.platform.binding.Bindings.invoke(Bindings.java:127)
[16:06:57 WARN]:        at com.sk89q.worldedit.extension.platform.binding.Bindings.lambda$register$1(Bindings.java:94)
[16:06:57 WARN]:        at org.enginehub.piston.inject.MapBackedValueStore.lambda$injectedValue$0(MapBackedValueStore.java:56)
[16:06:57 WARN]:        at java.base/java.util.Optional.flatMap(Optional.java:289)
[16:06:57 WARN]:        at org.enginehub.piston.inject.MapBackedValueStore.injectedValue(MapBackedValueStore.java:56)
[16:06:57 WARN]:        at org.enginehub.piston.inject.MergedValueAccess.lambda$injectedValue$0(MergedValueAccess.java:54)
[16:06:57 WARN]:        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[16:06:57 WARN]:        at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
[16:06:57 WARN]:        at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
[16:06:57 WARN]:        at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
[16:06:57 WARN]:        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
[16:06:57 WARN]:        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
[16:06:57 WARN]:        at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
[16:06:57 WARN]:        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[16:06:57 WARN]:        at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
[16:06:57 WARN]:        at org.enginehub.piston.inject.MergedValueAccess.injectedValue(MergedValueAccess.java:57)
[16:06:57 WARN]:        at org.enginehub.piston.inject.MemoizingValueAccess.injectedValue(MemoizingValueAccess.java:84)
[16:06:57 WARN]:        at org.enginehub.piston.impl.CommandParametersImpl.injectedValue(CommandParametersImpl.java:109)
[16:06:57 WARN]:        at org.enginehub.piston.inject.InjectedValueAccess.injectedValue(InjectedValueAccess.java:44)
[16:06:57 WARN]:        at com.sk89q.worldedit.command.RegionCommandsRegistration.extract$editSession(RegionCommandsRegistration.java:979)
[16:06:57 WARN]:        at com.sk89q.worldedit.command.RegionCommandsRegistration.cmd$_set(RegionCommandsRegistration.java:575)
[16:06:57 WARN]:        at org.enginehub.piston.CommandManager.execute(CommandManager.java:157)
[16:06:57 WARN]:        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommandOnCurrentThread$16(PlatformCommandManager.java:693)
[16:06:57 WARN]:        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandTask(PlatformCommandManager.java:709)
[16:06:57 WARN]:        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandOnCurrentThread(PlatformCommandManager.java:695)
[16:06:57 WARN]:        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommand$13(PlatformCommandManager.java:665)
[16:06:57 WARN]:        at com.sk89q.worldedit.extension.platform.AbstractPlayerActor.lambda$runAction$1(AbstractPlayerActor.java:697)
[16:06:57 WARN]:        at com.boydti.fawe.object.task.AsyncNotifyQueue.lambda$run$0(AsyncNotifyQueue.java:27)
[16:06:57 WARN]:        at com.boydti.fawe.object.task.AsyncNotifyQueue.lambda$call$1(AsyncNotifyQueue.java:44)
[16:06:57 WARN]:        at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1458)
[16:06:57 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295)
[16:06:57 WARN]:        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
[16:06:57 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
[16:06:57 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
[16:06:57 WARN]:        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

### To Reproduce

1. Use FastAsyncWorldEdit-Bukkit-p2v6-16 with PlotSquared-Bukkit-6.0.1-Premium
2. Use a worldedit command and make sure you are not OP

### Expected behaviour

The worldedit command should work without any errors in console

### Screenshots / Videos

![2021-06-24_16 06 59](https://user-images.githubusercontent.com/10485646/123287352-974f2a80-d506-11eb-943b-a317a0a70adc.png)

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/538c30cdd60b4b66bbfeddb35c3d3840

### Fawe Version

p2v6-16;e620b0c

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.16/ and the issue still persists.

**Comment by remyd95** [comment]
I can confirm this behaviour. 

Not a single FAWE version seems to work with PlotSquared-6.0.1.

Only with admin permissions and 'Toggle WorldEdit' enabled it is possible to use WorldEdit.

**Comment by NotMyFault** [comment]
Tested with Fawe 1.17 branch, can't reproduce. Assume resolved?

**Comment by SecretlyJealous** [comment]
> Tested with Fawe 1.17 branch, can't reproduce. Assume resolved?

PlotSquared v6 doesn't work with fawe 1.17: https://athion.net/ISPaster/paste/view/9d50ad06a12c4960a9b65e4314674f85
The console mentions that you have to use p2-v6 version of fawe:
`[10:19:46 ERROR]: [PlotSquared/BukkitPlatform] Incompatible version of FAWE to enable hook, please upgrade: https://ci.athion.net/job/FastAsyncWorldEdit-P2-V6/`

When using the P2-V6 version of FAWE it gives the same error: https://athion.net/ISPaster/paste/view/3ec700b00f0b4cafb3e4b175a5c8998e

**Comment by NotMyFault** [comment]
Ignore my previous comment, that was supposed to go to a different issue.

**Comment by SecretlyJealous** [comment]
Just going to update the error here now that PlotSquared-Bukkit-6.0.3-Premium has been released and is compatible with Fawe 1.17.

FAWE debugpaste: https://athion.net/ISPaster/paste/view/b46f95b4d6b64cc9aa3302f7bcbf5da8
Using **//cut** as a non-opped player:
```
[21:15:06 WARN]: java.lang.IllegalArgumentException: There is no registered PlotPlayer converter for type CraftPlayer
[21:15:06 WARN]:        at com.plotsquared.core.player.PlotPlayer.from(PlotPlayer.java:131)
[21:15:06 WARN]:        at com.fastasyncworldedit.bukkit.regions.plotsquared.PlotSquaredFeature.getMask(PlotSquaredFeature.java:79)
[21:15:06 WARN]:        at com.fastasyncworldedit.core.util.WEManager.getMask(WEManager.java:112)
[21:15:06 WARN]:        at com.sk89q.worldedit.extension.platform.AbstractPlayerActor.getCurrentRegions(AbstractPlayerActor.java:534)
[21:15:06 WARN]:        at com.sk89q.worldedit.extension.platform.AbstractPlayerActor.getCurrentRegions(AbstractPlayerActor.java:530)
[21:15:06 WARN]:        at com.fastasyncworldedit.core.util.EditSessionBuilder.compile(EditSessionBuilder.java:386)
[21:15:06 WARN]:        at com.sk89q.worldedit.EditSession.<init>(EditSession.java:258)
[21:15:06 WARN]:        at com.fastasyncworldedit.core.util.EditSessionBuilder.build(EditSessionBuilder.java:431)
[21:15:06 WARN]:        at com.sk89q.worldedit.LocalSession.createEditSession(LocalSession.java:1529)
[21:15:06 WARN]:        at com.sk89q.worldedit.extension.platform.binding.ProvideBindings.editSession(ProvideBindings.java:56)
[21:15:06 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:15:06 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[21:15:06 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[21:15:06 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[21:15:06 WARN]:        at com.sk89q.worldedit.extension.platform.binding.Bindings.invoke(Bindings.java:127)
[21:15:06 WARN]:        at com.sk89q.worldedit.extension.platform.binding.Bindings.lambda$register$1(Bindings.java:94)
[21:15:06 WARN]:        at org.enginehub.piston.inject.MapBackedValueStore.lambda$injectedValue$0(MapBackedValueStore.java:56)
[21:15:06 WARN]:        at java.base/java.util.Optional.flatMap(Optional.java:289)
[21:15:06 WARN]:        at org.enginehub.piston.inject.MapBackedValueStore.injectedValue(MapBackedValueStore.java:56)
[21:15:06 WARN]:        at org.enginehub.piston.inject.MergedValueAccess.lambda$injectedValue$0(MergedValueAccess.java:54)
[21:15:06 WARN]:        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[21:15:06 WARN]:        at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
[21:15:06 WARN]:        at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
[21:15:06 WARN]:        at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
[21:15:06 WARN]:        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
[21:15:06 WARN]:        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
[21:15:06 WARN]:        at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
[21:15:06 WARN]:        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[21:15:06 WARN]:        at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
[21:15:06 WARN]:        at org.enginehub.piston.inject.MergedValueAccess.injectedValue(MergedValueAccess.java:57)
[21:15:06 WARN]:        at org.enginehub.piston.inject.MemoizingValueAccess.injectedValue(MemoizingValueAccess.java:84)
[21:15:06 WARN]:        at org.enginehub.piston.impl.CommandParametersImpl.injectedValue(CommandParametersImpl.java:109)
[21:15:06 WARN]:        at org.enginehub.piston.inject.InjectedValueAccess.injectedValue(InjectedValueAccess.java:44)
[21:15:06 WARN]:        at com.sk89q.worldedit.command.ClipboardCommandsRegistration.extract$editSession(ClipboardCommandsRegistration.java:412)
[21:15:06 WARN]:        at com.sk89q.worldedit.command.ClipboardCommandsRegistration.cmd$_cut(ClipboardCommandsRegistration.java:303)
[21:15:06 WARN]:        at org.enginehub.piston.CommandManager.execute(CommandManager.java:157)
[21:15:06 WARN]:        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommandOnCurrentThread$16(PlatformCommandManager.java:693)
[21:15:06 WARN]:        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandTask(PlatformCommandManager.java:709)
[21:15:06 WARN]:        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandOnCurrentThread(PlatformCommandManager.java:695)
[21:15:06 WARN]:        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommand$13(PlatformCommandManager.java:665)
[21:15:06 WARN]:        at com.sk89q.worldedit.extension.platform.AbstractPlayerActor.lambda$runAction$1(AbstractPlayerActor.java:697)
[21:15:06 WARN]:        at com.fastasyncworldedit.core.object.task.AsyncNotifyQueue.lambda$run$0(AsyncNotifyQueue.java:27)
[21:15:06 WARN]:        at com.fastasyncworldedit.core.object.task.AsyncNotifyQueue.lambda$call$1(AsyncNotifyQueue.java:44)
[21:15:06 WARN]:        at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1458)
[21:15:06 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295)
[21:15:06 WARN]:        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
[21:15:06 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
[21:15:06 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
[21:15:06 WARN]:        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
[21:15:06 INFO]: Using com.sk89q.worldedit.bukkit.adapter.impl.fawe.TuinityRelighterFactory_1_17 as relighter factory.
```

**Comment by remyd95** [comment]
Same issue, same error. Using Latest FAWE 1.17, Plotsquared, and Paper builds. 

Current builds are unusable as no one can use the plugin except for op-ed players.

**Comment by byquanton** [comment]
The error happens only when you are in the restricted mode. 

FastAsyncWorldEdit: latest from branch: feature/1.17
PlotSquared: latest from branch: v6
Java Version: 16
Minecraft Version: Purpur 1.17 also tested with Paper 1.17 (both latest)

https://user-images.githubusercontent.com/32410361/123545109-b2b07480-d756-11eb-9422-9b331c1f3e44.mp4

**Comment by Will33ELS** [comment]
Patch on my pull request ;)
