### ISSUE TITLE
Not working from 1.17-1.17.1 version

### ISSUE THREAD

**Issue by permasha** [IntellectualSites/FastAsyncWorldEdit#1174]
### Server Implementation

Paper

### Server Version

1.17.+

### Describe the bug

java.lang.ArrayIndexOutOfBoundsException: Index 19 out of bounds for length 16
[15:55:17 WARN]:        at com.fastasyncworldedit.core.beta.implementation.blocks.CharBlocks.hasSection(CharBlocks.java:125)
[15:55:17 WARN]:        at com.fastasyncworldedit.core.beta.implementation.processors.HeightmapProcessor.processSet(HeightmapProcessor.java:44)
[15:55:17 WARN]:        at com.fastasyncworldedit.core.beta.implementation.processors.MultiBatchProcessor.processSet(MultiBatchProcessor.java:113)
[15:55:17 WARN]:        at com.fastasyncworldedit.core.beta.implementation.processors.MultiBatchProcessor.processSet(MultiBatchProcessor.java:93)
[15:55:17 WARN]:        at com.fastasyncworldedit.core.beta.implementation.processors.BatchProcessorHolder.processSet(BatchProcessorHolder.java:26)
[15:55:17 WARN]:        at com.fastasyncworldedit.core.beta.implementation.processors.BatchProcessorHolder.processSet(BatchProcessorHolder.java:26)
[15:55:17 WARN]:        at com.fastasyncworldedit.core.beta.implementation.chunk.ChunkHolder.call(ChunkHolder.java:932)
[15:55:17 WARN]:        at com.fastasyncworldedit.core.beta.implementation.chunk.ChunkHolder.call(ChunkHolder.java:920)
[15:55:17 WARN]:        at com.fastasyncworldedit.core.beta.implementation.chunk.ChunkHolder.call(ChunkHolder.java:33)
[15:55:17 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[15:55:17 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[15:55:17 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[15:55:17 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[15:55:17 WARN]: java.lang.ArrayIndexOutOfBoundsException: Index 19 out of bounds for length 16
[15:55:17 WARN]:        at com.fastasyncworldedit.core.beta.implementation.blocks.CharBlocks.hasSection(CharBlocks.java:125)
[15:55:17 WARN]:        at com.fastasyncworldedit.core.beta.implementation.processors.HeightmapProcessor.processSet(HeightmapProcessor.java:44)
[15:55:17 WARN]:        at com.fastasyncworldedit.core.beta.implementation.processors.MultiBatchProcessor.processSet(MultiBatchProcessor.java:113)
[15:55:17 WARN]:        at com.fastasyncworldedit.core.beta.implementation.processors.MultiBatchProcessor.processSet(MultiBatchProcessor.java:93)
[15:55:17 WARN]:        at com.fastasyncworldedit.core.beta.implementation.processors.BatchProcessorHolder.processSet(BatchProcessorHolder.java:26)
[15:55:17 WARN]:        at com.fastasyncworldedit.core.beta.implementation.processors.BatchProcessorHolder.processSet(BatchProcessorHolder.java:26)
[15:55:17 WARN]:        at com.fastasyncworldedit.core.beta.implementation.chunk.ChunkHolder.call(ChunkHolder.java:932)
[15:55:17 WARN]:        at com.fastasyncworldedit.core.beta.implementation.chunk.ChunkHolder.call(ChunkHolder.java:920)
[15:55:17 WARN]:        at com.fastasyncworldedit.core.beta.implementation.chunk.ChunkHolder.call(ChunkHolder.java:33)
[15:55:17 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[15:55:17 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[15:55:17 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[15:55:17 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[15:55:17 WARN]: java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: Index 19 out of bounds for length 16
[15:55:17 WARN]:        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
[15:55:17 WARN]:        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
[15:55:17 WARN]:        at com.fastasyncworldedit.core.beta.implementation.queue.SingleThreadQueueExtent.pollSubmissions(SingleThreadQueueExtent.java:

### To Reproduce

1. I prescribe the command //set block
2. The blocks do not change in the selected area, although a message is sent in the game about the successful completion of the operation

### Expected behaviour

I can't use the copy set and replace commands they just don't work

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/25135b5706d746c0a7edec026b27ed16

### Fawe Version

1.17-47;0434b86

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.17/ and the issue still persists.

**Comment by dordsor21** [comment]
Many duplicates of this. Please use search functions.

#1134
