### ISSUE TITLE
EditSessionEvent throws error on cancelation

### ISSUE THREAD

**Issue by MenschenToaster** [IntellectualSites/FastAsyncWorldEdit#1186]
### Server Implementation

Tuinity

### Server Version

1.16.5

### Describe the bug

I get this error when canceling the EditSessonEvent. The player also receives an error message. In my opinion, the player should not receive any message as it is not really an error and intentional.

```
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.sk89q.worldedit.extension.platform.binding.Bindings.invoke(Bindings.java:130) ~[?:?]
        at com.sk89q.worldedit.extension.platform.binding.Bindings.lambda$register$1(Bindings.java:94) ~[?:?]
        at org.enginehub.piston.inject.MapBackedValueStore.lambda$injectedValue$0(MapBackedValueStore.java:56) ~[?:?]
        at java.util.Optional.flatMap(Optional.java:289) ~[?:?]
        at org.enginehub.piston.inject.MapBackedValueStore.injectedValue(MapBackedValueStore.java:56) ~[?:?]
        at org.enginehub.piston.inject.MergedValueAccess.lambda$injectedValue$0(MergedValueAccess.java:54) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958) ~[?:?]
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?]
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647) ~[?:?]
        at org.enginehub.piston.inject.MergedValueAccess.injectedValue(MergedValueAccess.java:57) ~[?:?]
        at org.enginehub.piston.inject.MemoizingValueAccess.injectedValue(MemoizingValueAccess.java:84) ~[?:?]
        at org.enginehub.piston.impl.CommandParametersImpl.injectedValue(CommandParametersImpl.java:109) ~[?:?]
        at org.enginehub.piston.inject.InjectedValueAccess.injectedValue(InjectedValueAccess.java:44) ~[?:?]
        at com.sk89q.worldedit.command.RegionCommandsRegistration.extract$editSession(RegionCommandsRegistration.java:979) ~[?:?]
        at com.sk89q.worldedit.command.RegionCommandsRegistration.cmd$_set(RegionCommandsRegistration.java:575) ~[?:?]
        at org.enginehub.piston.CommandManager.execute(CommandManager.java:157) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommandOnCurrentThread$16(PlatformCommandManager.java:697) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandTask(PlatformCommandManager.java:713) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandOnCurrentThread(PlatformCommandManager.java:699) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommand$13(PlatformCommandManager.java:669) ~[?:?]
        at com.sk89q.worldedit.extension.platform.AbstractPlayerActor.lambda$runAction$1(AbstractPlayerActor.java:697) ~[?:?]
        at com.fastasyncworldedit.core.object.task.AsyncNotifyQueue.lambda$run$0(AsyncNotifyQueue.java:27) ~[?:?]
        at com.fastasyncworldedit.core.object.task.AsyncNotifyQueue.lambda$call$1(AsyncNotifyQueue.java:44) ~[?:?]
        at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1458) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?]
Caused by: java.lang.reflect.InvocationTargetException
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at com.sk89q.worldedit.extension.platform.binding.Bindings.invoke(Bindings.java:127) ~[?:?]
        ... 34 more
Caused by: com.fastasyncworldedit.core.object.exception.FaweException: Manual cancellation
```

### To Reproduce

1. Cancel the EditSessionEvent
2. Make a selection
3. Try to modify the world
4. See the error in console and chat.

### Expected behaviour

The player does not receive a message and the console won't print a stack trace.

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/cb446e8f54d647a7af904a1978a27907

### Fawe Version

FastAsyncWorldEdit-Bukkit-1.17-61.jar	

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.17/ and the issue still persists.

**Comment by dordsor21** [comment]
Do the latyest builds of FAWE have any impact upon the error?

**Comment by dordsor21** [comment]
No response. Assume no longer an issue.
