### ISSUE TITLE
Error with Craftbook5

### ISSUE THREAD

**Issue by kn-km** [IntellectualSites/FastAsyncWorldEdit#1188]
### Server Implementation

Tuinity

### Server Version

1.17.+

### Describe the bug

Craftbook5 does not work with fawe.

### To Reproduce

1. CraftBook5 v5.0.0-SNAPSHOT+4719-6de2ee2
2. FastAsyncWorldEdit-Bukkit-1.17-62.jar
3.
[21:26:56 INFO]: [CraftBook5] Enabling CraftBook5 v5.0.0-SNAPSHOT+4719-6de2ee2
[21:26:56 ERROR]: Error occurred while enabling CraftBook5 v5.0.0-SNAPSHOT+4719-6de2ee2 (Is it up to date?)
java.lang.NoClassDefFoundError: com/sk89q/worldedit/util/io/file/ArchiveUnpacker
        at org.enginehub.craftbook.CraftBook.<init>(CraftBook.java:48) ~[?:?]
        at org.enginehub.craftbook.CraftBook.<clinit>(CraftBook.java:44) ~[?:?]
        at org.enginehub.craftbook.bukkit.CraftBookPlugin.onEnable(CraftBookPlugin.java:128) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.17.1.jar:git-Airplane-53]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Airplane-53]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Airplane-53]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.17.1.jar:git-Airplane-53]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.17.1.jar:git-Airplane-53]
        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:710) ~[patched_1.17.1.jar:git-Airplane-53]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:309) ~[patched_1.17.1.jar:git-Airplane-53]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1197) ~[patched_1.17.1.jar:git-Airplane-53]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[patched_1.17.1.jar:git-Airplane-53]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldedit.util.io.file.ArchiveUnpacker
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:148) ~[patched_1.17.1.jar:git-Airplane-53]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:105) ~[patched_1.17.1.jar:git-Airplane-53]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        ... 13 more
[21:26:56 INFO]: [CraftBook5] Disabling CraftBook5 v5.0.0-SNAPSHOT+4719-6de2ee2
[21:26:56 ERROR]: Error occurred while disabling CraftBook5 v5.0.0-SNAPSHOT+4719-6de2ee2 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "org.enginehub.craftbook.CraftBookPlatform.unload()" because "org.enginehub.craftbook.bukkit.CraftBookPlugin.platform" is null
        at org.enginehub.craftbook.bukkit.CraftBookPlugin.onDisable(CraftBookPlugin.java:251) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.17.1.jar:git-Airplane-53]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:405) ~[patched_1.17.1.jar:git-Airplane-53]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:533) ~[patched_1.17.1.jar:git-Airplane-53]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374) ~[patched_1.17.1.jar:git-Airplane-53]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Airplane-53]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.17.1.jar:git-Airplane-53]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.17.1.jar:git-Airplane-53]
        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:710) ~[patched_1.17.1.jar:git-Airplane-53]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:309) ~[patched_1.17.1.jar:git-Airplane-53]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1197) ~[patched_1.17.1.jar:git-Airplane-53]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[patched_1.17.1.jar:git-Airplane-53]
        at java.lang.Thread.run(Thread.java:831) [?:?]

### Expected behaviour

Work well with craftbook5.

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/bf62aab2ecd845bd88ca72a9e59fbec4

### Fawe Version

FastAsyncWorldEdit version 1.17-62;e6b18cf

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.17/ and the issue still persists.

**Comment by NotMyFault** [comment]
I've addressed that in my pr: https://github.com/IntellectualSites/FastAsyncWorldEdit/pull/1187

**Comment by kn-km** [comment]
> I've addressed that in my pr: #1187

I've tried fe136d81(build 64), this error still occurred.
