### ISSUE TITLE
WorldEdit operations no longer working on build 75+ and produces error in console

### ISSUE THREAD

**Issue by SecretlyJealous** [IntellectualSites/FastAsyncWorldEdit#1196]
### Server Implementation

Tuinity

### Server Version

1.17.+

### Describe the bug

On build 75 onwards worldedit operations no longer work and produce an error in console:
```
[09:54:45 INFO]: Togusta issued server command: //set stone
[09:54:45 INFO]: [PlotSquared/PlotPlayer] Registered class org.bukkit.craftbukkit.v1_17_R1.entity.CraftPlayer as with converter for interface org.bukkit.entity.Player
[09:54:45 INFO]: Using com.sk89q.worldedit.bukkit.adapter.impl.fawe.TuinityRelighterFactory_1_17_1 as relighter factory.
[09:54:45 WARN]: java.lang.NoClassDefFoundError: com/sk89q/worldedit/bukkit/fastutil/longs/LongArraySet
[09:54:45 WARN]:        at com.sk89q.worldedit.bukkit.adapter.impl.fawe.TuinityRelighter_1_17_1.lambda$addChunk$1(TuinityRelighter_1_17_1.java:88)
[09:54:45 WARN]:        at com.sk89q.worldedit.bukkit.fastutil.longs.Long2ObjectLinkedOpenHashMap.computeIfAbsent(Long2ObjectLinkedOpenHashMap.java:823)
[09:54:45 WARN]:        at com.sk89q.worldedit.bukkit.adapter.impl.fawe.TuinityRelighter_1_17_1.addChunk(TuinityRelighter_1_17_1.java:88)
[09:54:45 WARN]:        at com.fastasyncworldedit.core.extent.processor.lighting.RelightProcessor.processSet(RelightProcessor.java:42)
[09:54:45 WARN]:        at com.fastasyncworldedit.core.extent.processor.MultiBatchProcessor.processSet(MultiBatchProcessor.java:113)
[09:54:45 WARN]:        at com.fastasyncworldedit.core.extent.processor.MultiBatchProcessor.processSet(MultiBatchProcessor.java:93)
[09:54:45 WARN]:        at com.fastasyncworldedit.core.extent.processor.BatchProcessorHolder.processSet(BatchProcessorHolder.java:26)
[09:54:45 WARN]:        at com.fastasyncworldedit.core.extent.processor.BatchProcessorHolder.processSet(BatchProcessorHolder.java:26)
[09:54:45 WARN]:        at com.fastasyncworldedit.core.queue.implementation.chunk.ChunkHolder.call(ChunkHolder.java:932)
[09:54:45 WARN]:        at com.fastasyncworldedit.core.queue.implementation.chunk.ChunkHolder.call(ChunkHolder.java:920)
[09:54:45 WARN]:        at com.fastasyncworldedit.core.queue.implementation.chunk.ChunkHolder.call(ChunkHolder.java:33)
[09:54:45 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[09:54:45 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[09:54:45 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[09:54:45 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[09:54:45 WARN]: Caused by: java.lang.ClassNotFoundException: com.sk89q.worldedit.bukkit.fastutil.longs.LongArraySet
[09:54:45 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:146)
[09:54:45 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
[09:54:45 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
[09:54:45 WARN]:        ... 15 more
[09:54:45 WARN]: java.lang.NoClassDefFoundError: com/sk89q/worldedit/bukkit/fastutil/longs/LongArraySet
[09:54:45 WARN]:        at com.sk89q.worldedit.bukkit.adapter.impl.fawe.TuinityRelighter_1_17_1.lambda$addChunk$1(TuinityRelighter_1_17_1.java:88)
[09:54:45 WARN]:        at com.sk89q.worldedit.bukkit.fastutil.longs.Long2ObjectLinkedOpenHashMap.computeIfAbsent(Long2ObjectLinkedOpenHashMap.java:823)
[09:54:45 WARN]:        at com.sk89q.worldedit.bukkit.adapter.impl.fawe.TuinityRelighter_1_17_1.addChunk(TuinityRelighter_1_17_1.java:88)
[09:54:45 WARN]:        at com.fastasyncworldedit.core.extent.processor.lighting.RelightProcessor.processSet(RelightProcessor.java:42)
[09:54:45 WARN]:        at com.fastasyncworldedit.core.extent.processor.MultiBatchProcessor.processSet(MultiBatchProcessor.java:113)
[09:54:45 WARN]:        at com.fastasyncworldedit.core.extent.processor.MultiBatchProcessor.processSet(MultiBatchProcessor.java:93)
[09:54:45 WARN]:        at com.fastasyncworldedit.core.extent.processor.BatchProcessorHolder.processSet(BatchProcessorHolder.java:26)
[09:54:45 WARN]:        at com.fastasyncworldedit.core.extent.processor.BatchProcessorHolder.processSet(BatchProcessorHolder.java:26)
[09:54:45 WARN]:        at com.fastasyncworldedit.core.queue.implementation.chunk.ChunkHolder.call(ChunkHolder.java:932)
[09:54:45 WARN]:        at com.fastasyncworldedit.core.queue.implementation.chunk.ChunkHolder.call(ChunkHolder.java:920)
[09:54:45 WARN]:        at com.fastasyncworldedit.core.queue.implementation.chunk.ChunkHolder.call(ChunkHolder.java:33)
[09:54:45 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[09:54:45 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[09:54:45 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[09:54:45 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[09:54:45 WARN]: Caused by: java.lang.ClassNotFoundException: com.sk89q.worldedit.bukkit.fastutil.longs.LongArraySet
[09:54:45 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:146)
[09:54:45 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
[09:54:45 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
[09:54:45 WARN]:        ... 15 more
[09:54:45 WARN]: java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: com/sk89q/worldedit/bukkit/fastutil/longs/LongArraySet
[09:54:45 WARN]:        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
[09:54:45 WARN]:        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
[09:54:45 WARN]:        at com.fastasyncworldedit.core.queue.implementation.SingleThreadQueueExtent.pollSubmissions(SingleThreadQueueExtent.java:301)
[09:54:45 WARN]:        at com.fastasyncworldedit.core.queue.implementation.SingleThreadQueueExtent.flush(SingleThreadQueueExtent.java:394)
[09:54:45 WARN]:        at com.fastasyncworldedit.core.queue.IQueueExtent.commit(IQueueExtent.java:110)
[09:54:45 WARN]:        at com.fastasyncworldedit.core.extent.PassthroughExtent.commit(PassthroughExtent.java:209)
[09:54:45 WARN]:        at com.sk89q.worldedit.extent.AbstractDelegateExtent.commit(AbstractDelegateExtent.java:151)
[09:54:45 WARN]:        at com.sk89q.worldedit.extent.AbstractDelegateExtent.commit(AbstractDelegateExtent.java:151)
[09:54:45 WARN]:        at com.fastasyncworldedit.core.extent.PassthroughExtent.commit(PassthroughExtent.java:209)
[09:54:45 WARN]:        at com.sk89q.worldedit.EditSession.flushQueue(EditSession.java:1169)
[09:54:45 WARN]:        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandTask(PlatformCommandManager.java:769)
[09:54:45 WARN]:        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandOnCurrentThread(PlatformCommandManager.java:705)
[09:54:45 WARN]:        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommand$13(PlatformCommandManager.java:675)
[09:54:45 WARN]:        at com.sk89q.worldedit.extension.platform.AbstractPlayerActor.lambda$runAction$1(AbstractPlayerActor.java:633)
[09:54:45 WARN]:        at com.fastasyncworldedit.core.util.task.AsyncNotifyQueue.lambda$run$0(AsyncNotifyQueue.java:27)
[09:54:45 WARN]:        at com.fastasyncworldedit.core.util.task.AsyncNotifyQueue.lambda$call$1(AsyncNotifyQueue.java:44)
[09:54:45 WARN]:        at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1458)
[09:54:45 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295)
[09:54:45 WARN]:        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
[09:54:45 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
[09:54:45 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
[09:54:45 WARN]:        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
[09:54:45 WARN]: Caused by: java.lang.NoClassDefFoundError: com/sk89q/worldedit/bukkit/fastutil/longs/LongArraySet
[09:54:45 WARN]:        at com.sk89q.worldedit.bukkit.adapter.impl.fawe.TuinityRelighter_1_17_1.lambda$addChunk$1(TuinityRelighter_1_17_1.java:88)
[09:54:45 WARN]:        at com.sk89q.worldedit.bukkit.fastutil.longs.Long2ObjectLinkedOpenHashMap.computeIfAbsent(Long2ObjectLinkedOpenHashMap.java:823)
[09:54:45 WARN]:        at com.sk89q.worldedit.bukkit.adapter.impl.fawe.TuinityRelighter_1_17_1.addChunk(TuinityRelighter_1_17_1.java:88)
[09:54:45 WARN]:        at com.fastasyncworldedit.core.extent.processor.lighting.RelightProcessor.processSet(RelightProcessor.java:42)
[09:54:45 WARN]:        at com.fastasyncworldedit.core.extent.processor.MultiBatchProcessor.processSet(MultiBatchProcessor.java:113)
[09:54:45 WARN]:        at com.fastasyncworldedit.core.extent.processor.MultiBatchProcessor.processSet(MultiBatchProcessor.java:93)
[09:54:45 WARN]:        at com.fastasyncworldedit.core.extent.processor.BatchProcessorHolder.processSet(BatchProcessorHolder.java:26)
[09:54:45 WARN]:        at com.fastasyncworldedit.core.extent.processor.BatchProcessorHolder.processSet(BatchProcessorHolder.java:26)
[09:54:45 WARN]:        at com.fastasyncworldedit.core.queue.implementation.chunk.ChunkHolder.call(ChunkHolder.java:932)
[09:54:45 WARN]:        at com.fastasyncworldedit.core.queue.implementation.chunk.ChunkHolder.call(ChunkHolder.java:920)
[09:54:45 WARN]:        at com.fastasyncworldedit.core.queue.implementation.chunk.ChunkHolder.call(ChunkHolder.java:33)
[09:54:45 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[09:54:45 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[09:54:45 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[09:54:45 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[09:54:45 WARN]: Caused by: java.lang.ClassNotFoundException: com.sk89q.worldedit.bukkit.fastutil.longs.LongArraySet
[09:54:45 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:146)
[09:54:45 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
[09:54:45 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
[09:54:45 WARN]:        ... 15 more
```
![2021-07-24_09 54 49](https://user-images.githubusercontent.com/10485646/126863253-8bcb2ef5-e2dd-4fc5-a59c-aa0dc4a3257b.png)

Build 73 and below do not have this issue:
![2021-07-24_10 00 10](https://user-images.githubusercontent.com/10485646/126863447-bdfbe9ba-a195-4c71-9c54-834d912934c2.png)

### To Reproduce

1. Use FastAsyncWorldEdit-Bukkit-1.17-75 or above
2. Do a set operation

### Expected behaviour

The operation should work in-game and produce no errors in console

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/3b34e15d7e444b699e6800c68f6ebcef

### Fawe Version

FastAsyncWorldEdit version 1.17-75;50ab8ad

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.17/ and the issue still persists.

**Comment by NotMyFault** [comment]
Fixed in https://github.com/IntellectualSites/FastAsyncWorldEdit/commit/b599d86a1ced10296ef42ff01c1ee3294b75015e
