### ISSUE TITLE
Copying or Saving Schematics is a nightmare.

### ISSUE THREAD

**Issue by c4mer0ns** [IntellectualSites/FastAsyncWorldEdit#1286]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

Basically, I have been trying to figure out for the past 2 days alongside another user in the discord on why this isn't working- I contacted a FAWE Developer and even he was confused why it wasn't and told me to create an issue report. 

Here is my code:

```
                try (EditSession editSession = new EditSessionBuilder(BukkitAdapter.adapt(Bukkit.getWorld("cells"))).fastmode(true).build()) {
                    Clipboard clipboard = new BlockArrayClipboard(region);
                    clipboard.setOrigin(region.getCenter().toBlockPoint());
                    ForwardExtentCopy copy = new ForwardExtentCopy(editSession, region, clipboard, BlockVector3.at(cellData.getCenterPoint().getBlockX(), cellData.getCenterPoint().getBlockY(), cellData.getCenterPoint().getBlockZ()));
                    copy.setCopyingEntities(true);
                    Operations.complete(copy);
                    BuiltInClipboardFormat.SPONGE_SCHEMATIC.getWriter(new FileOutputStream(schematicFile)).write(clipboard);
                }catch (WorldEditException | IOException e) {
                    e.printStackTrace();
                }
```

### To Reproduce

Use my code on the latest version of FAWE with 1.17 Paper with use-disk set to false, if it is not set to false, it will instead crash the server and send around 50mb of errors, and if you don't want any errors you can set compression-level to 0 but still have your schematic not work.

### Expected behaviour

It is supposed to save the schematic as "id.schem" in the "schematics" folder.

### Screenshots / Videos

The error, I tried setting use-disk to false and true.

```
[03:24:59 WARN]: [Cells] Plugin Cells v1.0 generated an exception while executing task 15989
java.lang.ArrayIndexOutOfBoundsException: Index 30 out of bounds for length 30
        at com.fastasyncworldedit.core.extent.clipboard.MemoryOptimizedClipboard.saveOrdinals(MemoryOptimizedClipboard.java:150) ~[?:?]
        at com.fastasyncworldedit.core.extent.clipboard.MemoryOptimizedClipboard.getOrdinal(MemoryOptimizedClipboard.java:133) ~[?:?]
        at com.fastasyncworldedit.core.extent.clipboard.MemoryOptimizedClipboard.getBlock(MemoryOptimizedClipboard.java:243) ~[?:?]
        at com.fastasyncworldedit.core.extent.clipboard.MemoryOptimizedClipboard.getFullBlock(MemoryOptimizedClipboard.java:238) ~[?:?]
        at com.fastasyncworldedit.core.extent.clipboard.MemoryOptimizedClipboard.getFullBlock(MemoryOptimizedClipboard.java:208) ~[?:?]
        at com.sk89q.worldedit.extent.clipboard.BlockArrayClipboard.getFullBlock(BlockArrayClipboard.java:136) ~[?:?]
        at com.sk89q.worldedit.extent.clipboard.io.SpongeSchematicWriter.write2(SpongeSchematicWriter.java:143) ~[?:?]
        at com.sk89q.worldedit.extent.clipboard.io.SpongeSchematicWriter.write(SpongeSchematicWriter.java:77) ~[?:?]
        at com.sk89q.worldedit.extent.clipboard.Clipboard.save(Clipboard.java:217) ~[?:?]
        at com.sk89q.worldedit.extent.clipboard.Clipboard.save(Clipboard.java:207) ~[?:?]
        at com.c4mer0ns.nebula.cells.manager.managers.CellManager$4.run(CellManager.java:214) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-124]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.17.1.jar:git-Paper-124]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Paper-124]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]`

One weird thing I did notice though, is when I set compression-level to 0, the error disappeared.. BUT my schematic still did not properly paste and when I tried it gave me this error.

`[06:15:54 WARN]: java.io.EOFException: Unexpected end of ZLIB input stream
[06:15:54 WARN]:        at java.base/java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:244)
[06:15:54 WARN]:        at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
[06:15:54 WARN]:        at java.base/java.util.zip.GZIPInputStream.read(GZIPInputStream.java:117)
[06:15:54 WARN]:        at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:244)
[06:15:54 WARN]:        at java.base/java.io.BufferedInputStream.skip(BufferedInputStream.java:378)
[06:15:54 WARN]:        at java.base/java.io.DataInputStream.skipBytes(DataInputStream.java:226)
[06:15:54 WARN]:        at com.sk89q.jnbt.NBTInputStream.readTagPayloadLazy(NBTInputStream.java:160)
[06:15:54 WARN]:        at com.sk89q.jnbt.NBTInputStream.readTagPayloadLazy(NBTInputStream.java:344)
[06:15:54 WARN]:        at com.fastasyncworldedit.core.jnbt.streamer.StreamDelegate.acceptRoot(StreamDelegate.java:210)
[06:15:54 WARN]:        at com.sk89q.jnbt.NBTInputStream.readNamedTagLazy(NBTInputStream.java:111)
[06:15:54 WARN]:        at com.fastasyncworldedit.core.extent.clipboard.io.FastSchematicReader.read(FastSchematicReader.java:235)
[06:15:54 WARN]:        at com.sk89q.worldedit.extent.clipboard.io.ClipboardReader.read(ClipboardReader.java:62)
[06:15:54 WARN]:        at com.sk89q.worldedit.extent.clipboard.io.ClipboardReader.read(ClipboardReader.java:47)
[06:15:54 WARN]:        at com.c4mer0ns.nebula.cells.manager.managers.CellManager$2.run(CellManager.java:121)
[06:15:54 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
[06:15:54 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[06:15:54 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[06:15:54 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[06:15:54 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[06:15:54 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[06:15:56 WARN]: java.io.EOFException: Unexpected end of ZLIB input stream
[06:15:56 WARN]:        at java.base/java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:244)
[06:15:56 WARN]:        at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
[06:15:56 WARN]:        at java.base/java.util.zip.GZIPInputStream.read(GZIPInputStream.java:117)
[06:15:56 WARN]:        at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:244)
[06:15:56 WARN]:        at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
[06:15:56 WARN]:        at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:343)
[06:15:56 WARN]:        at java.base/java.io.DataInputStream.readFully(DataInputStream.java:201)
[06:15:56 WARN]:        at java.base/java.io.DataInputStream.readFully(DataInputStream.java:172)
[06:15:56 WARN]:        at com.sk89q.jnbt.NBTInputStream.readTagPayloadLazy(NBTInputStream.java:373)
[06:15:56 WARN]:        at com.sk89q.jnbt.NBTInputStream.readTagPayloadLazy(NBTInputStream.java:346)
[06:15:56 WARN]:        at com.fastasyncworldedit.core.jnbt.streamer.StreamDelegate.acceptRoot(StreamDelegate.java:210)
[06:15:56 WARN]:        at com.sk89q.jnbt.NBTInputStream.readNamedTagLazy(NBTInputStream.java:111)
[06:15:56 WARN]:        at com.fastasyncworldedit.core.extent.clipboard.io.FastSchematicReader.read(FastSchematicReader.java:237)
[06:15:56 WARN]:        at com.sk89q.worldedit.extent.clipboard.io.ClipboardReader.read(ClipboardReader.java:62)
[06:15:56 WARN]:        at com.sk89q.worldedit.extent.clipboard.io.ClipboardReader.read(ClipboardReader.java:47)
[06:15:56 WARN]:        at com.c4mer0ns.nebula.cells.manager.managers.CellManager$2.run(CellManager.java:121)
[06:15:56 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
[06:15:56 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[06:15:56 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[06:15:56 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[06:15:56 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[06:15:56 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)`

### Error log (if applicable)

_No response_

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/4bd54499713a4dc0bed5dc7054bab710

### Fawe Version

FastAsyncWorldEdit version 1.17-210;195a13a

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.17/ and the issue still persists.

### Anything else?

_No response_

**Comment by dordsor21** [comment]
If using the same method there and closing the clipboard, do you still get errors?

**Comment by c4mer0ns** [comment]
Assuming you mean putting the schematic saving outside the edit session, it still has same issue.

**Comment by dordsor21** [comment]
No I mean adding the code "clipboard.close()"

**Comment by c4mer0ns** [comment]
Where do you want me to put that?

**Comment by dordsor21** [comment]
before saving to a schematic

**Comment by c4mer0ns** [comment]
0 errors in console, yet the schematic is 32 kb- and the original is over 600... Seems off, then I tried pasting it annnnd it sent this error once again.


``[06:15:54 WARN]: java.io.EOFException: Unexpected end of ZLIB input stream
[06:15:54 WARN]:        at java.base/java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:244)
[06:15:54 WARN]:        at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
[06:15:54 WARN]:        at java.base/java.util.zip.GZIPInputStream.read(GZIPInputStream.java:117)
[06:15:54 WARN]:        at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:244)
[06:15:54 WARN]:        at java.base/java.io.BufferedInputStream.skip(BufferedInputStream.java:378)
[06:15:54 WARN]:        at java.base/java.io.DataInputStream.skipBytes(DataInputStream.java:226)
[06:15:54 WARN]:        at com.sk89q.jnbt.NBTInputStream.readTagPayloadLazy(NBTInputStream.java:160)
[06:15:54 WARN]:        at com.sk89q.jnbt.NBTInputStream.readTagPayloadLazy(NBTInputStream.java:344)
[06:15:54 WARN]:        at com.fastasyncworldedit.core.jnbt.streamer.StreamDelegate.acceptRoot(StreamDelegate.java:210)
[06:15:54 WARN]:        at com.sk89q.jnbt.NBTInputStream.readNamedTagLazy(NBTInputStream.java:111)
[06:15:54 WARN]:        at com.fastasyncworldedit.core.extent.clipboard.io.FastSchematicReader.read(FastSchematicReader.java:235)
[06:15:54 WARN]:        at com.sk89q.worldedit.extent.clipboard.io.ClipboardReader.read(ClipboardReader.java:62)
[06:15:54 WARN]:        at com.sk89q.worldedit.extent.clipboard.io.ClipboardReader.read(ClipboardReader.java:47)
[06:15:54 WARN]:        at com.c4mer0ns.nebula.cells.manager.managers.CellManager$2.run(CellManager.java:121)
[06:15:54 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
[06:15:54 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[06:15:54 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[06:15:54 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[06:15:54 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[06:15:54 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[06:15:56 WARN]: java.io.EOFException: Unexpected end of ZLIB input stream
[06:15:56 WARN]:        at java.base/java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:244)
[06:15:56 WARN]:        at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
[06:15:56 WARN]:        at java.base/java.util.zip.GZIPInputStream.read(GZIPInputStream.java:117)
[06:15:56 WARN]:        at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:244)
[06:15:56 WARN]:        at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
[06:15:56 WARN]:        at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:343)
[06:15:56 WARN]:        at java.base/java.io.DataInputStream.readFully(DataInputStream.java:201)
[06:15:56 WARN]:        at java.base/java.io.DataInputStream.readFully(DataInputStream.java:172)
[06:15:56 WARN]:        at com.sk89q.jnbt.NBTInputStream.readTagPayloadLazy(NBTInputStream.java:373)
[06:15:56 WARN]:        at com.sk89q.jnbt.NBTInputStream.readTagPayloadLazy(NBTInputStream.java:346)
[06:15:56 WARN]:        at com.fastasyncworldedit.core.jnbt.streamer.StreamDelegate.acceptRoot(StreamDelegate.java:210)
[06:15:56 WARN]:        at com.sk89q.jnbt.NBTInputStream.readNamedTagLazy(NBTInputStream.java:111)
[06:15:56 WARN]:        at com.fastasyncworldedit.core.extent.clipboard.io.FastSchematicReader.read(FastSchematicReader.java:237)
[06:15:56 WARN]:        at com.sk89q.worldedit.extent.clipboard.io.ClipboardReader.read(ClipboardReader.java:62)
[06:15:56 WARN]:        at com.sk89q.worldedit.extent.clipboard.io.ClipboardReader.read(ClipboardReader.java:47)
[06:15:56 WARN]:        at com.c4mer0ns.nebula.cells.manager.managers.CellManager$2.run(CellManager.java:121)
[06:15:56 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
[06:15:56 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[06:15:56 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[06:15:56 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[06:15:56 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[06:15:56 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)`

**Comment by dordsor21** [comment]
What happens if you update to the latest FAWE (1.17-249) and use flush rather than close?

**Comment by dordsor21** [comment]
Latest commit should allow maintaining code between WE and FAWE for schematic saving with clipboards.

**Comment by c4mer0ns** [comment]
Welp.. I am back. Issues are still very much here, upon using the following code:

`                Clipboard clipboard = new BlockArrayClipboard(region);
                clipboard.setOrigin(BlockVector3.at(cellData.getCenterPoint().getBlockX(), cellData.getCenterPoint().getBlockY(), cellData.getCenterPoint().getBlockZ()));
                try (EditSession editSession = WorldEdit.getInstance().newEditSession(BukkitAdapter.adapt(Bukkit.getWorld("cells")))) {
                    ForwardExtentCopy copy = new ForwardExtentCopy(editSession, region, clipboard, BlockVector3.at(cellData.getCenterPoint().getBlockX(), cellData.getCenterPoint().getBlockY(), cellData.getCenterPoint().getBlockZ()));
                    copy.setCopyingEntities(true);
                    Operations.complete(copy);
                    editSession.setBlocks(region, BlockTypes.AIR);
                }catch (WorldEditException e) {
                    e.printStackTrace();
                }
                try (ClipboardWriter writer = BuiltInClipboardFormat.SPONGE_SCHEMATIC.getWriter(new FileOutputStream(schematicFile))) {
                    writer.write(clipboard);
                } catch (IOException e) {
                    e.printStackTrace();
                }`

I get the following error. (another depressing out of bounds error)

`java.lang.ArrayIndexOutOfBoundsException: Index 30 out of bounds for length 30
        at com.fastasyncworldedit.core.extent.clipboard.MemoryOptimizedClipboard.setOrdinal(MemoryOptimizedClipboard.java:172) ~[FastAsyncWorldEdit-Bukkit-1.17-327.jar:?]
        at com.fastasyncworldedit.core.extent.clipboard.MemoryOptimizedClipboard.setBlock(MemoryOptimizedClipboard.java:284) ~[FastAsyncWorldEdit-Bukkit-1.17-327.jar:?]
        at com.fastasyncworldedit.core.extent.clipboard.MemoryOptimizedClipboard.setBlock(MemoryOptimizedClipboard.java:275) ~[FastAsyncWorldEdit-Bukkit-1.17-327.jar:?]
        at com.sk89q.worldedit.extent.clipboard.BlockArrayClipboard.setBlock(BlockArrayClipboard.java:220) ~[FastAsyncWorldEdit-Bukkit-1.17-327.jar:?]
        at com.fastasyncworldedit.core.extent.BlockTranslateExtent.setBlock(BlockTranslateExtent.java:27) ~[FastAsyncWorldEdit-Bukkit-1.17-327.jar:?]
        at com.fastasyncworldedit.core.function.block.SimpleBlockCopy.apply(SimpleBlockCopy.java:20) ~[FastAsyncWorldEdit-Bukkit-1.17-327.jar:?]
        at com.sk89q.worldedit.function.visitor.RegionVisitor.apply(RegionVisitor.java:172) ~[FastAsyncWorldEdit-Bukkit-1.17-327.jar:?]
        at com.sk89q.worldedit.function.visitor.RegionVisitor.resume(RegionVisitor.java:158) ~[FastAsyncWorldEdit-Bukkit-1.17-327.jar:?]
        at com.sk89q.worldedit.function.operation.Operations.completeBlindly(Operations.java:74) ~[FastAsyncWorldEdit-Bukkit-1.17-327.jar:?]
        at com.sk89q.worldedit.function.operation.ForwardExtentCopy.resume(ForwardExtentCopy.java:421) ~[FastAsyncWorldEdit-Bukkit-1.17-327.jar:?]
        at com.sk89q.worldedit.function.operation.Operations.complete(Operations.java:41) ~[FastAsyncWorldEdit-Bukkit-1.17-327.jar:?]
        at com.c4mer0ns.nebula.cells.manager.managers.CellManager$5.run(CellManager.java:243) ~[Cells.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-264]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) [patched_1.17.1.jar:git-Paper-264]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.17.1.jar:git-Paper-264]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]`


I have been heavily relying on this code for a while and need it to keep my server running, and with it having issues like currently it's a big problem.

**Comment by c4mer0ns** [comment]
Not sure if I forgot to mention, when I enable use-disk it just completely explodes and sends a trillion errors (leaving me to disable that option), I have gone through all the configuration and my code multiple times and there is literally nothing I can figure out on my end.

**Comment by dordsor21** [comment]
Without seeing the use disk errors there's nothing we can do. Try clearing the current clipboard folder.

Regarding the code, You must create the clipboard with the correct region. To me it looks like you're attempting to translate the region from where it currently is to minimum point `cellData.getCenterPoint()` in the clipboard, but you're creating the clipboard with region `region` and minimum point `region#getMinimumPoint()`.
