### ISSUE TITLE
Commands not working in-game and producing error

### ISSUE THREAD

**Issue by SecretlyJealous** [IntellectualSites/FastAsyncWorldEdit#1290]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

When selecting position 1 and position 2 then using the //set command nothing happens in-game and an error is produced in console.

```
[13:47:26 INFO]: Togusta issued server command: //set 0
[13:47:26 INFO]: [PlotSquared/PlotPlayer] Registered class org.bukkit.craftbukkit.v1_17_R1.entity.CraftPlayer as with converter for interface org.bukkit.entity.Player
[13:47:26 ERROR]: [com.fastasyncworldedit.core.FaweCache] Catching
java.lang.AbstractMethodError: Receiver class com.sk89q.worldedit.bukkit.adapter.impl.fawe.BukkitGetBlocks_1_17_1 does not define or inherit an implementation of the resolved method 'int getMinSectionPosition()' of interface com.fastasyncworldedit.core.queue.IChunkGet.
        at com.fastasyncworldedit.core.extent.processor.heightmap.HeightmapProcessor.processSet(HeightmapProcessor.java:116) ~[FastAsyncWorldEdit-Bukkit-1.17-226.jar:?]
        at com.fastasyncworldedit.core.extent.processor.MultiBatchProcessor.processSet(MultiBatchProcessor.java:129) ~[FastAsyncWorldEdit-Bukkit-1.17-226.jar:?]
        at com.fastasyncworldedit.core.extent.processor.MultiBatchProcessor.processSet(MultiBatchProcessor.java:109) ~[FastAsyncWorldEdit-Bukkit-1.17-226.jar:?]
        at com.fastasyncworldedit.core.extent.processor.BatchProcessorHolder.processSet(BatchProcessorHolder.java:27) ~[FastAsyncWorldEdit-Bukkit-1.17-226.jar:?]
        at com.fastasyncworldedit.core.extent.processor.BatchProcessorHolder.processSet(BatchProcessorHolder.java:27) ~[FastAsyncWorldEdit-Bukkit-1.17-226.jar:?]
        at com.fastasyncworldedit.core.queue.implementation.chunk.ChunkHolder.call(ChunkHolder.java:1002) ~[FastAsyncWorldEdit-Bukkit-1.17-226.jar:?]
        at com.fastasyncworldedit.core.queue.implementation.chunk.ChunkHolder.call(ChunkHolder.java:991) ~[FastAsyncWorldEdit-Bukkit-1.17-226.jar:?]
        at com.fastasyncworldedit.core.queue.implementation.chunk.ChunkHolder.call(ChunkHolder.java:32) ~[FastAsyncWorldEdit-Bukkit-1.17-226.jar:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[13:47:26 ERROR]: [com.fastasyncworldedit.core.queue.implementation.SingleThreadQueueExtent] Catching
java.util.concurrent.ExecutionException: java.lang.AbstractMethodError: Receiver class com.sk89q.worldedit.bukkit.adapter.impl.fawe.BukkitGetBlocks_1_17_1 does not define or inherit an implementation of the resolved method 'int getMinSectionPosition()' of interface com.fastasyncworldedit.core.queue.IChunkGet.
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:?]
        at java.util.concurrent.FutureTask.get(FutureTask.java:191) ~[?:?]
        at com.fastasyncworldedit.core.queue.implementation.SingleThreadQueueExtent.iterateSubmissions(SingleThreadQueueExtent.java:440) ~[FastAsyncWorldEdit-Bukkit-1.17-226.jar:?]
        at com.fastasyncworldedit.core.queue.implementation.SingleThreadQueueExtent.pollSubmissions(SingleThreadQueueExtent.java:388) ~[FastAsyncWorldEdit-Bukkit-1.17-226.jar:?]
        at com.fastasyncworldedit.core.queue.implementation.SingleThreadQueueExtent.flush(SingleThreadQueueExtent.java:485) ~[FastAsyncWorldEdit-Bukkit-1.17-226.jar:?]
        at com.fastasyncworldedit.core.queue.IQueueExtent.commit(IQueueExtent.java:113) ~[FastAsyncWorldEdit-Bukkit-1.17-226.jar:?]
        at com.fastasyncworldedit.core.extent.PassthroughExtent.commit(PassthroughExtent.java:221) ~[FastAsyncWorldEdit-Bukkit-1.17-226.jar:?]
        at com.sk89q.worldedit.extent.AbstractDelegateExtent.commit(AbstractDelegateExtent.java:152) ~[FastAsyncWorldEdit-Bukkit-1.17-226.jar:?]
        at com.sk89q.worldedit.extent.AbstractDelegateExtent.commit(AbstractDelegateExtent.java:152) ~[FastAsyncWorldEdit-Bukkit-1.17-226.jar:?]
        at com.fastasyncworldedit.core.extent.PassthroughExtent.commit(PassthroughExtent.java:221) ~[FastAsyncWorldEdit-Bukkit-1.17-226.jar:?]
        at com.sk89q.worldedit.EditSession.flushQueue(EditSession.java:1229) ~[FastAsyncWorldEdit-Bukkit-1.17-226.jar:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandTask(PlatformCommandManager.java:800) ~[FastAsyncWorldEdit-Bukkit-1.17-226.jar:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandOnCurrentThread(PlatformCommandManager.java:726) ~[FastAsyncWorldEdit-Bukkit-1.17-226.jar:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommand$13(PlatformCommandManager.java:696) ~[FastAsyncWorldEdit-Bukkit-1.17-226.jar:?]
        at com.sk89q.worldedit.extension.platform.AbstractPlayerActor.lambda$runAction$1(AbstractPlayerActor.java:666) ~[FastAsyncWorldEdit-Bukkit-1.17-226.jar:?]
        at com.fastasyncworldedit.core.util.task.AsyncNotifyQueue.lambda$run$0(AsyncNotifyQueue.java:28) ~[FastAsyncWorldEdit-Bukkit-1.17-226.jar:?]
        at com.fastasyncworldedit.core.util.task.AsyncNotifyQueue.lambda$call$1(AsyncNotifyQueue.java:45) ~[FastAsyncWorldEdit-Bukkit-1.17-226.jar:?]
        at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1458) [?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295) [?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) [?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) [?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) [?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) [?:?]
Caused by: java.lang.AbstractMethodError: Receiver class com.sk89q.worldedit.bukkit.adapter.impl.fawe.BukkitGetBlocks_1_17_1 does not define or inherit an implementation of the resolved method 'int getMinSectionPosition()' of interface com.fastasyncworldedit.core.queue.IChunkGet.
        at com.fastasyncworldedit.core.extent.processor.heightmap.HeightmapProcessor.processSet(HeightmapProcessor.java:116) ~[FastAsyncWorldEdit-Bukkit-1.17-226.jar:?]
        at com.fastasyncworldedit.core.extent.processor.MultiBatchProcessor.processSet(MultiBatchProcessor.java:129) ~[FastAsyncWorldEdit-Bukkit-1.17-226.jar:?]
        at com.fastasyncworldedit.core.extent.processor.MultiBatchProcessor.processSet(MultiBatchProcessor.java:109) ~[FastAsyncWorldEdit-Bukkit-1.17-226.jar:?]
        at com.fastasyncworldedit.core.extent.processor.BatchProcessorHolder.processSet(BatchProcessorHolder.java:27) ~[FastAsyncWorldEdit-Bukkit-1.17-226.jar:?]
        at com.fastasyncworldedit.core.extent.processor.BatchProcessorHolder.processSet(BatchProcessorHolder.java:27) ~[FastAsyncWorldEdit-Bukkit-1.17-226.jar:?]
        at com.fastasyncworldedit.core.queue.implementation.chunk.ChunkHolder.call(ChunkHolder.java:1002) ~[FastAsyncWorldEdit-Bukkit-1.17-226.jar:?]
        at com.fastasyncworldedit.core.queue.implementation.chunk.ChunkHolder.call(ChunkHolder.java:991) ~[FastAsyncWorldEdit-Bukkit-1.17-226.jar:?]
        at com.fastasyncworldedit.core.queue.implementation.chunk.ChunkHolder.call(ChunkHolder.java:32) ~[FastAsyncWorldEdit-Bukkit-1.17-226.jar:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]
```

### To Reproduce

1. Use the //set command

### Expected behaviour

The command should work in-game and produce no errors in console

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/3caa476c229e4272907b83bef89284e3

### Fawe Version

1.17-226;82220ef

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.17/ and the issue still persists.

**Comment by dordsor21** [comment]
Fixed in latest build
