### ISSUE TITLE
NullPointerException on ``//undo``.

### ISSUE THREAD

**Issue by mibby** [IntellectualSites/FastAsyncWorldEdit#1296]
### Server Implementation

Purpur 1.17.1 dev 1383

### Server Version

1.17.1

### Describe the bug

Undo outputs NullPointerException and fails to rollback changes.

```
[20:27:53] [ForkJoinPool-8-worker-3/INFO]: Using com.sk89q.worldedit.bukkit.adapter.impl.fawe.TuinityRelighterFactory_1_17_1 as relighter factory.
[20:27:53] [ForkJoinPool-7-worker-3/WARN]: java.lang.NullPointerException
[20:27:53] [ForkJoinPool-7-worker-3/WARN]: 	at java.base/java.util.Objects.requireNonNull(Objects.java:208)
[20:27:53] [ForkJoinPool-7-worker-3/WARN]: 	at FastAsyncWorldEdit-Bukkit-1.17-242.jar//com.fastasyncworldedit.core.history.changeset.AbstractChangeSet.processSet(AbstractChangeSet.java:175)
[20:27:53] [ForkJoinPool-7-worker-3/WARN]: 	at FastAsyncWorldEdit-Bukkit-1.17-242.jar//com.fastasyncworldedit.core.history.changeset.AbstractChangeSet.lambda$postProcessSet$1(AbstractChangeSet.java:227)
[20:27:53] [ForkJoinPool-7-worker-3/WARN]: 	at FastAsyncWorldEdit-Bukkit-1.17-242.jar//com.fastasyncworldedit.core.history.changeset.AbstractChangeSet.lambda$addWriteTask$2(AbstractChangeSet.java:358)
[20:27:53] [ForkJoinPool-7-worker-3/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1414)
[20:27:53] [ForkJoinPool-7-worker-3/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295)
[20:27:53] [ForkJoinPool-7-worker-3/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
[20:27:53] [ForkJoinPool-7-worker-3/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
[20:27:53] [ForkJoinPool-7-worker-3/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
[20:27:53] [ForkJoinPool-7-worker-3/WARN]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
[20:27:53] [ForkJoinPool-7-worker-5/WARN]: java.lang.NullPointerException
[20:27:53] [ForkJoinPool-7-worker-5/WARN]: 	at java.base/java.util.Objects.requireNonNull(Objects.java:208)
[20:27:53] [ForkJoinPool-7-worker-5/WARN]: 	at FastAsyncWorldEdit-Bukkit-1.17-242.jar//com.fastasyncworldedit.core.history.changeset.AbstractChangeSet.processSet(AbstractChangeSet.java:175)
[20:27:53] [ForkJoinPool-7-worker-5/WARN]: 	at FastAsyncWorldEdit-Bukkit-1.17-242.jar//com.fastasyncworldedit.core.history.changeset.AbstractChangeSet.lambda$postProcessSet$1(AbstractChangeSet.java:227)
[20:27:53] [ForkJoinPool-7-worker-5/WARN]: 	at FastAsyncWorldEdit-Bukkit-1.17-242.jar//com.fastasyncworldedit.core.history.changeset.AbstractChangeSet.lambda$addWriteTask$2(AbstractChangeSet.java:358)
[20:27:53] [ForkJoinPool-7-worker-5/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1414)
[20:27:53] [ForkJoinPool-7-worker-5/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295)
[20:27:53] [ForkJoinPool-7-worker-5/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
[20:27:53] [ForkJoinPool-7-worker-5/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
[20:27:53] [ForkJoinPool-7-worker-5/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
[20:27:53] [ForkJoinPool-7-worker-5/WARN]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

Edit: This also seems to affect brushes when having someone relog and use a brush action bound.
```
[20:56:50] [Server thread/INFO]: TheFinalSnow[/ip] logged in with entity id 73020 at ([world]17034.86796992654, 67.0, 9269.651996836092)
[20:56:51] [ForkJoinPool-7-worker-3/WARN]: java.lang.NullPointerException
[20:56:51] [ForkJoinPool-7-worker-3/WARN]: 	at java.base/java.util.Objects.requireNonNull(Objects.java:208)
[20:56:51] [ForkJoinPool-7-worker-3/WARN]: 	at FastAsyncWorldEdit-Bukkit-1.17-242.jar//com.fastasyncworldedit.core.history.changeset.AbstractChangeSet.processSet(AbstractChangeSet.java:175)
[20:56:51] [ForkJoinPool-7-worker-3/WARN]: 	at FastAsyncWorldEdit-Bukkit-1.17-242.jar//com.fastasyncworldedit.core.history.changeset.AbstractChangeSet.lambda$postProcessSet$1(AbstractChangeSet.java:227)
[20:56:51] [ForkJoinPool-7-worker-3/WARN]: 	at FastAsyncWorldEdit-Bukkit-1.17-242.jar//com.fastasyncworldedit.core.history.changeset.AbstractChangeSet.lambda$addWriteTask$2(AbstractChangeSet.java:358)
[20:56:51] [ForkJoinPool-7-worker-3/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1414)
[20:56:51] [ForkJoinPool-7-worker-3/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295)
[20:56:51] [ForkJoinPool-7-worker-3/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
[20:56:51] [ForkJoinPool-7-worker-3/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
[20:56:51] [ForkJoinPool-7-worker-3/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
[20:56:51] [ForkJoinPool-7-worker-3/WARN]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

### To Reproduce

1. Do any WorldEdit operation. (such as 2 point selection with wand & //cut)
2. Try to undo.
3. Undo does not work and errors in console.

### Expected behaviour

Undo to work without erroring.

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/9904112bfbd345f48837f1b8ad2473d3

### Fawe Version

FastAsyncWorldEdit version 1.17-242;11c3219

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.17/ and the issue still persists.

**Comment by mibby** [comment]
Caused by commit https://github.com/IntellectualSites/FastAsyncWorldEdit/commit/5a9ad2e6895ce5535b2c5974edfeac2a3b9b8ec8#diff-b41e1938f690c1b42c429fd1611dc5028d809c8627e0f2b9767d5e262e3412e7?

Downgrading to dev 233 (build prior to above commit) resolves the problem.

**Comment by NotMyFault** [comment]
Update.
