### ISSUE TITLE
IOOBE on `//snow` with larger radii 

### ISSUE THREAD

**Issue by NotMyFault** [IntellectualSites/FastAsyncWorldEdit#1396]
```
[22:09:07] [Server thread/INFO]: NotMyFault issued server command: //snow 200
[22:09:07] [ForkJoinPool-7-worker-1/INFO]: Using com.sk89q.worldedit.bukkit.adapter.impl.fawe.v1_17_R1_2.PaperweightStarlightRelighterFactory as relighter factory.
[22:09:08] [ForkJoinPool-7-worker-1/ERROR]: An unexpected error while handling a FastAsyncWorldEdit command
java.lang.IndexOutOfBoundsException: Index 3 out of bounds for length 3
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
	at java.util.Objects.checkIndex(Objects.java:359) ~[?:?]
	at java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
	at com.sk89q.worldedit.registry.state.AbstractProperty.getValue(AbstractProperty.java:98) ~[FastAsyncWorldEdit-Bukkit-1.17-c4d0a4e.jar:?]
	at com.sk89q.worldedit.world.block.BlockState.getState(BlockState.java:302) ~[FastAsyncWorldEdit-Bukkit-1.17-c4d0a4e.jar:?]
	at com.sk89q.worldedit.function.block.SnowSimulator.apply(SnowSimulator.java:124) ~[FastAsyncWorldEdit-Bukkit-1.17-c4d0a4e.jar:?]
	at com.sk89q.worldedit.function.visitor.LayerVisitor.resume(LayerVisitor.java:152) ~[FastAsyncWorldEdit-Bukkit-1.17-c4d0a4e.jar:?]
	at com.sk89q.worldedit.function.operation.Operations.completeLegacy(Operations.java:55) ~[FastAsyncWorldEdit-Bukkit-1.17-c4d0a4e.jar:?]
	at com.sk89q.worldedit.EditSession.simulateSnow(EditSession.java:2724) ~[FastAsyncWorldEdit-Bukkit-1.17-c4d0a4e.jar:?]
	at com.sk89q.worldedit.command.UtilityCommands.snow(UtilityCommands.java:544) ~[FastAsyncWorldEdit-Bukkit-1.17-c4d0a4e.jar:?]
	at com.sk89q.worldedit.command.UtilityCommandsRegistration.cmd$snow(UtilityCommandsRegistration.java:665) ~[FastAsyncWorldEdit-Bukkit-1.17-c4d0a4e.jar:?]
	at org.enginehub.piston.CommandManager.execute(CommandManager.java:157) ~[FastAsyncWorldEdit-Bukkit-1.17-c4d0a4e.jar:?]
	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommandOnCurrentThread$16(PlatformCommandManager.java:725) ~[FastAsyncWorldEdit-Bukkit-1.17-c4d0a4e.jar:?]
	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandTask(PlatformCommandManager.java:746) ~[FastAsyncWorldEdit-Bukkit-1.17-c4d0a4e.jar:?]
	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandOnCurrentThread(PlatformCommandManager.java:727) ~[FastAsyncWorldEdit-Bukkit-1.17-c4d0a4e.jar:?]
	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommand$13(PlatformCommandManager.java:697) ~[FastAsyncWorldEdit-Bukkit-1.17-c4d0a4e.jar:?]
	at com.sk89q.worldedit.extension.platform.AbstractPlayerActor.lambda$runAction$1(AbstractPlayerActor.java:671) ~[FastAsyncWorldEdit-Bukkit-1.17-c4d0a4e.jar:?]
	at com.fastasyncworldedit.core.util.task.AsyncNotifyQueue.lambda$run$0(AsyncNotifyQueue.java:28) ~[FastAsyncWorldEdit-Bukkit-1.17-c4d0a4e.jar:?]
	at com.fastasyncworldedit.core.util.task.AsyncNotifyQueue.lambda$call$1(AsyncNotifyQueue.java:45) ~[FastAsyncWorldEdit-Bukkit-1.17-c4d0a4e.jar:?]
	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1428) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
```
Build off of c4d0a4e ~386

**Comment by PierreSchwang** [comment]
Could not reproduce with either 200 nor 400 radius 

![grafik](https://user-images.githubusercontent.com/27054324/141175239-61dfc37f-497b-4e6a-8f17-f80222978da4.png)

**Comment by NotMyFault** [comment]
I can't replicate it either anymore, closing.
