### ISSUE TITLE
WE operation dont works

### ISSUE THREAD

**Issue by chipNaughter** [IntellectualSites/FastAsyncWorldEdit#1411]
### Server Implementation

Purpur

### Server Version

1.17.1

### Describe the bug

The commands are in the chat, like //up and //pos1, but //set and //cyl dont works/ My server version is Purpur 1.17. Is there any way to use the FAWE in 1.17, and not 1.17.1?

### To Reproduce

[02:38:26 WARN]: [FastAsyncWorldEdit] Task #2970 for FastAsyncWorldEdit v1.17-365;e7a6c3e generated an exception
java.lang.NoClassDefFoundError: Could not initialize class com.sk89q.worldedit.bukkit.adapter.impl.fawe.BukkitAdapter_1_17
        at com.sk89q.worldedit.bukkit.adapter.impl.fawe.TuinityRelighter_1_17.postProcessChunks(TuinityRelighter_1_17.java:193) ~[?:?]
        at com.sk89q.worldedit.bukkit.adapter.impl.fawe.TuinityRelighter_1_17.lambda$fixLighting$5(TuinityRelighter_1_17.java:157) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.jar:git-Purpur-1255]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.17.jar:git-Purpur-1255]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1563) ~[patched_1.17.jar:git-Purpur-1255]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:490) ~[patched_1.17.jar:git-Purpur-1255]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1478) ~[patched_1.17.jar:git-Purpur-1255]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1262) ~[patched_1.17.jar:git-Purpur-1255]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[patched_1.17.jar:git-Purpur-1255]

### Expected behaviour

The blocks aren't being placeds with the commands

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/eece795e71594479a968b7c06101beee

### Fawe Version

This server is running Purpur version git-Purpur-1255 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: 89c9c90 on HEAD) Unknown versionThis server is running Purpur version git-Purpur-1255 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: 89c9c90 on HEAD) Unknown version

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.17/ and the issue still persists.

**Comment by NotMyFault** [comment]
Don't tick the checkboxes without going thru them, furthermore, there is no reason to use 1.17 over 1.17.1 as of now.
