### ISSUE TITLE
Schematics with Entitys

### ISSUE THREAD

**Issue by KleinCrafter** [IntellectualSites/FastAsyncWorldEdit#1456]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

I want to transfer a selection with blocks, Chests, Signes and entitys to another Server. (BungeeCord setup)
`//lazycopy` -> schematic -> `//paste` ... origin fail(?) and no container/sign content (Video second try)
`//copy -e` -> schematic ->`//paste` ... no entitys pasted -> Doku fail: `-e skips pasting entities` should be `-e pasting entities`
https://github.com/IntellectualSites/FastAsyncWorldEdit-Documentation/wiki/Main-Commands-and-Permissions#paste---s--a--o
Not in Video:
`copy -e` -> schematic -> `//paste -e` Console error from WorldGuard
```
[16:13:27] [Server thread/ERROR]: Could not pass event BreakBlockEvent to WorldGuard v7.0.6+1cff55f
java.lang.NullPointerException: null
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:877) ~[patched_1.17.1.jar:git-Paper-399]
        at com.fastasyncworldedit.bukkit.adapter.IBukkitAdapter.adapt(IBukkitAdapter.java:324) ~[FastAsyncWorldEdit-Bukkit-1.17-419.jar:?]
        at com.fastasyncworldedit.bukkit.adapter.IDelegateBukkitImplAdapter.adapt(IDelegateBukkitImplAdapter.java:261) ~[FastAsyncWorldEdit-Bukkit-1.17-419.jar:?]
        at com.sk89q.worldedit.bukkit.BukkitAdapter.adapt(BukkitAdapter.java:124) ~[FastAsyncWorldEdit-Bukkit-1.17-419.jar:?]
        at com.sk89q.worldedit.bukkit.BukkitAdapter.adapt(BukkitAdapter.java:225) ~[FastAsyncWorldEdit-Bukkit-1.17-419.jar:?]
        at com.sk89q.worldguard.bukkit.listener.AbstractListener.createRegionAssociable(AbstractListener.java:144) ~[worldguard-bukkit-7.0.6-dist.jar:?]
        at com.sk89q.worldguard.bukkit.listener.RegionProtectionListener.onBreakBlock(RegionProtectionListener.java:214) ~[worldguard-bukkit-7.0.6-dist.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor129.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Paper-399]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Paper-399]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-399]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[patched_1.17.1.jar:git-Paper-399]
        at com.sk89q.worldguard.bukkit.util.Events.fireToCancel(Events.java:74) ~[worldguard-bukkit-7.0.6-dist.jar:?]
        at com.sk89q.worldguard.bukkit.listener.EventAbstractionListener.onEntityChangeBlock(EventAbstractionListener.java:327) ~[worldguard-bukkit-7.0.6-dist.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor165.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Paper-399]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Paper-399]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-399]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[patched_1.17.1.jar:git-Paper-399]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callEntityChangeBlockEvent(CraftEventFactory.java:1271) ~[patched_1.17.1.jar:git-Paper-399]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callEntityChangeBlockEvent(CraftEventFactory.java:1263) ~[patched_1.17.1.jar:git-Paper-399]
        at net.minecraft.world.entity.animal.Fox$FoxEatBerriesGoal.pickSweetBerries(Fox.java:1292) ~[app:?]
        at net.minecraft.world.entity.animal.Fox$FoxEatBerriesGoal.onReachedTarget(Fox.java:1275) ~[app:?]
        at net.minecraft.world.entity.animal.Fox$FoxEatBerriesGoal.tick(Fox.java:1259) ~[app:?]
        at net.minecraft.world.entity.ai.goal.WrappedGoal.tick(WrappedGoal.java:53) ~[app:?]
        at net.minecraft.world.entity.ai.goal.GoalSelector.tick(GoalSelector.java:151) ~[app:?]
        at net.minecraft.world.entity.Mob.inactiveTick(Mob.java:211) ~[app:?]
        at net.minecraft.world.entity.AgeableMob.inactiveTick(AgeableMob.java:32) ~[app:?]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1122) ~[app:?]
        at net.minecraft.world.level.Level.guardEntityTick(Level.java:977) ~[app:?]
        at net.minecraft.server.level.ServerLevel.lambda$tick$7(ServerLevel.java:775) ~[app:?]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:43) ~[patched_1.17.1.jar:git-Paper-399]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:756) ~[app:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1627) ~[patched_1.17.1.jar:git-Paper-399]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:490) ~[patched_1.17.1.jar:git-Paper-399]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1483) ~[patched_1.17.1.jar:git-Paper-399]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1282) ~[patched_1.17.1.jar:git-Paper-399]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-399]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### To Reproduce

BungeeCord Setup with 2 or more server with FAWE and WorldGuard
All server share the same plugins directory `java -jar paper-jar --plugins ../plugins`
Select region with Chests, Signs and Entitys
`//copy -e`
`//schematic save <name>`
switch servers
`//schematic load <name>`
`//paste -e`
WorldGuard errors in Console

### Expected behaviour

`//lazycopy` -> No Origen fail? and copy Chest, Sign content
`//paste -e` Documentation not be wrong
No Exceptions in console,

### Screenshots / Videos

https://youtu.be/9eouS_JY2Vo

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/80b7e42d7a844d939aacb82d34e658a6

### Fawe Version

FastAsyncWorldEdit version 1.17-419;9fdff97

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.17/ and the issue still persists.

**Comment by NotMyFault** [comment]
That is how lazycopy works. It allows you to store larger clipboards under the premise of data loss, e.g. no history.
