### ISSUE TITLE
Task #17 for FastAsyncWorldEdit v2.0.1-SNAPSHOT-72;d17e3a6 generated an exception java.lang.NoClassDefFoundError: com/plotsquared/core/PlotSquared

### ISSUE THREAD

**Issue by PappoYT** [IntellectualSites/FastAsyncWorldEdit#1555]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

After installing FastAsyncWorldEdit I get this error during startup:

```
[06:05:50] [Server thread/WARN]: [FastAsyncWorldEdit] Task #17 for FastAsyncWorldEdit v2.0.1-SNAPSHOT-72;d17e3a6 generated an exception
java.lang.NoClassDefFoundError: com/plotsquared/core/PlotSquared
at com.fastasyncworldedit.bukkit.FaweBukkit.setupPlotSquared(FaweBukkit.java:322) ~[FastAsyncWorldEdit-Bukkit-2.0.1-SNAPSHOT-72.jar:?]
at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-408]
at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Paper-408]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1229) ~[patched_1.17.1.jar:git-Paper-408]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-408]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.plotsquared.core.PlotSquared
at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151) ~[patched_1.17.1.jar:git-Paper-408]
at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[patched_1.17.1.jar:git-Paper-408]
at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
... 6 more
```

### To Reproduce

Install build #72 https://ci.athion.net/job/FastAsyncWorldEdit/
startup server

### Expected behaviour

no errors

### Error log (if applicable)

https://mclo.gs/fstYjJW

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/f166a4ad79a844849695e527fd245a0e

### Fawe Version

FastAsyncWorldEdit-Bukkit-2.0.1-SNAPSHOT-72

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

Opened also https://github.com/IntellectualSites/PlotSquared/issues/3462

**Comment by NotMyFault** [comment]
> [06:05:19] [Server thread/WARN]: `plugins/FastAsyncWorldEdit-Bukkit-2.0.1-SNAPSHOT-72.jar provides `WorldEdit' while this is also the name of `plugins/worldedit-bukkit-7.2.8.jar' in `plugins'

> [06:05:25] [Server thread/WARN]: You installed WorldEdit alongside FastAsyncWorldEdit. That is unneeded and will cause unforeseen issues, because FastAsyncWorldEdit already provides WorldEdit. Stop your server and delete the 'worldedit-bukkit' jar from your plugins folder.
