### ISSUE TITLE
Could not pass event BreakBlockEvent to WorldGuard

### ISSUE THREAD

**Issue by mibby** [IntellectualSites/FastAsyncWorldEdit#1621]
### Server Implementation

Purpur

### Server Version

1.18.1

### Describe the bug

```
[07:45:02] [Server thread/ERROR]: Could not pass event BreakBlockEvent to WorldGuard v7.0.7-SNAPSHOT+2175-dca0515
java.lang.NullPointerException: null
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:889) ~[guava-31.0.1-jre.jar:?]
	at com.fastasyncworldedit.bukkit.adapter.IBukkitAdapter.adapt(IBukkitAdapter.java:324) ~[FastAsyncWorldEdit-Bukkit-2.0.2-SNAPSHOT-100.jar:?]
	at com.fastasyncworldedit.bukkit.adapter.IDelegateBukkitImplAdapter.adapt(IDelegateBukkitImplAdapter.java:261) ~[FastAsyncWorldEdit-Bukkit-2.0.2-SNAPSHOT-100.jar:?]
	at com.sk89q.worldedit.bukkit.BukkitAdapter.adapt(BukkitAdapter.java:124) ~[FastAsyncWorldEdit-Bukkit-2.0.2-SNAPSHOT-100.jar:?]
	at com.sk89q.worldedit.bukkit.BukkitAdapter.adapt(BukkitAdapter.java:225) ~[FastAsyncWorldEdit-Bukkit-2.0.2-SNAPSHOT-100.jar:?]
	at com.sk89q.worldguard.bukkit.listener.AbstractListener.createRegionAssociable(AbstractListener.java:144) ~[worldguard-bukkit-7.0.7-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldguard.bukkit.listener.RegionProtectionListener.onBreakBlock(RegionProtectionListener.java:214) ~[worldguard-bukkit-7.0.7-SNAPSHOT-dist.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor603.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:git-Purpur-1562]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:631) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at com.sk89q.worldguard.bukkit.util.Events.fireAndTestCancel(Events.java:60) ~[worldguard-bukkit-7.0.7-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldguard.bukkit.listener.debounce.legacy.AbstractEventDebounce.debounce(AbstractEventDebounce.java:56) ~[worldguard-bukkit-7.0.7-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldguard.bukkit.listener.debounce.legacy.BlockEntityEventDebounce.debounce(BlockEntityEventDebounce.java:36) ~[worldguard-bukkit-7.0.7-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldguard.bukkit.listener.EventAbstractionListener.onEntityChangeBlock(EventAbstractionListener.java:360) ~[worldguard-bukkit-7.0.7-SNAPSHOT-dist.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor639.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:git-Purpur-1562]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:631) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.callEntityChangeBlockEvent(CraftEventFactory.java:1328) ~[purpur-1.18.1.jar:git-Purpur-1562]
	at net.minecraft.world.entity.ai.goal.EatBlockGoal.tick(EatBlockGoal.java:90) ~[?:?]
	at net.minecraft.world.entity.ai.goal.WrappedGoal.tick(WrappedGoal.java:63) ~[?:?]
	at net.minecraft.world.entity.ai.goal.GoalSelector.tickRunningGoals(GoalSelector.java:155) ~[?:?]
	at net.minecraft.world.entity.ai.goal.GoalSelector.tick(GoalSelector.java:146) ~[?:?]
	at net.minecraft.world.entity.Mob.inactiveTick(Mob.java:218) ~[?:?]
	at net.minecraft.world.entity.AgeableMob.inactiveTick(AgeableMob.java:32) ~[?:?]
	at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1221) ~[?:?]
	at net.minecraft.server.level.ServerLevel.lambda$tick$5(ServerLevel.java:698) ~[?:?]
	at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:43) ~[purpur-1.18.1.jar:git-Purpur-1562]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:676) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1636) ~[purpur-1.18.1.jar:git-Purpur-1562]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:519) ~[purpur-1.18.1.jar:git-Purpur-1562]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1498) ~[purpur-1.18.1.jar:git-Purpur-1562]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1285) ~[purpur-1.18.1.jar:git-Purpur-1562]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322) ~[purpur-1.18.1.jar:git-Purpur-1562]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### To Reproduce

Not entirely sure. Error occurs numerous times throughout the day in the logs.

### Expected behaviour

No errors from WorldGuard.

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/8d5bb060b4f8452eb3f4bf7c5591b328

### Fawe Version

FastAsyncWorldEdit version 2.0.2-SNAPSHOT-100;39081e6

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

Is this caused by a recent change in FAWE? WorldGuard does not typically accept issue reports from WorldEdit forks.

WorldGuard dev 2175
https://builds.enginehub.org/job/worldguard?branch=master

FAWE dev 100
http://ci.athion.net/job/FastAsyncWorldEdit/

Purpur dev 1562
https://purpurmc.org/downloads?v=1.18.1

**Comment by dordsor21** [comment]
This would also be an i0ssue in upstream. Worlds are nullable in org.bukkit.Location

**Comment by mibby** [comment]
Should this be reported upstream to @wizjany then? Still an issue as of

Paper dev 250 (MC 1.18.2)
WorldGuard 7.1.0-SNAPSHOT dev 2189
FastAsyncWorldEdit dev 132

```
[17:19:02] [Server thread/ERROR]: Could not pass event BreakBlockEvent to WorldGuard v7.1.0-SNAPSHOT+2189-bc63119
java.lang.NullPointerException: null
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:889) ~[guava-31.0.1-jre.jar:?]
	at com.fastasyncworldedit.bukkit.adapter.IBukkitAdapter.adapt(IBukkitAdapter.java:324) ~[FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-132.jar:?]
	at com.fastasyncworldedit.bukkit.adapter.IDelegateBukkitImplAdapter.adapt(IDelegateBukkitImplAdapter.java:261) ~[FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-132.jar:?]
	at com.sk89q.worldedit.bukkit.BukkitAdapter.adapt(BukkitAdapter.java:124) ~[FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-132.jar:?]
	at com.sk89q.worldedit.bukkit.BukkitAdapter.adapt(BukkitAdapter.java:225) ~[FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-132.jar:?]
	at com.sk89q.worldguard.bukkit.listener.AbstractListener.createRegionAssociable(AbstractListener.java:144) ~[worldguard-bukkit-7.1.0-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldguard.bukkit.listener.RegionProtectionListener.onBreakBlock(RegionProtectionListener.java:214) ~[worldguard-bukkit-7.1.0-SNAPSHOT-dist.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor603.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:git-Paper-250]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at com.sk89q.worldguard.bukkit.util.Events.fireAndTestCancel(Events.java:60) ~[worldguard-bukkit-7.1.0-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldguard.bukkit.listener.debounce.legacy.AbstractEventDebounce.debounce(AbstractEventDebounce.java:56) ~[worldguard-bukkit-7.1.0-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldguard.bukkit.listener.debounce.legacy.BlockEntityEventDebounce.debounce(BlockEntityEventDebounce.java:36) ~[worldguard-bukkit-7.1.0-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldguard.bukkit.listener.EventAbstractionListener.onEntityChangeBlock(EventAbstractionListener.java:360) ~[worldguard-bukkit-7.1.0-SNAPSHOT-dist.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor639.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:git-Paper-250]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.callEntityChangeBlockEvent(CraftEventFactory.java:1308) ~[paper-1.18.2.jar:git-Paper-250]
	at net.minecraft.world.entity.ai.goal.EatBlockGoal.tick(EatBlockGoal.java:84) ~[?:?]
	at net.minecraft.world.entity.ai.goal.WrappedGoal.tick(WrappedGoal.java:63) ~[?:?]
	at net.minecraft.world.entity.ai.goal.GoalSelector.tickRunningGoals(GoalSelector.java:152) ~[?:?]
	at net.minecraft.world.entity.ai.goal.GoalSelector.tick(GoalSelector.java:143) ~[?:?]
	at net.minecraft.world.entity.Mob.inactiveTick(Mob.java:214) ~[?:?]
	at net.minecraft.world.entity.AgeableMob.inactiveTick(AgeableMob.java:32) ~[?:?]
	at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1136) ~[?:?]
	at net.minecraft.world.level.Level.guardEntityTick(Level.java:936) ~[?:?]
	at net.minecraft.server.level.ServerLevel.lambda$tick$5(ServerLevel.java:673) ~[?:?]
	at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:43) ~[paper-1.18.2.jar:git-Paper-250]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:653) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1591) ~[paper-1.18.2.jar:git-Paper-250]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-250]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1455) ~[paper-1.18.2.jar:git-Paper-250]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1225) ~[paper-1.18.2.jar:git-Paper-250]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-250]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by NotMyFault** [comment]
> Should this be reported upstream to wizjany then? Still an issue as of
> 
> Paper dev 250 (MC 1.18.2) WorldGuard 7.1.0-SNAPSHOT dev 2189 FastAsyncWorldEdit dev 132
> 
> ```
> [17:19:02] [Server thread/ERROR]: Could not pass event BreakBlockEvent to WorldGuard v7.1.0-SNAPSHOT+2189-bc63119
> java.lang.NullPointerException: null
> 	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:889) ~[guava-31.0.1-jre.jar:?]
> 	at com.fastasyncworldedit.bukkit.adapter.IBukkitAdapter.adapt(IBukkitAdapter.java:324) ~[FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-132.jar:?]
> 	at com.fastasyncworldedit.bukkit.adapter.IDelegateBukkitImplAdapter.adapt(IDelegateBukkitImplAdapter.java:261) ~[FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-132.jar:?]
> 	at com.sk89q.worldedit.bukkit.BukkitAdapter.adapt(BukkitAdapter.java:124) ~[FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-132.jar:?]
> 	at com.sk89q.worldedit.bukkit.BukkitAdapter.adapt(BukkitAdapter.java:225) ~[FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-132.jar:?]
> 	at com.sk89q.worldguard.bukkit.listener.AbstractListener.createRegionAssociable(AbstractListener.java:144) ~[worldguard-bukkit-7.1.0-SNAPSHOT-dist.jar:?]
> 	at com.sk89q.worldguard.bukkit.listener.RegionProtectionListener.onBreakBlock(RegionProtectionListener.java:214) ~[worldguard-bukkit-7.1.0-SNAPSHOT-dist.jar:?]
> 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor603.execute(Unknown Source) ~[?:?]
> 	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
> 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:git-Paper-250]
> 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
> 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
> 	at com.sk89q.worldguard.bukkit.util.Events.fireAndTestCancel(Events.java:60) ~[worldguard-bukkit-7.1.0-SNAPSHOT-dist.jar:?]
> 	at com.sk89q.worldguard.bukkit.listener.debounce.legacy.AbstractEventDebounce.debounce(AbstractEventDebounce.java:56) ~[worldguard-bukkit-7.1.0-SNAPSHOT-dist.jar:?]
> 	at com.sk89q.worldguard.bukkit.listener.debounce.legacy.BlockEntityEventDebounce.debounce(BlockEntityEventDebounce.java:36) ~[worldguard-bukkit-7.1.0-SNAPSHOT-dist.jar:?]
> 	at com.sk89q.worldguard.bukkit.listener.EventAbstractionListener.onEntityChangeBlock(EventAbstractionListener.java:360) ~[worldguard-bukkit-7.1.0-SNAPSHOT-dist.jar:?]
> 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor639.execute(Unknown Source) ~[?:?]
> 	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
> 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:git-Paper-250]
> 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
> 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
> 	at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.callEntityChangeBlockEvent(CraftEventFactory.java:1308) ~[paper-1.18.2.jar:git-Paper-250]
> 	at net.minecraft.world.entity.ai.goal.EatBlockGoal.tick(EatBlockGoal.java:84) ~[?:?]
> 	at net.minecraft.world.entity.ai.goal.WrappedGoal.tick(WrappedGoal.java:63) ~[?:?]
> 	at net.minecraft.world.entity.ai.goal.GoalSelector.tickRunningGoals(GoalSelector.java:152) ~[?:?]
> 	at net.minecraft.world.entity.ai.goal.GoalSelector.tick(GoalSelector.java:143) ~[?:?]
> 	at net.minecraft.world.entity.Mob.inactiveTick(Mob.java:214) ~[?:?]
> 	at net.minecraft.world.entity.AgeableMob.inactiveTick(AgeableMob.java:32) ~[?:?]
> 	at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1136) ~[?:?]
> 	at net.minecraft.world.level.Level.guardEntityTick(Level.java:936) ~[?:?]
> 	at net.minecraft.server.level.ServerLevel.lambda$tick$5(ServerLevel.java:673) ~[?:?]
> 	at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:43) ~[paper-1.18.2.jar:git-Paper-250]
> 	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:653) ~[?:?]
> 	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1591) ~[paper-1.18.2.jar:git-Paper-250]
> 	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-250]
> 	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1455) ~[paper-1.18.2.jar:git-Paper-250]
> 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1225) ~[paper-1.18.2.jar:git-Paper-250]
> 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-250]
> 	at java.lang.Thread.run(Thread.java:833) ~[?:?]
> ```
> 
> Also errors for UseBlockEvent.
> 
> ```
> [07:12:53] [Server thread/ERROR]: Could not pass event UseBlockEvent to WorldGuard v7.1.0-SNAPSHOT+2189-bc63119
> java.lang.NullPointerException: null
> 	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:889) ~[guava-31.0.1-jre.jar:?]
> 	at com.fastasyncworldedit.bukkit.adapter.IBukkitAdapter.adapt(IBukkitAdapter.java:324) ~[FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-132.jar:?]
> 	at com.fastasyncworldedit.bukkit.adapter.IDelegateBukkitImplAdapter.adapt(IDelegateBukkitImplAdapter.java:261) ~[FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-132.jar:?]
> 	at com.sk89q.worldedit.bukkit.BukkitAdapter.adapt(BukkitAdapter.java:124) ~[FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-132.jar:?]
> 	at com.sk89q.worldedit.bukkit.BukkitAdapter.adapt(BukkitAdapter.java:225) ~[FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-132.jar:?]
> 	at com.sk89q.worldguard.bukkit.listener.AbstractListener.createRegionAssociable(AbstractListener.java:144) ~[worldguard-bukkit-7.1.0-SNAPSHOT-dist.jar:?]
> 	at com.sk89q.worldguard.bukkit.listener.RegionProtectionListener.onUseBlock(RegionProtectionListener.java:249) ~[worldguard-bukkit-7.1.0-SNAPSHOT-dist.jar:?]
> 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor608.execute(Unknown Source) ~[?:?]
> 	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
> 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:git-Purpur-1592]
> 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
> 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:631) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
> 	at com.sk89q.worldguard.bukkit.util.Events.fireAndTestCancel(Events.java:60) ~[worldguard-bukkit-7.1.0-SNAPSHOT-dist.jar:?]
> 	at com.sk89q.worldguard.bukkit.listener.debounce.legacy.AbstractEventDebounce.debounce(AbstractEventDebounce.java:56) ~[worldguard-bukkit-7.1.0-SNAPSHOT-dist.jar:?]
> 	at com.sk89q.worldguard.bukkit.listener.debounce.legacy.BlockEntityEventDebounce.debounce(BlockEntityEventDebounce.java:36) ~[worldguard-bukkit-7.1.0-SNAPSHOT-dist.jar:?]
> 	at com.sk89q.worldguard.bukkit.listener.EventAbstractionListener.onEntityInteract(EventAbstractionListener.java:583) ~[worldguard-bukkit-7.1.0-SNAPSHOT-dist.jar:?]
> 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor660.execute(Unknown Source) ~[?:?]
> 	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
> 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:git-Purpur-1592]
> 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
> 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:631) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
> 	at net.minecraft.world.entity.ai.behavior.InteractWithDoor.start(InteractWithDoor.java:74) ~[?:?]
> 	at net.minecraft.world.entity.ai.behavior.Behavior.tryStart(Behavior.java:61) ~[purpur-1.18.2.jar:git-Purpur-1592]
> 	at net.minecraft.world.entity.ai.Brain.startEachNonRunningBehavior(Brain.java:512) ~[?:?]
> 	at net.minecraft.world.entity.ai.Brain.tick(Brain.java:471) ~[?:?]
> 	at net.minecraft.world.entity.npc.Villager.mobTick(Villager.java:357) ~[?:?]
> 	at net.minecraft.world.entity.npc.Villager.customServerAiStep(Villager.java:338) ~[?:?]
> 	at net.minecraft.world.entity.Mob.serverAiStep(Mob.java:900) ~[?:?]
> 	at net.minecraft.world.entity.LivingEntity.aiStep(LivingEntity.java:3351) ~[?:?]
> 	at net.minecraft.world.entity.Mob.aiStep(Mob.java:659) ~[?:?]
> 	at net.minecraft.world.entity.AgeableMob.aiStep(AgeableMob.java:154) ~[?:?]
> 	at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3001) ~[?:?]
> 	at net.minecraft.world.entity.Mob.tick(Mob.java:421) ~[?:?]
> 	at net.minecraft.world.entity.npc.Villager.tick(Villager.java:407) ~[?:?]
> 	at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1217) ~[?:?]
> 	at net.minecraft.server.level.ServerLevel.lambda$tick$5(ServerLevel.java:696) ~[?:?]
> 	at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:43) ~[purpur-1.18.2.jar:git-Purpur-1592]
> 	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:674) ~[?:?]
> 	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1619) ~[purpur-1.18.2.jar:git-Purpur-1592]
> 	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:522) ~[purpur-1.18.2.jar:git-Purpur-1592]
> 	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1482) ~[purpur-1.18.2.jar:git-Purpur-1592]
> 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1246) ~[purpur-1.18.2.jar:git-Purpur-1592]
> 	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320) ~[purpur-1.18.2.jar:git-Purpur-1592]
> 	at java.lang.Thread.run(Thread.java:833) ~[?:?]
> ```

If you can replicate that with WorldEdit instead of Fawe in a clean environment too, yeah, please raise an issue on the WorldEdit issue tracker as well.

**Comment by mibby** [comment]
> If you can replicate that with WorldEdit instead of Fawe in a clean environment too, yeah, please raise an issue on the WorldEdit issue tracker as well.

I can try but I'm not entirely sure _what_ exactly is causing it. It just spams my console/logs randomly and the error(s) seem to indicate it comes from many different sources of mobs (villagers, sheep, EatBlockGoal?).

i.e.
https://paste.gg/p/anonymous/09216a954e9a4d23a1bdcd56d76a63e5/files/df2b7bee84104e9b816b1026e9ff0ec4/raw
```at net.minecraft.world.entity.animal.Sheep.aiStep(Sheep.java:183) ~[?:?]``` ?

Besides, wouldn't the error indicate it has to be fixed upstream by WorldGuard anyways because it's WG that causes the error spam? Unless it's just something in FAWE that is breaking WorldGuard if it relies on some WorldEdit api for detection?

**Comment by mibby** [comment]
I couldn't find a way to reproduce this with vanilla worldedit, so not too sure if it's a FAWE specific conflict or just unlucky. Since I can't reproduce with vanilla WorldEdit, I'm unable to open an upstream ticket to WorldGuard if it is indeed an upstream issue. :(

For reference, still occuring as of;
[Purpur-1.18.2-1612 (Paper 1.18.2)](https://purpurmc.org/downloads)
[FastAsyncWorldEdit-Bukkit-2.1.3-SNAPSHOT-164](http://ci.athion.net/job/FastAsyncWorldEdit/changes)
[worldguard-bukkit-7.0.8-SNAPSHOT dev 2194](https://builds.enginehub.org/job/worldguard?branch=version/7.0.x)

UseBlockEvent & BreakBlockEvent 
https://paste.gg/p/anonymous/5555385e6aea4a7183fd1a0cbbde28bb/files/1fce879693e246168eca6a8f89fa9c15/raw

**Comment by PierreSchwang** [comment]
Based on WorldEdits [BukkitAdapter#adapt(org.bukkit.Location)](https://github.com/EngineHub/WorldEdit/blob/master/worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/BukkitAdapter.java#L219) implementation - which calls [BukkitAdapter#adapt(org.bukkit.World)](https://github.com/EngineHub/WorldEdit/blob/88db45b6bcf7465041a910d7c501cc7b9e03a5d2/worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/BukkitAdapter.java#L121) - this should be an issue with plain WorldEdit as well. Those require a non-null world for locations as well.

Not sure if I forgot something which may only cause the issue on FAWE

**Comment by dordsor21** [comment]
Please follow the linked PR above as this is neither a FAWE or WE issue
