### ISSUE TITLE
1.18.2 Unsupported

### ISSUE THREAD

**Issue by Fredo1650** [IntellectualSites/FastAsyncWorldEdit#1644]
### Server Implementation

Paper

### Server Version

1.18.2

### Describe the bug

[19:55:38] [Server thread/INFO]: [FastAsyncWorldEdit] Enabling FastAsyncWorldEdit v2.0.2-SNAPSHOT-114;668227e
[19:55:38] [Server thread/INFO]: [com.fastasyncworldedit.core.Fawe] LZ4 Compression Binding loaded successfully
[19:55:38] [Server thread/INFO]: [com.fastasyncworldedit.core.Fawe] ZSTD Compression Binding loaded successfully
[19:55:38] [Server thread/INFO]: Registering commands with com.sk89q.worldedit.bukkit.BukkitServerInterface
[19:55:38] [Server thread/INFO]: WEPIF: Using the Bukkit Permissions API.
[19:55:39] [Server thread/WARN]: java.lang.NoSuchMethodException: net.minecraft.world.level.chunk.Chunk.m(net.minecraft.core.BlockPosition)
[19:55:39] [Server thread/WARN]: 	at java.base/java.lang.Class.getDeclaredMethod(Class.java:2675)
[19:55:39] [Server thread/WARN]: 	at FastAsyncWorldEdit-2.0.2-114.jar//com.sk89q.worldedit.bukkit.adapter.impl.fawe.v1_18_R1.PaperweightPlatformAdapter.<clinit>(PaperweightPlatformAdapter.java:146)
[19:55:39] [Server thread/WARN]: 	at java.base/java.lang.Class.forName0(Native Method)
[19:55:39] [Server thread/WARN]: 	at java.base/java.lang.Class.forName(Class.java:375)
[19:55:39] [Server thread/WARN]: 	at FastAsyncWorldEdit-2.0.2-114.jar//com.sk89q.worldedit.bukkit.adapter.BukkitImplLoader.loadAdapter(BukkitImplLoader.java:170)
[19:55:39] [Server thread/WARN]: 	at FastAsyncWorldEdit-2.0.2-114.jar//com.sk89q.worldedit.bukkit.WorldEditPlugin.loadAdapter(WorldEditPlugin.java:361)
[19:55:39] [Server thread/WARN]: 	at FastAsyncWorldEdit-2.0.2-114.jar//com.sk89q.worldedit.bukkit.WorldEditPlugin.setupPreWorldData(WorldEditPlugin.java:232)
[19:55:39] [Server thread/WARN]: 	at FastAsyncWorldEdit-2.0.2-114.jar//com.sk89q.worldedit.bukkit.WorldEditPlugin.onEnable(WorldEditPlugin.java:205)
[19:55:39] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[19:55:39] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[19:55:39] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501)
[19:55:39] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559)
[19:55:39] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473)
[19:55:39] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:289)
[19:55:39] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1156)
[19:55:39] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[19:55:39] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[19:55:39] [Server thread/WARN]: java.lang.NoSuchFieldException: l
[19:55:39] [Server thread/WARN]: 	at java.base/java.lang.Class.getDeclaredField(Class.java:2610)
[19:55:39] [Server thread/WARN]: 	at FastAsyncWorldEdit-2.0.2-114.jar//com.sk89q.worldedit.bukkit.adapter.impl.fawe.v1_17_R1_2.PaperweightPlatformAdapter.<clinit>(PaperweightPlatformAdapter.java:95)
[19:55:39] [Server thread/WARN]: 	at java.base/java.lang.Class.forName0(Native Method)
[19:55:39] [Server thread/WARN]: 	at java.base/java.lang.Class.forName(Class.java:375)
[19:55:39] [Server thread/WARN]: 	at FastAsyncWorldEdit-2.0.2-114.jar//com.sk89q.worldedit.bukkit.adapter.BukkitImplLoader.loadAdapter(BukkitImplLoader.java:170)
[19:55:39] [Server thread/WARN]: 	at FastAsyncWorldEdit-2.0.2-114.jar//com.sk89q.worldedit.bukkit.WorldEditPlugin.loadAdapter(WorldEditPlugin.java:361)
[19:55:39] [Server thread/WARN]: 	at FastAsyncWorldEdit-2.0.2-114.jar//com.sk89q.worldedit.bukkit.WorldEditPlugin.setupPreWorldData(WorldEditPlugin.java:232)
[19:55:39] [Server thread/WARN]: 	at FastAsyncWorldEdit-2.0.2-114.jar//com.sk89q.worldedit.bukkit.WorldEditPlugin.onEnable(WorldEditPlugin.java:205)
[19:55:39] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[19:55:39] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[19:55:39] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501)
[19:55:39] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559)
[19:55:39] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473)
[19:55:39] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:289)
[19:55:39] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1156)
[19:55:39] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[19:55:39] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[19:55:39] [Server thread/WARN]: java.lang.NoSuchFieldException: l
[19:55:39] [Server thread/WARN]: 	at java.base/java.lang.Class.getDeclaredField(Class.java:2610)
[19:55:39] [Server thread/WARN]: 	at FastAsyncWorldEdit-2.0.2-114.jar//com.sk89q.worldedit.bukkit.adapter.impl.fawe.BukkitAdapter_1_17.<clinit>(BukkitAdapter_1_17.java:99)
[19:55:39] [Server thread/WARN]: 	at java.base/java.lang.Class.forName0(Native Method)
[19:55:39] [Server thread/WARN]: 	at java.base/java.lang.Class.forName(Class.java:375)
[19:55:39] [Server thread/WARN]: 	at FastAsyncWorldEdit-2.0.2-114.jar//com.sk89q.worldedit.bukkit.adapter.BukkitImplLoader.loadAdapter(BukkitImplLoader.java:170)
[19:55:39] [Server thread/WARN]: 	at FastAsyncWorldEdit-2.0.2-114.jar//com.sk89q.worldedit.bukkit.WorldEditPlugin.loadAdapter(WorldEditPlugin.java:361)
[19:55:39] [Server thread/WARN]: 	at FastAsyncWorldEdit-2.0.2-114.jar//com.sk89q.worldedit.bukkit.WorldEditPlugin.setupPreWorldData(WorldEditPlugin.java:232)
[19:55:39] [Server thread/WARN]: 	at FastAsyncWorldEdit-2.0.2-114.jar//com.sk89q.worldedit.bukkit.WorldEditPlugin.onEnable(WorldEditPlugin.java:205)
[19:55:39] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[19:55:39] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[19:55:39] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501)
[19:55:39] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559)
[19:55:39] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473)
[19:55:39] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:289)
[19:55:39] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1156)
[19:55:39] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[19:55:39] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[19:55:39] [Server thread/WARN]: 
**********************************************
** This FastAsyncWorldEdit version does not fully support your version of Bukkit.
** You can fix this by:
** - Updating your server version (Check /version to see how many versions you are behind)
** - Updating FAWE
**
** When working with blocks or undoing, chests will be empty, signs
** will be blank, and so on. There will be no support for entity
** and block property-related functions.
**********************************************

[19:55:39] [Server thread/WARN]: Failed to load the built-in legacy id registry
java.lang.ExceptionInInitializerError: null
	at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseLogic(DefaultBlockParser.java:543) ~[FastAsyncWorldEdit-2.0.2-114.jar:?]
	at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseFromInput(DefaultBlockParser.java:108) ~[FastAsyncWorldEdit-2.0.2-114.jar:?]
	at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseFromInput(DefaultBlockParser.java:78) ~[FastAsyncWorldEdit-2.0.2-114.jar:?]
	at com.sk89q.worldedit.internal.registry.AbstractFactory.parseFromInput(AbstractFactory.java:89) ~[FastAsyncWorldEdit-2.0.2-114.jar:?]
	at com.sk89q.worldedit.world.registry.LegacyMapper.loadFromResource(LegacyMapper.java:145) ~[FastAsyncWorldEdit-2.0.2-114.jar:?]
	at com.sk89q.worldedit.world.registry.LegacyMapper.<init>(LegacyMapper.java:84) ~[FastAsyncWorldEdit-2.0.2-114.jar:?]
	at com.sk89q.worldedit.world.registry.LegacyMapper.getInstance(LegacyMapper.java:329) ~[FastAsyncWorldEdit-2.0.2-114.jar:?]
	at com.sk89q.worldedit.WorldEdit.loadMappings(WorldEdit.java:431) ~[FastAsyncWorldEdit-2.0.2-114.jar:?]
	at com.sk89q.worldedit.bukkit.WorldEditPlugin.setupPreWorldData(WorldEditPlugin.java:233) ~[FastAsyncWorldEdit-2.0.2-114.jar:?]
	at com.sk89q.worldedit.bukkit.WorldEditPlugin.onEnable(WorldEditPlugin.java:205) ~[FastAsyncWorldEdit-2.0.2-114.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559) ~[paper-1.18.2.jar:git-Paper-225]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473) ~[paper-1.18.2.jar:git-Paper-225]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:289) ~[paper-1.18.2.jar:git-Paper-225]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1156) ~[paper-1.18.2.jar:git-Paper-225]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.2.jar:git-Paper-225]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:143) ~[?:?]
	at org.bukkit.craftbukkit.v1_18_R2.tag.CraftTag.getHandle(CraftTag.java:25) ~[paper-1.18.2.jar:git-Paper-225]
	at org.bukkit.craftbukkit.v1_18_R2.tag.CraftBlockTag.getValues(CraftBlockTag.java:32) ~[paper-1.18.2.jar:git-Paper-225]
	at com.sk89q.worldedit.bukkit.BukkitBlockCategoryRegistry.getFromBukkitTag(BukkitBlockCategoryRegistry.java:35) ~[FastAsyncWorldEdit-2.0.2-114.jar:?]
	at com.sk89q.worldedit.bukkit.BukkitBlockCategoryRegistry.getCategorisedByName(BukkitBlockCategoryRegistry.java:44) ~[FastAsyncWorldEdit-2.0.2-114.jar:?]
	at com.sk89q.worldedit.world.registry.CategoryRegistry.getAll(CategoryRegistry.java:41) ~[FastAsyncWorldEdit-2.0.2-114.jar:?]
	at com.sk89q.worldedit.world.block.BlockCategory.load(BlockCategory.java:49) ~[FastAsyncWorldEdit-2.0.2-114.jar:?]
	at com.sk89q.worldedit.world.block.BlockCategories.get(BlockCategories.java:162) ~[FastAsyncWorldEdit-2.0.2-114.jar:?]
	at com.sk89q.worldedit.world.block.BlockCategories.<clinit>(BlockCategories.java:62) ~[FastAsyncWorldEdit-2.0.2-114.jar:?]
	... 19 more

### To Reproduce

.

### Expected behaviour

.

### Fawe Debugpaste

.

### Fawe Version

FastAsyncWorldEdit-2.0.2-114

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by dordsor21** [comment]
1.18.2 isn't supported yet but I'll leave it open for others trying to us on 1.18.2 to see it

**Comment by SbirTeo** [comment]
The same error with 225 of paper and the latest fawe version

**Comment by aurorasmiles** [comment]
> 1.18.2 isn't supported yet

**Comment by Svish** [comment]
> 1.18.2 isn't supported yet but I'll leave it open for others trying to us on 1.18.2 to see it

Yeah, I came here too because of this. Subscribing to the issue, so I'll hopefully be notified when it _is_ supported 😊👍

**Comment by NotMyFault** [comment]
Feel free to give the snapshot a test: https://github.com/IntellectualSites/FastAsyncWorldEdit/suites/5553586915/artifacts/179161999
Just need to unzip it in the plugins folder, please report any issues found.
Thanks in advance!

**Comment by x9nico** [comment]
> Feel free to give the snapshot a test: https://github.com/IntellectualSites/FastAsyncWorldEdit/suites/5553586915/artifacts/179161999 Just need to unzip it in the plugins folder, please report any issues found. Thanks in advance!

Hey, I still have errors:
`r
[21:48:03 WARN]: Failed to load the built-in legacy id registry
java.lang.ExceptionInInitializerError: null
        at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseLogic(DefaultBlockParser.java:543) ~[FastAsyncWorldEdit-Bukkit-2.0.2-SNAPSHOT.jar:?]
        at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseFromInput(DefaultBlockParser.java:108) ~[FastAsyncWorldEdit-Bukkit-2.0.2-SNAPSHOT.jar:?]
        at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseFromInput(DefaultBlockParser.java:78) ~[FastAsyncWorldEdit-Bukkit-2.0.2-SNAPSHOT.jar:?]
        at com.sk89q.worldedit.internal.registry.AbstractFactory.parseFromInput(AbstractFactory.java:89) ~[FastAsyncWorldEdit-Bukkit-2.0.2-SNAPSHOT.jar:?]
        at com.sk89q.worldedit.world.registry.LegacyMapper.loadFromResource(LegacyMapper.java:137) ~[FastAsyncWorldEdit-Bukkit-2.0.2-SNAPSHOT.jar:?]
        at com.sk89q.worldedit.world.registry.LegacyMapper.<init>(LegacyMapper.java:84) ~[FastAsyncWorldEdit-Bukkit-2.0.2-SNAPSHOT.jar:?]
        at com.sk89q.worldedit.world.registry.LegacyMapper.getInstance(LegacyMapper.java:329) ~[FastAsyncWorldEdit-Bukkit-2.0.2-SNAPSHOT.jar:?]
        at com.sk89q.worldedit.WorldEdit.loadMappings(WorldEdit.java:431) ~[FastAsyncWorldEdit-Bukkit-2.0.2-SNAPSHOT.jar:?]
        at com.sk89q.worldedit.bukkit.WorldEditPlugin.setupPreWorldData(WorldEditPlugin.java:233) ~[FastAsyncWorldEdit-Bukkit-2.0.2-SNAPSHOT.jar:?]
        at com.sk89q.worldedit.bukkit.WorldEditPlugin.onEnable(WorldEditPlugin.java:205) ~[FastAsyncWorldEdit-Bukkit-2.0.2-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559) ~[paper-1.18.2.jar:git-Paper-220]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473) ~[paper-1.18.2.jar:git-Paper-220]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:289) ~[paper-1.18.2.jar:git-Paper-220]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1156) ~[paper-1.18.2.jar:git-Paper-220]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.2.jar:git-Paper-220]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.util.NoSuchElementException: No value present
        at java.util.Optional.get(Optional.java:143) ~[?:?]
        at org.bukkit.craftbukkit.v1_18_R2.tag.CraftTag.getHandle(CraftTag.java:25) ~[paper-1.18.2.jar:git-Paper-220]
        at org.bukkit.craftbukkit.v1_18_R2.tag.CraftBlockTag.getValues(CraftBlockTag.java:32) ~[paper-1.18.2.jar:git-Paper-220]
        at com.sk89q.worldedit.bukkit.BukkitBlockCategoryRegistry.getFromBukkitTag(BukkitBlockCategoryRegistry.java:36) ~[FastAsyncWorldEdit-Bukkit-2.0.2-SNAPSHOT.jar:?]
        at com.sk89q.worldedit.bukkit.BukkitBlockCategoryRegistry.getCategorisedByName(BukkitBlockCategoryRegistry.java:48) ~[FastAsyncWorldEdit-Bukkit-2.0.2-SNAPSHOT.jar:?]
        at com.sk89q.worldedit.world.registry.CategoryRegistry.getAll(CategoryRegistry.java:41) ~[FastAsyncWorldEdit-Bukkit-2.0.2-SNAPSHOT.jar:?]
        at com.sk89q.worldedit.world.block.BlockCategory.load(BlockCategory.java:49) ~[FastAsyncWorldEdit-Bukkit-2.0.2-SNAPSHOT.jar:?]
        at com.sk89q.worldedit.world.block.BlockCategories.get(BlockCategories.java:162) ~[FastAsyncWorldEdit-Bukkit-2.0.2-SNAPSHOT.jar:?]
        at com.sk89q.worldedit.world.block.BlockCategories.<clinit>(BlockCategories.java:62) ~[FastAsyncWorldEdit-Bukkit-2.0.2-SNAPSHOT.jar:?]
        ... 19 more
[21:48:04 WARN]: [com.fastasyncworldedit.core.util.UpdateNotification] You are using a snapshot or a custom version of FAWE. This is not an official build distributed via https://www.spigotmc.org/resources/13932/`

**Comment by NotMyFault** [comment]
Please file an issue [here](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/new/choose) according to the issue template.
This post solely informs about the workflow file, this is not a report thread.

**Comment by x9nico** [comment]
> Please file an issue [here](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/new/choose) according to the issue template. This post solely informs about the workflow file, this is not a report thread.

Nevermind, I updated to latest paper build, and it fixed the error.
