### ISSUE TITLE
Could not pass event WorldInitEvent to FastAsyncWorldEdit when using datapacks

### ISSUE THREAD

**Issue by mibby** [IntellectualSites/FastAsyncWorldEdit#1665]
### Server Implementation

Paper

### Server Version

1.18.2

### Describe the bug

```
[17:14:22] [Server thread/INFO]: Preparing level "world"
[17:14:23] [Server thread/ERROR]: Could not pass event WorldInitEvent to FastAsyncWorldEdit v2.1.1-SNAPSHOT-132;c672d7a
java.lang.NullPointerException: Cannot invoke "net.minecraft.core.Holder.a()" because "value" is null
	at net.minecraft.core.Registry$1.getId(Registry.java:522) ~[?:?]
	at net.minecraft.core.Registry$1.a(Registry.java:519) ~[?:?]
	at com.sk89q.worldedit.bukkit.adapter.impl.fawe.v1_18_R2.PaperweightFaweAdapter.getInternalBiomeId(PaperweightFaweAdapter.java:642) ~[FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-132.jar:?]
	at com.sk89q.worldedit.bukkit.WorldEditPlugin.setupBiomes(WorldEditPlugin.java:323) ~[FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-132.jar:?]
	at com.sk89q.worldedit.bukkit.WorldEditPlugin.setupWorldData(WorldEditPlugin.java:240) ~[FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-132.jar:?]
	at com.sk89q.worldedit.bukkit.WorldEditPlugin$WorldInitListener.onWorldInit(WorldEditPlugin.java:634) ~[FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-132.jar:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:git-Paper-250]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.MinecraftServer.initWorld(MinecraftServer.java:681) ~[paper-1.18.2.jar:git-Paper-250]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:633) ~[paper-1.18.2.jar:git-Paper-250]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.18.2.jar:git-Paper-250]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[paper-1.18.2.jar:git-Paper-250]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1163) ~[paper-1.18.2.jar:git-Paper-250]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-250]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### To Reproduce

* Add datapacks that have custom biomes to the server, i.e. Terralith
* Start server
* See FAWE complain during initialization of server at world loading

### Expected behaviour

No error.

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/c8302be672554bb6b7b90feb8165a799

### Fawe Version

FastAsyncWorldEdit-132

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by NotMyFault** [comment]
I was able to replicate that with [Terralith](https://www.planetminecraft.com/data-pack/terralith-overworld-evolved-100-biomes-caves-and-more/) v2-2

**Comment by mibby** [comment]
For reference, I never noticed this error happening under 1.18.1 so assuming it's due to some recent change in WE or Paper.

**Comment by purejosh** [comment]
Adding to the pot. Having this same error with terralith installed.

**Comment by Lorenzostuy** [comment]
Same here, terralith installed & incendium same error.
