### ISSUE TITLE
"minY <= maxY required" when using /fillr below Y0 and no depth parameter is specified

### ISSUE THREAD

**Issue by clrxbl** [IntellectualSites/FastAsyncWorldEdit#1667]
### Server Implementation

Paper

### Server Version

1.18.2

### Describe the bug

The /fillr command breaks when using it below Y0.

```
[12:29:37 INFO]: Antlia issued server command: //fillr 1 100
[12:29:37 ERROR]: An unexpected error while handling a FastAsyncWorldEdit command
java.lang.IllegalArgumentException: minY <= maxY required
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[guava-31.0.1-jre.jar:?]
        at com.sk89q.worldedit.function.mask.BoundedHeightMask.<init>(BoundedHeightMask.java:44) ~[FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-133.jar:?]
        at com.sk89q.worldedit.EditSession.fillXZ(EditSession.java:1465) ~[FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-133.jar:?]
        at com.sk89q.worldedit.command.UtilityCommands.fillr(UtilityCommands.java:331) ~[FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-133.jar:?]
        at com.sk89q.worldedit.command.UtilityCommandsRegistration.cmd$_fillr(UtilityCommandsRegistration.java:553) ~[FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-133.jar:?]
        at org.enginehub.piston.CommandManager.execute(CommandManager.java:157) ~[FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-133.jar:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommandOnCurrentThread$16(PlatformCommandManager.java:730) ~[FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-133.jar:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandTask(PlatformCommandManager.java:751) ~[FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-133.jar:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandOnCurrentThread(PlatformCommandManager.java:732) ~[FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-133.jar:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommand$13(PlatformCommandManager.java:702) ~[FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-133.jar:?]
        at com.sk89q.worldedit.extension.platform.AbstractPlayerActor.lambda$runAction$1(AbstractPlayerActor.java:672) ~[FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-133.jar:?]
        at com.fastasyncworldedit.core.util.task.AsyncNotifyQueue.lambda$run$0(AsyncNotifyQueue.java:28) ~[FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-133.jar:?]
        at com.fastasyncworldedit.core.util.task.AsyncNotifyQueue.lambda$call$1(AsyncNotifyQueue.java:45) ~[FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-133.jar:?]
        at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1428) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
```

### To Reproduce

1. Go below Y0
2. /fillr 1 10

### Expected behaviour

No exception.

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/3b6551a68fdb415d9ea91a836d50a9e0

### Fawe Version

2.1.1-SNAPSHOT-133;05f80f2

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by clrxbl** [comment]
NMF's workaround is to define a depth in the /fillr command, this does work.
