### ISSUE TITLE
Nothing works

### ISSUE THREAD

**Issue by Uniqeues** [IntellectualSites/FastAsyncWorldEdit#1669]
### Server Implementation

Paper

### Server Version

1.18.2

### Describe the bug

[15:05:57 WARN]: java.lang.NoClassDefFoundError: Could not initialize class com.sk89q.worldedit.world.block.BlockCategories
[15:05:57 WARN]: at FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-128.jar//com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseLogic(DefaultBlockParser.java:543)
[15:05:57 WARN]: at FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-128.jar//com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseFromInput(DefaultBlockParser.java:108)
[15:05:57 WARN]: at FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-128.jar//com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseFromInput(DefaultBlockParser.java:78)
[15:05:57 WARN]: at FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-128.jar//com.sk89q.worldedit.internal.registry.AbstractFactory.parseFromInput(AbstractFactory.java:89)
[15:05:57 WARN]: at FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-128.jar//com.fastasyncworldedit.core.extension.factory.parser.pattern.RichPatternParser.parseFromInput(RichPatternParser.java:130)
[15:05:57 WARN]: at FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-128.jar//com.sk89q.worldedit.extension.factory.PatternFactory.parseFromInput(PatternFactory.java:150)
[15:05:57 WARN]: at FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-128.jar//com.sk89q.worldedit.extension.factory.PatternFactory.parseFromInput(PatternFactory.java:80)
[15:05:57 WARN]: at FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-128.jar//com.sk89q.worldedit.command.argument.FactoryConverter.convert(FactoryConverter.java:144)
[15:05:57 WARN]: at FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-128.jar//org.enginehub.piston.impl.CommandParser.lambda$isAcceptedByTypeParsers$7(CommandParser.java:497)
[15:05:57 WARN]: at java.base/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
[15:05:57 WARN]: at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1856)
[15:05:57 WARN]: at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
[15:05:57 WARN]: at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
[15:05:57 WARN]: at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
[15:05:57 WARN]: at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[15:05:57 WARN]: at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
[15:05:57 WARN]: at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
[15:05:57 WARN]: at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[15:05:57 WARN]: at java.base/java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:632)
[15:05:57 WARN]: at FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-128.jar//org.enginehub.piston.impl.CommandParser.isAcceptedByTypeParsers(CommandParser.java:492)
[15:05:57 WARN]: at FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-128.jar//org.enginehub.piston.impl.CommandParser.parseRegularArgument(CommandParser.java:429)
[15:05:57 WARN]: at FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-128.jar//org.enginehub.piston.impl.CommandParser.parse(CommandParser.java:340)
[15:05:57 WARN]: at FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-128.jar//org.enginehub.piston.impl.CommandManagerImpl.parse(CommandManagerImpl.java:240)
[15:05:57 WARN]: at FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-128.jar//org.enginehub.piston.CommandManager.execute(CommandManager.java:154)
[15:05:57 WARN]: at FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-128.jar//com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommandOnCurrentThread$16(PlatformCommandManager.java:730)
[15:05:57 WARN]: at FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-128.jar//com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandTask(PlatformCommandManager.java:751)
[15:05:57 WARN]: at FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-128.jar//com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandOnCurrentThread(PlatformCommandManager.java:732)
[15:05:57 WARN]: at FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-128.jar//com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommand$13(PlatformCommandManager.java:702)
[15:05:57 WARN]: at FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-128.jar//com.sk89q.worldedit.extension.platform.AbstractPlayerActor.lambda$runAction$1(AbstractPlayerActor.java:672)
[15:05:57 WARN]: at FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-128.jar//com.fastasyncworldedit.core.util.task.AsyncNotifyQueue.lambda$run$0(AsyncNotifyQueue.java:28)
[15:05:57 WARN]: at FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-128.jar//com.fastasyncworldedit.core.util.task.AsyncNotifyQueue.lambda$call$1(AsyncNotifyQueue.java:45)
[15:05:57 WARN]: at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1428)
[15:05:57 WARN]: at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[15:05:57 WARN]: at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[15:05:57 WARN]: at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[15:05:57 WARN]: at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[15:05:57 WARN]: at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[15:05:57 WARN]: java.lang.NoClassDefFoundError: Could not initialize class com.sk89q.worldedit.world.block.BlockCategories
[15:05:57 WARN]: at FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-128.jar//com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseLogic(DefaultBlockParser.java:543)
[15:05:57 WARN]: at FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-128.jar//com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseFromInput(DefaultBlockParser.java:108)
[15:05:57 WARN]: at FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-128.jar//com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseFromInput(DefaultBlockParser.java:78)
[15:05:57 WARN]: at FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-128.jar//com.sk89q.worldedit.internal.registry.AbstractFactory.parseFromInput(AbstractFactory.java:89)
[15:05:57 WARN]: at FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-128.jar//com.fastasyncworldedit.core.extension.factory.parser.pattern.RichPatternParser.parseFromInput(RichPatternParser.java:130)
[15:05:57 WARN]: at FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-128.jar//com.sk89q.worldedit.extension.factory.PatternFactory.parseFromInput(PatternFactory.java:150)
[15:05:57 WARN]: at FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-128.jar//com.sk89q.worldedit.extension.factory.PatternFactory.parseFromInput(PatternFactory.java:80)
[15:05:57 WARN]: at FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-128.jar//com.sk89q.worldedit.command.argument.FactoryConverter.convert(FactoryConverter.java:144)
[15:05:57 WARN]: at FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-128.jar//org.enginehub.piston.impl.CommandParser.conversionFailedException(CommandParser.java:188)
[15:05:57 WARN]: at FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-128.jar//org.enginehub.piston.impl.CommandParser.parseRegularArgument(CommandParser.java:430)
[15:05:57 WARN]: at FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-128.jar//org.enginehub.piston.impl.CommandParser.parse(CommandParser.java:340)
[15:05:57 WARN]: at FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-128.jar//org.enginehub.piston.impl.CommandManagerImpl.parse(CommandManagerImpl.java:240)
[15:05:57 WARN]: at FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-128.jar//org.enginehub.piston.CommandManager.execute(CommandManager.java:154)
[15:05:57 WARN]: at FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-128.jar//com.sk89q.w[..]

[](url
![Screenshot_27](https://user-images.githubusercontent.com/101985113/159170395-bd211b56-f114-4f2a-a00a-b06dd3fa2db8.png)
)

### To Reproduce

I just started my server everything works but when i typed in command /br sphere tnt 1 nothing worked and it spammed this long error i sent you how it looks.

### Expected behaviour

That it will make a sphere of tnt.

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/dde12cd966ea4f788792384f5524ba35

### Fawe Version

2.1.1-SNAPSHOT-128;1708584

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

I tried lower this version but nothing worked.

**Comment by NotMyFault** [comment]
Update Paper, you are 41 builds out of date.
