### ISSUE TITLE
FAWE on 1.16.5

### ISSUE THREAD

**Issue by Justseanchristian** [IntellectualSites/FastAsyncWorldEdit#1879]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

Hello FAWE says it supports 1.16.5 however FAWE also requires Java 17. Paper 1.16.5 will not run on any Java version above Java 16. I attempted to use a fix mentioned in another issue request ("add -DPaper.IgnoreJavaVersion=true to your JVM flags and your server skips the Java version check") however that did not work for me. I understand y'all are following Mojang's java version rules however why does it say it supports 1.16.5 if it simply doesn't? And if it does support 1.16.5 what am I doing wrong?

Thank you!

### To Reproduce

1. Download the latest fawe version
2. Download the latest paper 1.16.5
3. Start the server and place the fawe plugin in the plugins folder
4. Restart the server

### Expected behaviour

```
[18:48:27 ERROR]: Could not load 'plugins/FastAsyncWorldEdit-Bukkit-2.4.1.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: com/sk89q/worldedit/bukkit/WorldEditPlugin has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 60.0
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:157) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:414) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:322) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:393) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:269) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.UnsupportedClassVersionError: com/sk89q/worldedit/bukkit/WorldEditPlugin has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 60.0
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1010) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:201) ~[patched_1.16.5.jar:git-Paper-794]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:586) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:119) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114) ~[patched_1.16.5.jar:git-Paper-794]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:466) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:82) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153) ~[patched_1.16.5.jar:git-Paper-794]
        ... 7 more
```

### Error log (if applicable)

https://gist.github.com/Justseanchristian/de6d4c119179a084b4a7cd18ad6517d8

### Fawe Debugpaste

Not applicable (plugin doesn't start)

### Fawe Version

FastAsyncWorldEdit-Bukkit-2.4.2-SNAPSHOT-247

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by NotMyFault** [comment]
The flag skips the java version check, but you need to launch the server with Java 17 still.
All the flag does is making your server accepting java 17 as valid java version.
