### ISSUE TITLE
Clipboard //cut : OverlappingFileLockException

### ISSUE THREAD

**Issue by chrisgdt** [IntellectualSites/FastAsyncWorldEdit#1909]
### Server Implementation

Paper

### Server Version

1.18.2

### Describe the bug

Sometimes, when someone uses //cut or //copy, an error is thrown and the command has no effect. I also noticed that another error happens when the player disconnects.

### To Reproduce

I actually can't reproduce it, it happens sometimes but not everytime... I wouldn't create an issue here if the error hasn't produced so many times for nearly four months. I hope the stacktrace is enough for you.

### Expected behaviour

A //cut without error, working properly.

### Screenshots / Videos

https://cdn.discordapp.com/attachments/376476327320223747/1009107342589177926/unknown.png

### Error log (if applicable)

https://pastebin.com/MpUbHb2c

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/1aec595eaf7f4e4987842ae5da778130

### Fawe Version

FastAsyncWorldEdit version 2.4.4-SNAPSHOT-264;26bd9ec

### Checklist

- [x] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

Other relevent plugin usage : fastasyncvoxelsniper-2.7.0.jar
Paper version : #347 1.18.2

**Comment by NotMyFault** [comment]
Please provide your full `latest.log` on a paste service, like https://gist.github.com/

**Comment by chrisgdt** [comment]
https://gist.github.com/chrisgdt/ece886f1f811e251c15bd4a5934642d5

**Comment by Floppy012** [comment]
Also happening with `//copy`

<details>
<summary>Exception</summary>

```
[10:39:16 INFO]: User issued server command: //copy
[10:39:16 ERROR]: An unexpected error while handling a FastAsyncWorldEdit command
java.nio.channels.OverlappingFileLockException: null
        at sun.nio.ch.FileLockTable.checkList(FileLockTable.java:229) ~[?:?]
        at sun.nio.ch.FileLockTable.add(FileLockTable.java:123) ~[?:?]
        at sun.nio.ch.FileChannelImpl.lock(FileChannelImpl.java:1276) ~[?:?]
        at java.nio.channels.FileChannel.lock(FileChannel.java:1089) ~[?:?]
        at com.fastasyncworldedit.core.extent.clipboard.DiskOptimizedClipboard.init(DiskOptimizedClipboard.java:288) ~[FastAsyncWorldEdit.jar:?]
        at com.fastasyncworldedit.core.extent.clipboard.DiskOptimizedClipboard.<init>(DiskOptimizedClipboard.java:140) ~[FastAsyncWorldEdit.jar:?]
        at com.fastasyncworldedit.core.extent.clipboard.DiskOptimizedClipboard.<init>(DiskOptimizedClipboard.java:78) ~[FastAsyncWorldEdit.jar:?]
        at com.sk89q.worldedit.extent.clipboard.Clipboard.create(Clipboard.java:101) ~[FastAsyncWorldEdit.jar:?]
        at com.sk89q.worldedit.extent.clipboard.BlockArrayClipboard.<init>(BlockArrayClipboard.java:114) ~[FastAsyncWorldEdit.jar:?]
        at com.sk89q.worldedit.command.ClipboardCommands.copy(ClipboardCommands.java:142) ~[FastAsyncWorldEdit.jar:?]
        at com.sk89q.worldedit.command.ClipboardCommandsRegistration.cmd$_copy(ClipboardCommandsRegistration.java:270) ~[FastAsyncWorldEdit.jar:?]
        at org.enginehub.piston.CommandManager.execute(CommandManager.java:157) ~[FastAsyncWorldEdit.jar:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommandOnCurrentThread$16(PlatformCommandManager.java:730) ~[FastAsyncWorldEdit.jar:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandTask(PlatformCommandManager.java:751) ~[FastAsyncWorldEdit.jar:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandOnCurrentThread(PlatformCommandManager.java:732) ~[FastAsyncWorldEdit.jar:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommand$13(PlatformCommandManager.java:702) ~[FastAsyncWorldEdit.jar:?]
        at com.sk89q.worldedit.extension.platform.AbstractPlayerActor.lambda$runAction$1(AbstractPlayerActor.java:672) ~[FastAsyncWorldEdit.jar:?]
        at com.fastasyncworldedit.core.util.task.AsyncNotifyQueue.lambda$run$0(AsyncNotifyQueue.java:28) ~[FastAsyncWorldEdit.jar:?]
        at com.fastasyncworldedit.core.util.task.AsyncNotifyQueue.lambda$call$1(AsyncNotifyQueue.java:45) ~[FastAsyncWorldEdit.jar:?]
        at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1428) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
```

</details>

## Version Information

System: Docker container (image is `openjdk:17-buster`). 
Server-Software: Paper 1.19 (ref: [c029645443cf7db35e8d2e2a0de05741993241c7](https://github.com/PaperMC/Paper/tree/c029645443cf7db35e8d2e2a0de05741993241c7))
FAWE-Version: `2.4.3;a55bb5` (also running FAVS `2.7.0`)

Probably related to #1260 and #356 

(If you need any more information, ping me 😄)

**Comment by liorsl** [comment]
Having the exact same issue after updating to the latest version.
System: Docker container (image is pterodactyl yolks:java_17).
Server-Software: Paper 1.18.2 build 310
FAWE-Version: 2.4.3;a55bb5

**Comment by PaBox** [comment]
I am also having this Problem: 
```
[11:43:49] [Server thread/INFO]: Jojo issued server command: //copy
[11:43:49] [ForkJoinPool-8-worker-53/ERROR]: An unexpected error while handling a FastAsyncWorldEdit command
java.nio.channels.OverlappingFileLockException: null
	at sun.nio.ch.FileLockTable.checkList(FileLockTable.java:229) ~[?:?]
	at sun.nio.ch.FileLockTable.add(FileLockTable.java:123) ~[?:?]
	at sun.nio.ch.FileChannelImpl.lock(FileChannelImpl.java:1276) ~[?:?]
	at java.nio.channels.FileChannel.lock(FileChannel.java:1089) ~[?:?]
	at com.fastasyncworldedit.core.extent.clipboard.DiskOptimizedClipboard.init(DiskOptimizedClipboard.java:288) ~[?:?]
	at com.fastasyncworldedit.core.extent.clipboard.DiskOptimizedClipboard.<init>(DiskOptimizedClipboard.java:140) ~[?:?]
	at com.fastasyncworldedit.core.extent.clipboard.DiskOptimizedClipboard.<init>(DiskOptimizedClipboard.java:78) ~[?:?]
	at com.sk89q.worldedit.extent.clipboard.Clipboard.create(Clipboard.java:101) ~[?:?]
	at com.sk89q.worldedit.extent.clipboard.BlockArrayClipboard.<init>(BlockArrayClipboard.java:114) ~[?:?]
	at com.sk89q.worldedit.command.ClipboardCommands.copy(ClipboardCommands.java:157) ~[?:?]
	at com.sk89q.worldedit.command.ClipboardCommandsRegistration.cmd$_copy(ClipboardCommandsRegistration.java:270) ~[?:?]
	at org.enginehub.piston.CommandManager.execute(CommandManager.java:157) ~[?:?]
	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommandOnCurrentThread$16(PlatformCommandManager.java:730) ~[?:?]
	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandTask(PlatformCommandManager.java:751) ~[?:?]
	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandOnCurrentThread(PlatformCommandManager.java:732) ~[?:?]
	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommand$13(PlatformCommandManager.java:702) ~[?:?]
	at com.sk89q.worldedit.extension.platform.AbstractPlayerActor.lambda$runAction$1(AbstractPlayerActor.java:672) ~[?:?]
	at com.fastasyncworldedit.core.util.task.AsyncNotifyQueue.lambda$run$0(AsyncNotifyQueue.java:28) ~[?:?]
	at com.fastasyncworldedit.core.util.task.AsyncNotifyQueue.lambda$call$1(AsyncNotifyQueue.java:45) ~[?:?]
	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1428) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
```



> FYI the workaround in #356 (setting `use-disk` under `clipboard` to `false`) still works

This does work, though with multiple Worlds on one Server its cheaper to buy disks then more RAM. Will there be a fix in the long run? Could it be due to it being an offline server and of misplaced UUIDs? We just wouldn't like to turn this option on forever :)

Here is my debugpaste:
https://athion.net/ISPaster/paste/view/1d54776d7710486bbb2c5c036e26ca4a
