### ISSUE TITLE
console error "blocks weren't placed because they were outside your allowed region" with FAWE API

### ISSUE THREAD

**Issue by fhebuterne** [IntellectualSites/FastAsyncWorldEdit#194]
# Bug report for FastAsyncWorldEdit 1.13.2

**[REQUIRED] FastAsyncWorldEdit Version Number:** 

[22:24:59] [Client thread/INFO]: [CHAT] FastAsyncWorldEdit-1.13-170 by Empire92
[22:24:59] [Client thread/INFO]: [CHAT] ----------- Platforms -----------
[22:24:59] [Client thread/INFO]: [CHAT]  - DATE: 10 juil. 2019 00:00:00
[22:24:59] [Client thread/INFO]: [CHAT]  - COMMIT: 2c76c23
[22:24:59] [Client thread/INFO]: [CHAT]  - BUILD: 170
[22:24:59] [Client thread/INFO]: [CHAT]  - PLATFORM: bukkit
[22:24:59] [Client thread/INFO]: [CHAT] ------------------------------------
[22:24:59] [Client thread/INFO]: [CHAT] ----------- Platforms -----------
[22:24:59] [Client thread/INFO]: [CHAT] * Bukkit
[22:24:59] [Client thread/INFO]: [CHAT] ----------- Capabilities -----------
[22:24:59] [Client thread/INFO]: [CHAT]  - GAME_HOOKS: Bukkit
[22:24:59] [Client thread/INFO]: [CHAT]  - CONFIGURATION: Bukkit
[22:24:59] [Client thread/INFO]: [CHAT]  - USER_COMMANDS: Bukkit
[22:24:59] [Client thread/INFO]: [CHAT]  - PERMISSIONS: Bukkit
[22:24:59] [Client thread/INFO]: [CHAT]  - WORLDEDIT_CUI: Bukkit
[22:24:59] [Client thread/INFO]: [CHAT]  - WORLD_EDITING: Bukkit
[22:24:59] [Client thread/INFO]: [CHAT] ------------------------------------

**[REQUIRED] Spigot/Paper Version Number:**
Paper version git-Paper-639 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**Links to config.yml and config-legacy.yml file:** 
config.yml : https://pastebin.com/iw4emjBY
config-legacy.yml : https://pastebin.com/BdfDTR00

**[REQUIRED] Description of the problem:**
When i using FAWE API to paste a schematic with console, i have this error :

[22:28:58 INFO]: (FAWE) 42237 blocks weren't placed because they were outside your allowed region.

And i have put region-restrictions on false.

**Plugins being used on the server:**
FAWE, MultiverseCore, WorldBorder, WorldEdit (FAWE) and CustomPlugin to paste schem

**How to replicate**:

Using this java code :
https://pastebin.com/mVj6V0Cf

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.13.2](https://ci.athion.net/job/FastAsyncWorldEdit-Breaking/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by Tsoccerguy3** [comment]
does using /wea fix this , it may be a permission problem

**Comment by fabien91** [comment]
> does using /wea fix this , it may be a permission problem

Permission problem with API ?? When i use /wea in server console, i have an other error :

`[21:41:17] [Craft Scheduler Thread - 10/WARN]: [WorldEdit] Plugin WorldEdit v1.13.163 generated an exception while executing task 14
java.lang.NullPointerException: null
	at com.sk89q.worldedit.extension.platform.CommandManager.lambda$handleCommand$1(CommandManager.java:537) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.13.2.jar:git-Paper-629]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.13.2.jar:git-Paper-629]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.13.2.jar:git-Paper-629]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_201]`

**Comment by fabien91** [comment]
Any news ? I can't paste big schematic with your plugin :(

**Comment by ArtNRG** [comment]
I have the same issue using FastAsyncWorldEdit-Breaking build 186.

**Comment by IronApollo** [comment]
The most common cause of this issue is attempting to paste the schematic outside of the world height bounds, 0<y<256. If you think this isn't the case, check again then check again more thoroughly.

**Comment by aurorasmiles** [comment]
Since there has been no reply for over a year now, I'm closing this issue
