### ISSUE TITLE
UnsupportedOperationException on Paper-177

### ISSUE THREAD

**Issue by Baktus79** [IntellectualSites/FastAsyncWorldEdit#1964]
### Server Implementation

Paper

### Server Version

1.19.2

### Describe the bug

A problem occurs when I try to set blocks. Recently, Paper has done a chunk system rewrite that most likely has something to do with this. The chunk is not updated and the area to be updated is locked. If I disconnect and reconnect, the chunk appears to be updated and everything looks great.

```
[10:06:19] [ForkJoinPool-7-worker-1/INFO]: Using com.sk89q.worldedit.bukkit.adapter.impl.fawe.v1_19_R1.PaperweightStarlightRelighterFactory as relighter factory.
[10:06:19] [Server thread/WARN]: [FastAsyncWorldEdit] Task #2487 for FastAsyncWorldEdit v2.4.5-SNAPSHOT-273;8233f13 generated an exception
java.lang.UnsupportedOperationException: null
	at net.minecraft.server.level.ChunkHolder.getTickingChunkFuture(ChunkHolder.java:178) ~[?:?]
	at com.sk89q.worldedit.bukkit.adapter.impl.fawe.v1_19_R1.PaperweightPlatformAdapter.sendChunk(PaperweightPlatformAdapter.java:283) ~[FastAsyncWorldEdit-Bukkit-2.4.5-SNAPSHOT-273.jar:?]
	at com.sk89q.worldedit.bukkit.adapter.impl.fawe.v1_19_R1.PaperweightStarlightRelighter.postProcessChunks(PaperweightStarlightRelighter.java:193) ~[FastAsyncWorldEdit-Bukkit-2.4.5-SNAPSHOT-273.jar:?]
	at com.sk89q.worldedit.bukkit.adapter.impl.fawe.v1_19_R1.PaperweightStarlightRelighter.lambda$fixLighting$5(PaperweightStarlightRelighter.java:157) ~[FastAsyncWorldEdit-Bukkit-2.4.5-SNAPSHOT-273.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-177]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.2.jar:git-Paper-177]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1473) ~[paper-1.19.2.jar:git-Paper-177]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.2.jar:git-Paper-177]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.2.jar:git-Paper-177]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.2.jar:git-Paper-177]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-177]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### To Reproduce

1. Using the wooden axe to mark the area.
2. Using command `//set grass_block`

### Expected behaviour

The area should have been covered with grass blocks.

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/7b015bf2a716486e89c374f26405876d

### Fawe Version

FastAsyncWorldEdit version 2.4.5-SNAPSHOT-273;8233f13

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by SirYwell** [comment]
Update FAWE, this is fixed for >3 weeks already (#1884).

**Comment by Baktus79** [comment]
Omg, guess I need another coffee. I did check for updates and I did download the newest version, but I forgot to update it on the server. My bad...
