### ISSUE TITLE
StringIndexOutOfBoundsException: String index out of range: 0

### ISSUE THREAD

**Issue by mibby** [IntellectualSites/FastAsyncWorldEdit#2041]
### Server Implementation

Paper

### Server Version

1.19.2

### Describe the bug

```
[11:01:46] [Paper Async Command Builder Thread Pool - 0/WARN]: java.lang.StringIndexOutOfBoundsException: String index out of range: 0
[11:01:46] [Paper Async Command Builder Thread Pool - 0/WARN]: 	at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:48)
[11:01:46] [Paper Async Command Builder Thread Pool - 0/WARN]: 	at java.base/java.lang.String.charAt(String.java:1515)
[11:01:46] [Paper Async Command Builder Thread Pool - 0/WARN]: 	at FastAsyncWorldEdit-Bukkit-2.4.11-SNAPSHOT-324.jar//com.sk89q.worldedit.world.entity.EntityTypes.convertEntityId(EntityTypes.java:460)
[11:01:46] [Paper Async Command Builder Thread Pool - 0/WARN]: 	at FastAsyncWorldEdit-Bukkit-2.4.11-SNAPSHOT-324.jar//com.sk89q.worldedit.world.entity.EntityTypes.parse(EntityTypes.java:469)
[11:01:46] [Paper Async Command Builder Thread Pool - 0/WARN]: 	at FastAsyncWorldEdit-Bukkit-2.4.11-SNAPSHOT-324.jar//com.sk89q.worldedit.entity.BaseEntity.<init>(BaseEntity.java:118)
[11:01:46] [Paper Async Command Builder Thread Pool - 0/WARN]: 	at FastAsyncWorldEdit-Bukkit-2.4.11-SNAPSHOT-324.jar//com.fastasyncworldedit.core.extent.clipboard.DiskOptimizedClipboard.loadNBTFromFileFooter(DiskOptimizedClipboard.java:250)
[11:01:46] [Paper Async Command Builder Thread Pool - 0/WARN]: 	at FastAsyncWorldEdit-Bukkit-2.4.11-SNAPSHOT-324.jar//com.fastasyncworldedit.core.extent.clipboard.DiskOptimizedClipboard.<init>(DiskOptimizedClipboard.java:182)
[11:01:46] [Paper Async Command Builder Thread Pool - 0/WARN]: 	at FastAsyncWorldEdit-Bukkit-2.4.11-SNAPSHOT-324.jar//com.fastasyncworldedit.core.extent.clipboard.DiskOptimizedClipboard.<init>(DiskOptimizedClipboard.java:156)
[11:01:46] [Paper Async Command Builder Thread Pool - 0/WARN]: 	at FastAsyncWorldEdit-Bukkit-2.4.11-SNAPSHOT-324.jar//com.fastasyncworldedit.core.extent.clipboard.DiskOptimizedClipboard.loadFromFile(DiskOptimizedClipboard.java:203)
[11:01:46] [Paper Async Command Builder Thread Pool - 0/WARN]: 	at FastAsyncWorldEdit-Bukkit-2.4.11-SNAPSHOT-324.jar//com.sk89q.worldedit.entity.Player.loadClipboardFromDisk(Player.java:473)
[11:01:46] [Paper Async Command Builder Thread Pool - 0/WARN]: 	at FastAsyncWorldEdit-Bukkit-2.4.11-SNAPSHOT-324.jar//com.sk89q.worldedit.bukkit.BukkitPlayer.<init>(BukkitPlayer.java:112)
[11:01:46] [Paper Async Command Builder Thread Pool - 0/WARN]: 	at FastAsyncWorldEdit-Bukkit-2.4.11-SNAPSHOT-324.jar//com.sk89q.worldedit.bukkit.WorldEditPlugin.wrapPlayer(WorldEditPlugin.java:558)
[11:01:46] [Paper Async Command Builder Thread Pool - 0/WARN]: 	at FastAsyncWorldEdit-Bukkit-2.4.11-SNAPSHOT-324.jar//com.sk89q.worldedit.bukkit.WorldEditPlugin.wrapCommandSender(WorldEditPlugin.java:588)
[11:01:46] [Paper Async Command Builder Thread Pool - 0/WARN]: 	at FastAsyncWorldEdit-Bukkit-2.4.11-SNAPSHOT-324.jar//com.sk89q.worldedit.bukkit.BukkitCommandInspector.lambda$testPermission$0(BukkitCommandInspector.java:80)
[11:01:46] [Paper Async Command Builder Thread Pool - 0/WARN]: 	at FastAsyncWorldEdit-Bukkit-2.4.11-SNAPSHOT-324.jar//org.enginehub.piston.inject.MapBackedValueStore.lambda$injectedValue$0(MapBackedValueStore.java:56)
[11:01:46] [Paper Async Command Builder Thread Pool - 0/WARN]: 	at java.base/java.util.Optional.flatMap(Optional.java:289)
[11:01:46] [Paper Async Command Builder Thread Pool - 0/WARN]: 	at FastAsyncWorldEdit-Bukkit-2.4.11-SNAPSHOT-324.jar//org.enginehub.piston.inject.MapBackedValueStore.injectedValue(MapBackedValueStore.java:56)
[11:01:46] [Paper Async Command Builder Thread Pool - 0/WARN]: 	at FastAsyncWorldEdit-Bukkit-2.4.11-SNAPSHOT-324.jar//org.enginehub.piston.inject.InjectedValueAccess.injectedValue(InjectedValueAccess.java:44)
[11:01:46] [Paper Async Command Builder Thread Pool - 0/WARN]: 	at FastAsyncWorldEdit-Bukkit-2.4.11-SNAPSHOT-324.jar//com.sk89q.worldedit.command.util.PermissionCondition.satisfied(PermissionCondition.java:54)
[11:01:46] [Paper Async Command Builder Thread Pool - 0/WARN]: 	at FastAsyncWorldEdit-Bukkit-2.4.11-SNAPSHOT-324.jar//com.sk89q.worldedit.bukkit.BukkitCommandInspector.testPermission(BukkitCommandInspector.java:81)
[11:01:46] [Paper Async Command Builder Thread Pool - 0/WARN]: 	at FastAsyncWorldEdit-Bukkit-2.4.11-SNAPSHOT-324.jar//com.sk89q.bukkit.util.DynamicPluginCommand.testPermissionSilent(DynamicPluginCommand.java:107)
[11:01:46] [Paper Async Command Builder Thread Pool - 0/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.command.BukkitCommandWrapper.test(BukkitCommandWrapper.java:56)
[11:01:46] [Paper Async Command Builder Thread Pool - 0/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.command.BukkitCommandWrapper.test(BukkitCommandWrapper.java:23)
[11:01:46] [Paper Async Command Builder Thread Pool - 0/WARN]: 	at com.mojang.brigadier.tree.CommandNode.canUse(CommandNode.java:80)
[11:01:46] [Paper Async Command Builder Thread Pool - 0/WARN]: 	at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:456)
[11:01:46] [Paper Async Command Builder Thread Pool - 0/WARN]: 	at net.minecraft.commands.CommandDispatcher.sendAsync(CommandDispatcher.java:412)
[11:01:46] [Paper Async Command Builder Thread Pool - 0/WARN]: 	at net.minecraft.commands.CommandDispatcher.lambda$sendCommands$4(CommandDispatcher.java:385)
[11:01:46] [Paper Async Command Builder Thread Pool - 0/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[11:01:46] [Paper Async Command Builder Thread Pool - 0/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[11:01:46] [Paper Async Command Builder Thread Pool - 0/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
```

### To Reproduce

Not entirely sure. Noticed it happen in two separate occasions immediately after someone joined after a server restart.

### Expected behaviour

No errors.

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/fef6978e1a1f43a39e5fe2c7267cb9cc

### Fawe Version

FastAsyncWorldEdit version 2.4.11-SNAPSHOT-324;62f561c

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by NotMyFault** [comment]
Don't select paper if you're not using Paper. Please raise a new issue if you can replicate this issue using Paper, thanks.
