### ISSUE TITLE
Error when using wand with nukkit server

### ISSUE THREAD

**Issue by EagleDotNet** [IntellectualSites/FastAsyncWorldEdit#2045]
### Server Implementation

Paper

### Server Version

1.19.3

### Describe the bug

> java.lang.UnsatisfiedLinkError: /tmp/sqlite-3.8.11.2-aeca9f82-883b-4b4f-b5cd-b6b02f86ea02-libsqlitejdbc.so: /tmp/sqlite-3.8.11.2-aeca9f$
2-883b-4b4f-b5cd-b6b02f86ea02-libsqlitejdbc.so: failed to map segment from shared object: Operation not permitted
java.lang.UnsatisfiedLinkError: org.sqlite.core.NativeDB._open(Ljava/lang/String;I)V
        at org.sqlite.core.NativeDB._open(Native Method)
        at org.sqlite.core.DB.open(DB.java:161)
        at org.sqlite.core.CoreConnection.open(CoreConnection.java:220)
        at org.sqlite.core.CoreConnection.<init>(CoreConnection.java:76)
        at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:24)
        at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:23)
        at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:45)
        at org.sqlite.JDBC.createConnection(JDBC.java:114)
        at org.sqlite.JDBC.connect(JDBC.java:88)
        at java.sql.DriverManager.getConnection(DriverManager.java:664)
        at java.sql.DriverManager.getConnection(DriverManager.java:270)
        at com.boydti.fawe.database.RollbackDatabase.openConnection(RollbackDatabase.java:282)
        at com.boydti.fawe.database.RollbackDatabase.<init>(RollbackDatabase.java:57)
        at com.boydti.fawe.database.DBHandler.getDatabase(DBHandler.java:20)
        at com.boydti.fawe.logging.rollback.RollbackOptimizedHistory.close(RollbackOptimizedHistory.java:88)
        at com.sk89q.worldedit.EditSession.flushQueue(EditSession.java:1322)
        at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandTask(CommandManager.java:496)
        at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandOnCurrentThread(CommandManager.java:417)
        at com.sk89q.worldedit.extension.platform.CommandManager$3$1.run(CommandManager.java:535)
        at com.boydti.fawe.object.FawePlayer.lambda$runAction$3(FawePlayer.java:335)
        at com.boydti.fawe.object.task.SimpleAsyncNotifyQueue.operate(SimpleAsyncNotifyQueue.java:25)
        at com.boydti.fawe.object.task.AsyncNotifyQueue$1.run(AsyncNotifyQueue.java:15)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)

### To Reproduce

when I using wand

### Expected behaviour

i think this error about SQLite

### Fawe Debugpaste

Dec 13, 2022 7:47:56 PM com.boydti.fawe.nukkit.optimization.FaweNukkit debug INFO: There was an error handling a FAWE command: [See console]

### Fawe Version

FastAsyncWorldEdit version 19.03.29-d13b946-1257-22.0.14

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by SirYwell** [comment]
Unsupported FAWE version.
