### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by Antonekkk** [IntellectualSites/FastAsyncWorldEdit#2049]
### Server Implementation

Paper

### Server Version

1.18.2

### Describe the bug

[ERROR] An unexpected error while handling a FastAsyncWorldEdit command
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
at com.fastasyncworldedit.core.extension.platform.binding.Bindings.invoke(Bindings.java:140) ~[FastAsyncWorldEdit-Bukkit-2.5.1-SNAPSHOT-332 (1).jar:?]
at com.fastasyncworldedit.core.extension.platform.binding.Bindings.lambda$register$1(Bindings.java:95) ~[FastAsyncWorldEdit-Bukkit-2.5.1-SNAPSHOT-332 (1).jar:?]
at org.enginehub.piston.inject.MapBackedValueStore.lambda$injectedValue$0(MapBackedValueStore.java:56) ~[FastAsyncWorldEdit-Bukkit-2.5.1-SNAPSHOT-332 (1).jar:?]
at java.util.Optional.flatMap(Unknown Source) ~[?:?]
at org.enginehub.piston.inject.MapBackedValueStore.injectedValue(MapBackedValueStore.java:56) ~[FastAsyncWorldEdit-Bukkit-2.5.1-SNAPSHOT-332 (1).jar:?]
at org.enginehub.piston.inject.MergedValueAccess.lambda$injectedValue$0(MergedValueAccess.java:54) ~[FastAsyncWorldEdit-Bukkit-2.5.1-SNAPSHOT-332 (1).jar:?]
at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:?]
at java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source) ~[?:?]
at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source) ~[?:?]
at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source) ~[?:?]
at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source) ~[?:?]
at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
at java.util.stream.ReferencePipeline.findFirst(Unknown Source) ~[?:?]
at org.enginehub.piston.inject.MergedValueAccess.injectedValue(MergedValueAccess.java:57) ~[FastAsyncWorldEdit-Bukkit-2.5.1-SNAPSHOT-332 (1).jar:?]
at org.enginehub.piston.inject.MemoizingValueAccess.injectedValue(MemoizingValueAccess.java:84) ~[FastAsyncWorldEdit-Bukkit-2.5.1-SNAPSHOT-332 (1).jar:?]
at org.enginehub.piston.impl.CommandParametersImpl.injectedValue(CommandParametersImpl.java:109) ~[FastAsyncWorldEdit-Bukkit-2.5.1-SNAPSHOT-332 (1).jar:?]
at org.enginehub.piston.inject.InjectedValueAccess.injectedValue(InjectedValueAccess.java:44) ~[FastAsyncWorldEdit-Bukkit-2.5.1-SNAPSHOT-332 (1).jar:?]
at com.sk89q.worldedit.command.util.annotation.PreloadHandler.beforeCall(PreloadHandler.java:25) ~[FastAsyncWorldEdit-Bukkit-2.5.1-SNAPSHOT-332 (1).jar:?]
at org.enginehub.piston.internal.RegistrationUtil.listenersBeforeCall(RegistrationUtil.java:53) ~[FastAsyncWorldEdit-Bukkit-2.5.1-SNAPSHOT-332 (1).jar:?]
at com.sk89q.worldedit.command.RegionCommandsRegistration.cmd$_set(RegionCommandsRegistration.java:599) ~[FastAsyncWorldEdit-Bukkit-2.5.1-SNAPSHOT-332 (1).jar:?]
at org.enginehub.piston.CommandManager.execute(CommandManager.java:157) ~[FastAsyncWorldEdit-Bukkit-2.5.1-SNAPSHOT-332 (1).jar:?]
at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommandOnCurrentThread$16(PlatformCommandManager.java:730) ~[FastAsyncWorldEdit-Bukkit-2.5.1-SNAPSHOT-332 (1).jar:?]
at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandTask(PlatformCommandManager.java:751) ~[FastAsyncWorldEdit-Bukkit-2.5.1-SNAPSHOT-332 (1).jar:?]
at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandOnCurrentThread(PlatformCommandManager.java:732) ~[FastAsyncWorldEdit-Bukkit-2.5.1-SNAPSHOT-332 (1).jar:?]
at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommand$13(PlatformCommandManager.java:702) ~[FastAsyncWorldEdit-Bukkit-2.5.1-SNAPSHOT-332 (1).jar:?]
at com.sk89q.worldedit.extension.platform.AbstractPlayerActor.lambda$runAction$1(AbstractPlayerActor.java:672) ~[FastAsyncWorldEdit-Bukkit-2.5.1-SNAPSHOT-332 (1).jar:?]
at com.fastasyncworldedit.core.util.task.AsyncNotifyQueue.lambda$run$0(AsyncNotifyQueue.java:28) ~[FastAsyncWorldEdit-Bukkit-2.5.1-SNAPSHOT-332 (1).jar:?]
at com.fastasyncworldedit.core.util.task.AsyncNotifyQueue.lambda$call$1(AsyncNotifyQueue.java:45) ~[FastAsyncWorldEdit-Bukkit-2.5.1-SNAPSHOT-332 (1).jar:?]
at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(Unknown Source) ~[?:?]
at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?]
at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?]
at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?]
at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?]
at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?]
Caused by: java.lang.reflect.InvocationTargetException
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
at com.fastasyncworldedit.core.extension.platform.binding.Bindings.invoke(Bindings.java:137) ~[FastAsyncWorldEdit-Bukkit-2.5.1-SNAPSHOT-332 (1).jar:?]
... 35 more
Caused by: java.lang.NullPointerException: Cannot invoke "com.sk89q.worldedit.bukkit.adapter.BukkitImplAdapter.getRelighterFactory()" because the return value of "com.sk89q.worldedit.bukkit.WorldEditPlugin.getBukkitImplAdapter()" is null
at com.sk89q.worldedit.bukkit.BukkitServerInterface.getRelighterFactory(BukkitServerInterface.java:279) ~[FastAsyncWorldEdit-Bukkit-2.5.1-SNAPSHOT-332 (1).jar:?]
at com.sk89q.worldedit.EditSessionBuilder.compile(EditSessionBuilder.java:569) ~[FastAsyncWorldEdit-Bukkit-2.5.1-SNAPSHOT-332 (1).jar:?]
at com.sk89q.worldedit.EditSession.<init>(EditSession.java:260) ~[FastAsyncWorldEdit-Bukkit-2.5.1-SNAPSHOT-332 (1).jar:?]
at com.sk89q.worldedit.EditSessionBuilder.build(EditSessionBuilder.java:232) ~[FastAsyncWorldEdit-Bukkit-2.5.1-SNAPSHOT-332 (1).jar:?]
at com.sk89q.worldedit.LocalSession.createEditSession(LocalSession.java:1652) ~[FastAsyncWorldEdit-Bukkit-2.5.1-SNAPSHOT-332 (1).jar:?]
at com.fastasyncworldedit.core.extension.platform.binding.ProvideBindings.editSession(ProvideBindings.java:57) ~[FastAsyncWorldEdit-Bukkit-2.5.1-SNAPSHOT-332 (1).jar:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
at com.fastasyncworldedit.core.extension.platform.binding.Bindings.invoke(Bindings.java:137) ~[FastAsyncWorldEdit-Bukkit-2.5.1-SNAPSHOT-332 (1).jar:?]
... 35 more
 

### To Reproduce

No commands work, plugin not working.

### Expected behaviour

To make it work.

### Screenshots / Videos

[https://ctrlv.cz/OHlS](url)

### Error log (if applicable)

https://paste.hostify.cz/?45bb4aa2f39c8d66#EVtvAXQYKGC15APWQagiZnivuCSb289caBJgbyHtAWC1

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/2e5ed6a7f81342a0aaaecebd49cf1917

### Fawe Version

FastAsyncWorldEdit-Bukkit-2.5.1-SNAPSHOT-332 (1)

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by SirYwell** [comment]
1.18.1 is unsupported, that's why it's not in the dropdown menu.
