### ISSUE TITLE
Regen - AutoCleanUp

### ISSUE THREAD

**Issue by Sh3r1ffCZ** [IntellectualSites/FastAsyncWorldEdit#2178]
### Server Implementation

Paper

### Server Version

1.19.4

### Describe the bug

Hello, on version 1.19.3, my AutoCleanUp from the Residence plugin worked, but after changing to 1.19.4, the Residence does not regenerate and it prints this error to the console. Meanwhile in game, my //regen works normally. Could this be a bug?

### To Reproduce

[05:43:58] [Server thread/ERROR]: [com.fastasyncworldedit.bukkit.adapter.Regenerator] Error while running structure_starts on chunk 88/950
java.lang.IllegalStateException: AsyncStructureSpawnEvent may only be triggered asynchronously.
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:40) ~[purpur-1.19.4.jar:git-Purpur-1957]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.19.4.jar:git-Purpur-1957]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.world.level.chunk.ChunkGenerator.tryGenerateStructure(ChunkGenerator.java:635) ~[purpur-1.19.4.jar:git-Purpur-1957]
	at net.minecraft.world.level.chunk.ChunkGenerator.lambda$createStructures$16(ChunkGenerator.java:607) ~[purpur-1.19.4.jar:git-Purpur-1957]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at net.minecraft.world.level.chunk.ChunkGenerator.createStructures(ChunkGenerator.java:557) ~[purpur-1.19.4.jar:git-Purpur-1957]
	at net.minecraft.world.level.chunk.ChunkStatus.lambda$static$2(ChunkStatus.java:76) ~[purpur-1.19.4.jar:git-Purpur-1957]
	at net.minecraft.world.level.chunk.ChunkStatus.generate(ChunkStatus.java:305) ~[purpur-1.19.4.jar:git-Purpur-1957]
	at com.sk89q.worldedit.bukkit.adapter.impl.fawe.v1_19_R3.regen.PaperweightRegen$ChunkStatusWrap.processChunk(PaperweightRegen.java:553) ~[FastAsyncWorldEdit-Bukkit-2.6.0-SNAPSHOT-399.jar:?]
	at com.fastasyncworldedit.bukkit.adapter.Regenerator$ChunkStatusWrapper.processChunkSave(Regenerator.java:580) ~[FastAsyncWorldEdit-Bukkit-2.6.0-SNAPSHOT-399.jar:?]
	at com.fastasyncworldedit.bukkit.adapter.Regenerator.generate(Regenerator.java:258) ~[FastAsyncWorldEdit-Bukkit-2.6.0-SNAPSHOT-399.jar:?]
	at com.fastasyncworldedit.bukkit.adapter.Regenerator.regenerate(Regenerator.java:119) ~[FastAsyncWorldEdit-Bukkit-2.6.0-SNAPSHOT-399.jar:?]
	at com.sk89q.worldedit.bukkit.adapter.impl.fawe.v1_19_R3.PaperweightFaweAdapter.regenerate(PaperweightFaweAdapter.java:628) ~[FastAsyncWorldEdit-Bukkit-2.6.0-SNAPSHOT-399.jar:?]
	at com.sk89q.worldedit.bukkit.BukkitWorld.regenerate(BukkitWorld.java:253) ~[FastAsyncWorldEdit-Bukkit-2.6.0-SNAPSHOT-399.jar:?]
	at com.sk89q.worldedit.world.World.regenerate(World.java:266) ~[FastAsyncWorldEdit-Bukkit-2.6.0-SNAPSHOT-399.jar:?]
	at com.bekvon.bukkit.residence.selection.WorldEdit7SelectionManager.regenerate(WorldEdit7SelectionManager.java:146) ~[Residence5.1.1.1.jar:?]
	at com.bekvon.bukkit.residence.protection.ResidenceManager.removeResidence(ResidenceManager.java:663) ~[Residence5.1.1.1.jar:?]
	at com.bekvon.bukkit.residence.utils.FileCleanUp.cleanOldResidence(FileCleanUp.java:80) ~[Residence5.1.1.1.jar:?]
	at com.bekvon.bukkit.residence.Residence.onEnable(Residence.java:683) ~[Residence5.1.1.1.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:192) ~[purpur-1.19.4.jar:git-Purpur-1957]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.19.4.jar:git-Purpur-1957]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:569) ~[purpur-1.19.4.jar:git-Purpur-1957]
	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:480) ~[purpur-1.19.4.jar:git-Purpur-1957]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:643) ~[purpur-1.19.4.jar:git-Purpur-1957]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:442) ~[purpur-1.19.4.jar:git-Purpur-1957]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:344) ~[purpur-1.19.4.jar:git-Purpur-1957]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1120) ~[purpur-1.19.4.jar:git-Purpur-1957]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325) ~[purpur-1.19.4.jar:git-Purpur-1957]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Expected behaviour

regen

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/9519e75376d0473c814d437d03636062

### Fawe Version

FastAsyncWorldEdit-Bukkit-2.6.0-SNAPSHOT-399.jar

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

I also tried older versions + the official FastAsyncWorldEdit-Bukkit-2.6.0

**Comment by OneLiteFeather** [comment]
https://github.com/Zrips/Residence/issues/1009 This might be an issue with Residence. You mentioned that you use Paper, but your debugpaste shows Purpur.

**Comment by PierreSchwang** [comment]
> 



> [Zrips/Residence#1009](https://github.com/Zrips/Residence/issues/1009) This might be an issue with Residence. You mentioned that you use Paper, but your debugpaste shows Purpur.

Not really sure if that's more of an "us"-problem or not. We don't seem to enqueue all the chunk regeneration tasks into an async task, which is no issue with the //regen-command itself as commands are dispatched in an async-queue itself (but may lead to issue with concurrent command execution tho) but api-usage-wise that shouldn't be the case. 
Residence could wrap that in an async task if using FAWE - or, we enqueue that ourself (which would require a blocking task either way, so meh).
