### ISSUE TITLE
Error while i'm using wand

### ISSUE THREAD

**Issue by TBAProgramming** [IntellectualSites/FastAsyncWorldEdit#2189]
### Server Implementation

Paper

### Server Version

1.19.4

### Describe the bug

**bug/error- [https://imgur.com/MvFC1zu](url)**

### To Reproduce

**1 downloaded lastet version
2 see changelog version
3 not working
4 see console logs server**

### Expected behaviour

idk

### Screenshots / Videos

**bug/error- [https://imgur.com/MvFC1zu](url)**

https://paste.gg/p/anonymous/0f4ea8245a394f3bae7b5d6c3ceebdd9/files/169cf25f0d14444e9f37b1e337086dcf/raw

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/a049ee3810b54b1689ed389f781315eb

### Fawe Version

2.6.1

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by OneLiteFeather** [comment]
Can't reproduce what you did here. Please test FAWE without other plugins and scripts first.

`14:58:14] [Server thread/INFO]: [SkStuff] WorldEdit found! Registering WorldEdit stuff...
[14:58:14] [Server thread/ERROR]: Error occurred while enabling SkStuff v1.6.4.1 (Is it up to date?)
java.lang.NoClassDefFoundError: com/sk89q/worldedit/data/DataException
	at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:?]
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:3373) ~[?:?]
	at java.lang.Class.getConstructor0(Class.java:3578) ~[?:?]
	at java.lang.Class.getConstructor(Class.java:2271) ~[?:?]
	at ch.njol.skript.lang.SyntaxElementInfo.<init>(SyntaxElementInfo.java:38) ~[Skript-2.7.0-beta2.jar:?]
	at ch.njol.skript.Skript.registerEffect(Skript.java:1355) ~[Skript-2.7.0-beta2.jar:?]
	at me.TheBukor.SkStuff.SkStuff.onEnable(SkStuff.java:194) ~[SkStuff.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:192) ~[paper-1.19.4.jar:git-Paper-466]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.19.4.jar:git-Paper-466]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:555) ~[paper-1.19.4.jar:git-Paper-466]
	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:466) ~[paper-1.19.4.jar:git-Paper-466]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:637) ~[paper-1.19.4.jar:git-Paper-466]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:436) ~[paper-1.19.4.jar:git-Paper-466]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.19.4.jar:git-Paper-466]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1103) ~[paper-1.19.4.jar:git-Paper-466]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.19.4.jar:git-Paper-466]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldedit.data.DataException
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:183) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 19 more
[14:58:14] [Server thread/INFO]: [SkStuff] Disabling SkStuff v1.6.4.1`

This script is the reason it doesn't work.

**Comment by TBAProgramming** [comment]
ok

**Comment by TBAProgramming** [comment]
https://paste.gg/p/anonymous/8877a83a58a74d009694348ce0d44e78/files/d07cd2c1397d4bac9f5d6038d7dfb125/raw

**Comment by TBAProgramming** [comment]
@OneLiteFeather

**Comment by OneLiteFeather** [comment]
Half of the log is missing, I saw the log on your issue before. FAWE is clearly not working because of the SkStuff.

**Comment by TBAProgramming** [comment]
deleted*

**Comment by TBAProgramming** [comment]
@OneLiteFeather

**Comment by OneLiteFeather** [comment]
Can you test FAWE on a clean test server without other plugins/scripts?

**Comment by PierreSchwang** [comment]
Try without any other plugin than FAWE. If the issue persists you may open a correct bug report. 
Otherwise do a binary search to find the culprit (Google should help)
