### ISSUE TITLE
Failed to load the built-in legacy id registry on Mohist

### ISSUE THREAD

**Issue by JLSkyzer** [IntellectualSites/FastAsyncWorldEdit#2199]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

When i start the game i have this error:
`[15:10:52 WARN]: Failed to load the built-in legacy id registry
java.lang.ExceptionInInitializerError: null
	at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseLogic(DefaultBlockParser.java:543) ~[?:?]
	at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseFromInput(DefaultBlockParser.java:108) ~[?:?]
	at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseFromInput(DefaultBlockParser.java:78) ~[?:?]
	at com.sk89q.worldedit.internal.registry.AbstractFactory.parseFromInput(AbstractFactory.java:89) ~[?:?]
	at com.sk89q.worldedit.world.registry.LegacyMapper.loadFromResource(LegacyMapper.java:137) ~[?:?]
	at com.sk89q.worldedit.world.registry.LegacyMapper.<init>(LegacyMapper.java:84) ~[?:?]
	at com.sk89q.worldedit.world.registry.LegacyMapper.getInstance(LegacyMapper.java:329) ~[?:?]
	at com.sk89q.worldedit.WorldEdit.loadMappings(WorldEdit.java:432) ~[?:?]
	at com.sk89q.worldedit.bukkit.WorldEditPlugin.setupPreWorldData(WorldEditPlugin.java:237) ~[?:?]
	at com.sk89q.worldedit.bukkit.WorldEditPlugin.onEnable(WorldEditPlugin.java:207) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[forge:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) ~[forge:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:479) ~[forge:?]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:503) ~[forge:7e29f765-296df566-9fb885e8]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[forge:7e29f765-296df566-9fb885e8]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:213) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:771) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:269) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "com.sk89q.worldedit.world.block.BlockType.getInternalId()" because the return value of "com.sk89q.worldedit.world.block.BlockTypes.get(String)" is null
	at com.fastasyncworldedit.bukkit.adapter.CachedBukkitAdapter.init(CachedBukkitAdapter.java:36) ~[?:?]
	at com.fastasyncworldedit.bukkit.adapter.CachedBukkitAdapter.asBlockType(CachedBukkitAdapter.java:70) ~[?:?]
	at com.sk89q.worldedit.bukkit.BukkitAdapter.asBlockType(BukkitAdapter.java:417) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at com.sk89q.worldedit.bukkit.BukkitBlockCategoryRegistry.getFromBukkitTag(BukkitBlockCategoryRegistry.java:36) ~[?:?]
	at com.sk89q.worldedit.bukkit.BukkitBlockCategoryRegistry.getCategorisedByName(BukkitBlockCategoryRegistry.java:48) ~[?:?]
	at com.sk89q.worldedit.world.registry.CategoryRegistry.getAll(CategoryRegistry.java:41) ~[?:?]
	at com.sk89q.worldedit.world.block.BlockCategory.load(BlockCategory.java:49) ~[?:?]
	at com.sk89q.worldedit.world.block.BlockCategories.get(BlockCategories.java:198) ~[?:?]
	at com.sk89q.worldedit.world.block.BlockCategories.<clinit>(BlockCategories.java:30) ~[?:?]
	... 19 more`

the worst is that it worked 3 days ago since I put a plugin like BuyCraft it makes this error

### To Reproduce

- Set java 17
- Add the plugin
- Launch the server with Mohist
- Install other plugin like Buycraft 
- and you will see the problème

### Expected behaviour

When i try to do //set and other i have an error
`[15:15:23 WARN]: java.lang.NoClassDefFoundError: Could not initialize class com.sk89q.worldedit.world.block.BlockCategories
[15:15:23 WARN]: 	at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseLogic(DefaultBlockParser.java:543)
[15:15:23 WARN]: 	at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseFromInput(DefaultBlockParser.java:108)
[15:15:23 WARN]: 	at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseFromInput(DefaultBlockParser.java:78)
[15:15:23 WARN]: 	at com.sk89q.worldedit.internal.registry.AbstractFactory.parseFromInput(AbstractFactory.java:89)
[15:15:23 WARN]: 	at com.fastasyncworldedit.core.extension.factory.parser.pattern.RichPatternParser.parseFromInput(RichPatternParser.java:130)
[15:15:23 WARN]: 	at com.sk89q.worldedit.extension.factory.PatternFactory.parseFromInput(PatternFactory.java:150)
[15:15:23 WARN]: 	at com.sk89q.worldedit.extension.factory.PatternFactory.parseFromInput(PatternFactory.java:80)
[15:15:23 WARN]: 	at com.sk89q.worldedit.command.argument.FactoryConverter.convert(FactoryConverter.java:144)
[15:15:23 WARN]: 	at org.enginehub.piston.impl.CommandParser.lambda$isAcceptedByTypeParsers$7(CommandParser.java:497)
[15:15:23 WARN]: 	at java.base/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
[15:15:23 WARN]: 	at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1856)
[15:15:23 WARN]: 	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
[15:15:23 WARN]: 	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
[15:15:23 WARN]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
[15:15:23 WARN]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[15:15:23 WARN]: 	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
[15:15:23 WARN]: 	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
[15:15:23 WARN]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[15:15:23 WARN]: 	at java.base/java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:632)
[15:15:23 WARN]: 	at org.enginehub.piston.impl.CommandParser.isAcceptedByTypeParsers(CommandParser.java:492)
[15:15:23 WARN]: 	at org.enginehub.piston.impl.CommandParser.parseRegularArgument(CommandParser.java:429)
[15:15:23 WARN]: 	at org.enginehub.piston.impl.CommandParser.parse(CommandParser.java:340)
[15:15:23 WARN]: 	at org.enginehub.piston.impl.CommandManagerImpl.parse(CommandManagerImpl.java:240)
[15:15:23 WARN]: 	at org.enginehub.piston.CommandManager.execute(CommandManager.java:154)
[15:15:23 WARN]: 	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommandOnCurrentThread$16(PlatformCommandManager.java:725)
[15:15:23 WARN]: 	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandTask(PlatformCommandManager.java:746)
[15:15:23 WARN]: 	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandOnCurrentThread(PlatformCommandManager.java:727)
[15:15:23 WARN]: 	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommand$14(PlatformCommandManager.java:698)
[15:15:23 WARN]: 	at com.sk89q.worldedit.extension.platform.AbstractPlayerActor.lambda$runAction$1(AbstractPlayerActor.java:672)
[15:15:23 WARN]: 	at com.fastasyncworldedit.core.util.task.AsyncNotifyQueue.lambda$run$0(AsyncNotifyQueue.java:28)
[15:15:23 WARN]: 	at com.fastasyncworldedit.core.util.task.AsyncNotifyQueue.lambda$call$1(AsyncNotifyQueue.java:45)
[15:15:23 WARN]: 	at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1428)
[15:15:23 WARN]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[15:15:23 WARN]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[15:15:23 WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[15:15:23 WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[15:15:23 WARN]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[15:15:23 WARN]: Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NullPointerException [in thread "Server thread"]
[15:15:23 WARN]: 	at com.fastasyncworldedit.bukkit.adapter.CachedBukkitAdapter.init(CachedBukkitAdapter.java:36)
[15:15:23 WARN]: 	at com.fastasyncworldedit.bukkit.adapter.CachedBukkitAdapter.asBlockType(CachedBukkitAdapter.java:70)
[15:15:23 WARN]: 	at com.sk89q.worldedit.bukkit.BukkitAdapter.asBlockType(BukkitAdapter.java:417)
[15:15:23 WARN]: 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[15:15:23 WARN]: 	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707)
[15:15:23 WARN]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[15:15:23 WARN]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[15:15:23 WARN]: 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
[15:15:23 WARN]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[15:15:23 WARN]: 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
[15:15:23 WARN]: 	at com.sk89q.worldedit.bukkit.BukkitBlockCategoryRegistry.getFromBukkitTag(BukkitBlockCategoryRegistry.java:36)
[15:15:23 WARN]: 	at com.sk89q.worldedit.bukkit.BukkitBlockCategoryRegistry.getCategorisedByName(BukkitBlockCategoryRegistry.java:48)
[15:15:23 WARN]: 	at com.sk89q.worldedit.world.registry.CategoryRegistry.getAll(CategoryRegistry.java:41)
[15:15:23 WARN]: 	at com.sk89q.worldedit.world.block.BlockCategory.load(BlockCategory.java:49)
[15:15:23 WARN]: 	at com.sk89q.worldedit.world.block.BlockCategories.get(BlockCategories.java:198)
[15:15:23 WARN]: 	at com.sk89q.worldedit.world.block.BlockCategories.<clinit>(BlockCategories.java:30)
[15:15:23 WARN]: 	at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseLogic(DefaultBlockParser.java:543)
[15:15:23 WARN]: 	at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseFromInput(DefaultBlockParser.java:108)
[15:15:23 WARN]: 	at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseFromInput(DefaultBlockParser.java:78)
[15:15:23 WARN]: 	at com.sk89q.worldedit.internal.registry.AbstractFactory.parseFromInput(AbstractFactory.java:89)
[15:15:23 WARN]: 	at com.sk89q.worldedit.world.registry.LegacyMapper.loadFromResource(LegacyMapper.java:137)
[15:15:23 WARN]: 	at com.sk89q.worldedit.world.registry.LegacyMapper.<init>(LegacyMapper.java:84)
[15:15:23 WARN]: 	at com.sk89q.worldedit.world.registry.LegacyMapper.getInstance(LegacyMapper.java:329)
[15:15:23 WARN]: 	at com.sk89q.worldedit.WorldEdit.loadMappings(WorldEdit.java:432)
[15:15:23 WARN]: 	at com.sk89q.worldedit.bukkit.WorldEditPlugin.setupPreWorldData(WorldEditPlugin.java:237)
[15:15:23 WARN]: 	at com.sk89q.worldedit.bukkit.WorldEditPlugin.onEnable(WorldEditPlugin.java:207)
[15:15:23 WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[15:15:23 WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335)
[15:15:23 WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:479)
[15:15:23 WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:503)
[15:15:23 WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415)
[15:15:23 WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:213)
[15:15:23 WARN]: 	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:771)
[15:15:23 WARN]: 	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:269)
[15:15:23 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[15:15:23 WARN]: java.lang.NoClassDefFoundError: Could not initialize class com.sk89q.worldedit.world.block.BlockCategories
[15:15:23 WARN]: 	at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseLogic(DefaultBlockParser.java:543)
[15:15:23 WARN]: 	at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseFromInput(DefaultBlockParser.java:108)
[15:15:23 WARN]: 	at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseFromInput(DefaultBlockParser.java:78)
[15:15:23 WARN]: 	at com.sk89q.worldedit.internal.registry.AbstractFactory.parseFromInput(AbstractFactory.java:89)
[15:15:23 WARN]: 	at com.fastasyncworldedit.core.extension.factory.parser.pattern.RichPatternParser.parseFromInput(RichPatternParser.java:130)
[15:15:23 WARN]: 	at com.sk89q.worldedit.extension.factory.PatternFactory.parseFromInput(PatternFactory.java:150)
[15:15:23 WARN]: 	at com.sk89q.worldedit.extension.factory.PatternFactory.parseFromInput(PatternFactory.java:80)
[15:15:23 WARN]: 	at com.sk89q.worldedit.command.argument.FactoryConverter.convert(FactoryConverter.java:144)
[15:15:23 WARN]: 	at org.enginehub.piston.impl.CommandParser.conversionFailedException(CommandParser.java:188)
[15:15:23 WARN]: 	at org.enginehub.piston.impl.CommandParser.parseRegularArgument(CommandParser.java:430)
[15:15:23 WARN]: 	at org.enginehub.piston.impl.CommandParser.parse(CommandParser.java:340)
[15:15:23 WARN]: 	at org.enginehub.piston.impl.CommandManagerImpl.parse(CommandManagerImpl.java:240)
[15:15:23 WARN]: 	at org.enginehub.piston.CommandManager.execute(CommandManager.java:154)
[15:15:23 WARN]: 	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommandOnCurrentThread$16(PlatformCommandManager.java:725)
[15:15:23 WARN]: 	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandTask(PlatformCommandManager.java:746)
[15:15:23 WARN]: 	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandOnCurrentThread(PlatformCommandManager.java:727)
[15:15:23 WARN]: 	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommand$14(PlatformCommandManager.java:698)
[15:15:23 WARN]: 	at com.sk89q.worldedit.extension.platform.AbstractPlayerActor.lambda$runAction$1(AbstractPlayerActor.java:672)
[15:15:23 WARN]: 	at com.fastasyncworldedit.core.util.task.AsyncNotifyQueue.lambda$run$0(AsyncNotifyQueue.java:28)
[15:15:23 WARN]: 	at com.fastasyncworldedit.core.util.task.AsyncNotifyQueue.lambda$call$1(AsyncNotifyQueue.java:45)
[15:15:23 WARN]: 	at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1428)
[15:15:23 WARN]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[15:15:23 WARN]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[15:15:23 WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[15:15:23 WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[15:15:23 WARN]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[15:15:23 WARN]: Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NullPointerException [in thread "Server thread"]
[15:15:23 WARN]: 	at com.fastasyncworldedit.bukkit.adapter.CachedBukkitAdapter.init(CachedBukkitAdapter.java:36)
[15:15:23 WARN]: 	at com.fastasyncworldedit.bukkit.adapter.CachedBukkitAdapter.asBlockType(CachedBukkitAdapter.java:70)
[15:15:23 WARN]: 	at com.sk89q.worldedit.bukkit.BukkitAdapter.asBlockType(BukkitAdapter.java:417)
[15:15:23 WARN]: 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[15:15:23 WARN]: 	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707)
[15:15:23 WARN]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[15:15:23 WARN]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[15:15:23 WARN]: 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
[15:15:23 WARN]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[15:15:23 WARN]: 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
[15:15:23 WARN]: 	at com.sk89q.worldedit.bukkit.BukkitBlockCategoryRegistry.getFromBukkitTag(BukkitBlockCategoryRegistry.java:36)
[15:15:23 WARN]: 	at com.sk89q.worldedit.bukkit.BukkitBlockCategoryRegistry.getCategorisedByName(BukkitBlockCategoryRegistry.java:48)
[15:15:23 WARN]: 	at com.sk89q.worldedit.world.registry.CategoryRegistry.getAll(CategoryRegistry.java:41)
[15:15:23 WARN]: 	at com.sk89q.worldedit.world.block.BlockCategory.load(BlockCategory.java:49)
[15:15:23 WARN]: 	at com.sk89q.worldedit.world.block.BlockCategories.get(BlockCategories.java:198)
[15:15:23 WARN]: 	at com.sk89q.worldedit.world.block.BlockCategories.<clinit>(BlockCategories.java:30)
[15:15:23 WARN]: 	at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseLogic(DefaultBlockParser.java:543)
[15:15:23 WARN]: 	at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseFromInput(DefaultBlockParser.java:108)
[15:15:23 WARN]: 	at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseFromInput(DefaultBlockParser.java:78)
[15:15:23 WARN]: 	at com.sk89q.worldedit.internal.registry.AbstractFactory.parseFromInput(AbstractFactory.java:89)
[15:15:23 WARN]: 	at com.sk89q.worldedit.world.registry.LegacyMapper.loadFromResource(LegacyMapper.java:137)
[15:15:23 WARN]: 	at com.sk89q.worldedit.world.registry.LegacyMapper.<init>(LegacyMapper.java:84)
[15:15:23 WARN]: 	at com.sk89q.worldedit.world.registry.LegacyMapper.getInstance(LegacyMapper.java:329)
[15:15:23 WARN]: 	at com.sk89q.worldedit.WorldEdit.loadMappings(WorldEdit.java:432)
[15:15:23 WARN]: 	at com.sk89q.worldedit.bukkit.WorldEditPlugin.setupPreWorldData(WorldEditPlugin.java:237)
[15:15:23 WARN]: 	at com.sk89q.worldedit.bukkit.WorldEditPlugin.onEnable(WorldEditPlugin.java:207)
[15:15:23 WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[15:15:23 WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335)
[15:15:23 WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:479)
[15:15:23 WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:503)
[15:15:23 WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415)
[15:15:23 WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:213)
[15:15:23 WARN]: 	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:771)
[15:15:23 WARN]: 	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:269)
[15:15:23 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)`

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/60830349/235354843-a6d1f173-8593-4477-91dd-c59327874322.png)
[latest.log](https://github.com/IntellectualSites/FastAsyncWorldEdit/files/11361383/latest.log)
[debug.log](https://github.com/IntellectualSites/FastAsyncWorldEdit/files/11361382/debug.log)

### Error log (if applicable)

https://paste.gg/p/anonymous/5270521dffb64f1a91a9e726bf372359

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/d3270fcf47444e71ad4adb9effd89e46

### Fawe Version

FastAsyncWorldEdit-Bukkit-2.6.2-SNAPSHOT-408

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

Please, i know Mohist is poop but try to help me ☹

**Comment by TheMeinerLP** [comment]
Moshit is not offical supported

**Comment by JLSkyzer** [comment]
but please try to help me

**Comment by TheMeinerLP** [comment]
We will not support mohist in future. Thats means we will not investigate time here

**Comment by NotMyFault** [comment]
> but please try to help me

Mohist is the reason it doesn't work. If you replace it with Paper, FAWE will start working, as it does for everyone else.
