### ISSUE TITLE
can't place any blocks!

### ISSUE THREAD

**Issue by MavLeague** [IntellectualSites/FastAsyncWorldEdit#2214]
### Server Implementation

Paper

### Server Version

1.19.4

### Describe the bug

I've just tried to simply place some blocks with the //set commad but it didnt work. The message was normal but no blocks appeared. So I've restarted the server, because maybe thats the but but now there comes the error `Could not initialize class` and the message `Please report this error: [See console]`. This is what is written there:
`[12:40:13 INFO]: Using com.sk89q.worldedit.bukkit.adapter.impl.fawe.v1_19_R3.PaperweightStarlightRelighterFactory as relighter factory.
[12:40:13 ERROR]: An unexpected error while handling a FastAsyncWorldEdit command
java.lang.NoClassDefFoundError: Could not initialize class com.sk89q.worldedit.bukkit.adapter.impl.fawe.v1_19_R3.PaperweightPlatformAdapter
	at com.sk89q.worldedit.bukkit.adapter.impl.fawe.v1_19_R3.PaperweightGetBlocks.ensureLoaded(PaperweightGetBlocks.java:384) ~[FastAsyncWorldEdit-Bukkit-2.6.2-SNAPSHOT-415.jar:?]
	at com.sk89q.worldedit.bukkit.adapter.impl.fawe.v1_19_R3.PaperweightGetBlocks.getChunk(PaperweightGetBlocks.java:1030) ~[FastAsyncWorldEdit-Bukkit-2.6.2-SNAPSHOT-415.jar:?]
	at com.sk89q.worldedit.bukkit.adapter.impl.fawe.v1_19_R3.PaperweightGetBlocks.getSections(PaperweightGetBlocks.java:1012) ~[FastAsyncWorldEdit-Bukkit-2.6.2-SNAPSHOT-415.jar:?]
	at com.sk89q.worldedit.bukkit.adapter.impl.fawe.v1_19_R3.PaperweightGetBlocks.hasSection(PaperweightGetBlocks.java:1117) ~[FastAsyncWorldEdit-Bukkit-2.6.2-SNAPSHOT-415.jar:?]
	at com.fastasyncworldedit.core.extent.filter.block.CharFilterBlock.initLayer(CharFilterBlock.java:73) ~[FastAsyncWorldEdit-Bukkit-2.6.2-SNAPSHOT-415.jar:?]
	at com.sk89q.worldedit.regions.Region.filter(Region.java:349) ~[FastAsyncWorldEdit-Bukkit-2.6.2-SNAPSHOT-415.jar:?]
	at com.sk89q.worldedit.regions.CuboidRegion.filter(CuboidRegion.java:776) ~[FastAsyncWorldEdit-Bukkit-2.6.2-SNAPSHOT-415.jar:?]
	at com.fastasyncworldedit.core.extent.filter.block.ChunkFilterBlock.filter(ChunkFilterBlock.java:88) ~[FastAsyncWorldEdit-Bukkit-2.6.2-SNAPSHOT-415.jar:?]
	at com.fastasyncworldedit.core.queue.implementation.chunk.ChunkHolder.filterBlocks(ChunkHolder.java:938) ~[FastAsyncWorldEdit-Bukkit-2.6.2-SNAPSHOT-415.jar:?]
	at com.fastasyncworldedit.core.queue.IQueueExtent.apply(IQueueExtent.java:148) ~[FastAsyncWorldEdit-Bukkit-2.6.2-SNAPSHOT-415.jar:?]
	at com.fastasyncworldedit.core.queue.implementation.ParallelQueueExtent.apply(ParallelQueueExtent.java:108) ~[FastAsyncWorldEdit-Bukkit-2.6.2-SNAPSHOT-415.jar:?]
	at com.fastasyncworldedit.core.queue.implementation.ParallelQueueExtent.setBlocks(ParallelQueueExtent.java:189) ~[FastAsyncWorldEdit-Bukkit-2.6.2-SNAPSHOT-415.jar:?]
	at com.sk89q.worldedit.extent.AbstractDelegateExtent.setBlocks(AbstractDelegateExtent.java:427) ~[FastAsyncWorldEdit-Bukkit-2.6.2-SNAPSHOT-415.jar:?]
	at com.fastasyncworldedit.core.extent.LimitExtent.setBlocks(LimitExtent.java:324) ~[FastAsyncWorldEdit-Bukkit-2.6.2-SNAPSHOT-415.jar:?]
	at com.fastasyncworldedit.core.extent.PassthroughExtent.setBlocks(PassthroughExtent.java:163) ~[FastAsyncWorldEdit-Bukkit-2.6.2-SNAPSHOT-415.jar:?]
	at com.sk89q.worldedit.EditSession.setBlocks(EditSession.java:1118) ~[FastAsyncWorldEdit-Bukkit-2.6.2-SNAPSHOT-415.jar:?]
	at com.sk89q.worldedit.command.RegionCommands.set(RegionCommands.java:119) ~[FastAsyncWorldEdit-Bukkit-2.6.2-SNAPSHOT-415.jar:?]
	at com.sk89q.worldedit.command.RegionCommandsRegistration.cmd$_set(RegionCommandsRegistration.java:602) ~[FastAsyncWorldEdit-Bukkit-2.6.2-SNAPSHOT-415.jar:?]
	at org.enginehub.piston.CommandManager.execute(CommandManager.java:157) ~[FastAsyncWorldEdit-Bukkit-2.6.2-SNAPSHOT-415.jar:?]
	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommandOnCurrentThread$16(PlatformCommandManager.java:725) ~[FastAsyncWorldEdit-Bukkit-2.6.2-SNAPSHOT-415.jar:?]
	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandTask(PlatformCommandManager.java:746) ~[FastAsyncWorldEdit-Bukkit-2.6.2-SNAPSHOT-415.jar:?]
	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandOnCurrentThread(PlatformCommandManager.java:727) ~[FastAsyncWorldEdit-Bukkit-2.6.2-SNAPSHOT-415.jar:?]
	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommand$14(PlatformCommandManager.java:698) ~[FastAsyncWorldEdit-Bukkit-2.6.2-SNAPSHOT-415.jar:?]
	at com.sk89q.worldedit.extension.platform.AbstractPlayerActor.lambda$runAction$1(AbstractPlayerActor.java:672) ~[FastAsyncWorldEdit-Bukkit-2.6.2-SNAPSHOT-415.jar:?]
	at com.fastasyncworldedit.core.util.task.AsyncNotifyQueue.lambda$run$0(AsyncNotifyQueue.java:28) ~[FastAsyncWorldEdit-Bukkit-2.6.2-SNAPSHOT-415.jar:?]
	at com.fastasyncworldedit.core.util.task.AsyncNotifyQueue.lambda$call$1(AsyncNotifyQueue.java:45) ~[FastAsyncWorldEdit-Bukkit-2.6.2-SNAPSHOT-415.jar:?]
	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1428) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]`

### To Reproduce

1. Make a selection
2. type //set hand
3. get an error

### Expected behaviour

place some blocks

### Screenshots / Videos

https://user-images.githubusercontent.com/79117866/236828559-44b6b48a-c99d-4e44-8b34-ce671c06aee2.mp4

![image](https://user-images.githubusercontent.com/79117866/236828656-1ef5a035-fec0-483e-a31a-63a8ef965825.png)
![2023-05-08_14 50 48](https://user-images.githubusercontent.com/79117866/236828814-8f42a911-5228-4a5c-9a55-d6519e90588c.png)

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/1e15a9d9ba4148fdba4708fbed64fd4b

### Fawe Version

FastAsyncWorldEdit version 2.6.2-SNAPSHOT-415

### Checklist

- [X] I have included a Fawe debugpaste.
- [x] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by TheMeinerLP** [comment]
Update Paper

**Comment by OneLiteFeather** [comment]
@MavLeague I saw following datapacks on your server in the debugpaste:
 - vanilla
 - file/bukkit
 - file/advancements-datapack
 - file/datapack
 - file/engines

Can you disable all above that are not vanilla, for example "file/engines", generate a new world without the datapack and retry this issue?

**Comment by SirYwell** [comment]
Paper is not up to date according to your debugpaste.
