### ISSUE TITLE
Console Startup Error FAWE 1.19.4 | Custom Worlds

### ISSUE THREAD

**Issue by TheTechnologyStudio** [IntellectualSites/FastAsyncWorldEdit#2218]
### Server Implementation

Paper

### Server Version

1.19.4

### Describe the bug

Error on loading in console

### To Reproduce

Just starting the server

### Expected behaviour

No error?

### Error log (if applicable)

[10:49:13 INFO]: Preparing level "NewWorld" [10:49:14 ERROR]: Could not pass event WorldInitEvent to FastAsyncWorldEdit v2.6.2-SNAPSHOT-415;2987550 java.lang.IllegalArgumentException: Invalid key. Must be [a-z0-9/._-]: at com.google.common.base.Preconditions.checkArgument(Preconditions.java:220) ~[guava-31.1-jre.jar:?] at org.bukkit.NamespacedKey.<init>(NamespacedKey.java:86) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?] at org.bukkit.craftbukkit.v1_19_R3.util.CraftNamespacedKey.fromMinecraft(CraftNamespacedKey.java:24) ~[purpur-1.19.4.jar:git-Purpur-1952] at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?] at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?] at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?] at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?] at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[?:?] at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?] at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?] at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?] at com.sk89q.worldedit.bukkit.adapter.impl.fawe.v1_19_R3.PaperweightFaweAdapter.getRegisteredBiomes(PaperweightFaweAdapter.java:608) ~[FastAsyncWorldEdit-Bukkit-2.6.2-SNAPSHOT-415.jar:?] at com.sk89q.worldedit.bukkit.WorldEditPlugin.setupBiomes(WorldEditPlugin.java:321) ~[FastAsyncWorldEdit-Bukkit-2.6.2-SNAPSHOT-415.jar:?] at com.sk89q.worldedit.bukkit.WorldEditPlugin.setupWorldData(WorldEditPlugin.java:244) ~[FastAsyncWorldEdit-Bukkit-2.6.2-SNAPSHOT-415.jar:?] at com.sk89q.worldedit.bukkit.WorldEditPlugin$WorldInitListener.onWorldInit(WorldEditPlugin.java:646) ~[FastAsyncWorldEdit-Bukkit-2.6.2-SNAPSHOT-415.jar:?] at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?] at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:git-Purpur-1952] at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?] at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.19.4.jar:git-Purpur-1952] at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.19.4.jar:git-Purpur-1952] at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?] at net.minecraft.server.MinecraftServer.initWorld(MinecraftServer.java:660) ~[purpur-1.19.4.jar:git-Purpur-1952] at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:613) ~[purpur-1.19.4.jar:git-Purpur-1952] at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:442) ~[purpur-1.19.4.jar:git-Purpur-1952] at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:344) ~[purpur-1.19.4.jar:git-Purpur-1952] at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1120) ~[purpur-1.19.4.jar:git-Purpur-1952] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325) ~[purpur-1.19.4.jar:git-Purpur-1952] at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/41828f6b207b4b938d5c43d19087580c

### Fawe Version

2.6.2-SNAPSHOT-415;2987550

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by MattBDev** [comment]
I haven’t looked much into this issue but from what I have seen, it’s not something we can or will fix.

**Comment by TheTechnologyStudio** [comment]
Okay, no worry, It does not affect me in any way that i've seen.
