### ISSUE TITLE
Removing beacon, causes an error in the console

### ISSUE THREAD

**Issue by EpicPlayerA10** [IntellectualSites/FastAsyncWorldEdit#2263]
### Server Implementation

Paper

### Server Version

1.19.4

### Describe the bug

When I try to remove beacon using FAWE then server throws this error:
```
[11:16:32] [pool-59-thread-4/WARN]: java.lang.IllegalArgumentException: Can not set final net.minecraft.core.BlockPosition field net.minecraft.world.level.block.entity.TileEntity.p to java.lang.Boolean
[11:16:32] [pool-59-thread-4/WARN]: 	at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
[11:16:32] [pool-59-thread-4/WARN]: 	at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
[11:16:32] [pool-59-thread-4/WARN]: 	at java.base/jdk.internal.reflect.UnsafeQualifiedObjectFieldAccessorImpl.set(UnsafeQualifiedObjectFieldAccessorImpl.java:83)
[11:16:32] [pool-59-thread-4/WARN]: 	at java.base/java.lang.reflect.Field.set(Field.java:799)
[11:16:32] [pool-59-thread-4/WARN]: 	at FastAsyncWorldEdit-Bukkit-2.6.2-SNAPSHOT-448(1).jar//com.sk89q.worldedit.bukkit.adapter.impl.fawe.v1_19_R3.PaperweightPlatformAdapter.removeBeacon(PaperweightPlatformAdapter.java:646)
[11:16:32] [pool-59-thread-4/WARN]: 	at FastAsyncWorldEdit-Bukkit-2.6.2-SNAPSHOT-448(1).jar//com.sk89q.worldedit.bukkit.adapter.impl.fawe.v1_19_R3.PaperweightGetBlocks.call(PaperweightGetBlocks.java:418)
[11:16:32] [pool-59-thread-4/WARN]: 	at FastAsyncWorldEdit-Bukkit-2.6.2-SNAPSHOT-448(1).jar//com.fastasyncworldedit.core.queue.implementation.chunk.ChunkHolder.call(ChunkHolder.java:1076)
[11:16:32] [pool-59-thread-4/WARN]: 	at FastAsyncWorldEdit-Bukkit-2.6.2-SNAPSHOT-448(1).jar//com.fastasyncworldedit.core.queue.implementation.chunk.ChunkHolder.call(ChunkHolder.java:1047)
[11:16:32] [pool-59-thread-4/WARN]: 	at FastAsyncWorldEdit-Bukkit-2.6.2-SNAPSHOT-448(1).jar//com.fastasyncworldedit.core.queue.implementation.chunk.ChunkHolder.call(ChunkHolder.java:33)
[11:16:32] [pool-59-thread-4/WARN]: 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[11:16:32] [pool-59-thread-4/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[11:16:32] [pool-59-thread-4/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[11:16:32] [pool-59-thread-4/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[11:16:32] [Server thread/WARN]: Block entity minecraft:beacon @ BlockPosition{x=-408, y=91, z=84} state Block{minecraft:air} invalid for ticking:
```

### To Reproduce

1. Place beacon
2. Select the beacon using wand.
3. Run `//set 0`

! An error is thrown in the console.

### Expected behaviour

It should not throw an error.

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/52a0fb4d68cf495497025d7986088a26

### Fawe Version

FastAsyncWorldEdit version 2.6.2-SNAPSHOT-448;048dcaf

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by TheMeinerLP** [comment]
1.19.2 produces now following issues:
```
13:16:29] [Server thread/INFO]: Registering commands with com.sk89q.worldedit.bukkit.BukkitServerInterface
[13:16:29] [Server thread/INFO]: WEPIF: Using the Bukkit Permissions API.
[13:16:29] [Server thread/WARN]: java.lang.NoSuchFieldException: q
[13:16:29] [Server thread/WARN]: 	at java.base/java.lang.Class.getDeclaredField(Class.java:2642)
[13:16:29] [Server thread/WARN]: 	at FastAsyncWorldEdit-Bukkit-2.6.2-SNAPSHOT-457.jar//com.sk89q.worldedit.bukkit.adapter.impl.fawe.v1_19_R3.PaperweightPlatformAdapter.<clinit>(PaperweightPlatformAdapter.java:187)
[13:16:29] [Server thread/WARN]: 	at java.base/java.lang.Class.forName0(Native Method)
[13:16:29] [Server thread/WARN]: 	at java.base/java.lang.Class.forName(Class.java:383)
[13:16:29] [Server thread/WARN]: 	at java.base/java.lang.Class.forName(Class.java:376)
[13:16:29] [Server thread/WARN]: 	at FastAsyncWorldEdit-Bukkit-2.6.2-SNAPSHOT-457.jar//com.sk89q.worldedit.bukkit.adapter.BukkitImplLoader.loadAdapter(BukkitImplLoader.java:170)
[13:16:29] [Server thread/WARN]: 	at FastAsyncWorldEdit-Bukkit-2.6.2-SNAPSHOT-457.jar//com.sk89q.worldedit.bukkit.WorldEditPlugin.loadAdapter(WorldEditPlugin.java:369)
[13:16:29] [Server thread/WARN]: 	at FastAsyncWorldEdit-Bukkit-2.6.2-SNAPSHOT-457.jar//com.sk89q.worldedit.bukkit.WorldEditPlugin.setupPreWorldData(WorldEditPlugin.java:240)
[13:16:29] [Server thread/WARN]: 	at FastAsyncWorldEdit-Bukkit-2.6.2-SNAPSHOT-457.jar//com.sk89q.worldedit.bukkit.WorldEditPlugin.onEnable(WorldEditPlugin.java:211)
[13:16:29] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[13:16:29] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[13:16:29] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542)
[13:16:29] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565)
[13:16:29] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479)
[13:16:29] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:279)
[13:16:29] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1100)
[13:16:29] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
[13:16:29] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[13:16:29] [Server thread/INFO]: Using com.sk89q.worldedit.bukkit.adapter.impl.fawe.v1_19_R1.PaperweightFaweAdapter as the Bukkit adapter
[13:16:29] [Server thread/WARN]: [com.fastasyncworldedit.core.util.UpdateNotification] An update for FastAsyncWorldEdit is available. You are 1 build(s) out of date.
You are running build 457, the latest version is build 458.
Update at https://www.spigotmc.org/resources/13932/
```
This is just a notice/documentation

**Comment by EpicPlayerA10** [comment]
Huh, why 1.19.2 server is using 1.19.4 adapter?

**Comment by TheMeinerLP** [comment]
Thats a good point

**Comment by EpicPlayerA10** [comment]
Ah I know why. FAWE is trying to load all adapters and it is trying to find the best. And when adapter will fail to load then FAWE is printing `Throwable` stacktrace but not `RuntimeException` stacktrace.

https://github.com/IntellectualSites/FastAsyncWorldEdit/blob/5da5b216f3ce36bf79e417c47285b89e65b699ac/worldedit-bukkit/adapters/adapter-1_19_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R3/PaperweightPlatformAdapter.java#L221

It seems that `NoSuchFieldException` is not a `RuntimeException`.
