### ISSUE TITLE
fawe have a delete bug with plotsquared

### ISSUE THREAD

**Issue by FBDKPlus** [IntellectualSites/FastAsyncWorldEdit#2377]
### Server Implementation

Paper

### Server Version

1.20.1

### Describe the bug

[21:26:18 INFO]: Wink_Cat issued server command: /p2 delete
[21:26:18 INFO]: Using com.sk89q.worldedit.bukkit.adapter.impl.fawe.v1_20_R1.PaperweightStarlightRelighterFactory as relighter factory.
[21:26:18 WARN]: [FastAsyncWorldEdit] Plugin FastAsyncWorldEdit v2.7.1-SNAPSHOT-537;2f6de99 generated an exception while executing task 3602
java.lang.NoSuchMethodError: 'int com.plotsquared.core.generator.HybridPlotWorld.getPlotYStart()'
        at com.fastasyncworldedit.bukkit.regions.plotsquared.FaweDelegateRegionManager.lambda$handleClear$1(FaweDelegateRegionManager.java:178) ~[FastAsyncWorldEdit-Bukkit-2.7.1-SNAPSHOT-537.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-63]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.1.jar:git-Paper-63]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.1.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### To Reproduce

Ver: PaperSpigot 1.20.1-63
PlotsQuared v7
I use command : plots delete

but can't finish a delete

### Expected behaviour

I hope it is well compatible with plotsquared

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/f8f8f905ea1d454f84490f2e714b86e1

### Fawe Version

FastAsyncWorldEdit v2.7.1-SNAPSHOT-537;2f6de99

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

1

**Comment by dordsor21** [comment]
Update P2
