### ISSUE TITLE
Worledit not working

### ISSUE THREAD

**Issue by skTanky** [IntellectualSites/FastAsyncWorldEdit#2387]
### Server Implementation

Paper

### Server Version

1.19.4

### Describe the bug

[01:54:32 INFO]: skTank issued server command: //set diamond_block
[01:54:33 ERROR]: An unexpected error while handling a FastAsyncWorldEdit command
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.fastasyncworldedit.core.extension.platform.binding.Bindings.invoke(Bindings.java:140) ~[FastAsyncWorldEdit-Bukkit-2.7.1-SNAPSHOT-540.jar:?]
	at com.fastasyncworldedit.core.extension.platform.binding.Bindings.lambda$register$1(Bindings.java:95) ~[FastAsyncWorldEdit-Bukkit-2.7.1-SNAPSHOT-540.jar:?]
	at org.enginehub.piston.inject.MapBackedValueStore.lambda$injectedValue$0(MapBackedValueStore.java:56) ~[FastAsyncWorldEdit-Bukkit-2.7.1-SNAPSHOT-540.jar:?]
	at java.util.Optional.flatMap(Optional.java:289) ~[?:?]
	at org.enginehub.piston.inject.MapBackedValueStore.injectedValue(MapBackedValueStore.java:56) ~[FastAsyncWorldEdit-Bukkit-2.7.1-SNAPSHOT-540.jar:?]
	at org.enginehub.piston.inject.MergedValueAccess.lambda$injectedValue$0(MergedValueAccess.java:54) ~[FastAsyncWorldEdit-Bukkit-2.7.1-SNAPSHOT-540.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:1002) ~[?:?]
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647) ~[?:?]
	at org.enginehub.piston.inject.MergedValueAccess.injectedValue(MergedValueAccess.java:57) ~[FastAsyncWorldEdit-Bukkit-2.7.1-SNAPSHOT-540.jar:?]
	at org.enginehub.piston.inject.MemoizingValueAccess.injectedValue(MemoizingValueAccess.java:84) ~[FastAsyncWorldEdit-Bukkit-2.7.1-SNAPSHOT-540.jar:?]
	at org.enginehub.piston.impl.CommandParametersImpl.injectedValue(CommandParametersImpl.java:109) ~[FastAsyncWorldEdit-Bukkit-2.7.1-SNAPSHOT-540.jar:?]
	at org.enginehub.piston.inject.InjectedValueAccess.injectedValue(InjectedValueAccess.java:44) ~[FastAsyncWorldEdit-Bukkit-2.7.1-SNAPSHOT-540.jar:?]
	at com.sk89q.worldedit.command.util.annotation.PreloadHandler.beforeCall(PreloadHandler.java:25) ~[FastAsyncWorldEdit-Bukkit-2.7.1-SNAPSHOT-540.jar:?]
	at org.enginehub.piston.internal.RegistrationUtil.listenersBeforeCall(RegistrationUtil.java:53) ~[FastAsyncWorldEdit-Bukkit-2.7.1-SNAPSHOT-540.jar:?]
	at com.sk89q.worldedit.command.RegionCommandsRegistration.cmd$_set(RegionCommandsRegistration.java:599) ~[FastAsyncWorldEdit-Bukkit-2.7.1-SNAPSHOT-540.jar:?]
	at org.enginehub.piston.CommandManager.execute(CommandManager.java:157) ~[FastAsyncWorldEdit-Bukkit-2.7.1-SNAPSHOT-540.jar:?]
	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommandOnCurrentThread$16(PlatformCommandManager.java:725) ~[FastAsyncWorldEdit-Bukkit-2.7.1-SNAPSHOT-540.jar:?]
	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandTask(PlatformCommandManager.java:746) ~[FastAsyncWorldEdit-Bukkit-2.7.1-SNAPSHOT-540.jar:?]
	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandOnCurrentThread(PlatformCommandManager.java:727) ~[FastAsyncWorldEdit-Bukkit-2.7.1-SNAPSHOT-540.jar:?]
	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommand$14(PlatformCommandManager.java:698) ~[FastAsyncWorldEdit-Bukkit-2.7.1-SNAPSHOT-540.jar:?]
	at com.sk89q.worldedit.extension.platform.AbstractPlayerActor.lambda$runAction$1(AbstractPlayerActor.java:672) ~[FastAsyncWorldEdit-Bukkit-2.7.1-SNAPSHOT-540.jar:?]
	at com.fastasyncworldedit.core.util.task.AsyncNotifyKeyedQueue.lambda$run$0(AsyncNotifyKeyedQueue.java:48) ~[FastAsyncWorldEdit-Bukkit-2.7.1-SNAPSHOT-540.jar:?]
	at com.fastasyncworldedit.core.util.task.AsyncNotifyKeyedQueue.lambda$call$1(AsyncNotifyKeyedQueue.java:58) ~[FastAsyncWorldEdit-Bukkit-2.7.1-SNAPSHOT-540.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at com.fastasyncworldedit.core.util.task.KeyQueuedExecutorService$KeyRunner.lambda$run$0(KeyQueuedExecutorService.java:150) ~[FastAsyncWorldEdit-Bukkit-2.7.1-SNAPSHOT-540.jar:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at com.fastasyncworldedit.core.extension.platform.binding.Bindings.invoke(Bindings.java:137) ~[FastAsyncWorldEdit-Bukkit-2.7.1-SNAPSHOT-540.jar:?]
	... 37 more
Caused by: java.lang.NullPointerException: Cannot invoke "com.sk89q.worldedit.bukkit.adapter.BukkitImplAdapter.getRelighterFactory()" because the return value of "com.sk89q.worldedit.bukkit.WorldEditPlugin.getBukkitImplAdapter()" is null
	at com.sk89q.worldedit.bukkit.BukkitServerInterface.getRelighterFactory(BukkitServerInterface.java:279) ~[FastAsyncWorldEdit-Bukkit-2.7.1-SNAPSHOT-540.jar:?]
	at com.sk89q.worldedit.EditSessionBuilder.compile(EditSessionBuilder.java:552) ~[FastAsyncWorldEdit-Bukkit-2.7.1-SNAPSHOT-540.jar:?]
	at com.sk89q.worldedit.EditSession.<init>(EditSession.java:262) ~[FastAsyncWorldEdit-Bukkit-2.7.1-SNAPSHOT-540.jar:?]
	at com.sk89q.worldedit.EditSessionBuilder.build(EditSessionBuilder.java:234) ~[FastAsyncWorldEdit-Bukkit-2.7.1-SNAPSHOT-540.jar:?]
	at com.sk89q.worldedit.LocalSession.createEditSession(LocalSession.java:1709) ~[FastAsyncWorldEdit-Bukkit-2.7.1-SNAPSHOT-540.jar:?]
	at com.fastasyncworldedit.core.extension.platform.binding.ProvideBindings.editSession(ProvideBindings.java:57) ~[FastAsyncWorldEdit-Bukkit-2.7.1-SNAPSHOT-540.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at com.fastasyncworldedit.core.extension.platform.binding.Bindings.invoke(Bindings.java:137) ~[FastAsyncWorldEdit-Bukkit-2.7.1-SNAPSHOT-540.jar:?]
	... 37 more
	
	
	

After selecting positions, then using any // command it give me an error and does not do what the command is supposed to

### To Reproduce

![worledit bug](https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/121093474/e0bc2095-a8e5-4565-9e82-ef955ec91ab8)

### Expected behaviour

Should execute what has been stated in the command

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/b61f06644b7d44858b60516c84e138c6

### Fawe Version

2.7.1-SNAPSHOT-540;d428548

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by PierreSchwang** [comment]
You are not running 1.19.4
