### ISSUE TITLE
org.bukkit.event.EventException: null on PlayerQuitEvent

### ISSUE THREAD

**Issue by lucacodes** [IntellectualSites/FastAsyncWorldEdit#2410]
### Server Implementation

Spigot

### Server Version

1.19.4

### Describe the bug

When a player quits, there is always an error/stacktrace "Given attachment is not part of Permissible object CraftPlayer"

```

[20:16:30] [Server thread/INFO]: LucaUDev lost connection: Disconnected
[20:16:30] [Server thread/ERROR]: Could not pass event PlayerQuitEvent to FastAsyncWorldEdit v2.7.1-SNAPSHOT-548;fe33be5
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.remove(PlayerList.java:521) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1790) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]
        at net.minecraft.network.NetworkManager.m(NetworkManager.java:444) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]
        at net.minecraft.server.network.ServerConnection.c(ServerConnection.java:195) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1326) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:388) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1200) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1017) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Given attachment is not part of Permissible object CraftPlayer{name=LucaUDev}
        at org.bukkit.permissions.PermissibleBase.removeAttachment(PermissibleBase.java:153) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at nl.svenar.powerranks.data.PowerPermissibleBase.removeAttachment(PowerPermissibleBase.java:234) ~[?:?]
        at org.bukkit.craftbukkit.v1_19_R3.entity.CraftHumanEntity.removeAttachment(CraftHumanEntity.java:224) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]
        at com.fastasyncworldedit.bukkit.BukkitPermissionAttachmentManager.removeAttachment(BukkitPermissionAttachmentManager.java:41) ~[?:?]
        at com.sk89q.worldedit.bukkit.BukkitPlayer.unregister(BukkitPlayer.java:454) ~[?:?]
        at com.fastasyncworldedit.bukkit.FaweBukkit.onPlayerQuit(FaweBukkit.java:284) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]

```

### To Reproduce

- Login
- Logout
- Error occurs

### Expected behaviour

No error

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/99f194a6710e433ba2bb7fbd2e728ef2

### Fawe Version

2.7.1-SNAPSHOT-550;6f9c3c3

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by TheMeinerLP** [comment]
Please reach the developer of power ranks. This issue is not directly from FAWE.

**Comment by lucacodes** [comment]
> Please reach the developer of power ranks. This issue is not directly from FAWE.

Thank you!
