### ISSUE TITLE
Unexpected error occurred while generating suggestions for input

### ISSUE THREAD

**Issue by SecretlyJealous** [IntellectualSites/FastAsyncWorldEdit#2425]
### Server Implementation

Paper

### Server Version

1.20.1

### Describe the bug

I have this error:

```
[09:45:43] [Async Tab Complete Thread - #3/ERROR]: Unexpected error occurred while generating suggestions for input: /mask dark_prismarine,prismarine,sands
java.lang.ClassCastException: class org.enginehub.piston.converter.SuccessfulConversion cannot be cast to class org.enginehub.piston.converter.FailedConversion (org.enginehub.piston.converter.SuccessfulConversion and org.enginehub.piston.converter.FailedConversion are in unnamed module of loader 'FastAsyncWorldEdit-Bukkit-2.7.2-SNAPSHOT-557.jar' @10854dc5)
	at org.enginehub.piston.impl.CommandParser.conversionFailedException(CommandParser.java:188) ~[FastAsyncWorldEdit-Bukkit-2.7.2-SNAPSHOT-557.jar:?]
	at org.enginehub.piston.impl.CommandParser.parse(CommandParser.java:344) ~[FastAsyncWorldEdit-Bukkit-2.7.2-SNAPSHOT-557.jar:?]
	at org.enginehub.piston.impl.CommandManagerImpl.parse(CommandManagerImpl.java:240) ~[FastAsyncWorldEdit-Bukkit-2.7.2-SNAPSHOT-557.jar:?]
	at org.enginehub.piston.impl.CommandManagerImpl.getSuggestions(CommandManagerImpl.java:190) ~[FastAsyncWorldEdit-Bukkit-2.7.2-SNAPSHOT-557.jar:?]
	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandSuggestion(PlatformCommandManager.java:904) ~[FastAsyncWorldEdit-Bukkit-2.7.2-SNAPSHOT-557.jar:?]
	at com.sk89q.worldedit.util.eventbus.MethodHandleEventHandler.dispatch(MethodHandleEventHandler.java:51) ~[FastAsyncWorldEdit-Bukkit-2.7.2-SNAPSHOT-557.jar:?]
	at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[FastAsyncWorldEdit-Bukkit-2.7.2-SNAPSHOT-557.jar:?]
	at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:193) ~[FastAsyncWorldEdit-Bukkit-2.7.2-SNAPSHOT-557.jar:?]
	at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:181) ~[FastAsyncWorldEdit-Bukkit-2.7.2-SNAPSHOT-557.jar:?]
	at com.sk89q.worldedit.bukkit.WorldEditPlugin$AsyncTabCompleteListener.onAsyncTabComplete(WorldEditPlugin.java:690) ~[FastAsyncWorldEdit-Bukkit-2.7.2-SNAPSHOT-557.jar:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:git-Paper-176]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.1.jar:git-Paper-176]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.1.jar:git-Paper-176]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.event.Event.callEvent(Event.java:45) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleCustomCommandSuggestions$8(ServerGamePacketListenerImpl.java:913) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
```

### To Reproduce

1. Use `/mask dark_prismarine,prismarine,sands`

### Expected behaviour

No error

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/8dc2485ecc634332a787b48024ad7b20

### Fawe Version

FastAsyncWorldEdit-557

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by PierreSchwang** [comment]
I can't reproduce the exception, but I think the tab complete should also fire for e.g. `stone,` - that after the comma all available masks are suggested again (Tho that is more of a feature request)

**Comment by OneLiteFeather** [comment]
Well I was able to reproduce this issue with the mask given AND the //replace sandstone_stairs[facing=east] smooth_sandstone_stairs[facing=east] the builder used to rotate stairs. It is a combination of both, the mask may not understand the brackets of the secound command that much.
https://athion.net/ISPaster/paste/view/e897ba7c85b24be0af7d07d5af041e7c

**Comment by OneLiteFeather** [comment]
https://athion.net/ISPaster/paste/view/0f3d5bb8a85843ee8b9082c1c3055732
I know how it works. You have to use the mask on an item (shovel for example) which has no brush on. then you select your stairs with the axe and replace them with the command that has nbt in it.
![grafik](https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/77929075/91bad354-628e-4e46-a4cf-8fd31802232e)

**Comment by Zoriot** [comment]
Still happening. 
```
Unexpected error occurred while generating suggestions for input: gmask 35.

ClassCastException: class org.enginehub.piston.converter.SuccessfulConversion cannot be cast to class org.enginehub.piston.converter.FailedConversion (org.enginehub.piston.converter.SuccessfulConversion and org.enginehub.piston.converter.FailedConversion are in unnamed module of loader 'FastAsyncWorldEdit-Paper-2.15.3.jar' @3bdc429b)
```
