### ISSUE TITLE
Could not pass event PlayerQuitEvent to FastAsyncWorldEdit

### ISSUE THREAD

**Issue by Atomik0** [IntellectualSites/FastAsyncWorldEdit#2434]
### Server Implementation

Paper

### Server Version

1.20.1

### Describe the bug

hello, I am having this problem with FAWE, is it a bug in another plugin that is causing this in FAWE?

`[23:41:00] [Server thread/ERROR]: Could not pass event PlayerQuitEvent to FastAsyncWorldEdit v2.7.2-SNAPSHOT-560;7b0f1b3
java.lang.NoClassDefFoundError: com/sk89q/worldedit/util/formatting/component/TextUtils
	at com.sk89q.worldedit.bukkit.BukkitPlayer.getLocale(BukkitPlayer.java:358) ~[FastAsyncWorldEdit-Bukkit.jar:?]
	at com.sk89q.worldedit.bukkit.BukkitPlayer.print(BukkitPlayer.java:225) ~[FastAsyncWorldEdit-Bukkit.jar:?]
	at com.sk89q.worldedit.entity.Player.loadClipboardFromDisk(Player.java:462) ~[FastAsyncWorldEdit-Bukkit.jar:?]
	at com.sk89q.worldedit.bukkit.BukkitPlayer.<init>(BukkitPlayer.java:112) ~[FastAsyncWorldEdit-Bukkit.jar:?]
	at com.sk89q.worldedit.bukkit.WorldEditPlugin.wrapPlayer(WorldEditPlugin.java:566) ~[FastAsyncWorldEdit-Bukkit.jar:?]
	at com.sk89q.worldedit.bukkit.WorldEditListener.onPlayerQuit(WorldEditListener.java:184) ~[FastAsyncWorldEdit-Bukkit.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor23.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:git-Paper-170]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.1.jar:git-Paper-170]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.1.jar:git-Paper-170]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.players.PlayerList.remove(PlayerList.java:607) ~[paper-1.20.1.jar:git-Paper-170]
	at net.minecraft.server.players.PlayerList.remove(PlayerList.java:592) ~[paper-1.20.1.jar:git-Paper-170]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2178) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2157) ~[?:?]
	at net.minecraft.network.Connection.handleDisconnection(Connection.java:818) ~[?:?]
	at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:254) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1586) ~[paper-1.20.1.jar:git-Paper-170]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.20.1.jar:git-Paper-170]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1393) ~[paper-1.20.1.jar:git-Paper-170]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1170) ~[paper-1.20.1.jar:git-Paper-170]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-170]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldedit.util.formatting.component.TextUtils
	... 25 more`

### To Reproduce

console error

### Expected behaviour

eliminates console error

### Error log (if applicable)

https://paste.gg/p/anonymous/7fbb9563e0ef4231a67622a777deb8b1

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/d477e8bb9aa048109a2757140cabefef

### Fawe Version

FastAsyncWorldEdit version 2.7.2-SNAPSHOT-561;889e9b7

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by OneLiteFeather** [comment]
Please update Paper to 1.20.1 latest aka build 196

**Comment by Atomik0** [comment]
perfect, I just updated, I will keep you updated in case the error appears again in the console, thank you.

**Comment by Atomik0** [comment]
hi, I come to report again the incident, I updated paper to 1.20.1 latest aka build 196, as I was told, but the error still appears, I leave link with the error.

[https://paste.gg/p/anonymous/0d7fce13a9b64d489c8a645bd6c8309f](url)

thanks

**Comment by OneLiteFeather** [comment]
> hi, I come to report again the incident, I updated paper to 1.20.1 latest aka build 196, as I was told, but the error still appears, I leave link with the error.
> 
> [https://paste.gg/p/anonymous/0d7fce13a9b64d489c8a645bd6c8309f](url)
> 
> thanks

Can you send us the whole log with the errors, not only start up? Without that, we can't reproduce your errors

**Comment by OneLiteFeather** [comment]
What changes you made on the worldedit / fawe configuration files?

**Comment by Atomik0** [comment]
I have not made any modifications to the configuration files, I only updated Paper to build 196

**Comment by NotMyFault** [comment]
Without a precise list of steps to reproduce the issue, there's nothing we can do for you, but assure the class is present in https://github.com/IntellectualSites/FastAsyncWorldEdit/blob/main/worldedit-core/src/main/java/com/sk89q/worldedit/util/formatting/component/TextUtils.java
