### ISSUE TITLE
An unexpected error while handling a FastAsyncWorldEdit command java.lang.IllegalArgumentException: minY <= maxY required

### ISSUE THREAD

**Issue by SecretlyJealous** [IntellectualSites/FastAsyncWorldEdit#2491]
### Server Implementation

Paper

### Server Version

1.20.2

### Describe the bug

The player is using the command incorrectly based on the log but it prints an error, is there a way to not print this error to console if the player used the command incorrectly?
```
[11:57:47] [Server thread/INFO]: PillowHealer974 issued server command: //fill stone 4
[11:57:47] [AsyncNotifyKeyedQueue - 20/ERROR]: An unexpected error while handling a FastAsyncWorldEdit command
java.lang.IllegalArgumentException: minY <= maxY required
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143) ~[guava-32.1.2-jre.jar:?]
	at com.sk89q.worldedit.function.mask.BoundedHeightMask.<init>(BoundedHeightMask.java:44) ~[FastAsyncWorldEdit-Bukkit-2.8.2.jar:?]
	at com.sk89q.worldedit.EditSession.fillXZ(EditSession.java:1491) ~[FastAsyncWorldEdit-Bukkit-2.8.2.jar:?]
	at com.sk89q.worldedit.EditSession.fillDirection(EditSession.java:1420) ~[FastAsyncWorldEdit-Bukkit-2.8.2.jar:?]
	at com.sk89q.worldedit.command.UtilityCommands.fill(UtilityCommands.java:253) ~[FastAsyncWorldEdit-Bukkit-2.8.2.jar:?]
	at com.sk89q.worldedit.command.UtilityCommandsRegistration.cmd$_fill(UtilityCommandsRegistration.java:539) ~[FastAsyncWorldEdit-Bukkit-2.8.2.jar:?]
	at org.enginehub.piston.CommandManager.execute(CommandManager.java:157) ~[FastAsyncWorldEdit-Bukkit-2.8.2.jar:?]
	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommandOnCurrentThread$16(PlatformCommandManager.java:725) ~[FastAsyncWorldEdit-Bukkit-2.8.2.jar:?]
	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandTask(PlatformCommandManager.java:746) ~[FastAsyncWorldEdit-Bukkit-2.8.2.jar:?]
	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandOnCurrentThread(PlatformCommandManager.java:727) ~[FastAsyncWorldEdit-Bukkit-2.8.2.jar:?]
	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommand$14(PlatformCommandManager.java:698) ~[FastAsyncWorldEdit-Bukkit-2.8.2.jar:?]
	at com.sk89q.worldedit.extension.platform.AbstractPlayerActor.lambda$runAction$1(AbstractPlayerActor.java:672) ~[FastAsyncWorldEdit-Bukkit-2.8.2.jar:?]
	at com.fastasyncworldedit.core.util.task.AsyncNotifyKeyedQueue.lambda$run$0(AsyncNotifyKeyedQueue.java:48) ~[FastAsyncWorldEdit-Bukkit-2.8.2.jar:?]
	at com.fastasyncworldedit.core.util.task.AsyncNotifyKeyedQueue.lambda$call$1(AsyncNotifyKeyedQueue.java:58) ~[FastAsyncWorldEdit-Bukkit-2.8.2.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
	at com.fastasyncworldedit.core.util.task.KeyQueuedExecutorService$KeyRunner.lambda$run$0(KeyQueuedExecutorService.java:150) ~[FastAsyncWorldEdit-Bukkit-2.8.2.jar:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?]
```

### To Reproduce

1. Use //fill stone 4

### Expected behaviour

No error in console

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/e0aa3c2b58744559ac6f4bcff0b2b087

### Fawe Version

FastAsyncWorldEdit-Bukkit-2.8.2

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by SirYwell** [comment]
The command seems to be used correctly. Does that happen everytime the command is used like that? Or only above/below y=0? What world heights are you using?

**Comment by rpsrv** [comment]
i use standard plotsquared heights.

They dont eat or Regrowth...

**Comment by SecretlyJealous** [comment]
> The command seems to be used correctly. Does that happen everytime the command is used like that? Or only above/below y=0? What world heights are you using?
I'm not sure what scenario is causing the error but I have this for my world height:
```
    world:
      border: false
      max_height: 320
      gamemode: creative
      min_height: -63
      max_gen_height: 319
      min_gen_height: -64
      border_size: 1
```

**Comment by dordsor21** [comment]
Is this still occurring? The error message has been updated to give a little more information on the heights involved so if it still occurs, these errors would be useful to see

**Comment by Zeranny** [comment]
You can reproduce this by going above/below the world such that the fill will max out at a block out of bounds.

- Go to Y=323 and do `//fill stone 4 4` = `[22:28:35 ERROR]: An unexpected error while handling a FastAsyncWorldEdit command java.lang.IllegalArgumentException: minY <= maxY required. minY:320 and maxY:319 were given.`
- Go to Y=322 and do `//fill stone 4 4` = No error or blocks placed
- Go to Y=320 and do `//fill stone 4 4` = No error, and a line of vertical line of blocks placed below the player at Y=319
- Go to Y=319 and do `//fill stone 4 4` = Works normally with a spherical fill

You can do the same thing below the world by doing `//fill stone 4 4 up`.

Note that `//fill stone 4 4 up` will not error above max world height, and `//fill stone 4 4 down` will not error below min world height, even if the depth would go out of bounds.
