### ISSUE TITLE
java.lang.StringIndexOutOfBoundsException: Index 0 out of bounds for length 0

### ISSUE THREAD

**Issue by SecretlyJealous** [IntellectualSites/FastAsyncWorldEdit#2494]
### Server Implementation

Paper

### Server Version

1.20.2

### Describe the bug

When this player joins the server this error is printed:
```
[09:42:01 INFO]: UUID of player yefreitor is f7c78a7c-f655-44e6-a40b-5ea36782c1f1
[09:42:01 WARN]: java.lang.StringIndexOutOfBoundsException: Index 0 out of bounds for length 0
[09:42:01 WARN]:        at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:55)
[09:42:01 WARN]:        at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:52)
[09:42:01 WARN]:        at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213)
[09:42:01 WARN]:        at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210)
[09:42:01 WARN]:        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98)
[09:42:01 WARN]:        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
[09:42:01 WARN]:        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
[09:42:01 WARN]:        at java.base/java.lang.String.checkIndex(String.java:4575)
[09:42:01 WARN]:        at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:46)
[09:42:01 WARN]:        at java.base/java.lang.String.charAt(String.java:1535)
[09:42:01 WARN]:        at FastAsyncWorldEdit-Bukkit-2.8.2.jar//com.sk89q.worldedit.world.entity.EntityTypes.convertEntityId(EntityTypes.java:472)
[09:42:01 WARN]:        at FastAsyncWorldEdit-Bukkit-2.8.2.jar//com.sk89q.worldedit.world.entity.EntityTypes.parse(EntityTypes.java:481)
[09:42:01 WARN]:        at FastAsyncWorldEdit-Bukkit-2.8.2.jar//com.sk89q.worldedit.entity.BaseEntity.<init>(BaseEntity.java:118)
[09:42:01 WARN]:        at FastAsyncWorldEdit-Bukkit-2.8.2.jar//com.fastasyncworldedit.core.extent.clipboard.DiskOptimizedClipboard.loadNBTFromFileFooter(DiskOptimizedClipboard.java:270)
[09:42:01 WARN]:        at FastAsyncWorldEdit-Bukkit-2.8.2.jar//com.fastasyncworldedit.core.extent.clipboard.DiskOptimizedClipboard.<init>(DiskOptimizedClipboard.java:198)
[09:42:01 WARN]:        at FastAsyncWorldEdit-Bukkit-2.8.2.jar//com.fastasyncworldedit.core.extent.clipboard.DiskOptimizedClipboard.<init>(DiskOptimizedClipboard.java:167)
[09:42:01 WARN]:        at FastAsyncWorldEdit-Bukkit-2.8.2.jar//com.fastasyncworldedit.core.extent.clipboard.DiskOptimizedClipboard.loadFromFile(DiskOptimizedClipboard.java:223)
[09:42:01 WARN]:        at FastAsyncWorldEdit-Bukkit-2.8.2.jar//com.sk89q.worldedit.LocalSession.lambda$loadClipboardFromDisk$1(LocalSession.java:921)
[09:42:01 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[09:42:01 WARN]:        at FastAsyncWorldEdit-Bukkit-2.8.2.jar//com.fastasyncworldedit.core.util.task.KeyQueuedExecutorService$KeyRunner.lambda$run$0(KeyQueuedExecutorService.java:150)
[09:42:01 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[09:42:01 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[09:42:01 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1623)
[09:42:01 INFO]: yefreitor[/*:54562] logged in with entity id 3161 at ([plotworld]-2090.565644499244, 68.49120751720224, -37060.77915434401)
```

### To Reproduce

1. Not sure

### Expected behaviour

No error in console

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/d3dcbe34a5a2403cb2fe8a94deac18fc

### Fawe Version

FastAsyncWorldEdit-Bukkit-2.8.2.jar

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by SirYwell** [comment]
you can likely just remove the clipboard of the player, but it would be interesting to analyze these files to track down the issue.

**Comment by SecretlyJealous** [comment]
Here are the files: https://www.dropbox.com/scl/fi/goj7p7nunw1i9e2ubgqz5/f7c78a7c-f655-44e6-a40b-5ea36782c1f1.zip?rlkey=j3wqps152agt38nu83wewnsny&dl=1

**Comment by dordsor21** [comment]
That's the player's history - the erroneous clipboard file is what's wanted

**Comment by SecretlyJealous** [comment]
> That's the player's history - the erroneous clipboard file is what's wanted

Apologies: https://www.dropbox.com/scl/fi/dj177svf3lvkhepoumygb/f7c78a7c-f655-44e6-a40b-5ea36782c1f1.bd?rlkey=fu9q09llosvjriof069dqh8bh&dl=1

**Comment by dordsor21** [comment]
I'm not having any issues with that/been able to identify any issues

**Comment by BlueTree242** [comment]
i am having the same issue

**Comment by SecretlyJealous** [comment]
Getting the error on 1.21.10 so I thought it would be better to post the up to date error since the line numbers have changed
FAWE Debugpaste: https://athion.net/ISPaster/paste/view/55741559a9df45e9894ad1b17799fc33

```
[09:52:19 INFO]: UUID of player yefreitor is f7c78a7c-f655-44e6-a40b-5ea36782c1f1
[09:52:19 WARN]: java.lang.StringIndexOutOfBoundsException: Index 0 out of bounds for length 0
[09:52:19 WARN]:        at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:55)
[09:52:19 WARN]:        at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:52)
[09:52:19 WARN]:        at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213)
[09:52:19 WARN]:        at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210)
[09:52:19 WARN]:        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98)
[09:52:19 WARN]:        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
[09:52:19 WARN]:        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
[09:52:19 WARN]:        at java.base/java.lang.String.checkIndex(String.java:4904)
[09:52:19 WARN]:        at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:45)
[09:52:19 WARN]:        at java.base/java.lang.String.charAt(String.java:1624)
[09:52:19 WARN]:        at FastAsyncWorldEdit-Paper-2.14.4-SNAPSHOT-1248.jar//com.sk89q.worldedit.world.entity.EntityTypes.convertEntityId(EntityTypes.java:549)
[09:52:19 WARN]:        at FastAsyncWorldEdit-Paper-2.14.4-SNAPSHOT-1248.jar//com.sk89q.worldedit.world.entity.EntityTypes.parse(EntityTypes.java:558)
[09:52:19 WARN]:        at FastAsyncWorldEdit-Paper-2.14.4-SNAPSHOT-1248.jar//com.sk89q.worldedit.entity.BaseEntity.<init>(BaseEntity.java:126)
[09:52:19 WARN]:        at FastAsyncWorldEdit-Paper-2.14.4-SNAPSHOT-1248.jar//com.fastasyncworldedit.core.extent.clipboard.DiskOptimizedClipboard.loadNBTFromFileFooter(DiskOptimizedClipboard.java:275)
[09:52:19 WARN]:        at FastAsyncWorldEdit-Paper-2.14.4-SNAPSHOT-1248.jar//com.fastasyncworldedit.core.extent.clipboard.DiskOptimizedClipboard.<init>(DiskOptimizedClipboard.java:203)
[09:52:19 WARN]:        at FastAsyncWorldEdit-Paper-2.14.4-SNAPSHOT-1248.jar//com.fastasyncworldedit.core.extent.clipboard.DiskOptimizedClipboard.<init>(DiskOptimizedClipboard.java:172)
[09:52:19 WARN]:        at FastAsyncWorldEdit-Paper-2.14.4-SNAPSHOT-1248.jar//com.fastasyncworldedit.core.extent.clipboard.DiskOptimizedClipboard.loadFromFile(DiskOptimizedClipboard.java:228)
[09:52:19 WARN]:        at FastAsyncWorldEdit-Paper-2.14.4-SNAPSHOT-1248.jar//com.sk89q.worldedit.LocalSession.lambda$loadClipboardFromDisk$1(LocalSession.java:936)
[09:52:19 WARN]:        at FastAsyncWorldEdit-Paper-2.14.4-SNAPSHOT-1248.jar//com.fastasyncworldedit.core.Fawe.submitUUIDKeyQueuedTask(Fawe.java:510)
[09:52:19 WARN]:        at FastAsyncWorldEdit-Paper-2.14.4-SNAPSHOT-1248.jar//com.sk89q.worldedit.LocalSession.loadClipboardFromDisk(LocalSession.java:934)
[09:52:19 WARN]:        at FastAsyncWorldEdit-Paper-2.14.4-SNAPSHOT-1248.jar//com.sk89q.worldedit.extension.platform.AbstractPlayerActor.lambda$loadClipboardFromDisk$1(AbstractPlayerActor.java:554)
[09:52:19 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:545)
[09:52:19 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:328)
[09:52:19 WARN]:        at FastAsyncWorldEdit-Paper-2.14.4-SNAPSHOT-1248.jar//com.fastasyncworldedit.core.util.task.KeyQueuedExecutorService$KeyRunner.lambda$run$0(KeyQueuedExecutorService.java:150)
[09:52:19 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1090)
[09:52:19 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:614)
[09:52:19 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1474)
[09:52:19 INFO]: yefreitor[/*] logged in with entity id 3524 at ([plotworld]-13607.58206716849, 36.0, -8442.497820432247)
```

**Comment by PierreSchwang** [comment]
Share the new clipboard file (f7c78a7c-f655-44e6-a40b-5ea36782c1f1.bd) again please.

**Comment by SecretlyJealous** [comment]
> Share the new clipboard file (f7c78a7c-f655-44e6-a40b-5ea36782c1f1.bd) again please.

https://www.dropbox.com/scl/fi/0x8kefakokx11u83jv2f9/f7c78a7c-f655-44e6-a40b-5ea36782c1f1.bd?rlkey=au1ytqhe80qi1nfk2x6pdvy0o&st=wwqsmj23&dl=1

**Comment by PierreSchwang** [comment]
I can reproduce the issue and see the reason. The stored entity NBT contains a `id` tag with the entity id, even though FAWE expects `Id`. The former is valid in terms of the minecraft entity format, but FAWE internally works with the uppercase variant.

I would be interested when or how the clipboard was created? Can the player remember anything about that? Do you have any plugin installed that might hook into WE/FAWE? I guess we could forcefully add the `Id` tag when writing the entity nbt in the disk clipboard - but the correct `Id` tag should already be present when writing (especially given the issue is so rare).


And did the player copy anything recently or is this clipboard just extremely old?
