### ISSUE TITLE
loading a schematic and using //paste throws error and does not paste

### ISSUE THREAD

**Issue by Imwreckk** [IntellectualSites/FastAsyncWorldEdit#2517]
### Server Implementation

Paper

### Server Version

1.20

### Describe the bug

When loading a schematic from a clipboard it shoots an error and doesn't let you paste. Maybe an old schematic file. I will attach said schematic link : https://mcbuild.org/download/16957?k=pgRbcbeahf

### To Reproduce

Load a schematic while the server is running 
reload FAWE
List schematics
Click on schematic to loadall
use //paste

Even if schematic is downloaded and server restarts, you get the same error

### Expected behaviour

Should paste designated schematic. Instead prints error

### Screenshots / Videos

![Screenshot_6](https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/153773353/8caa21c2-9178-4e98-824c-1c0161090418)

### Error log (if applicable)

[12:26:23 ERROR]: An unexpected error while handling a FastAsyncWorldEdit command java.lang.NullPointerException: Cannot invoke "com.sk89q.worldedit.extent.clipboard.Clipboard.getOrigin()" because "clipboard" is null         at com.sk89q.worldedit.command.ClipboardCommands.place(ClipboardCommands.java:460) ~[FastAsyncWorldEdit-Bukkit-2.8.2.jar:?]         at com.sk89q.worldedit.command.ClipboardCommands.paste(ClipboardCommands.java:522) ~[FastAsyncWorldEdit-Bukkit-2.8.2.jar:?]         at com.sk89q.worldedit.command.ClipboardCommandsRegistration.cmd$_paste(ClipboardCommandsRegistration.java:345) ~[FastAsyncWorldEdit-Bukkit-2.8.2.jar:?]         at org.enginehub.piston.CommandManager.execute(CommandManager.java:157) ~[FastAsyncWorldEdit-Bukkit-2.8.2.jar:?]         at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommandOnCurrentThread$16(PlatformCommandManager.java:725) ~[FastAsyncWorldEdit-Bukkit-2.8.2.jar:?]         at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandTask(PlatformCommandManager.java:746) ~[FastAsyncWorldEdit-Bukkit-2.8.2.jar:?]         at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandOnCurrentThread(PlatformCommandManager.java:727) ~[FastAsyncWorldEdit-Bukkit-2.8.2.jar:?]         at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommand$14(PlatformCommandManager.java:698) ~[FastAsyncWorldEdit-Bukkit-2.8.2.jar:?]         at com.sk89q.worldedit.extension.platform.AbstractPlayerActor.lambda$runAction$1(AbstractPlayerActor.java:672) ~[FastAsyncWorldEdit-Bukkit-2.8.2.jar:?]         at com.fastasyncworldedit.core.util.task.AsyncNotifyKeyedQueue.lambda$run$0(AsyncNotifyKeyedQueue.java:48) ~[FastAsyncWorldEdit-Bukkit-2.8.2.jar:?]         at com.fastasyncworldedit.core.util.task.AsyncNotifyKeyedQueue.lambda$call$1(AsyncNotifyKeyedQueue.java:58) ~[FastAsyncWorldEdit-Bukkit-2.8.2.jar:?]         at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]         at com.fastasyncworldedit.core.util.task.KeyQueuedExecutorService$KeyRunner.lambda$run$0(KeyQueuedExecutorService.java:150) ~[FastAsyncWorldEdit-Bukkit-2.8.2.jar:?]         at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[?:?]         at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]         at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]         at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]         at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]         at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/104734f553b64bd38476a584b9b64e02

### Fawe Version

2.8.4 - snapshot 625

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by TheMeinerLP** [comment]
How did you reload ?

**Comment by Imwreckk** [comment]
I used /fawe reload and restarted the server also
Sent from my iPhone

On 13 Dec 2023, at 20:58, Phillipp Glanz ***@***.***> wrote:

﻿

How did you reload ?

**Comment by Lele289** [comment]
I have the same problem, but I tried to load the schematic using the command //schematic loadall jungle.schematic

Error log: https://pastebin.com/PH7SDHmH

**Comment by dordsor21** [comment]
Why's everyone ignored the error actually causing this issue in their logs... It's only present in the debugpaste. Please. If you see an error, send the entire error. It's also helpful if it's in a format that we can actually read. A massive blocks text that isn't even line separated is not very helpful

**Comment by dordsor21** [comment]
```
[12:26:20] [Server thread/INFO]: _T8B issued server command: //schematic loadall Goticcastle.schematic
[12:26:23] [Server thread/INFO]: _T8B issued server command: //paste
[12:26:23] [AsyncNotifyKeyedQueue - 0/INFO]: Using com.sk89q.worldedit.bukkit.adapter.impl.fawe.v1_20_R2.PaperweightStarlightRelighterFactory as relighter factory.
[12:26:23] [AsyncNotifyKeyedQueue - 0/WARN]: java.io.IOException: Tag 'Schematic' does not exist or is not first
[12:26:23] [AsyncNotifyKeyedQueue - 0/WARN]: 	at FastAsyncWorldEdit-Bukkit-2.8.2.jar//com.sk89q.worldedit.extent.clipboard.io.MCEditSchematicReader.read(MCEditSchematicReader.java:113)
[12:26:23] [AsyncNotifyKeyedQueue - 0/WARN]: 	at FastAsyncWorldEdit-Bukkit-2.8.2.jar//com.sk89q.worldedit.extent.clipboard.io.ClipboardReader.read(ClipboardReader.java:74)
[12:26:23] [AsyncNotifyKeyedQueue - 0/WARN]: 	at FastAsyncWorldEdit-Bukkit-2.8.2.jar//com.sk89q.worldedit.extent.clipboard.io.ClipboardReader.read(ClipboardReader.java:62)
[12:26:23] [AsyncNotifyKeyedQueue - 0/WARN]: 	at FastAsyncWorldEdit-Bukkit-2.8.2.jar//com.fastasyncworldedit.core.extent.clipboard.LazyClipboardHolder.getClipboard(LazyClipboardHolder.java:42)
[12:26:23] [AsyncNotifyKeyedQueue - 0/WARN]: 	at FastAsyncWorldEdit-Bukkit-2.8.2.jar//com.sk89q.worldedit.session.ClipboardHolder.getClipboards(ClipboardHolder.java:78)
[12:26:23] [AsyncNotifyKeyedQueue - 0/WARN]: 	at FastAsyncWorldEdit-Bukkit-2.8.2.jar//com.fastasyncworldedit.core.extent.clipboard.MultiClipboardHolder.getClipboards(MultiClipboardHolder.java:120)
[12:26:23] [AsyncNotifyKeyedQueue - 0/WARN]: 	at FastAsyncWorldEdit-Bukkit-2.8.2.jar//com.fastasyncworldedit.core.extent.clipboard.MultiClipboardHolder.getClipboard(MultiClipboardHolder.java:151)
[12:26:23] [AsyncNotifyKeyedQueue - 0/WARN]: 	at FastAsyncWorldEdit-Bukkit-2.8.2.jar//com.sk89q.worldedit.command.ClipboardCommands.place(ClipboardCommands.java:459)
[12:26:23] [AsyncNotifyKeyedQueue - 0/WARN]: 	at FastAsyncWorldEdit-Bukkit-2.8.2.jar//com.sk89q.worldedit.command.ClipboardCommands.paste(ClipboardCommands.java:522)
[12:26:23] [AsyncNotifyKeyedQueue - 0/WARN]: 	at FastAsyncWorldEdit-Bukkit-2.8.2.jar//com.sk89q.worldedit.command.ClipboardCommandsRegistration.cmd$_paste(ClipboardCommandsRegistration.java:345)
[12:26:23] [AsyncNotifyKeyedQueue - 0/WARN]: 	at FastAsyncWorldEdit-Bukkit-2.8.2.jar//org.enginehub.piston.CommandManager.execute(CommandManager.java:157)
[12:26:23] [AsyncNotifyKeyedQueue - 0/WARN]: 	at FastAsyncWorldEdit-Bukkit-2.8.2.jar//com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommandOnCurrentThread$16(PlatformCommandManager.java:725)
[12:26:23] [AsyncNotifyKeyedQueue - 0/WARN]: 	at FastAsyncWorldEdit-Bukkit-2.8.2.jar//com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandTask(PlatformCommandManager.java:746)
[12:26:23] [AsyncNotifyKeyedQueue - 0/WARN]: 	at FastAsyncWorldEdit-Bukkit-2.8.2.jar//com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandOnCurrentThread(PlatformCommandManager.java:727)
[12:26:23] [AsyncNotifyKeyedQueue - 0/WARN]: 	at FastAsyncWorldEdit-Bukkit-2.8.2.jar//com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommand$14(PlatformCommandManager.java:698)
[12:26:23] [AsyncNotifyKeyedQueue - 0/WARN]: 	at FastAsyncWorldEdit-Bukkit-2.8.2.jar//com.sk89q.worldedit.extension.platform.AbstractPlayerActor.lambda$runAction$1(AbstractPlayerActor.java:672)
[12:26:23] [AsyncNotifyKeyedQueue - 0/WARN]: 	at FastAsyncWorldEdit-Bukkit-2.8.2.jar//com.fastasyncworldedit.core.util.task.AsyncNotifyKeyedQueue.lambda$run$0(AsyncNotifyKeyedQueue.java:48)
[12:26:23] [AsyncNotifyKeyedQueue - 0/WARN]: 	at FastAsyncWorldEdit-Bukkit-2.8.2.jar//com.fastasyncworldedit.core.util.task.AsyncNotifyKeyedQueue.lambda$call$1(AsyncNotifyKeyedQueue.java:58)
[12:26:23] [AsyncNotifyKeyedQueue - 0/WARN]: 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[12:26:23] [AsyncNotifyKeyedQueue - 0/WARN]: 	at FastAsyncWorldEdit-Bukkit-2.8.2.jar//com.fastasyncworldedit.core.util.task.KeyQueuedExecutorService$KeyRunner.lambda$run$0(KeyQueuedExecutorService.java:150)
[12:26:23] [AsyncNotifyKeyedQueue - 0/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
[12:26:23] [AsyncNotifyKeyedQueue - 0/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[12:26:23] [AsyncNotifyKeyedQueue - 0/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[12:26:23] [AsyncNotifyKeyedQueue - 0/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[12:26:23] [AsyncNotifyKeyedQueue - 0/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[12:26:23] [AsyncNotifyKeyedQueue - 0/WARN]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[12:26:23] [AsyncNotifyKeyedQueue - 0/ERROR]: An unexpected error while handling a FastAsyncWorldEdit command
java.lang.NullPointerException: Cannot invoke "com.sk89q.worldedit.extent.clipboard.Clipboard.getOrigin()" because "clipboard" is null
	at com.sk89q.worldedit.command.ClipboardCommands.place(ClipboardCommands.java:460) ~[FastAsyncWorldEdit-Bukkit-2.8.2.jar:?]
	at com.sk89q.worldedit.command.ClipboardCommands.paste(ClipboardCommands.java:522) ~[FastAsyncWorldEdit-Bukkit-2.8.2.jar:?]
	at com.sk89q.worldedit.command.ClipboardCommandsRegistration.cmd$_paste(ClipboardCommandsRegistration.java:345) ~[FastAsyncWorldEdit-Bukkit-2.8.2.jar:?]
	at org.enginehub.piston.CommandManager.execute(CommandManager.java:157) ~[FastAsyncWorldEdit-Bukkit-2.8.2.jar:?]
	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommandOnCurrentThread$16(PlatformCommandManager.java:725) ~[FastAsyncWorldEdit-Bukkit-2.8.2.jar:?]
	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandTask(PlatformCommandManager.java:746) ~[FastAsyncWorldEdit-Bukkit-2.8.2.jar:?]
	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandOnCurrentThread(PlatformCommandManager.java:727) ~[FastAsyncWorldEdit-Bukkit-2.8.2.jar:?]
	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommand$14(PlatformCommandManager.java:698) ~[FastAsyncWorldEdit-Bukkit-2.8.2.jar:?]
	at com.sk89q.worldedit.extension.platform.AbstractPlayerActor.lambda$runAction$1(AbstractPlayerActor.java:672) ~[FastAsyncWorldEdit-Bukkit-2.8.2.jar:?]
	at com.fastasyncworldedit.core.util.task.AsyncNotifyKeyedQueue.lambda$run$0(AsyncNotifyKeyedQueue.java:48) ~[FastAsyncWorldEdit-Bukkit-2.8.2.jar:?]
	at com.fastasyncworldedit.core.util.task.AsyncNotifyKeyedQueue.lambda$call$1(AsyncNotifyKeyedQueue.java:58) ~[FastAsyncWorldEdit-Bukkit-2.8.2.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at com.fastasyncworldedit.core.util.task.KeyQueuedExecutorService$KeyRunner.lambda$run$0(KeyQueuedExecutorService.java:150) ~[FastAsyncWorldEdit-Bukkit-2.8.2.jar:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
	```

**Comment by dordsor21** [comment]
I am assuming that you are attempting either to load a corrupt/incorrectly-formated legacy schematic, or it is not actually an mcedit schematic, in which case the file ending should be `.schem` not `.schematic`.
