### ISSUE TITLE
History of other players gets pasted after copying & pasting other buildings

### ISSUE THREAD

**Issue by MarvinKlar** [IntellectualSites/FastAsyncWorldEdit#2559]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

When copying buildings on other Plotsquared plots and pasting them, parts of them are different than the actual building. This bug could also be related to PlotSquared.

### To Reproduce

1. Install WorldGuard 7.0.6, FAWE 1.17-426 and PlotSquared 6.2.3
2. Create a plot with player A, copy something and paste it. Trust player B on your plot.
3. Create a plot with player B, got to plot A, copy something and paste it on plot B.

### Expected behaviour

The copyied blocks should be pasted. Instead, the copied blocks of the previous player are beeing pasted.

### Screenshots / Videos

https://marvinklar.de/download/FAWE.mp4

### Error log (if applicable)

There are no errors in the console

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/0f4df2307c4f46bba21b4f34fda39000

### Fawe Version

1.17.1-423;42035bd

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by OneLiteFeather** [comment]
Is your server on offline mode to support cracked players? I didn't find the online mode inside your debugpaste. If yes, this is why it may happens

**Comment by MarvinKlar** [comment]
No, the server is running in online mode (online-mode=true).

**Comment by OneLiteFeather** [comment]
can you do a spark profiling and send it here?

**Comment by MarvinKlar** [comment]
How would I do so?

**Comment by OneLiteFeather** [comment]
Install the [spark plugin](https://www.spigotmc.org/resources/spark.57242/) on your server and run the profiler for 30 minutes (you can still do all the building stuff while it is running), share the profiler link here

**Comment by MarvinKlar** [comment]
I wasn't able to reproduce the bug now, but here is the profiler result: https://spark.lucko.me/FVSex7Nmzx

If the bug occours again, I'll create another profiling.

**Comment by OneLiteFeather** [comment]
#2567
 Also I am not 100% sure if this can be caused by custom entities, I saw that you customized some stuff like the ladders on your server too (if it isn't just ressource pack magic).

**Comment by OneLiteFeather** [comment]
@MarvinKlar can you try replicating the bug with the given issue in the PR linked ?
> #2567

**Comment by MarvinKlar** [comment]
The ladders are just retextured.

Would I need to update FAWE?

**Comment by OneLiteFeather** [comment]
@MarvinKlar please update fawe, plotsquared and if possible worldguard too to latest if it still supports 1.17.1 and retry if the bug still exists.

**Comment by MarvinKlar** [comment]
I updated WorldGuard, but I was not yet able to update FAWE, since the latest version is not compatible to our PlotSqaured version. And we can't figure out who bought PlotSquared back then xD Was it once free?

Anyways I encountered another error, which might be related?

```
java.nio.channels.OverlappingFileLockException
[00:55:48] [Paper Async Task Handler Thread - 184/WARN]: 	at [java.base/sun.nio.ch.FileLockTable.checkList(FileLockTable.java:229)](http://java.base/sun.nio.ch.FileLockTable.checkList(FileLockTable.java:229))9
[00:55:48] [Paper Async Task Handler Thread - 184/WARN]: 	at [java.base/sun.nio.ch.FileLockTable.add(FileLockTable.java:123)](http://java.base/sun.nio.ch.FileLockTable.add(FileLockTable.java:123))3
[00:55:48] [Paper Async Task Handler Thread - 184/WARN]: 	at [java.base/sun.nio.ch.FileChannelImpl.lock(FileChannelImpl.java:1276)](http://java.base/sun.nio.ch.FileChannelImpl.lock(FileChannelImpl.java:1276))6
[00:55:48] [Paper Async Task Handler Thread - 184/WARN]: 	at [java.base/java.nio.channels.FileChannel.lock(FileChannel.java:1089)](http://java.base/java.nio.channels.FileChannel.lock(FileChannel.java:1089))9
[00:55:48] [Paper Async Task Handler Thread - 184/WARN]: 	at FastAsyncWorldEdit-Bukkit[-1.17-426.jar//com.fastasyncworldedit.core.extent.clipboard.DiskOptimizedClipboard.init(DiskOptimizedClipboard.java:174)](http://-1.17-426.jar//com.fastasyncworldedit.core.extent.clipboard.DiskOptimizedClipboard.init(DiskOptimizedClipboard.java:174))4
[00:55:48] [Paper Async Task Handler Thread - 184/WARN]: 	at FastAsyncWorldEdit-Bukkit[-1.17-426.jar//com.fastasyncworldedit.core.extent.clipboard.DiskOptimizedClipboard](http://-1.17-426.jar//com.fastasyncworldedit.core.extent.clipboard.DiskOptimizedClipboard).<init>(DiskOptimizedClipboard.java:138)
[00:55:48] [Paper Async Task Handler Thread - 184/WARN]: 	at FastAsyncWorldEdit-Bukkit[-1.17-426.jar//com.sk89q.worldedit.entity.Player.loadClipboardFromDisk(Player.java:466)](http://-1.17-426.jar//com.sk89q.worldedit.entity.Player.loadClipboardFromDisk(Player.java:466))6
[00:55:48] [Paper Async Task Handler Thread - 184/WARN]: 	at FastAsyncWorldEdit-Bukkit[-1.17-426.jar//com.sk89q.worldedit.bukkit.BukkitPlayer](http://-1.17-426.jar//com.sk89q.worldedit.bukkit.BukkitPlayer).<init>(BukkitPlayer.java:113)
[00:55:48] [Paper Async Task Handler Thread - 184/WARN]: 	at FastAsyncWorldEdit-Bukkit[-1.17-426.jar//com.sk89q.worldedit.bukkit.WorldEditPlugin.wrapPlayer(WorldEditPlugin.java:546)](http://-1.17-426.jar//com.sk89q.worldedit.bukkit.WorldEditPlugin.wrapPlayer(WorldEditPlugin.java:546))6
[00:55:48] [Paper Async Task Handler Thread - 184/WARN]: 	at FastAsyncWorldEdit-Bukkit[-1.17-426.jar//com.sk89q.worldedit.bukkit.WorldEditPlugin.wrapCommandSender(WorldEditPlugin.java:568)](http://-1.17-426.jar//com.sk89q.worldedit.bukkit.WorldEditPlugin.wrapCommandSender(WorldEditPlugin.java:568))8
[00:55:48] [Paper Async Task Handler Thread - 184/WARN]: 	at FastAsyncWorldEdit-Bukkit[-1.17-426.jar//com.sk89q.worldedit.bukkit.BukkitCommandInspector.lambda$testPermission$0(BukkitCommandInspector.java:80)](http://-1.17-426.jar//com.sk89q.worldedit.bukkit.BukkitCommandInspector.lambda$testPermission$0(BukkitCommandInspector.java:80))0
[00:55:48] [Paper Async Task Handler Thread - 184/WARN]: 	at FastAsyncWorldEdit-Bukkit[-1.17-426.jar//org.enginehub.piston.inject.MapBackedValueStore.lambda$injectedValue$0(MapBackedValueStore.java:56)](http://-1.17-426.jar//org.enginehub.piston.inject.MapBackedValueStore.lambda$injectedValue$0(MapBackedValueStore.java:56))6
[00:55:48] [Paper Async Task Handler Thread - 184/WARN]: 	at [java.base/java.util.Optional.flatMap(Optional.java:289)](http://java.base/java.util.Optional.flatMap(Optional.java:289))9
[00:55:48] [Paper Async Task Handler Thread - 184/WARN]: 	at FastAsyncWorldEdit-Bukkit[-1.17-426.jar//org.enginehub.piston.inject.MapBackedValueStore.injectedValue(MapBackedValueStore.java:56)](http://-1.17-426.jar//org.enginehub.piston.inject.MapBackedValueStore.injectedValue(MapBackedValueStore.java:56))6
[00:55:48] [Paper Async Task Handler Thread - 184/WARN]: 	at FastAsyncWorldEdit-Bukkit[-1.17-426.jar//org.enginehub.piston.inject.InjectedValueAccess.injectedValue(InjectedValueAccess.java:44)](http://-1.17-426.jar//org.enginehub.piston.inject.InjectedValueAccess.injectedValue(InjectedValueAccess.java:44))4
[00:55:48] [Paper Async Task Handler Thread - 184/WARN]: 	at FastAsyncWorldEdit-Bukkit[-1.17-426.jar//com.sk89q.worldedit.command.util.PermissionCondition.satisfied(PermissionCondition.java:54)](http://-1.17-426.jar//com.sk89q.worldedit.command.util.PermissionCondition.satisfied(PermissionCondition.java:54))4
[00:55:48] [Paper Async Task Handler Thread - 184/WARN]: 	at FastAsyncWorldEdit-Bukkit[-1.17-426.jar//com.sk89q.worldedit.bukkit.BukkitCommandInspector.testPermission(BukkitCommandInspector.java:81)](http://-1.17-426.jar//com.sk89q.worldedit.bukkit.BukkitCommandInspector.testPermission(BukkitCommandInspector.java:81))1
[00:55:48] [Paper Async Task Handler Thread - 184/WARN]: 	at FastAsyncWorldEdit-Bukkit[-1.17-426.jar//com.sk89q.bukkit.util.DynamicPluginCommand.testPermissionSilent(DynamicPluginCommand.java:107)](http://-1.17-426.jar//com.sk89q.bukkit.util.DynamicPluginCommand.testPermissionSilent(DynamicPluginCommand.java:107))7
[00:55:48] [Paper Async Task Handler Thread - 184/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.command.BukkitCommandWrapper.test(BukkitCommandWrapper.java:48)
[00:55:48] [Paper Async Task Handler Thread - 184/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.command.BukkitCommandWrapper.test(BukkitCommandWrapper.java:20)
[00:55:48] [Paper Async Task Handler Thread - 184/WARN]: 	at com.mojang.brigadier.tree.CommandNode.canUse(CommandNode.java:78)
[00:55:48] [Paper Async Task Handler Thread - 184/WARN]: 	at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:405)
[00:55:48] [Paper Async Task Handler Thread - 184/WARN]: 	at net.minecraft.commands.CommandDispatcher.sendAsync(CommandDispatcher.java:369)
[00:55:48] [Paper Async Task Handler Thread - 184/WARN]: 	at net.minecraft.commands.CommandDispatcher.lambda$sendCommands$5(CommandDispatcher.java:353)
[00:55:48] [Paper Async Task Handler Thread - 184/WARN]: 	at [java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)](http://java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136))6
[00:55:48] [Paper Async Task Handler Thread - 184/WARN]: 	at [java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)](http://java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635))5
[00:55:48] [Paper Async Task Handler Thread - 184/WARN]: 	at [java.base/java.lang.Thread.run(Thread.java:840)](http://java.base/java.lang.Thread.run(Thread.java:840))0
```

**Comment by OneLiteFeather** [comment]
Plotsquared free to build on your own, the additional support on discord is the one you can buy. You can update both fawe and Plotsquared and the Exception should be gone

**Comment by dordsor21** [comment]
Using a massively outdated version and no response for a while
