### ISSUE TITLE
ERROR]: An unexpected error while handling a FastAsyncWorldEdit command java.lang.NoSuchMethodError: 'boolean net.minecraft.world.level.block.state.IBlockData.isOpaque()'

### ISSUE THREAD

**Issue by HyacinthYC** [IntellectualSites/FastAsyncWorldEdit#2607]
### Server Implementation

Paper

### Server Version

1.20.4

### Describe the bug

当我在服务器使用//fixconnect时的报错

ERROR]: An unexpected error while handling a FastAsyncWorldEdit command
java.lang.NoSuchMethodError: 'boolean net.minecraft.world.level.block.state.IBlockData.isOpaque()'
        at com.sk89q.worldedit.bukkit.adapter.impl.fawe.v1_20_R3.PaperweightBlockMaterial.isOpaque(PaperweightBlockMaterial.java:78) ~[FastAsyncWorldEdit-Bukkit-2.9.0.jar:?]
        at com.arceon.core.command.FixConnectHandler.G(Unknown Source) ~[Arceon-0.4.4_1.16+.jar:?]
        at com.arceon.core.command.FixConnectHandler.fixconnect(Unknown Source) ~[Arceon-0.4.4_1.16+.jar:?]
        at com.arceon.core.command.FixConnectHandlerRegistration.A(Unknown Source) ~[Arceon-0.4.4_1.16+.jar:?]
        at org.enginehub.piston.CommandManager.execute(CommandManager.java:157) ~[FastAsyncWorldEdit-Bukkit-2.9.0.jar:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommandOnCurrentThread$16(PlatformCommandManager.java:725) ~[FastAsyncWorldEdit-Bukkit-2.9.0.jar:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandTask(PlatformCommandManager.java:746) ~[FastAsyncWorldEdit-Bukkit-2.9.0.jar:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandOnCurrentThread(PlatformCommandManager.java:727) ~[FastAsyncWorldEdit-Bukkit-2.9.0.jar:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommand$14(PlatformCommandManager.java:698) ~[FastAsyncWorldEdit-Bukkit-2.9.0.jar:?]
        at com.sk89q.worldedit.extension.platform.AbstractPlayerActor.lambda$runAction$1(AbstractPlayerActor.java:672) ~[FastAsyncWorldEdit-Bukkit-2.9.0.jar:?]
        at com.fastasyncworldedit.core.util.task.AsyncNotifyKeyedQueue.lambda$run$0(AsyncNotifyKeyedQueue.java:48) ~[FastAsyncWorldEdit-Bukkit-2.9.0.jar:?]
        at com.fastasyncworldedit.core.util.task.AsyncNotifyKeyedQueue.lambda$call$1(AsyncNotifyKeyedQueue.java:58) ~[FastAsyncWorldEdit-Bukkit-2.9.0.jar:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at com.fastasyncworldedit.core.util.task.KeyQueuedExecutorService$KeyRunner.lambda$run$0(KeyQueuedExecutorService.java:150) ~[FastAsyncWorldEdit-Bukkit-2.9.0.jar:?]
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]

### To Reproduce

//fixconnect

### Expected behaviour

当有调整链接状态

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/971b83c908234ac782fd304fcfb92746

### Fawe Version

FastAsyncWorldEdit-Bukkit-2.9.0.jar

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by Zeranny** [comment]
This is technically a problem for Arceon, I have passed on your issue to the Plugin author.

The underlying issue however is that `isOpaque()` doesn't seem to exist anymore, so perhaps that needs to be removed from Material?
