### ISSUE TITLE
Regen support for 1.21

### ISSUE THREAD

**Issue by dordsor21** [IntellectualSites/FastAsyncWorldEdit#2818]
The new generation system broke regen support in 1.21 by a large amount

**Comment by JoeTheOrangeCat** [comment]
Yeah it just errors for me completely.
Here the error if its helpfull, I feel this is more of a bug fix instead of a Enhancement

> [10:53:50] [AsyncNotifyKeyedQueue - 0/ERROR]: An unexpected error while handling a FastAsyncWorldEdit command
java.lang.IllegalAccessError: class com.sk89q.worldedit.bukkit.adapter.impl.fawe.v1_21_R1.regen.PaperweightRegen tried to access private field net.minecraft.server.level.PlayerChunkMap.P (com.sk89q.worldedit.bukkit.adapter.impl.fawe.v1_21_R1.regen.PaperweightRegen is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @52f7d97b; net.minecraft.server.level.PlayerChunkMap is in unnamed module of loader java.net.URLClassLoader @736e9adb)
        at com.sk89q.worldedit.bukkit.adapter.impl.fawe.v1_21_R1.regen.PaperweightRegen.initNewWorld(PaperweightRegen.java:389) ~[?:?]
        at com.fastasyncworldedit.bukkit.adapter.Regenerator.regenerate(Regenerator.java:116) ~[?:?]
        at com.sk89q.worldedit.bukkit.adapter.impl.fawe.v1_21_R1.PaperweightFaweAdapter.regenerate(PaperweightFaweAdapter.java:561) ~[?:?]
        at com.sk89q.worldedit.bukkit.BukkitWorld.regenerate(BukkitWorld.java:258) ~[?:?]
        at com.fastasyncworldedit.core.wrappers.WorldWrapper.regenerate(WorldWrapper.java:278) ~[?:?]
        at com.sk89q.worldedit.command.RegionCommands.regenerate(RegionCommands.java:712) ~[?:?]
        at com.sk89q.worldedit.command.RegionCommandsRegistration.cmd$_regen(RegionCommandsRegistration.java:954) ~[?:?]
        at org.enginehub.piston.CommandManager.execute(CommandManager.java:157) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommandOnCurrentThread$16(PlatformCommandManager.java:727) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandTask(PlatformCommandManager.java:748) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandOnCurrentThread(PlatformCommandManager.java:729) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommand$14(PlatformCommandManager.java:700) ~[?:?]
        at com.sk89q.worldedit.extension.platform.AbstractPlayerActor.lambda$runAction$1(AbstractPlayerActor.java:672) ~[?:?]
        at com.fastasyncworldedit.core.util.task.AsyncNotifyKeyedQueue.lambda$run$0(AsyncNotifyKeyedQueue.java:48) ~[?:?]
        at com.fastasyncworldedit.core.util.task.AsyncNotifyKeyedQueue.lambda$call$1(AsyncNotifyKeyedQueue.java:58) ~[?:?]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
        at com.fastasyncworldedit.core.util.task.KeyQueuedExecutorService$KeyRunner.lambda$run$0(KeyQueuedExecutorService.java:150) ~[?:?]
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423) [?:?]
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) [?:?]
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) [?:?]
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) [?:?]
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) [?:?]
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) [?:?]

**Comment by nuttapillar** [comment]
I'm having a similar issue, but my error looks different. 
! [Wed 15:14:24 WARN  com.sk89q.worldedit.bukkit.BukkitWorld] Regeneration via adapter failed.
java.lang.UnsupportedOperationException: Regeneration currently not support on Paper due to the new generation system
    at FastAsyncWorldEdit-Bukkit-2.11.0.jar//com.sk89q.worldedit.bukkit.adapter.impl.fawe.v1_21_R1.regen.PaperweightRegen.<init>(PaperweightRegen.java:196)
    at FastAsyncWorldEdit-Bukkit-2.11.0.jar//com.sk89q.worldedit.bukkit.adapter.impl.fawe.v1_21_R1.PaperweightFaweAdapter.regenerate(PaperweightFaweAdapter.java:561)
    at FastAsyncWorldEdit-Bukkit-2.11.0.jar//com.sk89q.worldedit.bukkit.BukkitWorld.regenerate(BukkitWorld.java:258)
    at FastAsyncWorldEdit-Bukkit-2.11.0.jar//com.fastasyncworldedit.core.wrappers.WorldWrapper.regenerate(WorldWrapper.java:278)
    at FastAsyncWorldEdit-Bukkit-2.11.0.jar//com.sk89q.worldedit.command.RegionCommands.regenerate(RegionCommands.java:712)
    at FastAsyncWorldEdit-Bukkit-2.11.0.jar//com.sk89q.worldedit.command.RegionCommandsRegistration.cmd$_regen(RegionCommandsRegistration.java:954)
    at FastAsyncWorldEdit-Bukkit-2.11.0.jar//org.enginehub.piston.CommandManager.execute(CommandManager.java:157)
    at FastAsyncWorldEdit-Bukkit-2.11.0.jar//com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommandOnCurrentThread$16(PlatformCommandManager.java:727)
    at FastAsyncWorldEdit-Bukkit-2.11.0.jar//com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandTask(PlatformCommandManager.java:748)
    at FastAsyncWorldEdit-Bukkit-2.11.0.jar//com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandOnCurrentThread(PlatformCommandManager.java:729)
    at FastAsyncWorldEdit-Bukkit-2.11.0.jar//com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommand$14(PlatformCommandManager.java:700)
    at FastAsyncWorldEdit-Bukkit-2.11.0.jar//com.sk89q.worldedit.extension.platform.AbstractPlayerActor.lambda$runAction$1(AbstractPlayerActor.java:672)
    at FastAsyncWorldEdit-Bukki

**Comment by PierreSchwang** [comment]
> I'm having a similar issue, but my error looks different. ! [Wed 15:14:24 WARN com.sk89q.worldedit.bukkit.BukkitWorld] Regeneration via adapter failed. java.lang.UnsupportedOperationException: Regeneration currently not support on Paper due to the new generation system at FastAsyncWorldEdit-Bukkit-2.11.0.jar//com.sk89q.worldedit.bukkit.adapter.impl.fawe.v1_21_R1.regen.PaperweightRegen.(PaperweightRegen.java:196) at FastAsyncWorldEdit-Bukkit-2.11.0.jar//com.sk89q.worldedit.bukkit.adapter.impl.fawe.v1_21_R1.PaperweightFaweAdapter.regenerate(PaperweightFaweAdapter.java:561) at FastAsyncWorldEdit-Bukkit-2.11.0.jar//com.sk89q.worldedit.bukkit.BukkitWorld.regenerate(BukkitWorld.java:258) at FastAsyncWorldEdit-Bukkit-2.11.0.jar//com.fastasyncworldedit.core.wrappers.WorldWrapper.regenerate(WorldWrapper.java:278) at FastAsyncWorldEdit-Bukkit-2.11.0.jar//com.sk89q.worldedit.command.RegionCommands.regenerate(RegionCommands.java:712) at FastAsyncWorldEdit-Bukkit-2.11.0.jar//com.sk89q.worldedit.command.RegionCommandsRegistration.cmd$_regen(RegionCommandsRegistration.java:954) at FastAsyncWorldEdit-Bukkit-2.11.0.jar//org.enginehub.piston.CommandManager.execute(CommandManager.java:157) at FastAsyncWorldEdit-Bukkit-2.11.0.jar//com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommandOnCurrentThread$16(PlatformCommandManager.java:727) at FastAsyncWorldEdit-Bukkit-2.11.0.jar//com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandTask(PlatformCommandManager.java:748) at FastAsyncWorldEdit-Bukkit-2.11.0.jar//com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandOnCurrentThread(PlatformCommandManager.java:729) at FastAsyncWorldEdit-Bukkit-2.11.0.jar//com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommand$14(PlatformCommandManager.java:700) at FastAsyncWorldEdit-Bukkit-2.11.0.jar//com.sk89q.worldedit.extension.platform.AbstractPlayerActor.lambda$runAction$1(AbstractPlayerActor.java:672) at FastAsyncWorldEdit-Bukki


`Regeneration currently not support on Paper due to the new generation system`

**Comment by nuttapillar** [comment]
Yeah, so when will it be supported again?

**Comment by dordsor21** [comment]
When we have the time to do it, and want to do it
