### ISSUE TITLE
Unsupported class file major version 65

### ISSUE THREAD

**Issue by Yurium7** [IntellectualSites/FastAsyncWorldEdit#2835]
### Server Implementation

Paper

### Server Version

1.19.4

### Describe the bug

The junk information appearing in the console during the server startup process did not affect the normal loading of the plugin

### To Reproduce

Download plugins

Put it into the plugin folder

Restart the server

### Expected behaviour

Fix this issue

### Error log (if applicable)

[19:09:34 ERROR]: Fatal error trying to convert FastAsyncWorldEdit v2.11.1-SNAPSHOT-849;d4dd363:org/enginehub/linbus/stream/token/LinToken.class java.lang.IllegalArgumentException: Unsupported class file major version 65         at org.objectweb.asm.ClassReader.<init>(ClassReader.java:199) ~[asm-9.4.jar:9.4]         at org.objectweb.asm.ClassReader.<init>(ClassReader.java:180) ~[asm-9.4.jar:9.4]         at org.objectweb.asm.ClassReader.<init>(ClassReader.java:166) ~[asm-9.4.jar:9.4]         at org.bukkit.craftbukkit.v1_19_R3.util.Commodore.convert(Commodore.java:171) ~[purpur-1.19.4.jar:git-Purpur-1985]         at org.bukkit.craftbukkit.v1_19_R3.util.CraftMagicNumbers.processClass(CraftMagicNumbers.java:405) ~[purpur-1.19.4.jar:git-Purpur-1985]         at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:209) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]         at java.lang.ClassLoader.loadClass(ClassLoader.java:593) ~[?:?]         at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:157) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]         at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:152) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]         at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]         at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:?]         at java.lang.Class.privateGetDeclaredConstructors(Class.java:3549) ~[?:?]         at java.lang.Class.getConstructor0(Class.java:3754) ~[?:?]         at java.lang.Class.getDeclaredConstructor(Class.java:2930) ~[?:?]         at com.google.gson.internal.ConstructorConstructor.newDefaultConstructor(ConstructorConstructor.java:212) ~[gson-2.10.jar:?]         at com.google.gson.internal.ConstructorConstructor.get(ConstructorConstructor.java:120) ~[gson-2.10.jar:?]         at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:129) ~[gson-2.10.jar:?]         at com.google.gson.Gson.getAdapter(Gson.java:546) ~[gson-2.10.jar:?]         at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:160) ~[gson-2.10.jar:?]         at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:295) ~[gson-2.10.jar:?]         at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:130) ~[gson-2.10.jar:?]         at com.google.gson.Gson.getAdapter(Gson.java:546) ~[gson-2.10.jar:?]         at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:160) ~[gson-2.10.jar:?]         at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:295) ~[gson-2.10.jar:?]         at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:130) ~[gson-2.10.jar:?]         at com.google.gson.Gson.getAdapter(Gson.java:546) ~[gson-2.10.jar:?]         at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:160) ~[gson-2.10.jar:?]         at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:295) ~[gson-2.10.jar:?]         at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:130) ~[gson-2.10.jar:?]         at com.google.gson.Gson.getAdapter(Gson.java:546) ~[gson-2.10.jar:?]         at com.google.gson.internal.bind.CollectionTypeAdapterFactory.create(CollectionTypeAdapterFactory.java:53) ~[gson-2.10.jar:?]         at com.google.gson.Gson.getAdapter(Gson.java:546) ~[gson-2.10.jar:?]         at com.google.gson.Gson.fromJson(Gson.java:1213) ~[gson-2.10.jar:?]         at com.google.gson.Gson.fromJson(Gson.java:1124) ~[gson-2.10.jar:?]         at com.google.gson.Gson.fromJson(Gson.java:1034) ~[gson-2.10.jar:?]         at com.google.gson.Gson.fromJson(Gson.java:1001) ~[gson-2.10.jar:?]         at com.sk89q.worldedit.world.registry.BundledBlockData.loadFromResource(BundledBlockData.java:98) ~[FastAsyncWorldEdit-Bukkit-2.11.1-SNAPSHOT-849.jar:?]         at com.sk89q.worldedit.world.registry.BundledBlockData.<init>(BundledBlockData.java:68) ~[FastAsyncWorldEdit-Bukkit-2.11.1-SNAPSHOT-849.jar:?]         at com.sk89q.worldedit.world.registry.BundledBlockData.getInstance(BundledBlockData.java:144) ~[FastAsyncWorldEdit-Bukkit-2.11.1-SNAPSHOT-849.jar:?]         at com.sk89q.worldedit.WorldEdit.loadMappings(WorldEdit.java:434) ~[FastAsyncWorldEdit-Bukkit-2.11.1-SNAPSHOT-849.jar:?]         at com.sk89q.worldedit.bukkit.WorldEditPlugin.setupPreWorldData(WorldEditPlugin.java:246) ~[FastAsyncWorldEdit-Bukkit-2.11.1-SNAPSHOT-849.jar:?]         at com.sk89q.worldedit.bukkit.WorldEditPlugin.onEnable(WorldEditPlugin.java:216) ~[FastAsyncWorldEdit-Bukkit-2.11.1-SNAPSHOT-849.jar:?]         at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]         at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[purpur-1.19.4.jar:git-Purpur-1985]         at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.19.4.jar:git-Purpur-1985]         at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]         at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:577) ~[purpur-1.19.4.jar:git-Purpur-1985]         at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:488) ~[purpur-1.19.4.jar:git-Purpur-1985]         at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:311) ~[purpur-1.19.4.jar:git-Purpur-1985]         at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1120) ~[purpur-1.19.4.jar:git-Purpur-1985]         at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325) ~[purpur-1.19.4.jar:git-Purpur-1985]         at java.lang.Thread.run(Thread.java:1583) ~[?:?]

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/56dc521e7bf24c97910036c3bd9c663b

### Fawe Version

FastAsyncWorldEdit-Bukkit-2.11.1-SNAPSHOT-849

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by MarkGG8181** [comment]
Same situtation over here. Running a small server: https://pastebin.com/X7k7xtNH 
Java:
openjdk 21.0.10 2026-01-20 LTS
OpenJDK Runtime Environment Zulu21.48+15-CA (build 21.0.10+7-LTS)
OpenJDK 64-Bit Server VM Zulu21.48+15-CA (build 21.0.10+7-LTS, mixed mode, sharing)

Os: Debian GNU/Linux 13 (trixie) aarch64
Kernel: Linux 6.12.62+rpt-rpi-v8

Running Paper 1.19.4 [#550](https://fill-ui.papermc.io/projects/paper/version/1.19.4?build=550)
