### ISSUE TITLE
Persistent Brushes Failed

### ISSUE THREAD

**Issue by SnowzNZ** [IntellectualSites/FastAsyncWorldEdit#2848]
### Server Implementation

Paper

### Server Version

1.21

### Describe the bug

Didn't run any FAWE commands or anything and I randomly got this error in the console
```
[15:46:02 ERROR]: [com.fastasyncworldedit.bukkit.FaweBukkit] Persistent Brushes Failed
java.lang.NullPointerException: null
        at com.google.gson.internal.$Gson$Preconditions.checkNotNull($Gson$Preconditions.java:47) ~[gson-2.10.1.jar:?]
        at FastAsyncWorldEdit-Bukkit-2.9.3-SNAPSHOT-748.jar/com.fastasyncworldedit.bukkit.util.ItemUtil.<init>(ItemUtil.java:32) ~[FastAsyncWorldEdit-Bukkit-2.9.3-SNAPSHOT-748.jar:?]
        at FastAsyncWorldEdit-Bukkit-2.9.3-SNAPSHOT-748.jar/com.fastasyncworldedit.bukkit.FaweBukkit.getItemUtil(FaweBukkit.java:146) ~[FastAsyncWorldEdit-Bukkit-2.9.3-SNAPSHOT-748.jar:?]
        at FastAsyncWorldEdit-Bukkit-2.9.3-SNAPSHOT-748.jar/com.fastasyncworldedit.bukkit.util.BukkitItemStack.getNativeItem(BukkitItemStack.java:37) ~[FastAsyncWorldEdit-Bukkit-2.9.3-SNAPSHOT-748.jar:?]
        at FastAsyncWorldEdit-Bukkit-2.9.3-SNAPSHOT-748.jar/com.sk89q.worldedit.LocalSession.getTool(LocalSession.java:1243) ~[FastAsyncWorldEdit-Bukkit-2.9.3-SNAPSHOT-748.jar:?]
        at FastAsyncWorldEdit-Bukkit-2.9.3-SNAPSHOT-748.jar/com.sk89q.worldedit.LocalSession.getTool(LocalSession.java:1236) ~[FastAsyncWorldEdit-Bukkit-2.9.3-SNAPSHOT-748.jar:?]
        at FastAsyncWorldEdit-Bukkit-2.9.3-SNAPSHOT-748.jar/com.sk89q.worldedit.extension.platform.PlatformManager.handlePlayerInput(PlatformManager.java:481) ~[FastAsyncWorldEdit-Bukkit-2.9.3-SNAPSHOT-748.jar:?]
        at FastAsyncWorldEdit-Bukkit-2.9.3-SNAPSHOT-748.jar/com.sk89q.worldedit.util.eventbus.MethodHandleEventHandler.dispatch(MethodHandleEventHandler.java:51) ~[FastAsyncWorldEdit-Bukkit-2.9.3-SNAPSHOT-748.jar:?]
        at FastAsyncWorldEdit-Bukkit-2.9.3-SNAPSHOT-748.jar/com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[FastAsyncWorldEdit-Bukkit-2.9.3-SNAPSHOT-748.jar:?]
        at FastAsyncWorldEdit-Bukkit-2.9.3-SNAPSHOT-748.jar/com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:193) ~[FastAsyncWorldEdit-Bukkit-2.9.3-SNAPSHOT-748.jar:?]
        at FastAsyncWorldEdit-Bukkit-2.9.3-SNAPSHOT-748.jar/com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:181) ~[FastAsyncWorldEdit-Bukkit-2.9.3-SNAPSHOT-748.jar:?]
        at FastAsyncWorldEdit-Bukkit-2.9.3-SNAPSHOT-748.jar/com.sk89q.worldedit.WorldEdit.handleArmSwing(WorldEdit.java:680) ~[FastAsyncWorldEdit-Bukkit-2.9.3-SNAPSHOT-748.jar:?]
        at FastAsyncWorldEdit-Bukkit-2.9.3-SNAPSHOT-748.jar/com.sk89q.worldedit.bukkit.WorldEditListener.onPlayerInteract(WorldEditListener.java:165) ~[FastAsyncWorldEdit-Bukkit-2.9.3-SNAPSHOT-748.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor24.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:1.21-108-73a863b]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.jar:1.21-108-73a863b]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.jar:1.21-108-73a863b]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:598) ~[paper-1.21.jar:1.21-108-73a863b]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:554) ~[paper-1.21.jar:1.21-108-73a863b]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:549) ~[paper-1.21.jar:1.21-108-73a863b]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:545) ~[paper-1.21.jar:1.21-108-73a863b]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleAnimate(ServerGamePacketListenerImpl.java:2513) ~[paper-1.21.jar:1.21-108-73a863b]
        at net.minecraft.network.protocol.game.ServerboundSwingPacket.handle(ServerboundSwingPacket.java:34) ~[paper-1.21.jar:1.21-108-73a863b]
        at net.minecraft.network.protocol.game.ServerboundSwingPacket.handle(ServerboundSwingPacket.java:16) ~[paper-1.21.jar:1.21-108-73a863b]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[paper-1.21.jar:1.21-108-73a863b]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.jar:1.21-108-73a863b]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.jar:1.21-108-73a863b]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.jar:1.21-108-73a863b]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1536) ~[paper-1.21.jar:1.21-108-73a863b]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.jar:1.21-108-73a863b]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.jar:1.21-108-73a863b]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1513) ~[paper-1.21.jar:1.21-108-73a863b]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1506) ~[paper-1.21.jar:1.21-108-73a863b]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.21.jar:1.21-108-73a863b]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1465) ~[paper-1.21.jar:1.21-108-73a863b]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1472) ~[paper-1.21.jar:1.21-108-73a863b]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1317) ~[paper-1.21.jar:1.21-108-73a863b]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-108-73a863b]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### To Reproduce

1. Start up server
2. Check console

### Expected behaviour

I expect no console error

### Error log (if applicable)

https://mclo.gs/s5qilFi

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/5decc45e209d44db8e6c25630d4888b2

### Fawe Version

FastAsyncWorldEdit version 2.9.3-SNAPSHOT-748;1a31f39

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by SnowzNZ** [comment]
Whoops, I thought I was using the latest dev build.
