### ISSUE TITLE
 Cannot invoke "com.sk89q.worldedit.extent.clipboard.Clipboard.getOrigin()" because "clipboard" is null

### ISSUE THREAD

**Issue by TheYonyo** [IntellectualSites/FastAsyncWorldEdit#2851]
### Error load schematics

Paper

### Server Version

1.20.4

### Describe the bug

When loading then pasting a schematic I received the error in the codeblock below, It doesn't only happen to me on that server, it happens to me on all servers. Before I could paste schematics without that error and now I can't. I thought it could be caused by the coreprotec plugin, but I didn't see anything related to that plugin.

### To Reproduce

Load a schematic from //schematic list
Paste schematic with //paste
Receive error above

### Expected behaviour

The schematic should paste without errors

### Screenshots / Videos

![image](https://github.com/user-attachments/assets/897072cc-689a-49e5-a4ba-98bf96a2fe3f)

### Error log (if applicable)

[23:37:27 INFO]: TheYonyo issued server command: //paste
[23:37:27 ERROR]: An unexpected error while handling a FastAsyncWorldEdit command
java.lang.NullPointerException: Cannot invoke "com.sk89q.worldedit.extent.clipboard.Clipboard.getOrigin()" because "clipboard" is null
        at com.sk89q.worldedit.command.ClipboardCommands.place(ClipboardCommands.java:461) ~[FastAsyncWorldEdit-Bukkit-2.11.1-SNAPSHOT-852.jar:?]
        at com.sk89q.worldedit.command.ClipboardCommands.paste(ClipboardCommands.java:533) ~[FastAsyncWorldEdit-Bukkit-2.11.1-SNAPSHOT-852.jar:?]
        at com.sk89q.worldedit.command.ClipboardCommandsRegistration.cmd$_paste(ClipboardCommandsRegistration.java:352) ~[FastAsyncWorldEdit-Bukkit-2.11.1-SNAPSHOT-852.jar:?]
        at org.enginehub.piston.CommandManager.execute(CommandManager.java:157) ~[FastAsyncWorldEdit-Bukkit-2.11.1-SNAPSHOT-852.jar:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommandOnCurrentThread$16(PlatformCommandManager.java:727) ~[FastAsyncWorldEdit-Bukkit-2.11.1-SNAPSHOT-852.jar:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandTask(PlatformCommandManager.java:748) ~[FastAsyncWorldEdit-Bukkit-2.11.1-SNAPSHOT-852.jar:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandOnCurrentThread(PlatformCommandManager.java:729) ~[FastAsyncWorldEdit-Bukkit-2.11.1-SNAPSHOT-852.jar:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommand$14(PlatformCommandManager.java:700) ~[FastAsyncWorldEdit-Bukkit-2.11.1-SNAPSHOT-852.jar:?]
        at com.sk89q.worldedit.extension.platform.AbstractPlayerActor.lambda$runAction$1(AbstractPlayerActor.java:672) ~[FastAsyncWorldEdit-Bukkit-2.11.1-SNAPSHOT-852.jar:?]
        at com.fastasyncworldedit.core.util.task.AsyncNotifyKeyedQueue.lambda$run$0(AsyncNotifyKeyedQueue.java:48) ~[FastAsyncWorldEdit-Bukkit-2.11.1-SNAPSHOT-852.jar:?]
        at com.fastasyncworldedit.core.util.task.AsyncNotifyKeyedQueue.lambda$call$1(AsyncNotifyKeyedQueue.java:58) ~[FastAsyncWorldEdit-Bukkit-2.11.1-SNAPSHOT-852.jar:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
        at com.fastasyncworldedit.core.util.task.KeyQueuedExecutorService$KeyRunner.lambda$run$0(KeyQueuedExecutorService.java:150) ~[FastAsyncWorldEdit-Bukkit-2.11.1-SNAPSHOT-852.jar:?]
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?]

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/416cc8f772f9484997e88beba79fbfa0

### Fawe Version

FastAsyncWorldEdit-2.11.1-SNAPSHOT-852;561ef4a

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by dordsor21** [comment]
Please update FAWE

**Comment by TheYonyo** [comment]
The .jar file is now updated to the version FastAsyncWorldEdit-Bukkit-2.11.1-SNAPSHOT-859.jar

**Comment by TheAnythingBin** [comment]
this persists on build 915

**Comment by PierreSchwang** [comment]
> this persists on build 915

Join the discord / create a new issue for that with details.
