### ISSUE TITLE
Can't use //set.

### ISSUE THREAD

**Issue by MagoLione** [IntellectualSites/FastAsyncWorldEdit#2872]
### Server Implementation

Paper

### Server Version

1.21

### Describe the bug

I tried to use //set stone command but it returns me that error.

`[20:23:26 ERROR]: An unexpected error while handling a WorldEdit command
java.lang.NoSuchMethodError: 'boolean com.sk89q.worldedit.extent.Extent.setBlock(int, int, int, com.sk89q.worldedit.world.block.BlockStateHolder)'
	at CoreProtect-22.4.jar/net.coreprotect.worldedit.CoreProtectLogger.setBlock(CoreProtectLogger.java:60) ~[CoreProtect-22.4.jar:?]
	at worldedit-bukkit-7.3.4.jar/com.sk89q.worldedit.extent.AbstractDelegateExtent.setBlock(AbstractDelegateExtent.java:78) ~[worldedit-bukkit-7.3.4.jar:?]
	at worldedit-bukkit-7.3.4.jar/com.sk89q.worldedit.extent.AbstractBufferingExtent.setDelegateBlock(AbstractBufferingExtent.java:52) ~[worldedit-bukkit-7.3.4.jar:?]
	at worldedit-bukkit-7.3.4.jar/com.sk89q.worldedit.extent.reorder.MultiStageReorder.setBlock(MultiStageReorder.java:231) ~[worldedit-bukkit-7.3.4.jar:?]
	at worldedit-bukkit-7.3.4.jar/com.sk89q.worldedit.extent.AbstractDelegateExtent.setBlock(AbstractDelegateExtent.java:78) ~[worldedit-bukkit-7.3.4.jar:?]
	at worldedit-bukkit-7.3.4.jar/com.sk89q.worldedit.extent.AbstractBufferingExtent.setDelegateBlock(AbstractBufferingExtent.java:52) ~[worldedit-bukkit-7.3.4.jar:?]
	at worldedit-bukkit-7.3.4.jar/com.sk89q.worldedit.extent.reorder.ChunkBatchingExtent.setBlock(ChunkBatchingExtent.java:72) ~[worldedit-bukkit-7.3.4.jar:?]
	at worldedit-bukkit-7.3.4.jar/com.sk89q.worldedit.extent.AbstractDelegateExtent.setBlock(AbstractDelegateExtent.java:78) ~[worldedit-bukkit-7.3.4.jar:?]
	at worldedit-bukkit-7.3.4.jar/com.sk89q.worldedit.extent.world.WatchdogTickingExtent.setBlock(WatchdogTickingExtent.java:83) ~[worldedit-bukkit-7.3.4.jar:?]
	at worldedit-bukkit-7.3.4.jar/com.sk89q.worldedit.extent.AbstractDelegateExtent.setBlock(AbstractDelegateExtent.java:78) ~[worldedit-bukkit-7.3.4.jar:?]
	at worldedit-bukkit-7.3.4.jar/com.sk89q.worldedit.extent.ChangeSetExtent.setBlock(ChangeSetExtent.java:100) ~[worldedit-bukkit-7.3.4.jar:?]
	at worldedit-bukkit-7.3.4.jar/com.sk89q.worldedit.extent.AbstractDelegateExtent.setBlock(AbstractDelegateExtent.java:78) ~[worldedit-bukkit-7.3.4.jar:?]
	at worldedit-bukkit-7.3.4.jar/com.sk89q.worldedit.extent.MaskingExtent.setBlock(MaskingExtent.java:69) ~[worldedit-bukkit-7.3.4.jar:?]
	at worldedit-bukkit-7.3.4.jar/com.sk89q.worldedit.extent.AbstractDelegateExtent.setBlock(AbstractDelegateExtent.java:78) ~[worldedit-bukkit-7.3.4.jar:?]
	at worldedit-bukkit-7.3.4.jar/com.sk89q.worldedit.extent.validation.BlockChangeLimiter.setBlock(BlockChangeLimiter.java:88) ~[worldedit-bukkit-7.3.4.jar:?]
	at worldedit-bukkit-7.3.4.jar/com.sk89q.worldedit.extent.AbstractDelegateExtent.setBlock(AbstractDelegateExtent.java:78) ~[worldedit-bukkit-7.3.4.jar:?]
	at worldedit-bukkit-7.3.4.jar/com.sk89q.worldedit.extent.validation.DataValidatorExtent.setBlock(DataValidatorExtent.java:77) ~[worldedit-bukkit-7.3.4.jar:?]
	at worldedit-bukkit-7.3.4.jar/com.sk89q.worldedit.EditSession.setBlock(EditSession.java:757) ~[worldedit-bukkit-7.3.4.jar:?]
	at worldedit-bukkit-7.3.4.jar/com.sk89q.worldedit.EditSession.setBlock(EditSession.java:797) ~[worldedit-bukkit-7.3.4.jar:?]
	at worldedit-bukkit-7.3.4.jar/com.sk89q.worldedit.function.block.BlockReplace.apply(BlockReplace.java:53) ~[worldedit-bukkit-7.3.4.jar:?]
	at worldedit-bukkit-7.3.4.jar/com.sk89q.worldedit.function.visitor.RegionVisitor.resume(RegionVisitor.java:60) ~[worldedit-bukkit-7.3.4.jar:?]
	at worldedit-bukkit-7.3.4.jar/com.sk89q.worldedit.function.operation.Operations.completeBlindly(Operations.java:74) ~[worldedit-bukkit-7.3.4.jar:?]
	at worldedit-bukkit-7.3.4.jar/com.sk89q.worldedit.command.RegionCommands.set(RegionCommands.java:108) ~[worldedit-bukkit-7.3.4.jar:?]
	at worldedit-bukkit-7.3.4.jar/com.sk89q.worldedit.command.RegionCommandsRegistration.cmd$_set(RegionCommandsRegistration.java:437) ~[worldedit-bukkit-7.3.4.jar:?]
	at worldedit-bukkit-7.3.4.jar/org.enginehub.piston.CommandManager.execute(CommandManager.java:157) ~[worldedit-bukkit-7.3.4.jar:?]
	at worldedit-bukkit-7.3.4.jar/com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommand(PlatformCommandManager.java:506) ~[worldedit-bukkit-7.3.4.jar:?]
	at worldedit-bukkit-7.3.4.jar/com.sk89q.worldedit.util.eventbus.MethodHandleEventHandler.dispatch(MethodHandleEventHandler.java:51) ~[worldedit-bukkit-7.3.4.jar:?]
	at worldedit-bukkit-7.3.4.jar/com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[worldedit-bukkit-7.3.4.jar:?]
	at worldedit-bukkit-7.3.4.jar/com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:193) ~[worldedit-bukkit-7.3.4.jar:?]
	at worldedit-bukkit-7.3.4.jar/com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:181) ~[worldedit-bukkit-7.3.4.jar:?]
	at worldedit-bukkit-7.3.4.jar/com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:391) ~[worldedit-bukkit-7.3.4.jar:?]
	at worldedit-bukkit-7.3.4.jar/com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:55) ~[worldedit-bukkit-7.3.4.jar:?]
	at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:91) ~[paper-1.21.jar:1.21-116-3234b20]
	at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31) ~[paper-1.21.jar:1.21-116-3234b20]
	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[paper-1.21.jar:1.21-116-3234b20]
	at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[paper-1.21.jar:1.21-116-3234b20]
	at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5) ~[paper-1.21.jar:1.21-116-3234b20]
	at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[paper-1.21.jar:1.21-116-3234b20]
	at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:443) ~[paper-1.21.jar:1.21-116-3234b20]
	at net.minecraft.commands.Commands.performCommand(Commands.java:350) ~[paper-1.21.jar:1.21-116-3234b20]
	at net.minecraft.commands.Commands.performCommand(Commands.java:337) ~[paper-1.21.jar:1.21-116-3234b20]
	at net.minecraft.commands.Commands.performCommand(Commands.java:332) ~[paper-1.21.jar:1.21-116-3234b20]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2147) ~[paper-1.21.jar:1.21-116-3234b20]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$11(ServerGamePacketListenerImpl.java:2121) ~[paper-1.21.jar:1.21-116-3234b20]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.jar:1.21-116-3234b20]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.jar:1.21-116-3234b20]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.jar:1.21-116-3234b20]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1536) ~[paper-1.21.jar:1.21-116-3234b20]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.jar:1.21-116-3234b20]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.jar:1.21-116-3234b20]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1513) ~[paper-1.21.jar:1.21-116-3234b20]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1506) ~[paper-1.21.jar:1.21-116-3234b20]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.21.jar:1.21-116-3234b20]
	at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1465) ~[paper-1.21.jar:1.21-116-3234b20]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1472) ~[paper-1.21.jar:1.21-116-3234b20]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1317) ~[paper-1.21.jar:1.21-116-3234b20]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-116-3234b20]
	at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
`

When I uninstall FastAsyncWorldEdit it doesn't  appear.
I'm using core protect.

### To Reproduce

Take the tool with //wand.
Select a region full of sand with the tool.
Do the //set stone command.
See the error.

### Expected behaviour

An error will appear and the //set command fails.

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/051854e9421448dc84ee2ad7a230cbe2

### Fawe Version

FastAsyncWorldEdit version 2.11.1-SNAPSHOT-871;fcbd346

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by PierreSchwang** [comment]
1. You are running WorldEdit alongside FAWE. Install either, but not both simultaneously. 
2. That CoreProtect version does not seem to be supported for 1.21 (see https://github.com/PlayPro/CoreProtect/issues/600)
