### ISSUE TITLE
/fawe debugpaste errors inbetween waiting time

### ISSUE THREAD

**Issue by StealWonders** [IntellectualSites/FastAsyncWorldEdit#289]
# Bug report for FastAsyncWorldEdit 1.15-4

**FastAsyncWorldEdit Configuration Files:** 
https://athion.net/ISPaster/paste/view/90022d51a35b4efdbe65eb5b61694643

**FastAsyncWorldEdit Version Number:** FAWE-4 (1.13.2 - 1.15.1)

**Paper Version Number:** git-Paper-236 (MC: 1.14.4)

**Description of the problem:**
When using: `/fawe debugpaste` in the console for a second time there is an improper handled exception stating that I have to wait 3 minutes before creating a new paste.

The console displays the following when executing the command for a 2. time:
`[18:25:03 INFO]: &cPlease report this error: [See console]
[18:25:03 INFO]: java.io.IOException: Failed to upload files: you need to wait 3 minutes before creating a new paste
[18:25:03 ERROR]: An unexpected error while handling a WorldEdit command
java.io.IOException: Failed to upload files: you need to wait 3 minutes before creating a new paste
at com.boydti.fawe.util.IncendoPaster.debugPaste(IncendoPaster.java:260) ~[?:?]
at com.sk89q.worldedit.command.WorldEditCommands.report(WorldEditCommands.java:142) ~[?:?]
at com.sk89q.worldedit.command.WorldEditCommandsRegistration.cmd$report(WorldEditCommandsRegistration.java:210) ~[?:?]
at org.enginehub.piston.CommandManager.execute(CommandManager.java:158) ~[?:?]
at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommandOnCurrentThread$17(PlatformCommandManager.java:673) ~[?:?]
at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandTask(PlatformCommandManager.java:689) ~[?:?]
at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandOnCurrentThread(PlatformCommandManager.java:675) ~[?:?]
at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommand$15(PlatformCommandManager.java:645) ~[?:?]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-237]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.14.4.jar:git-Paper-237]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.14.4.jar:git-Paper-237]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]`

**How to replicate**:
Use the described command for a second time within a couple of seconds.

**Comment by StealWonders** [comment]
Wanted to fix this today but it seems like it has already been fixed. Closing.
![Screenshot from 2020-03-30 16-43-55](https://user-images.githubusercontent.com/6114858/77926067-f394b180-72a5-11ea-801c-a79c7e7acc8a.png)
