### ISSUE TITLE
FastAsyncWorldEdit not matching the same version as CraftBukkit

### ISSUE THREAD

**Issue by TheRealKushi** [IntellectualSites/FastAsyncWorldEdit#2893]
### Server Implementation

Spigot

### Server Version

1.21

### Describe the bug

Occurs on a CraftBukkit server, whenever I try to execute any action with the wand or through commands. Using Magmanode server hosting.

### To Reproduce

1-Download the latest version and upload it to magmanode.
2-Go ingame and use //wand or grab a wooden axe
3-Try to use any command

### Expected behaviour

I expected to use the wand or the commands

### Screenshots / Videos

![bug-report](https://github.com/user-attachments/assets/9ce63069-3fc0-4d5f-9b30-357f4d999f02)

### Error log (if applicable)

[22:15:32] [AsyncNotifyKeyedQueue - 0/ERROR]: An unexpected error while handling a FastAsyncWorldEdit command java.lang.RuntimeException: java.lang.reflect.InvocationTargetException         at com.fastasyncworldedit.core.extension.platform.binding.Bindings.invoke(Bindings.java:140) ~[?:?]         at com.fastasyncworldedit.core.extension.platform.binding.Bindings.lambda$register$1(Bindings.java:95) ~[?:?]         at org.enginehub.piston.inject.MapBackedValueStore.lambda$injectedValue$0(MapBackedValueStore.java:56) ~[?:?]         at java.base/java.util.Optional.flatMap(Optional.java:289) ~[?:?]         at org.enginehub.piston.inject.MapBackedValueStore.injectedValue(MapBackedValueStore.java:56) ~[?:?]         at org.enginehub.piston.inject.MergedValueAccess.lambda$injectedValue$0(MergedValueAccess.java:54) ~[?:?]         at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]         at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:1034) ~[?:?]         at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?]         at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?]         at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?]         at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]         at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150) ~[?:?]         at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]         at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647) ~[?:?]         at org.enginehub.piston.inject.MergedValueAccess.injectedValue(MergedValueAccess.java:57) ~[?:?]         at org.enginehub.piston.inject.MemoizingValueAccess.injectedValue(MemoizingValueAccess.java:84) ~[?:?]         at org.enginehub.piston.impl.CommandParametersImpl.injectedValue(CommandParametersImpl.java:109) ~[?:?]         at org.enginehub.piston.inject.InjectedValueAccess.injectedValue(InjectedValueAccess.java:44) ~[?:?]         at com.sk89q.worldedit.command.util.annotation.PreloadHandler.beforeCall(PreloadHandler.java:25) ~[?:?]         at org.enginehub.piston.internal.RegistrationUtil.listenersBeforeCall(RegistrationUtil.java:53) ~[?:?]         at com.sk89q.worldedit.command.RegionCommandsRegistration.cmd$_set(RegionCommandsRegistration.java:604) ~[?:?]         at org.enginehub.piston.CommandManager.execute(CommandManager.java:157) ~[?:?]         at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommandOnCurrentThread$16(PlatformCommandManager.java:727) ~[?:?]         at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandTask(PlatformCommandManager.java:748) ~[?:?]         at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandOnCurrentThread(PlatformCommandManager.java:729) ~[?:?]         at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommand$14(PlatformCommandManager.java:700) ~[?:?]         at com.sk89q.worldedit.extension.platform.AbstractPlayerActor.lambda$runAction$1(AbstractPlayerActor.java:672) ~[?:?]         at com.fastasyncworldedit.core.util.task.AsyncNotifyKeyedQueue.lambda$run$0(AsyncNotifyKeyedQueue.java:48) ~[?:?]         at com.fastasyncworldedit.core.util.task.AsyncNotifyKeyedQueue.lambda$call$1(AsyncNotifyKeyedQueue.java:58) ~[?:?]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]         at com.fastasyncworldedit.core.util.task.KeyQueuedExecutorService$KeyRunner.lambda$run$0(KeyQueuedExecutorService.java:150) ~[?:?]         at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423) [?:?]         at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) [?:?]         at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) [?:?]         at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) [?:?]         at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) [?:?]         at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) [?:?] Caused by: java.lang.reflect.InvocationTargetException         at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:115) ~[?:?]         at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]         at com.fastasyncworldedit.core.extension.platform.binding.Bindings.invoke(Bindings.java:137) ~[?:?]         ... 37 more Caused by: java.lang.NullPointerException: Cannot invoke "com.sk89q.worldedit.bukkit.adapter.BukkitImplAdapter.getRelighterFactory()" because the return value of "com.sk89q.worldedit.bukkit.WorldEditPlugin.getBukkitImplAdapter()" is null         at com.sk89q.worldedit.bukkit.BukkitServerInterface.getRelighterFactory(BukkitServerInterface.java:288) ~[?:?]         at com.sk89q.worldedit.EditSessionBuilder.compile(EditSessionBuilder.java:552) ~[?:?]         at com.sk89q.worldedit.EditSession.<init>(EditSession.java:262) ~[?:?]         at com.sk89q.worldedit.EditSessionBuilder.build(EditSessionBuilder.java:234) ~[?:?]         at com.sk89q.worldedit.LocalSession.createEditSession(LocalSession.java:1753) ~[?:?]         at com.fastasyncworldedit.core.extension.platform.binding.ProvideBindings.editSession(ProvideBindings.java:57) ~[?:?]         at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]         at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]         at com.fastasyncworldedit.core.extension.platform.binding.Bindings.invoke(Bindings.java:137) ~[?:?]         ... 37 more

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/82344170f9a9450798ff01ff44c3d3e7

### Fawe Version

FastAsyncWorldEdit-Bukkit-2.11.2-SNAPSHOT-886.jar

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by PierreSchwang** [comment]
1. That's 1.20.6 - not 1.21
2. You are running CraftBukkit? Use Spigot or Paper

**Comment by TheRealKushi** [comment]
I downloaded the Bukkit version, from here: https://dev.bukkit.org/projects/fawe/files, and it supports 1.20.6. I just put spigot there because there was not a "CraftBukkit" option. Do you know what may be causing the issue? @PierreSchwang

**Comment by PierreSchwang** [comment]
Yes, the issue is you using CraftBukkit.

**Comment by TheRealKushi** [comment]
Why? Doesn't it support bukkit?

**Comment by PierreSchwang** [comment]
As there is no reason to. The Plugin support is limited and CB is not used anymore.

**Comment by TheRealKushi** [comment]
Well, thanks
