### ISSUE TITLE
crashes if no internet

### ISSUE THREAD

**Issue by SergioK29** [IntellectualSites/FastAsyncWorldEdit#2950]
### Server Implementation

Paper

### Server Version

1.21

### Describe the bug

I have reported this bug before, months ago, still not fixed  https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/2756

[23:26:07 ERROR]: Error occurred while enabling FastAsyncWorldEdit v2.11.3-SNAPSHOT-937;91bdd15 (Is it up to date?)
java.net.SocketTimeoutException: Connection timed out
        at java.net.http/jdk.internal.net.http.HttpRequestImpl.<init>(HttpRequestImpl.java:137) ~[java.net.http:?]
        at java.net.http/jdk.internal.net.http.HttpClientImpl.sendAsync(HttpClientImpl.java:1018) ~[java.net.http:?]
        at java.net.http/jdk.internal.net.http.HttpClientImpl.sendAsync(HttpClientImpl.java:990) ~[java.net.http:?]
        at java.net.http/jdk.internal.net.http.HttpClientImpl.sendAsync(HttpClientImpl.java:982) ~[java.net.http:?]
        at java.net.http/jdk.internal.net.http.HttpClientFacade.sendAsync(HttpClientFacade.java:143) ~[java.net.http:?]
        at FastAsyncWorldEdit-Bukkit-2.11.3-SNAPSHOT-937.jar/com.fastasyncworldedit.core.util.UpdateNotification.doUpdateCheck(UpdateNotification.java:43) ~[FastAsyncWorldEdit-Bukkit-2.11.3-SNAPSHOT-937.jar:?]
        at FastAsyncWorldEdit-Bukkit-2.11.3-SNAPSHOT-937.jar/com.sk89q.worldedit.bukkit.WorldEditPlugin.onEnable(WorldEditPlugin.java:241) ~[FastAsyncWorldEdit-Bukkit-2.11.3-SNAPSHOT-937.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.1.jar:1.21.1-DEV-7cd4f2c]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.1.jar:1.21.1-DEV-7cd4f2c]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.21.1.jar:1.21.1-DEV-7cd4f2c]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589) ~[paper-1.21.1.jar:1.21.1-DEV-7cd4f2c]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:293) ~[paper-1.21.1.jar:1.21.1-DEV-7cd4f2c]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214) ~[paper-1.21.1.jar:1.21.1-DEV-7cd4f2c]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-DEV-7cd4f2c]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]

### To Reproduce

have no internet/ firewall, FAWE refuses to boot because there is no try catch in its update checker

### Expected behaviour

Shouldn't crash when no internet

### Fawe Debugpaste

no

### Fawe Version

FastAsyncWorldEdit-Bukkit-2.11.3-SNAPSHOT-937.jar

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by dordsor21** [comment]
I'm unable to replicate this. The exception is correctly caught by the CompletableFuture and the server loads as normal

**Comment by dordsor21** [comment]
No-one else has ever reported this and none of the dev team are able to replicate, and no further information is provided
