### ISSUE TITLE
AsyncWorld | IllegalStateException: WorldInitEvent may only be triggered synchronously.

### ISSUE THREAD

**Issue by xXSchrandXx** [IntellectualSites/FastAsyncWorldEdit#299]
# Bug report for FastAsyncWorldEdit 1.14.4
**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 

https://athion.net/ISPaster/paste/view/77bc53510dce43f68dbd2d6e658042f4

**[REQUIRED] FastAsyncWorldEdit Version Number:** 

Bukkit-Official(1.15-13;9efdd88)

**[REQUIRED] Spigot/Paper Version Number:** 

git-Paper-237 (MC: 1.14.4)

**[REQUIRED] Description of the problem:**

```
[21:45:06 WARN]: [WorldEdit] Plugin WorldEdit v1.15-13;9efdd88 generated an exception while executing task 76
java.lang.IllegalStateException: WorldInitEvent may only be triggered synchronously.
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:533) ~[patched_1.14.4.jar:git-Paper-237]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.createWorld(CraftServer.java:1018) ~[patched_1.14.4.jar:git-Paper-237]
        at org.bukkit.Bukkit.createWorld(Bukkit.java:492) ~[patched_1.14.4.jar:git-Paper-237]
        at org.bukkit.WorldCreator.createWorld(WorldCreator.java:284) ~[patched_1.14.4.jar:git-Paper-237]
        at com.boydti.fawe.bukkit.FaweBukkit.createWorldUnloaded(FaweBukkit.java:315) ~[?:?]
        at com.sk89q.worldedit.bukkit.adapter.BukkitImplAdapter.createWorld(BukkitImplAdapter.java:222) ~[?:?]
        at com.sk89q.worldedit.bukkit.adapter.IDelegateBukkitImplAdapter.createWorld(IDelegateBukkitImplAdapter.java:151) ~[?:?]
        at com.boydti.fawe.bukkit.wrapper.AsyncWorld.create(AsyncWorld.java:144) ~[?:?]
        at de.butzlabben.world.wrapper.AsyncCreatorAdapter.lambda$0(AsyncCreatorAdapter.java:22) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-237]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.14.4.jar:git-Paper-237]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.14.4.jar:git-Paper-237]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**How to replicate**:

Create a AsyncWorld. (I used: [WorldSystem](https://www.spigotmc.org/resources/worldsystem-%E2%97%8F-the-one-world-per-player-solution-%E2%97%8F-gui-%E2%97%8F-highly-configurable-%E2%97%8F-1-8-1-14.49756/))
Plugincode for creating the world: https://github.com/Butzlabben/worldsystem/blob/master/src/main/java/de/butzlabben/world/wrapper/AsyncCreatorAdapter.java 

**Plugins being used on the server:**

Plugins: 
 - CleanroomGenerator: 1.1.0
 - LuckPerms: 5.0.43
 - SkinsRestorer: 13.7.5
 - NametagEdit: 4.4.6
 - WorldSystem: 2.4.8.1
 - Vault: 1.7.2-b107
 - ProtocolSupport: 4.29-dev
 - WorldEdit: 1.15-13;9efdd88
 - FastAsyncWorldEdit: 1.14
 - Essentials: 2.17.1.0
 - EssentialsChat: 2.17.1.0
 - ViaVersion: 2.2.2
 - EssentialsSpawn: 2.17.1.0
 - WorldGuard: 7.0.2-SNAPSHOT;1998-f43a4ea
 - ProtocolLib: 4.5.0
 - WorldEditSelectionVisualizer: 2.0.4
 - FastLogin: 1.11-SNAPSHOT-1375cf3
 - AuthMe: 5.6.0-SNAPSHOT-b2358
 - ProtocolSupportStuff: 2.0.0
 - ServerListPlus: 3.4.8

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.14.4](https://ci.athion.net/job/FastAsyncWorldEdit-pipeline/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by xXSchrandXx** [comment]
As far as I have it right, this can only be done by modifying the [WorldEvent.class](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/world/WorldEvent.html), [WorldInitEvent.class](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/world/WorldInitEvent.html) and [WorldLoadEvent.class](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/world/WorldLoadEvent.html).
The [Async function](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/Event.html#Event-boolean-) is missing for these events.

**Comment by aurorasmiles** [comment]
Is this still an issue with the latest version?

**Comment by xXSchrandXx** [comment]
> Is this still an issue with the latest version?

Gonna test this...

**Comment by xXSchrandXx** [comment]
I started and stopped the testserver directly. I didn't join the world with a player.
But I got a error message from FAWE:
``` LOG
[18:11:24] [Craft Scheduler Thread - 0/WARN]: [FastAsyncWorldEdit] Plugin FastAsyncWorldEdit v1.16-366;fc91c3b generated an exception while executing task 41
java.lang.IllegalStateException: Asynchronous ChunkMapDistance::addTicket!
	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[patched_1.16.3.jar:git-Paper-198]
	at net.minecraft.server.v1_16_R2.ChunkMapDistance.addTicket(ChunkMapDistance.java:158) ~[patched_1.16.3.jar:git-Paper-198]
	at net.minecraft.server.v1_16_R2.ChunkMapDistance.addTicket(ChunkMapDistance.java:363) ~[patched_1.16.3.jar:git-Paper-198]
	at net.minecraft.server.v1_16_R2.ChunkProviderServer.addTicket(ChunkProviderServer.java:919) ~[patched_1.16.3.jar:git-Paper-198]
	at net.minecraft.server.v1_16_R2.WorldServer.addTicketsForSpawn(WorldServer.java:1809) ~[patched_1.16.3.jar:git-Paper-198]
	at net.minecraft.server.v1_16_R2.MinecraftServer.loadSpawn(MinecraftServer.java:638) ~[patched_1.16.3.jar:git-Paper-198]
	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.createWorld(CraftServer.java:1164) ~[patched_1.16.3.jar:git-Paper-198]
	at org.bukkit.Bukkit.createWorld(Bukkit.java:581) ~[patched_1.16.3.jar:git-Paper-198]
	at org.bukkit.WorldCreator.createWorld(WorldCreator.java:325) ~[patched_1.16.3.jar:git-Paper-198]
	at com.boydti.fawe.bukkit.FaweBukkit.createWorldUnloaded(FaweBukkit.java:257) ~[?:?]
	at com.sk89q.worldedit.bukkit.adapter.BukkitImplAdapter.createWorld(BukkitImplAdapter.java:221) ~[?:?]
	at com.sk89q.worldedit.bukkit.adapter.IDelegateBukkitImplAdapter.createWorld(IDelegateBukkitImplAdapter.java:143) ~[?:?]
	at com.boydti.fawe.bukkit.wrapper.AsyncWorld.create(AsyncWorld.java:152) ~[?:?]
	at de.xxschrandxx.awm.api.worldcreation.fawe$1.run(fawe.java:54) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.3.jar:git-Paper-198]
	at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.3.jar:git-Paper-198]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.3.jar:git-Paper-198]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

Class wich is loading the world: https://github.com/xXSchrandXx/SpigotPlugins/blob/master/AsyncWorldManager/src/main/java/de/xxschrandxx/awm/api/worldcreation/fawe.java

**Comment by xXSchrandXx** [comment]
And I tried to create a world with FAWE AsyncWorld:
``` LOG
[18:27:26] [Craft Scheduler Thread - 9/WARN]: [FastAsyncWorldEdit] Plugin FastAsyncWorldEdit v1.16-366;fc91c3b generated an exception while executing task 622
net.minecraft.server.v1_16_R2.ReportedException: Exception initializing level
	at net.minecraft.server.v1_16_R2.MinecraftServer.initWorld(MinecraftServer.java:503) ~[patched_1.16.3.jar:git-Paper-198]
	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.createWorld(CraftServer.java:1157) ~[patched_1.16.3.jar:git-Paper-198]
	at org.bukkit.Bukkit.createWorld(Bukkit.java:581) ~[patched_1.16.3.jar:git-Paper-198]
	at org.bukkit.WorldCreator.createWorld(WorldCreator.java:325) ~[patched_1.16.3.jar:git-Paper-198]
	at com.boydti.fawe.bukkit.FaweBukkit.createWorldUnloaded(FaweBukkit.java:257) ~[?:?]
	at com.sk89q.worldedit.bukkit.adapter.BukkitImplAdapter.createWorld(BukkitImplAdapter.java:221) ~[?:?]
	at com.sk89q.worldedit.bukkit.adapter.IDelegateBukkitImplAdapter.createWorld(IDelegateBukkitImplAdapter.java:143) ~[?:?]
	at com.boydti.fawe.bukkit.wrapper.AsyncWorld.create(AsyncWorld.java:152) ~[?:?]
	at de.xxschrandxx.awm.api.worldcreation.fawe$1.run(fawe.java:54) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.3.jar:git-Paper-198]
	at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.3.jar:git-Paper-198]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.3.jar:git-Paper-198]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.IllegalStateException: Asynchronous ChunkMapDistance::addTicket!
	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[patched_1.16.3.jar:git-Paper-198]
	at net.minecraft.server.v1_16_R2.ChunkMapDistance.addTicket(ChunkMapDistance.java:158) ~[patched_1.16.3.jar:git-Paper-198]
	at net.minecraft.server.v1_16_R2.ChunkMapDistance.addTicketAtLevel(ChunkMapDistance.java:346) ~[patched_1.16.3.jar:git-Paper-198]
	at net.minecraft.server.v1_16_R2.ChunkMapDistance.a(ChunkMapDistance.java:213) ~[patched_1.16.3.jar:git-Paper-198]
	at net.minecraft.server.v1_16_R2.ChunkProviderServer.getChunkFutureMainThread(ChunkProviderServer.java:568) ~[patched_1.16.3.jar:git-Paper-198]
	at net.minecraft.server.v1_16_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:501) ~[patched_1.16.3.jar:git-Paper-198]
	at net.minecraft.server.v1_16_R2.World.getChunkAt(World.java:356) ~[patched_1.16.3.jar:git-Paper-198]
	at net.minecraft.server.v1_16_R2.IWorldReader.getChunkAt(IWorldReader.java:100) ~[patched_1.16.3.jar:git-Paper-198]
	at net.minecraft.server.v1_16_R2.World.getChunkAt(World.java:297) ~[patched_1.16.3.jar:git-Paper-198]
	at net.minecraft.server.v1_16_R2.WorldProviderNormal.a(SourceFile:28) ~[patched_1.16.3.jar:git-Paper-198]
	at net.minecraft.server.v1_16_R2.WorldProviderNormal.a(SourceFile:62) ~[patched_1.16.3.jar:git-Paper-198]
	at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:570) ~[patched_1.16.3.jar:git-Paper-198]
	at net.minecraft.server.v1_16_R2.MinecraftServer.initWorld(MinecraftServer.java:489) ~[patched_1.16.3.jar:git-Paper-198]
	... 14 more
```

If you try to join a world, the server crasshes...

**Comment by Peda1996** [comment]
Same error happens to me, while trying to initialize a world async.

**Comment by jacklollz2** [comment]
I hope this can be resolved soon.

**Comment by NotMyFault** [comment]
This has been resolved in some modern version.
