### ISSUE TITLE
LinBus fails to deserialize BaseItem using BaseItemAdapter

### ISSUE THREAD

**Issue by PierreSchwang** [IntellectualSites/FastAsyncWorldEdit#2991]
### Server Implementation

Paper

### Server Version

1.21.3

### Describe the bug

Most likely since the LinBus introduction?

### To Reproduce

-

### Expected behaviour

-

### Fawe Debugpaste

-

### Fawe Version

-

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

```
Caused by: org.enginehub.linbus.stream.exception.NbtParseException: At character index 1: Unexpected token: '}', expected Text
        at FastAsyncWorldEdit-Bukkit-2.12.1-SNAPSHOT-965.jar/org.enginehub.linbus.format.snbt.impl.reader.LinSnbtReader.unexpectedTokenSpecificError(LinSnbtReader.java:165) ~[FastAsyncWorldEdit-Bukkit-2.12.1-SNAPSHOT-965.jar:?]
        at FastAsyncWorldEdit-Bukkit-2.12.1-SNAPSHOT-965.jar/org.enginehub.linbus.format.snbt.impl.reader.LinSnbtReader.readName(LinSnbtReader.java:256) ~[FastAsyncWorldEdit-Bukkit-2.12.1-SNAPSHOT-965.jar:?]
        at FastAsyncWorldEdit-Bukkit-2.12.1-SNAPSHOT-965.jar/org.enginehub.linbus.format.snbt.impl.reader.LinSnbtReader.fillTokenStack(LinSnbtReader.java:187) ~[FastAsyncWorldEdit-Bukkit-2.12.1-SNAPSHOT-965.jar:?]
        at FastAsyncWorldEdit-Bukkit-2.12.1-SNAPSHOT-965.jar/org.enginehub.linbus.format.snbt.impl.reader.LinSnbtReader.nextOrNull(LinSnbtReader.java:176) ~[FastAsyncWorldEdit-Bukkit-2.12.1-SNAPSHOT-965.jar:?]
        at FastAsyncWorldEdit-Bukkit-2.12.1-SNAPSHOT-965.jar/org.enginehub.linbus.stream.impl.OptionalInfoCalculator.nextOrNull(OptionalInfoCalculator.java:68) ~[FastAsyncWorldEdit-Bukkit-2.12.1-SNAPSHOT-965.jar:?]
        at FastAsyncWorldEdit-Bukkit-2.12.1-SNAPSHOT-965.jar/org.enginehub.linbus.tree.impl.LinTagReader.readCompound(LinTagReader.java:93) ~[FastAsyncWorldEdit-Bukkit-2.12.1-SNAPSHOT-965.jar:?]
        at FastAsyncWorldEdit-Bukkit-2.12.1-SNAPSHOT-965.jar/org.enginehub.linbus.tree.LinCompoundTag.readFrom(LinCompoundTag.java:257) ~[FastAsyncWorldEdit-Bukkit-2.12.1-SNAPSHOT-965.jar:?]
        at FastAsyncWorldEdit-Bukkit-2.12.1-SNAPSHOT-965.jar/com.fastasyncworldedit.core.util.gson.BaseItemAdapter.deserialize(BaseItemAdapter.java:42) ~[FastAsyncWorldEdit-Bukkit-2.12.1-SNAPSHOT-965.jar:?]
        at FastAsyncWorldEdit-Bukkit-2.12.1-SNAPSHOT-965.jar/com.fastasyncworldedit.core.util.gson.BaseItemAdapter.deserialize(BaseItemAdapter.java:21) ~[FastAsyncWorldEdit-Bukkit-2.12.1-SNAPSHOT-965.jar:?]
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[gson-2.10.1.jar:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.readIntoField(ReflectiveTypeAdapterFactory.java:212) ~[gson-2.10.1.jar:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$FieldReflectionAdapter.readField(ReflectiveTypeAdapterFactory.java:433) ~[gson-2.10.1.jar:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:393) ~[gson-2.10.1.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1227) ~[gson-2.10.1.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1137) ~[gson-2.10.1.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1075) ~[gson-2.10.1.jar:?]
        at FastAsyncWorldEdit-Bukkit-2.12.1-SNAPSHOT-965.jar/com.sk89q.worldedit.session.storage.JsonFileSessionStore.load(JsonFileSessionStore.java:104) ~[FastAsyncWorldEdit-Bukkit-2.12.1-SNAPSHOT-965.jar:?]
        at FastAsyncWorldEdit-Bukkit-2.12.1-SNAPSHOT-965.jar/com.sk89q.worldedit.session.SessionManager.get(SessionManager.java:160) ~[FastAsyncWorldEdit-Bukkit-2.12.1-SNAPSHOT-965.jar:?]
        at FastAsyncWorldEdit-Bukkit-2.12.1-SNAPSHOT-965.jar/com.sk89q.worldedit.extension.platform.PlatformManager.handleBlockInteract(PlatformManager.java:393) ~[FastAsyncWorldEdit-Bukkit-2.12.1-SNAPSHOT-965.jar:?]
        at FastAsyncWorldEdit-Bukkit-2.12.1-SNAPSHOT-965.jar/com.sk89q.worldedit.util.eventbus.MethodHandleEventHandler.dispatch(MethodHandleEventHandler.java:51) ~[FastAsyncWorldEdit-Bukkit-2.12.1-SNAPSHOT-965.jar:?]
        at FastAsyncWorldEdit-Bukkit-2.12.1-SNAPSHOT-965.jar/com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[FastAsyncWorldEdit-Bukkit-2.12.1-SNAPSHOT-965.jar:?]```

**Comment by PierreSchwang** [comment]
https://github.com/EngineHub/lin-bus/pull/15
