### ISSUE TITLE
Pasting TileEntities causes chunk errors

### ISSUE THREAD

**Issue by TheoRetisch1** [IntellectualSites/FastAsyncWorldEdit#304]
**FastAsyncWorldEdit Configuration Files:** 
config.yml: https://pastebin.com/ujeAs9cC
config-legacy.yml: https://pastebin.com/46pr1EFy
logs/latest.log: https://pastebin.com/dBi3PDd8

**FastAsyncWorldEdit Version Number:** 
FastAsyncWorldEdit-13 created by Empire92
FAWE version:
 - Date Dec 25, 2019 12:00:00 AM
 - Commit f6102278
 - Build 13
 - Platform bukkit
[19:16:13 INFO]: &7Wiki: https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/wiki
------------------ Platforms ------------------
* Bukkit-Official(1.15-13;9efdd88)

---------------- Capabilities ----------------
GAME_HOOKS: Bukkit-Official
CONFIGURATION: Bukkit-Official
USER_COMMANDS: Bukkit-Official
PERMISSIONS: Bukkit-Official
WORLDEDIT_CUI: Bukkit-Official
WORLD_EDITING: Bukkit-Official

**Spigot/Paper Version Number:** 
This server is running Paper version git-Paper-32 (MC: 1.15.1) (Implementing API version 1.15.1-R0.1-SNAPSHOT)

**Description of the problem:**
There is an Paper Tile Entity error after copying and pasting tile entities, like chests and signs. 
error:
```
[19:48:12] [Server thread/WARN]: com.destroystokyo.paper.exception.ServerInternalException: Attempted to place a tile entity (net.minecraft.server.v1_15_R1.TileEntitySign@3ac4d0ca) at -132,90,269 (Block{minecraft:air}) where there was no entity tile!
[19:48:12] [Server thread/WARN]: Chunk coordinates: -144,256
[19:48:12] [Server thread/WARN]:    at net.minecraft.server.v1_15_R1.Chunk.setTileEntity(Chunk.java:567)
[19:48:12] [Server thread/WARN]:    at net.minecraft.server.v1_15_R1.Chunk.a(Chunk.java:539)
[19:48:12] [Server thread/WARN]:    at net.minecraft.server.v1_15_R1.ChunkRegionLoader.loadEntities(ChunkRegionLoader.java:571)
[19:48:12] [Server thread/WARN]:    at net.minecraft.server.v1_15_R1.ChunkRegionLoader.lambda$loadChunk$6(ChunkRegionLoader.java:154)
[19:48:12] [Server thread/WARN]:    at net.minecraft.server.v1_15_R1.Chunk.addEntities(Chunk.java:622)
[19:48:12] [Server thread/WARN]:    at net.minecraft.server.v1_15_R1.PlayerChunkMap.lambda$null$27(PlayerChunkMap.java:737)
[19:48:12] [Server thread/WARN]:    at com.mojang.datafixers.util.Either.lambda$mapLeft$0(Either.java:162)
[19:48:12] [Server thread/WARN]:    at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
[19:48:12] [Server thread/WARN]:    at com.mojang.datafixers.util.Either.mapLeft(Either.java:162)
[19:48:12] [Server thread/WARN]:    at net.minecraft.server.v1_15_R1.PlayerChunkMap.lambda$c$28(PlayerChunkMap.java:722)
[19:48:12] [Server thread/WARN]:    at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
[19:48:12] [Server thread/WARN]:    at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
[19:48:12] [Server thread/WARN]:    at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
[19:48:12] [Server thread/WARN]:    at net.minecraft.server.v1_15_R1.ChunkTaskQueueSorter.b(SourceFile:58)
[19:48:12] [Server thread/WARN]:    at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[19:48:12] [Server thread/WARN]:    at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[19:48:12] [Server thread/WARN]:    at net.minecraft.server.v1_15_R1.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:810)
[19:48:12] [Server thread/WARN]:    at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[19:48:12] [Server thread/WARN]:    at net.minecraft.server.v1_15_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:285)
[19:48:12] [Server thread/WARN]:    at net.minecraft.server.v1_15_R1.World.getChunkAt(World.java:330)
[19:48:12] [Server thread/WARN]:    at net.minecraft.server.v1_15_R1.IWorldReader.getChunkAt(IWorldReader.java:87)
[19:48:12] [Server thread/WARN]:    at net.minecraft.server.v1_15_R1.World.getChunkAt(World.java:274)
[19:48:12] [Server thread/WARN]:    at net.minecraft.server.v1_15_R1.MinecraftServer.loadSpawn(MinecraftServer.java:617)
[19:48:12] [Server thread/WARN]:    at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:463)
[19:48:12] [Server thread/WARN]:    at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:290)
[19:48:12] [Server thread/WARN]:    at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:884)
[19:48:12] [Server thread/WARN]:    at java.lang.Thread.run(Thread.java:748)
```

**How to replicate**:
1. //copy a selection with TileEntities (chest+sign)
2. //paste
3. //undo
4. //restart the server and let Paper handle the problems

**Plugins being used on the server:**
https://pastebin.com/Tsn1XUWp

**Checklist**:
- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.15.1]
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by aurorasmiles** [comment]
I was able to reproduce this issue with build 144, but I can't reproduce it with 155.
