### ISSUE TITLE
ArrayIndexOutOfBoundsException when editing below zero.

### ISSUE THREAD

**Issue by dordsor21** [IntellectualSites/FastAsyncWorldEdit#307]
**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 
https://athion.net/ISPaster/paste/view/0ac4075295744e31a381a59a0630dd32

**[REQUIRED] FastAsyncWorldEdit Version Number:** 
1.15-13 (latest)

**[REQUIRED] Spigot/Paper Version Number:** 
git-Paper-32 (MC: 1.15.1)

**[REQUIRED] Description of the problem:**
Following error when /paste'ing below zero.
```[11:15:35] [Craft Scheduler Thread - 107/ERROR]: An unexpected error while handling a WorldEdit command
java.lang.ArrayIndexOutOfBoundsException: -1
	at com.boydti.fawe.beta.implementation.blocks.CharBlocks.set(CharBlocks.java:119) ~[?:?]
	at com.boydti.fawe.beta.implementation.blocks.CharBlocks.set(CharBlocks.java:107) ~[?:?]
	at com.boydti.fawe.beta.implementation.blocks.CharSetBlocks.setBlock(CharSetBlocks.java:89) ~[?:?]
	at com.boydti.fawe.beta.implementation.chunk.ChunkHolder$3.setBlock(ChunkHolder.java:212) ~[?:?]
	at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.setBlock(ChunkHolder.java:452) ~[?:?]
	at com.boydti.fawe.beta.implementation.IChunkExtent.setBlock(IChunkExtent.java:25) ~[?:?]
	at com.sk89q.worldedit.extent.OutputExtent.setBlock(OutputExtent.java:59) ~[?:?]
	at com.sk89q.worldedit.extent.PassthroughExtent.setBlock(PassthroughExtent.java:200) ~[?:?]
	at com.sk89q.worldedit.EditSession.setBlock(EditSession.java:874) ~[?:?]
	at com.boydti.fawe.object.extent.BlockTranslateExtent.setBlock(BlockTranslateExtent.java:31) ~[?:?]
	at com.boydti.fawe.object.extent.BlockTranslateExtent.setBlock(BlockTranslateExtent.java:36) ~[?:?]
	at com.sk89q.worldedit.extent.AbstractDelegateExtent.setBlock(AbstractDelegateExtent.java:183) ~[?:?]
	at com.boydti.fawe.object.extent.PositionTransformExtent.setBlock(PositionTransformExtent.java:79) ~[?:?]
	at com.boydti.fawe.object.function.block.SimpleBlockCopy.apply(SimpleBlockCopy.java:21) ~[?:?]
	at com.sk89q.worldedit.function.visitor.RegionVisitor.resume(RegionVisitor.java:83) ~[?:?]
	at com.sk89q.worldedit.function.operation.Operations.completeBlindly(Operations.java:76) ~[?:?]
	at com.sk89q.worldedit.function.operation.ForwardExtentCopy.resume(ForwardExtentCopy.java:395) ~[?:?]
	at com.sk89q.worldedit.function.operation.Operations.completeLegacy(Operations.java:57) ~[?:?]
	at com.sk89q.worldedit.command.ClipboardCommands.paste(ClipboardCommands.java:464) ~[?:?]
	at com.sk89q.worldedit.command.ClipboardCommandsRegistration.cmd$_paste(ClipboardCommandsRegistration.java:354) ~[?:?]
	at org.enginehub.piston.CommandManager.execute(CommandManager.java:158) ~[?:?]
	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommandOnCurrentThread$17(PlatformCommandManager.java:673) ~[?:?]
	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandTask(PlatformCommandManager.java:689) ~[?:?]
	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandOnCurrentThread(PlatformCommandManager.java:675) ~[?:?]
	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommand$15(PlatformCommandManager.java:645) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) [patched_1.15.1.jar:git-Paper-32]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [patched_1.15.1.jar:git-Paper-32]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.15.1.jar:git-Paper-32]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_232]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_232]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
```

Following error when //stack'ing below zero
```
[11:23:52 ERROR]: An unexpected error while handling a WorldEdit command
java.lang.ArrayIndexOutOfBoundsException: null
````

**How to replicate**:
//stack or //paste below y=0

**Checklist**:
- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.14.4](https://ci.athion.net/job/FastAsyncWorldEdit-pipeline/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by BrodyBeckwith** [comment]
Can confirm this issue. Stacking above world height also causes this. Additionally the current worldedit operation will "lag" until the error is completed and an error occurs for each coordinate outside the world causing significant spam and lag.
