### ISSUE TITLE
//generatebiome does not work

### ISSUE THREAD

**Issue by RealmportalMC** [IntellectualSites/FastAsyncWorldEdit#32]
select a region

type //generatebiome <valid biome> <some integer>

Nothing happens. it says X columns changed, but nothing occurs

Using @IronApollo Vector update

**Comment by AeSix** [comment]
I can confirm this is still an issue with FAWE-NVS 165:
I attempted to do //generatebiome nether 
I get the same result for just //generatebiome

https://puu.sh/D31Qx/8939bd05b5.png

**Comment by RedstoneFuture** [comment]
https://issues.intellectualsites.com/issue/PS-97

**Comment by NotMyFault** [comment]
This will need to be revisited now with 1.17 and P2 v6:
```
[19:41:48 WARN]: java.lang.NoClassDefFoundError: com/fastasyncworldedit/core/adventure/adventure/text/minimessage/Template
[19:41:48 WARN]:        at com.fastasyncworldedit.bukkit.regions.plotsquared.PlotSetBiome.execute(PlotSetBiome.java:51)
[19:41:48 WARN]:        at com.plotsquared.core.command.Command.execute(Command.java:365)
[19:41:48 WARN]:        at com.plotsquared.core.command.MainCommand.execute(MainCommand.java:312)
[19:41:48 WARN]:        at com.plotsquared.core.command.MainCommand.onCommand(MainCommand.java:187)
[19:41:48 WARN]:        at com.plotsquared.bukkit.BukkitCommand.onCommand(BukkitCommand.java:54)
[19:41:48 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[19:41:48 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[19:41:48 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:821)
[19:41:48 WARN]:        at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2185)
[19:41:48 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1996)
[19:41:48 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1977)
[19:41:48 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[19:41:48 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[19:41:48 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:36)
[19:41:48 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[19:41:48 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[19:41:48 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[19:41:48 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1340)
[19:41:48 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:193)
[19:41:48 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[19:41:48 WARN]:        at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1319)
[19:41:48 WARN]:        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1312)
[19:41:48 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132)
[19:41:48 WARN]:        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1273)
[19:41:48 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1184)
[19:41:48 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[19:41:48 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[19:41:48 WARN]: Caused by: java.lang.ClassNotFoundException: com.fastasyncworldedit.core.adventure.adventure.text.minimessage.Template
[19:41:48 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:146)
[19:41:48 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
[19:41:48 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
[19:41:48 WARN]:        ... 27 more
```

**Comment by dordsor21** [comment]
The command //generatebiome is for setting biomes to the world via the given expression, thus all commands mentioned in this issue are invalid for `//generatebiome <biome> <expression> [-h] [-r] [-o] [-c]`
