### ISSUE TITLE
Unable to do any WE operation on 1.15.2

### ISSUE THREAD

**Issue by Nikox3003** [IntellectualSites/FastAsyncWorldEdit#322]
# Bug report for FastAsyncWorldEdit 1.14.4

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 
https://athion.net/ISPaster/paste/view/c0e13db8331043959e3ec288ede17b6a

**[REQUIRED] FastAsyncWorldEdit Version Number:** 
 &7FAWE version:
- Date 2020-01-15 00:00:00
- Commit ff35280e
- Build 45
- Platform bukkit
 &7Wiki: https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/wiki
------------------ Platforms ------------------
* Bukkit-Official(1.15-45;0cad7f2)

 ---------------- Capabilities ----------------
GAME_HOOKS: Bukkit-Official
CONFIGURATION: Bukkit-Official
USER_COMMANDS: Bukkit-Official
PERMISSIONS: Bukkit-Official
WORLDEDIT_CUI: Bukkit-Official
WORLD_EDITING: Bukkit-Official

**[REQUIRED] Spigot/Paper Version Number:** 
This server is running Paper version git-Paper-71 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**[REQUIRED] Description of the problem:**
Trying to do any WE operation results throwing following error to console:
```
[10:43:50] [Craft Scheduler Thread - 5/ERROR]: An unexpected error while handling a WorldEdit command
java.lang.NullPointerException: null
	at com.sk89q.worldedit.bukkit.BukkitWorld.get(BukkitWorld.java:567) ~[?:?]
	at com.sk89q.worldedit.bukkit.BukkitWorld.get(BukkitWorld.java:79) ~[?:?]
	at com.boydti.fawe.beta.implementation.cache.ChunkCache.newChunk(ChunkCache.java:43) ~[?:?]
	at com.boydti.fawe.beta.implementation.cache.ChunkCache.get(ChunkCache.java:37) ~[?:?]
	at com.boydti.fawe.beta.implementation.cache.ChunkCache.get(ChunkCache.java:12) ~[?:?]
	at com.boydti.fawe.beta.implementation.queue.SingleThreadQueueExtent.getCachedGet(SingleThreadQueueExtent.java:76) ~[?:?]
	at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.newWrappedGet(ChunkHolder.java:388) ~[?:?]
	at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.getOrCreateGet(ChunkHolder.java:355) ~[?:?]
	at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.filterBlocks(ChunkHolder.java:311) ~[?:?]
	at com.boydti.fawe.beta.IQueueExtent.apply(IQueueExtent.java:152) ~[?:?]
	at com.boydti.fawe.beta.implementation.queue.ParallelQueueExtent.apply(ParallelQueueExtent.java:95) ~[?:?]
	at com.boydti.fawe.beta.implementation.queue.ParallelQueueExtent.setBlocks(ParallelQueueExtent.java:157) ~[?:?]
	at com.sk89q.worldedit.extent.PassthroughExtent.setBlocks(PassthroughExtent.java:158) ~[?:?]
	at com.sk89q.worldedit.command.RegionCommands.set(RegionCommands.java:111) ~[?:?]
	at com.sk89q.worldedit.command.RegionCommandsRegistration.cmd$_set(RegionCommandsRegistration.java:583) ~[?:?]
	at org.enginehub.piston.CommandManager.execute(CommandManager.java:158) ~[?:?]
	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommandOnCurrentThread$17(PlatformCommandManager.java:693) ~[?:?]
	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandTask(PlatformCommandManager.java:709) ~[?:?]
	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandOnCurrentThread(PlatformCommandManager.java:695) ~[?:?]
	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommand$15(PlatformCommandManager.java:665) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-71]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.2.jar:git-Paper-71]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.2.jar:git-Paper-71]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

```
**How to replicate**:
Install latest version of FAWE, make region selection and run //set stone

**Plugins being used on the server:**
Plugins (14): CoreProtect, Essentials, EssentialsChat, EssentialsSpawn, FastAsyncWorldEdit, Hub*, IPWhitelist*, Multiverse-Core, ProtocolLib, ProtocolSupport, Vault, VoxelSniper, WorldEdit, WorldGuard
**Note: I have disabled WE check in CoreProtect, also i didn't install WorldEdit manually.** 

**Checklist**:
- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.14.4](https://ci.athion.net/job/FastAsyncWorldEdit-pipeline/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by imDaniX** [comment]
Same problem, same error, same FAWE. Paper-77.

**Comment by MrPowerGamerBR** [comment]
Can confirm, same problem.

**Comment by MattBDev** [comment]
We don't support 1.15.2 yet so this issue was technically invalid. I'll consider opening it after IronApollo commits his adapter stuff or reviews NMF adapter changes. Everyone saying they are experiencing this is using a version that didn't even support 1.15.2
