### ISSUE TITLE
FAWE Legacy Mapper broken in 1.13.2

### ISSUE THREAD

**Issue by MattBDev** [IntellectualSites/FastAsyncWorldEdit#323]
Relevant Debug Paste:https://athion.net/ISPaster/paste/view/33fca1f04db74a7eb62999d5f5417496
Using Build 45 from Jenkins. Issue still occurs on local internal builds. 
**[REQUIRED] Spigot/Paper Version Number:** 
1.13.2
**[REQUIRED] Description of the problem:**
LegacyMapper fails to register all blocks in 1.13.2 but it works in 1.15.1

Error: http://haste.athion.net/yisiwugodo.sql

**How to replicate**:
Just load up the plugin.

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.14.4](https://ci.athion.net/job/FastAsyncWorldEdit-pipeline/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by MattBDev** [comment]
Won't fix.

**Comment by ChristophHD** [comment]
I know that 1.13 support has been dropped, but for some reasons I needed to use the plugin for that version and, after seeing that issue and looking for the files shown in the error, I saw that the method loadFromResource in com.sk89q.worldedit.world.registry.LegacyMapper was causing the problem because of the number of exceptions produced by this:

```
[17:18:36 WARN]: com.boydti.fawe.command.SuggestInputParseException: Does not match a valid block type: minecraft:oak_sign
[17:18:36 WARN]:        at com.sk89q.worldedit.world.block.BlockTypes.parse(BlockTypes.java:765)
[17:18:36 WARN]:        at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseLogic(DefaultBlockParser.java:334)
[17:18:36 WARN]:        at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseFromInput(DefaultBlockParser.java:110)
[17:18:36 WARN]:        at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseFromInput(DefaultBlockParser.java:75)
[17:18:36 WARN]:        at com.sk89q.worldedit.internal.registry.AbstractFactory.parseFromInput(AbstractFactory.java:73)
[17:18:36 WARN]:        at com.sk89q.worldedit.world.registry.LegacyMapper.loadFromResource(LegacyMapper.java:137)
```

I just print the stack trace and that is the result, in the file named legacy.json, located at resources/com/sk89q/worldedit/world/registry, it's defined a non-legacy block, oak_sign belongs to 1.14, as well as oak_wall_sign, and because of the number of exceptions produced by that in the same method, the StackOverflowError was been thrown. If you rename all oak_sign as **sign** and oak_wall_sign as **wall_sign**, the issue is gone. As I said at the beginning, I know that, at this moment, 1.13 support has been dropped, but considering that the fix is just to replace a few strings in the json file, I think it could be good enough if, at least, the jar file of the website were updated with just that change, in case there's someone who need it in some moment for that specific version, and I thought it was important to be said at least.

**Comment by MattBDev** [comment]
We already updated the files o  the download page.
