### ISSUE TITLE
Exception on startup

### ISSUE THREAD

**Issue by PSNRigner** [IntellectualSites/FastAsyncWorldEdit#344]
# Bug report for FastAsyncWorldEdit 1.14.4

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 

Not needed

**[REQUIRED] FastAsyncWorldEdit Version Number:** 

Build #91 (currently latest)

**[REQUIRED] Spigot/Paper Version Number:** 

Paper git-paper-243 (1.14.4)

**[REQUIRED] Description of the problem:**

Once the plugin is loaded, an exception is printed in the logs. Nothing important, It's just missing a try-catch around the setupPlotSquared() call. If the plugin isn't present, an exception is thrown. Doesn't break anything but still logs.

**How to replicate**:

Start a server with FAWE and without PlotSquared and wait for it to be fully loaded.

**Plugins being used on the server:**

Confidential, but only using FAWE / FAVS and not PlotSquared.

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.14.4](https://ci.athion.net/job/FastAsyncWorldEdit-pipeline/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by MattBDev** [comment]
> Confidential
Not an excuse but I'll allow it this time. We do need to see the error log though.

**Comment by PSNRigner** [comment]
You don't need it because I told you exactly what the issue in the code is (just missing a try-catch in setupPlotSquared(), like all the other lib loading is doing), but here it is : 

```
java.lang.NoClassDefFoundError: com/github/intellectualsites/plotsquared/plot/util/SchematicHandler
        at com.boydti.fawe.bukkit.FaweBukkit.setupPlotSquared(FaweBukkit.java:328) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-243]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1171) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1098) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925) ~[patched_1.14.4.jar:git-Paper-243]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
Caused by: java.lang.ClassNotFoundException: com.github.intellectualsites.plotsquared.plot.util.SchematicHandler
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_232]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:139) ~[patched_1.14.4.jar:git-Paper-243]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:85) ~[patched_1.14.4.jar:git-Paper-243]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_232]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_232]
        ... 8 more
```

**Comment by IronApollo** [comment]
Fixed in https://github.com/IntellectualSites/FastAsyncWorldEdit/commit/14ac3205ce3ce81f7ebedf5b8b0b39ee13d1e275 .
