### ISSUE TITLE
set does not react when used by user in wg region

### ISSUE THREAD

**Issue by banit** [IntellectualSites/FastAsyncWorldEdit#347]
Users cant worldedit in their Regions. 

Following error comes up in console

User Permissions for Fawe:
https://i.vgy.me/1PF51H.png

https://athion.net/ISPaster/paste/view/d83d1484ef9b40c5b53c492da506b8d8

Paper 1.15.2 - 112
FAWE 1.15 - 97;d2bcc6d

```
21:14:24
We_Craftchen issued server command: //set 1
WARN 21:14:24
java.lang.AbstractMethodError: com.boydti.fawe.regions.FaweMaskManager.getMask(Lcom/sk89q/worldedit/entity/Player;Lcom/boydti/fawe/regions/FaweMaskManager$MaskType;)Lcom/boydti/fawe/regions/FaweMask;
at com.boydti.fawe.util.WEManager.getMask(WEManager.java:111)
at com.sk89q.worldedit.extension.platform.AbstractPlayerActor.getCurrentRegions(AbstractPlayerActor.java:695)
at com.sk89q.worldedit.extension.platform.AbstractPlayerActor.getCurrentRegions(AbstractPlayerActor.java:691)
at com.boydti.fawe.util.EditSessionBuilder.compile(EditSessionBuilder.java:408)
at com.sk89q.worldedit.EditSession.<init>(EditSession.java:248)
at com.boydti.fawe.util.EditSessionBuilder.build(EditSessionBuilder.java:448)
at com.sk89q.worldedit.LocalSession.createEditSession(LocalSession.java:1478)
at com.sk89q.worldedit.extension.platform.binding.ProvideBindings.editSession(ProvideBindings.java:70)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.sk89q.worldedit.extension.platform.binding.Bindings.invoke(Bindings.java:123)
at com.sk89q.worldedit.extension.platform.binding.Bindings.lambda$register$1(Bindings.java:94)
at org.enginehub.piston.inject.MapBackedValueStore.lambda$injectedValue$0(MapBackedValueStore.java:56)
at java.util.Optional.flatMap(Optional.java:241)
at org.enginehub.piston.inject.MapBackedValueStore.injectedValue(MapBackedValueStore.java:56)
at org.enginehub.piston.inject.MergedValueAccess.lambda$injectedValue$0(MergedValueAccess.java:54)
at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:531)
at org.enginehub.piston.inject.MergedValueAccess.injectedValue(MergedValueAccess.java:57)
at org.enginehub.piston.inject.MemoizingValueAccess.injectedValue(MemoizingValueAccess.java:84)
at org.enginehub.piston.impl.CommandParametersImpl.injectedValue(CommandParametersImpl.java:109)
at org.enginehub.piston.inject.InjectedValueAccess.injectedValue(InjectedValueAccess.java:44)
at com.sk89q.worldedit.command.RegionCommandsRegistration.extract$editSession(RegionCommandsRegistration.java:974)
at com.sk89q.worldedit.command.RegionCommandsRegistration.cmd$_set(RegionCommandsRegistration.java:555)
at org.enginehub.piston.CommandManager.execute(CommandManager.java:158)
at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommandOnCurrentThread$15(PlatformCommandManager.java:685)
at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandTask(PlatformCommandManager.java:701)
at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandOnCurrentThread(PlatformCommandManager.java:687)
at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommand$13(PlatformCommandManager.java:657)
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84)
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
```

**Plugins being used on the server:**
 AdvancedRegionMarket, antiRedstoneClock, BungeeTabListPlus, Citizens, CMI, CoreProtect, DiscordSRV, dtlTradersPlus, dynmap*, EasyPrefix, FastAsyncWorldEdit, HackedCore*, HackedServer*, HeadDatabase*, HideStream*, LibsDisguises, LuckPerms, MaSuiteCore*, MaSuiteHomes, MaSuiteTeleports*, MaSuiteWarps*, MoreCommandsPlus*, MysqlPlayerDataBridge, PlaceholderAPI, Plan, ProtocolLib, StaffChat, SystemInfo, Vault, Votifier, VotingPlugin, VoxelSniper, WorldBorder, WorldEdit, WorldEditGlobalizerBukkit*, WorldEditSUI, WorldGuard, WorldGuardExtraFlags

**Comment by IronApollo** [comment]
Must be an issue with how I changed some of the hook code earlier. I'll look into it soon.

**Comment by banit** [comment]
Problem persists but without error in log
https://i.vgy.me/48hOqi.png

**Comment by RealmportalMC** [comment]
Im experiencing what could very well be this issue. i can edit stuff with the FAWE bypass permissions.

Players arent able to edit within their plots

**Comment by aurorasmiles** [comment]
Is this still an issue with the latest build?

**Comment by aurorasmiles** [comment]
No answer, assuming this is fixed
