### ISSUE TITLE
NullPointerException in RegionIterator

### ISSUE THREAD

**Issue by MattBDev** [IntellectualSites/FastAsyncWorldEdit#351]
# Bug report for FastAsyncWorldEdit 1.14.4

Build Number 112
WorldGuard 7
[21:14:52 INFO]: >> PlotSquared (Version: PlotSquared-4.453)
Paper - 243
Minecraft 1.14.4
```
[22:54:28 INFO]: Aequotis issued server command: //set 1
[22:54:28 WARN]: java.lang.NullPointerException
[22:54:28 WARN]: at com.sk89q.worldedit.regions.iterator.RegionIterator.<init>(RegionIterator.java:46)
[22:54:28 WARN]: at com.sk89q.worldedit.regions.AbstractRegion.iterator(AbstractRegion.java:62)
[22:54:28 WARN]: at java.util.AbstractSet.hashCode(AbstractSet.java:122)
[22:54:28 WARN]: at java.util.HashMap.hash(HashMap.java:339)
[22:54:28 WARN]: at java.util.HashMap.put(HashMap.java:612)
[22:54:28 WARN]: at java.util.HashSet.add(HashSet.java:220)
[22:54:28 WARN]: at com.boydti.fawe.util.WEManager.getMask(WEManager.java:113)
[22:54:28 WARN]: at com.sk89q.worldedit.extension.platform.AbstractPlayerActor.getCurrentRegions(AbstractPlayerActor.java:695)
[22:54:28 WARN]: at com.sk89q.worldedit.extension.platform.AbstractPlayerActor.getCurrentRegions(AbstractPlayerActor.java:691)
[22:54:28 WARN]: at com.boydti.fawe.util.EditSessionBuilder.compile(EditSessionBuilder.java:408)
[22:54:28 WARN]: at com.sk89q.worldedit.EditSession.<init>(EditSession.java:248)
[22:54:28 WARN]: at com.boydti.fawe.util.EditSessionBuilder.build(EditSessionBuilder.java:448)
[22:54:28 WARN]: at com.sk89q.worldedit.LocalSession.createEditSession(LocalSession.java:1478)
[22:54:28 WARN]: at com.sk89q.worldedit.extension.platform.binding.ProvideBindings.editSession(ProvideBindings.java:70)
[22:54:28 WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[22:54:28 WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[22:54:28 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[22:54:28 WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
[22:54:28 WARN]: at com.sk89q.worldedit.extension.platform.binding.Bindings.invoke(Bindings.java:123)
[22:54:28 WARN]: at com.sk89q.worldedit.extension.platform.binding.Bindings.lambda$register$1(Bindings.java:94)
[22:54:28 WARN]: at org.enginehub.piston.inject.MapBackedValueStore.lambda$injectedValue$0(MapBackedValueStore.java:56)
[22:54:28 WARN]: at java.util.Optional.flatMap(Optional.java:241)
[22:54:28 WARN]: at org.enginehub.piston.inject.MapBackedValueStore.injectedValue(MapBackedValueStore.java:56)
[22:54:28 WARN]: at org.enginehub.piston.inject.MergedValueAccess.lambda$injectedValue$0(MergedValueAccess.java:54)
[22:54:28 WARN]: at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
[22:54:28 WARN]: at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
[22:54:28 WARN]: at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
[22:54:28 WARN]: at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
[22:54:28 WARN]: at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
[22:54:28 WARN]: at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
[22:54:28 WARN]: at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
[22:54:28 WARN]: at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[22:54:28 WARN]: at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
[22:54:28 WARN]: at org.enginehub.piston.inject.MergedValueAccess.injectedValue(MergedValueAccess.java:57)
[22:54:28 WARN]: at org.enginehub.piston.inject.MemoizingValueAccess.injectedValue(MemoizingValueAccess.java:84)
[22:54:28 WARN]: at org.enginehub.piston.impl.CommandParametersImpl.injectedValue(CommandParametersImpl.java:109)
[22:54:28 WARN]: at org.enginehub.piston.inject.InjectedValueAccess.injectedValue(InjectedValueAccess.java:44)
[22:54:28 WARN]: at com.sk89q.worldedit.command.RegionCommandsRegistration.extract$editSession(RegionCommandsRegistration.java:974)
[22:54:28 WARN]: at com.sk89q.worldedit.command.RegionCommandsRegistration.cmd$_set(RegionCommandsRegistration.java:555)
[22:54:28 WARN]: at org.enginehub.piston.CommandManager.execute(CommandManager.java:158)
[22:54:28 WARN]: at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommandOnCurrentThread$15(PlatformCommandManager.java:685)
[22:54:28 WARN]: at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandTask(PlatformCommandManager.java:701)
[22:54:28 WARN]: at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandOnCurrentThread(PlatformCommandManager.java:687)
[22:54:28 WARN]: at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommand$13(PlatformCommandManager.java:657)
[22:54:28 WARN]: at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84)
[22:54:28 WARN]: at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[22:54:28 WARN]: at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[22:54:28 WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[22:54:28 WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[22:54:28 WARN]: at java.lang.Thread.run(Thread.java:748)
[22:54:28 WARN]: java.lang.NullPointerException
[22:54:28 WARN]: at com.boydti.fawe.bukkit.regions.plotsquared.PlotSquaredFeature.getMask(PlotSquaredFeature.java:112)
[22:54:28 WARN]: at com.boydti.fawe.util.WEManager.getMask(WEManager.java:111)
[22:54:28 WARN]: at com.sk89q.worldedit.extension.platform.AbstractPlayerActor.getCurrentRegions(AbstractPlayerActor.java:695)
[22:54:28 WARN]: at com.sk89q.worldedit.extension.platform.AbstractPlayerActor.getCurrentRegions(AbstractPlayerActor.java:691)
[22:54:28 WARN]: at com.boydti.fawe.util.EditSessionBuilder.compile(EditSessionBuilder.java:408)
[22:54:28 WARN]: at com.sk89q.worldedit.EditSession.<init>(EditSession.java:248)
[22:54:28 WARN]: at com.boydti.fawe.util.EditSessionBuilder.build(EditSessionBuilder.java:448)
[22:54:28 WARN]: at com.sk89q.worldedit.LocalSession.createEditSession(LocalSession.java:1478)
[22:54:28 WARN]: at com.sk89q.worldedit.extension.platform.binding.ProvideBindings.editSession(ProvideBindings.java:70)
[22:54:28 WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[22:54:28 WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[22:54:28 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[22:54:28 WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
[22:54:28 WARN]: at com.sk89q.worldedit.extension.platform.binding.Bindings.invoke(Bindings.java:123)
[22:54:28 WARN]: at com.sk89q.worldedit.extension.platform.binding.Bindings.lambda$register$1(Bindings.java:94)
[22:54:28 WARN]: at org.enginehub.piston.inject.MapBackedValueStore.lambda$injectedValue$0(MapBackedValueStore.java:56)
[22:54:28 WARN]: at java.util.Optional.flatMap(Optional.java:241)
[22:54:28 WARN]: at org.enginehub.piston.inject.MapBackedValueStore.injectedValue(MapBackedValueStore.java:56)
[22:54:28 WARN]: at org.enginehub.piston.inject.MergedValueAccess.lambda$injectedValue$0(MergedValueAccess.java:54)
[22:54:28 WARN]: at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
[22:54:28 WARN]: at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
[22:54:28 WARN]: at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
[22:54:28 WARN]: at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
[22:54:28 WARN]: at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
[22:54:28 WARN]: at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
[22:54:28 WARN]: at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
[22:54:28 WARN]: at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[22:54:28 WARN]: at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
[22:54:28 WARN]: at org.enginehub.piston.inject.MergedValueAccess.injectedValue(MergedValueAccess.java:57)
[22:54:28 WARN]: at org.enginehub.piston.inject.MemoizingValueAccess.injectedValue(MemoizingValueAccess.java:84)
[22:54:28 WARN]: at org.enginehub.piston.impl.CommandParametersImpl.injectedValue(CommandParametersImpl.java:109)
[22:54:28 WARN]: at org.enginehub.piston.inject.InjectedValueAccess.injectedValue(InjectedValueAccess.java:44)
[22:54:28 WARN]: at com.sk89q.worldedit.command.RegionCommandsRegistration.extract$editSession(RegionCommandsRegistration.java:974)
[22:54:28 WARN]: at com.sk89q.worldedit.command.RegionCommandsRegistration.cmd$_set(RegionCommandsRegistration.java:555)
[22:54:28 WARN]: at org.enginehub.piston.CommandManager.execute(CommandManager.java:158)
[22:54:28 WARN]: at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommandOnCurrentThread$15(PlatformCommandManager.java:685)
[22:54:28 WARN]: at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandTask(PlatformCommandManager.java:701)
[22:54:28 WARN]: at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandOnCurrentThread(PlatformCommandManager.java:687)
[22:54:28 WARN]: at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommand$13(PlatformCommandManager.java:657)
[22:54:28 WARN]: at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84)
[22:54:28 WARN]: at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[22:54:28 WARN]: at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[22:54:28 WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[22:54:28 WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[22:54:28 WARN]: at java.lang.Thread.run(Thread.java:748)
```

Reported by Aequotis on Discord

**Comment by Aequotis** [comment]
_**Extra information as of Build 164 of FAWE:**_

- If WEA enabled or fully opped, FAWE actions will work.
- If `fawe.plotsquared` permission is not set to true (for the user), FAWE actions will not work.
- If `fawe.plotsquared` permission is set to true (for the user), FAWE actions will not work & a further permission node is requested: `fawe.plotsquaredflag` (https://prnt.sc/rsfkxa)
- If `fawe.plotsquaredflag` is set to tru (for the user), FAWE actions will not work (although no errors shown in chat) and console will print the following error: https://hastebin.com/uwokerayul.md
- All FAWE attempted actions will print this message in console: https://hastebin.com/luwanezigo.md

_Debugpaste: https://athion.net/ISPaster/paste/view/130ab3299814415cb1c06f805010a36d_

**Comment by aurorasmiles** [comment]
Is this still an issue with the latest version?
