### ISSUE TITLE
CS-CoreLib2 not work with FAWE

### ISSUE THREAD

**Issue by andris155** [IntellectualSites/FastAsyncWorldEdit#352]
# Bug report for FastAsyncWorldEdit 1.14.4

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 

Config: https://pastebin.com/gcSfbjgK
Config-legacy: https://pastebin.com/sDxPYDtn

**[REQUIRED] FastAsyncWorldEdit Version Number:** 

```
[11:52:46 INFO]: FastAsyncWorldEdit-112 created by Empire92
[11:52:46 INFO]: FAWE version:
- Date Mar 4, 2020, 12:00:00 AM
- Commit fbe8342b
- Build 112
- Platform Bukkit
[11:52:46 INFO]: Wiki: https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/wiki
[11:52:46 INFO]: ------------------ Platforms ------------------
* Bukkit-Official(1.15-112;417cbd5)
[11:52:46 INFO]: ---------------- Capabilities ----------------
GAME_HOOKS: Bukkit-Official
CONFIGURATION: Bukkit-Official
USER_COMMANDS: Bukkit-Official
PERMISSIONS: Bukkit-Official
WORLDEDIT_CUI: Bukkit-Official
WORLD_EDITING: Bukkit-Official
```

**[REQUIRED] Spigot/Paper Version Number:** 

```
[11:53:24 INFO]: This server is running Paper version git-Paper-125 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
[11:53:24 INFO]: Checking version, please wait...
[11:53:24 INFO]: Previous version: git-Paper-122 (MC: 1.15.2)
[11:53:24 INFO]: You are 1 version(s) behind

```
**[REQUIRED] Description of the problem:**

```
[11:32:03] [Server thread/ERROR]: [CS-CoreLib2] [CS-CoreLib2 - Protection] An Error occured while querying the Protection Module: "WorldGuard"
java.lang.NullPointerException: null
	at com.sk89q.worldedit.bukkit.WorldEditPlugin.getCachedPlayer(WorldEditPlugin.java:584) ~[?:?]
	at com.sk89q.worldedit.bukkit.BukkitPlayer.getExistingMap(BukkitPlayer.java:97) ~[?:?]
	at com.sk89q.worldedit.bukkit.BukkitPlayer.<init>(BukkitPlayer.java:79) ~[?:?]
	at com.sk89q.worldguard.bukkit.BukkitPlayer.<init>(BukkitPlayer.java:43) ~[?:?]
	at com.sk89q.worldguard.bukkit.BukkitPlayer.<init>(BukkitPlayer.java:39) ~[?:?]
	at com.sk89q.worldguard.bukkit.BukkitOfflinePlayer.<init>(BukkitOfflinePlayer.java:42) ~[?:?]
	at com.sk89q.worldguard.bukkit.WorldGuardPlugin.wrapOfflinePlayer(WorldGuardPlugin.java:452) ~[?:?]
	at me.mrCookieSlime.Slimefun.cscorelib2.protection.modules.WorldGuardProtectionModule.hasPermission(WorldGuardProtectionModule.java:44) ~[?:?]
	at me.mrCookieSlime.Slimefun.cscorelib2.protection.ProtectionManager.hasPermission(ProtectionManager.java:191) ~[?:?]
	at io.github.thebusybiscuit.slimefun4.implementation.items.androids.WoodcutterAndroid.chopTree(WoodcutterAndroid.java:45) ~[?:?]
	at io.github.thebusybiscuit.slimefun4.implementation.items.androids.ProgrammableAndroid.tick(ProgrammableAndroid.java:382) ~[?:?]
	at io.github.thebusybiscuit.slimefun4.implementation.items.androids.Android$1.tick(Android.java:59) ~[?:?]
	at io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.lambda$run$0(TickerTask.java:112) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-125]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.15.2.jar:git-Paper-125]
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1185) ~[patched_1.15.2.jar:git-Paper-125]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-125]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112) ~[patched_1.15.2.jar:git-Paper-125]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Paper-125]
	at java.lang.Thread.run(Unknown Source) [?:?]
```
**How to replicate**:

Use CS-CoreLib2 with Slimefun.
Use Androids.

**Plugins being used on the server:**

AdminVedelem, antiRedstoneClock, AreaShop, ArmorStandEditor, ChangeSkin, ChatControl, ChestCommands, ChestShop, ChestShopNotifier*, ChestSort, Citizens, CitizensCMD, CombatLogX, CommandHook, CommandSigns, CompatNoCheatPlus*, ConditionalCommands*, CoreProtect, CraftBook, CratesPlus, CrazyAuctions, CrazyAuctionsLog, CreativeNbtControl, CS-CoreLib, DyedBackpacks, EnderContainers, EntityDetection, Essentials, EssentialsChat, EssentialsSpawn, EventekGUI, EventRendszer, ExtraGear, GriefPrevention, GriefPreventionFlags, HeadDatabase*, HeapDump*, HideAndSeek, HolographicDisplays, HonapStaffja, HotbarPets, HungerGames, JukeBox, Kemkedes, Kezdes, LibsDisguises, LockettePro, Lottery, LuckPerms, mcMMO, MineMarket-Universal*, MobArena, MobFarmManager, Multiverse-Core, Multiverse-NetherPortals, MyCommand, MyPet, NametagEdit*, NoCheatPlus, NoSpawnerChange, NoteBlockAPI, OpenInv, Paintball, PickupSpawners, PlaceholderAPI, PlayerWarp, PlayerWarpTab, PlotSquared, PlugMan, PocketGames, ProtocolLib, RedstoneClockDetector, RemoveUnbreaking, RestrictedCreative, Shopkeepers, SignEdit, Sleepy*, Slimefun, SlimefunLuckyBlocks, SlimefunOreChunks, SlimefunPomaFix, StaffChat, StaffTime, TimeIsMoney*, TitleManager, TokenManager, TokenShopEditor, TokenStaff*, TreasureChest, Vault, Votifier, VotingPlugin, WDLCompanion*, WDLCompanionGriefPreventionSupport*, Wild, WorldBorder, WorldEdit, WorldGuard, WorldGuardExtraFlags, WorldGuardPomaFlags, YoutubeBridge

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.14.4](https://ci.athion.net/job/FastAsyncWorldEdit-pipeline/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by Tsoccerguy3** [comment]
Craftbook does not work with FAWE  on 1.14.x ,1.15.x it will crash the server

Quote from ME4502
"Every time a plugin uses a WorldEdit API player, FAWE loads a file from disk. No wonder having a plugin that uses the WorldEdit API kills the server"

**Comment by aurorasmiles** [comment]
> 
> 
> Craftbook does not work with FAWE on 1.14.x ,1.15.x it will crash the server
> 
> Quote from ME4502
> "Every time a plugin uses a WorldEdit API player, FAWE loads a file from disk. No wonder having a plugin that uses the WorldEdit API kills the server"

@Tsoccerguy3 This has nothing to do with that issue? Please open a new one and don't comment on random other issues

**Comment by N0tMyFaultOG** [comment]
I'm not sure what `CoreLib2` is and how that is related to Fawe. It's not a dependency of Fawe, it appears to be some library for an external plugin., so report issues there. We cannot provide a fix for the broken CoreLib2.
