### ISSUE TITLE
Data cycler. Array index out of range: 8

### ISSUE THREAD

**Issue by jokbon** [IntellectualSites/FastAsyncWorldEdit#358]
# Bug report for FAWE 1.15.2

**Console error:** 
[10:13:41 WARN]: java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 8
[10:13:41 WARN]:        at com.sk89q.worldedit.world.block.BlockType.withPropertyId(BlockType.java:123)
[10:13:41 WARN]:        at com.sk89q.worldedit.world.block.BlockType.withStateId(BlockType.java:128)
[10:13:41 WARN]:        at com.sk89q.worldedit.world.block.BlockState.with(BlockState.java:263)
[10:13:41 WARN]:        at com.sk89q.worldedit.command.tool.BlockDataCyler.handleCycle(BlockDataCyler.java:86)
[10:13:41 WARN]:        at com.sk89q.worldedit.command.tool.BlockDataCyler.actPrimary(BlockDataCyler.java:119)
[10:13:41 WARN]:        at com.sk89q.worldedit.extension.platform.PlatformManager.lambda$handleBlockInteract$2(PlatformManager.java:378)
[10:13:41 WARN]:        at com.sk89q.worldedit.extension.platform.PlatformManager$$Lambda$3810.000000002C797420.run(Unknown Source)
[10:13:41 WARN]:        at com.sk89q.worldedit.extension.platform.AbstractPlayerActor.lambda$runAction$1(AbstractPlayerActor.java:671)
[10:13:41 WARN]:        at com.sk89q.worldedit.extension.platform.AbstractPlayerActor$$Lambda$3772.000000003505D070.run(Unknown Source)
[10:13:41 WARN]:        at com.boydti.fawe.object.task.AsyncNotifyQueue.lambda$run$0(AsyncNotifyQueue.java:26)
[10:13:41 WARN]:        at com.boydti.fawe.object.task.AsyncNotifyQueue$$Lambda$3773.000000002C8222C0.call(Unknown Source)
[10:13:41 WARN]:        at com.boydti.fawe.object.task.AsyncNotifyQueue.lambda$call$1(AsyncNotifyQueue.java:43)
[10:13:41 WARN]:        at com.boydti.fawe.object.task.AsyncNotifyQueue$$Lambda$3774.000000003595FB50.call(Unknown Source)
[10:13:41 WARN]:        at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
[10:13:41 WARN]:        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[10:13:41 WARN]:        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[10:13:41 WARN]:        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[10:13:41 WARN]:        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**[REQUIRED] FastAsyncWorldEdit Version Number:** 

Jenkins Build #110
**[REQUIRED] Spigot/Paper Version Number:** 

Paper build #118
**[REQUIRED] Description of the problem + How to replicate:**
Isusue each time performing data cycling with fawe, data cycling not hapening, Console error.

**Plugins being used on the server:**
EssentialsX2.17.1.60 main spawn and chat

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.14.4](https://ci.athion.net/job/FastAsyncWorldEdit-pipeline/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by aurorasmiles** [comment]
Is this still an issue with the latest version?

**Comment by aurorasmiles** [comment]
No answer, assuming this is fixed
