### ISSUE TITLE
FAWE 1.14.4 - Error when attempting to create a //line over 1024 blocks long

### ISSUE THREAD

**Issue by NomadMC** [IntellectualSites/FastAsyncWorldEdit#362]
# Bug report for FastAsyncWorldEdit 1.14.4

**FastAsyncWorldEdit Configuration Files:** 

https://athion.net/ISPaster/paste/view/37e4f249de6f461c86a2942ba7f4720d

**FastAsyncWorldEdit Version Number:** 

FastAsyncWorldEdit-113 [latest stable as of writing this]

**Spigot/Paper Version Number:** 

git-Spigot-56f8471-13caf84 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

**Description of the problem:**

Upon attempting to run a //line command with a selection over 1024 blocks long in a given direction, the line is not created, and an error in console is generated:

```12.03 11:19:41 [Server] Server thread/INFO NomadicNom issued server command: //line dirt
12.03 11:19:41 [Server] Craft Scheduler Thread - 16/ERROR An unexpected error while handling a WorldEdit command
12.03 11:19:41 [Server] INFO java.lang.UnsupportedOperationException: LocalVectorSet can only contain vectors within 1024 blocks (cuboid) of the first entry. 
12.03 11:19:41 [Server] INFO at com.boydti.fawe.object.collection.LocalBlockVectorSet.add(LocalBlockVectorSet.java:203) ~[?:?]
12.03 11:19:41 [Server] INFO at com.boydti.fawe.object.collection.LocalBlockVectorSet.add(LocalBlockVectorSet.java:219) ~[?:?]
12.03 11:19:41 [Server] INFO at com.sk89q.worldedit.EditSession.drawLine(EditSession.java:2580) ~[?:?]
12.03 11:19:41 [Server] INFO at com.sk89q.worldedit.EditSession.drawLine(EditSession.java:2524) ~[?:?]
12.03 11:19:41 [Server] INFO at com.sk89q.worldedit.command.RegionCommands.line(RegionCommands.java:245) ~[?:?]
12.03 11:19:41 [Server] INFO at com.sk89q.worldedit.command.RegionCommandsRegistration.cmd$_line(RegionCommandsRegistration.java:689) ~[?:?]
12.03 11:19:41 [Server] INFO at org.enginehub.piston.CommandManager.execute(CommandManager.java:158) ~[?:?]
12.03 11:19:41 [Server] INFO at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommandOnCurrentThread$15(PlatformCommandManager.java:685) ~[?:?]
12.03 11:19:41 [Server] INFO at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandTask(PlatformCommandManager.java:701) ~[?:?]
12.03 11:19:41 [Server] INFO at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandOnCurrentThread(PlatformCommandManager.java:687) ~[?:?]
12.03 11:19:41 [Server] INFO at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommand$13(PlatformCommandManager.java:657) ~[?:?]
12.03 11:19:41 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) [spigot-1.14.4.jar:git-Spigot-56f8471-13caf84]
12.03 11:19:41 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.14.4.jar:git-Spigot-56f8471-13caf84]
12.03 11:19:41 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_211]
12.03 11:19:41 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_211]
12.03 11:19:41 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]```

An error also pops up in-game:

![2020-03-11_15 29](https://user-images.githubusercontent.com/44537660/76550001-60fbb200-645f-11ea-918a-327c28bac0a3.png)

**How to replicate**:
<!--- If you can reproduce the issue please tell us as detailed as possible step by step how to do that -->

1) Create an area selection over 1024 blocks long in at least one direction.
2) Run a line command, such as `//line dirt`.
3) The line will not be created, and the above-mentioned errors in console and in-game will be generated instead.

**Plugins being used on the server:**
<!--- Optional but recommended - issue "/plugins" in-game or in console and copy/paste the list `-->

`LuckPerms, neoPaintingSwitch, CrackShot, AutoMessage, Chairs, RealisticTime, Modifyworld, Votifier, VotingPlugin, FastAsyncWorldEdit, Images, ViaVersion, Vault, WorldEdit, Essentials, PerWorldInventory, PlotSquared, WorldGuard, Multiverse-Core, ProtocolLib, Citizens, Shopkeepers, DiscordSRV, EssentialsGeoIP, TAB, FalloutDallas, ChatEx, EssentialsSpawn, BKCommonLib, LightCleaner, HolographicDisplays, CitizensCMD, Train_Carts, TCCoasters`

**Checklist**:
<!--- Make sure you've completed the following steps (put an "X" between of brackets): -->
- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.14.4](https://ci.athion.net/job/FastAsyncWorldEdit-pipeline/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by MattBDev** [comment]
It looks like this limitation was intentional. I'll see if there is anything that can be done about this.

**Comment by dordsor21** [comment]
This seems like it was fixed at some point
