### ISSUE TITLE
[BUG] Schematic Load java.lang.NullPointerException and ArrayIndexOutOfBoundsException: 11338

### ISSUE THREAD

**Issue by FredTheBigCactus** [IntellectualSites/FastAsyncWorldEdit#398]
When using the //sel poly and selecting a block (left click) warnings come up, after a couple of attempts an error appears.

[Error.txt](https://github.com/IntellectualSites/FastAsyncWorldEdit/files/4454188/Error.txt)

- [ ] > op FredTheBigCactus
[12:21:10 INFO]: Made FredTheBigCactus a server operator
[12:21:13 INFO]: FredTheBigCactus issued server command: //wand
[12:21:21 INFO]: FredTheBigCactus issued server command: //sel poly
[12:21:28 WARN]: java.lang.NullPointerException
[12:21:28 WARN]:        at com.sk89q.worldedit.math.BlockVector3.equals(BlockVector3.java:768)
[12:21:28 WARN]:        at com.sk89q.worldedit.regions.selector.Polygonal2DRegionSelector.selectPrimary(Polygonal2DRegionSelector.java:137)
[12:21:28 WARN]:        at com.sk89q.worldedit.command.tool.SelectionWand.actSecondary(SelectionWand.java:40)
[12:21:28 WARN]:        at com.sk89q.worldedit.extension.platform.PlatformManager.lambda$handleBlockInteract$1(PlatformManager.java:364)
[12:21:28 WARN]:        at com.sk89q.worldedit.extension.platform.AbstractPlayerActor.lambda$runAction$1(AbstractPlayerActor.java:671)
[12:21:28 WARN]:        at com.boydti.fawe.object.task.AsyncNotifyQueue.lambda$run$0(AsyncNotifyQueue.java:26)
[12:21:28 WARN]:        at com.boydti.fawe.object.task.AsyncNotifyQueue.lambda$call$1(AsyncNotifyQueue.java:43)
[12:21:28 WARN]:        at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(Unknown Source)
[12:21:28 WARN]:        at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
[12:21:28 WARN]:        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
[12:21:28 WARN]:        at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
[12:21:28 WARN]:        at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
[12:22:12 INFO]: FredTheBigCactus issued server command: //set air
[12:22:18 WARN]: java.lang.NullPointerException
[12:22:18 WARN]:        at com.sk89q.worldedit.math.BlockVector3.equals(BlockVector3.java:768)
[12:22:18 WARN]:        at com.sk89q.worldedit.regions.selector.Polygonal2DRegionSelector.selectPrimary(Polygonal2DRegionSelector.java:137)
[12:22:18 WARN]:        at com.sk89q.worldedit.command.tool.SelectionWand.actSecondary(SelectionWand.java:40)
[12:22:18 WARN]:        at com.sk89q.worldedit.extension.platform.PlatformManager.lambda$handleBlockInteract$1(PlatformManager.java:364)
[12:22:18 WARN]:        at com.sk89q.worldedit.extension.platform.AbstractPlayerActor.lambda$runAction$1(AbstractPlayerActor.java:671)
[12:22:18 WARN]:        at com.boydti.fawe.object.task.AsyncNotifyQueue.lambda$run$0(AsyncNotifyQueue.java:26)
[12:22:18 WARN]:        at com.boydti.fawe.object.task.AsyncNotifyQueue.lambda$call$1(AsyncNotifyQueue.java:43)
[12:22:18 WARN]:        at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(Unknown Source)
[12:22:18 WARN]:        at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
[12:22:18 WARN]:        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
[12:22:18 WARN]:        at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
[12:22:18 WARN]:        at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
[12:22:28 INFO]: FredTheBigCactus issued server command: //set air
[12:22:29 ERROR]: An unexpected error while handling a WorldEdit command
java.lang.ArrayIndexOutOfBoundsException: 11338
        at com.sk89q.worldedit.bukkit.adapter.impl.FAWE_Spigot_v1_15_R2.init(FAWE_Spigot_v1_15_R2.java:104) ~[?:?]
        at com.sk89q.worldedit.bukkit.adapter.impl.FAWE_Spigot_v1_15_R2.adaptToChar(FAWE_Spigot_v1_15_R2.java:288) ~[?:?]
        at com.boydti.fawe.bukkit.adapter.mc1_15_2.BukkitGetBlocks_1_15_2.ordinal(BukkitGetBlocks_1_15_2.java:580) ~[?:?]
        at com.boydti.fawe.bukkit.adapter.mc1_15_2.BukkitGetBlocks_1_15_2.update(BukkitGetBlocks_1_15_2.java:547) ~[?:?]        at com.boydti.fawe.beta.implementation.blocks.CharBlocks$2.get(CharBlocks.java:23) ~[?:?]
        at com.boydti.fawe.beta.implementation.blocks.CharBlocks.load(CharBlocks.java:92) ~[?:?]
        at com.boydti.fawe.beta.implementation.filter.block.CharFilterBlock.initLayer(CharFilterBlock.java:61) ~[?:?]
        at com.sk89q.worldedit.regions.Region.filter(Region.java:208) ~[?:?]
        at com.boydti.fawe.beta.implementation.filter.block.ChunkFilterBlock.filter(ChunkFilterBlock.java:122) ~[?:?]
        at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.filterBlocks(ChunkHolder.java:313) ~[?:?]
        at com.boydti.fawe.beta.IQueueExtent.apply(IQueueExtent.java:153) ~[?:?]
        at com.boydti.fawe.beta.implementation.queue.ParallelQueueExtent.apply(ParallelQueueExtent.java:89) ~[?:?]
        at com.boydti.fawe.beta.implementation.queue.ParallelQueueExtent.setBlocks(ParallelQueueExtent.java:151) ~[?:?]
        at com.sk89q.worldedit.extent.PassthroughExtent.setBlocks(PassthroughExtent.java:156) ~[?:?]
        at com.sk89q.worldedit.command.RegionCommands.set(RegionCommands.java:108) ~[?:?]
        at com.sk89q.worldedit.command.RegionCommandsRegistration.cmd$_set(RegionCommandsRegistration.java:537) ~[?:?]
        at org.enginehub.piston.CommandManager.execute(CommandManager.java:158) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommandOnCurrentThread$15(PlatformCommandManager.java:679) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandTask(PlatformCommandManager.java:695) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandOnCurrentThread(PlatformCommandManager.java:681) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommand$13(PlatformCommandManager.java:651) ~[?:?]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-164]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.2.jar:git-Paper-164]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.2.jar:git-Paper-164]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_241]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_241]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]

**Comment by IronApollo** [comment]
Labeled invalid and closed. Please fill out the proper bug template provided for you.
