### ISSUE TITLE
Problem with Clipboard loading in FAWE API!

### ISSUE THREAD

**Issue by derverdox** [IntellectualSites/FastAsyncWorldEdit#410]
**[REQUIRED] FastAsyncWorldEdit Version Number:** 
167

**[REQUIRED] Spigot/Paper Version Number:** 
git-Paper-126 (MC: 1.15.2) 

**[REQUIRED] Description of the problem:**
I am using the FAWE API. I am trying to load a clipboard.

`    private Clipboard loadClipboard (){

        ClipboardFormat format = ClipboardFormats.findByFile(schematicFile);
        try{
            ClipboardReader reader = format.getReader(new FileInputStream(schematicFile));
            Clipboard clipboard = reader.read();
            reader.close();
            return clipboard;
        }
        catch (IOException e){
            e.printStackTrace();
            return null;
        }
    }`
When doing so i receive this error:

```[01:40:23 WARN]: java.io.EOFException: Stream ended prematurely
[01:40:23 WARN]:        at net.jpountz.lz4.LZ4BlockInputStream.readFully(LZ4BlockInputStream.java:207)
[01:40:23 WARN]:        at net.jpountz.lz4.LZ4BlockInputStream.refill(LZ4BlockInputStream.java:137)
[01:40:23 WARN]:        at net.jpountz.lz4.LZ4BlockInputStream.read(LZ4BlockInputStream.java:89)
[01:40:23 WARN]:        at com.sk89q.worldedit.extent.clipboard.io.SchematicReader.readCombined(SchematicReader.java:178)
[01:40:23 WARN]:        at com.sk89q.worldedit.extent.clipboard.io.SchematicReader.readwrite(SchematicReader.java:199)
[01:40:23 WARN]:        at com.sk89q.worldedit.extent.clipboard.io.SchematicReader.read(SchematicReader.java:271)
[01:40:23 WARN]:        at com.sk89q.worldedit.extent.clipboard.io.ClipboardReader.read(ClipboardReader.java:58)
[01:40:23 WARN]:        at com.sk89q.worldedit.extent.clipboard.io.ClipboardReader.read(ClipboardReader.java:45)
[01:40:23 WARN]:        at de.verdox.vschematicshop.model.Schematic.loadClipboard(Schematic.java:101)
[01:40:23 WARN]:        at de.verdox.vschematicshop.model.Schematic.<init>(Schematic.java:58)
[01:40:23 WARN]:        at de.verdox.vschematicshop.configuration.SchematicConfig.lambda$readSchematicFiles$2(SchematicConfig.java:147)
[01:40:23 WARN]:        at java.util.HashMap$KeySpliterator.forEachRemaining(Unknown Source)
[01:40:23 WARN]:        at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
[01:40:23 WARN]:        at de.verdox.vschematicshop.configuration.SchematicConfig.readSchematicFiles(SchematicConfig.java:131)
[01:40:23 WARN]:        at de.verdox.vschematicshop.VSchematicShop.initFiles(VSchematicShop.java:96)
[01:40:23 WARN]:        at de.verdox.vschematicshop.VSchematicShop.onEnable(VSchematicShop.java:47)
[01:40:23 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[01:40:23 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[01:40:23 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:435)
[01:40:23 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:470)
[01:40:23 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:384)
[01:40:23 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:482)
[01:40:23 WARN]:        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298)
[01:40:23 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:885)
[01:40:23 WARN]:        at java.lang.Thread.run(Unknown Source)
```
**How to replicate**:
Already said

**Plugins being used on the server:**
CommandGUI, CustomBooks*, DoorKeys, EconomyMain*, EggReplacer, Essentials, FastAsyncWorldEdit, HolographicDisplays, NBTAPI*, Polls, TimoCloudGUI*, V-Animals, V-Core*, V-Levels*, V-Processing, V-SchematicShop, V-Towny*, Vault, ViaVersion*, WorldEdit, WorldGuard, WorldSystem

**Comment by derverdox** [comment]
Only seems to happen with old .schematic files.

**Comment by dordsor21** [comment]
Seems to me that I can only replicate this if I save a schematic in the new format, and then change the file extension to .schematic (forcing it to load as an old format schematic). Was this schematic created in 1.13+ but over a few weeks ago?

**Comment by derverdox** [comment]
I got the used schematics from this website.

https://www.minecraft-schematics.com/
If you want me to i can search for the schematics that made the problem

**Comment by dordsor21** [comment]
Having the schematic file would be useful. Could you also give the entire error? It's missing the Exception at the top of the stacktrace.
