### ISSUE TITLE
Error with manipulating tile entities

### ISSUE THREAD

**Issue by Firestar311** [IntellectualSites/FastAsyncWorldEdit#420]
# Bug report for FastAsyncWorldEdit 1.15.2

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 

 https://athion.net/ISPaster/paste/view/2a370eefc2254e67bf40e52c494eb4bb

**[REQUIRED] FastAsyncWorldEdit Version Number:** 
 

**[REQUIRED] Spigot/Paper Version Number:** 

- Date Apr 16, 2020, 12:00:00 AM
[22:43:42] [Craft Scheduler Thread - 4/INFO]: FAWE version:
- Commit f6828c78
- Build 168
[22:43:42] [Craft Scheduler Thread - 4/INFO]: Wiki: https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/wiki
- Platform Bukkit
* Bukkit-Official(1.15-168;97d7388)
WORLD_EDITING: Bukkit-Official
[22:43:42] [Craft Scheduler Thread - 4/INFO]: ------------------ Platforms ------------------
[22:43:42] [Craft Scheduler Thread - 4/INFO]: ---------------- Capabilities ----------------
CONFIGURATION: Bukkit-Official
GAME_HOOKS: Bukkit-Official
PERMISSIONS: Bukkit-Official
USER_COMMANDS: Bukkit-Official
WORLDEDIT_CUI: Bukkit-Official
**[REQUIRED] Description of the problem:**
 There was an error

[22:41:04] [Server thread/INFO]: Attempted to place a tile entity (net.minecraft.server.v1_15_R1.TileEntityChest@1c5c0d7) at 246,30,-46 lock{minecraft:air}) where there was no entity tile!
[22:41:04] [Server thread/WARN]: java.lang.Exception
[22:41:04] [Server thread/INFO]: Chunk coordinates: 240,-48
[22:41:04] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.Chunk.a(Chunk.java:433)
[22:41:04] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.Chunk.setTileEntity(Chunk.java:456)
[22:41:04] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.ChunkRegionLoader.lambda$6(ChunkRegionLoader.java:114)
[22:41:04] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.ChunkRegionLoader.loadEntities(ChunkRegionLoader.java:417)
[22:41:04] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.PlayerChunkMap.lambda$33(PlayerChunkMap.java:588)
[22:41:04] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.Chunk.addEntities(Chunk.java:501)
[22:41:04] [Server thread/WARN]: at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
[22:41:04] [Server thread/WARN]: at com.mojang.datafixers.util.Either.lambda$mapLeft$0(Either.java:162)
[22:41:04] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.PlayerChunkMap.lambda$31(PlayerChunkMap.java:574)
[22:41:04] [Server thread/WARN]: at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
[22:41:04] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118)
[22:41:04] [Server thread/WARN]: at com.mojang.datafixers.util.Either.mapLeft(Either.java:162)
[22:41:04] [Server thread/WARN]: at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
[22:41:04] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:911)
[22:41:04] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144)
[22:41:04] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.ChunkProviderServer$a.executeTask(ChunkProviderServer.java:578)
[22:41:04] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.ChunkProviderServer.runTasks(ChunkProviderServer.java:248)
[22:41:04] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:589)
[22:41:04] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.ChunkTaskQueueSorter.b(SourceFile:58)
[22:41:04] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:927)
[22:41:04] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127)
[22:41:04] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144)
skQueueSorter.b(SourceFile:58)
[22:41:04] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118)
[22:41:04] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.ChunkProviderServer.runTasks(ChunkProviderServer.java:248)
[22:41:04] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.ChunkProviderServer$a.executeTask(ChunkProviderServer.java:578)
[22:41:04] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:589)
[22:41:04] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:911)
[22:41:04] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:927)
[22:41:04] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:895)
[22:41:04] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127)
[22:41:04] [Server thread/WARN]: at java.base/java.lang.Thread.run(Thread.java:834)
[22:41:04] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:828)

**How to replicate**:

This happens when manipulating tile entities in general with fawe, and it seems to be every time

**Plugins being used on the server:**
 LuckPerms, FastAsyncWorldEdit, BuycraftX, Vault, VoxelSniper, ProtocolLib, WorldEdit, CoreProtect

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.15.2](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by dordsor21** [comment]
You're not using an up-to-date version. Don't tick boxes that aren't complete.

What a waste of ticket 420.
