### ISSUE TITLE
Errors after reloading a world.

### ISSUE THREAD

**Issue by NanoAi** [IntellectualSites/FastAsyncWorldEdit#431]
# Bug report for FastAsyncWorldEdit 1.15.2

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** Unchanged from defaults.

**[REQUIRED] FastAsyncWorldEdit Version Number:** 

```
FAWE version:
- Commit fffb59f3
- Build 180
- Platform Bukkit
Wiki: https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/wiki
------------------ Platforms ------------------
* Bukkit-Official(1.15-180;004a60d)
---------------- Capabilities ----------------
GAME_HOOKS: Bukkit-Official
CONFIGURATION: Bukkit-Official
USER_COMMANDS: Bukkit-Official
PERMISSIONS: Bukkit-Official
WORLDEDIT_CUI: Bukkit-Official
WORLD_EDITING: Bukkit-Official
```

**[REQUIRED] Spigot/Paper Version Number:** 

```
This server is running Paper version git-Paper-226 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
Checking version, please wait...
Previous version: git-Paper-201 (MC: 1.15.2)
You are running the latest version
```

**[REQUIRED] Description of the problem:**

After a world has been unloaded, and then reloaded trying to run some commands like `//undo` yields the following error...
![image](https://user-images.githubusercontent.com/3096584/80532474-365fad00-896a-11ea-9a5d-3a9271f58a6d.png)
Even though that world is actually currently loaded and should be accessible.

**How to replicate**:

The easiest way to replicate this is to use Multiverse-Core ( https://dev.bukkit.org/projects/multiverse-core ).
Create a new world using `/mv create`, unload the world using `/mv unload`, load the world again using `/mv load`, then try using FAWE in that world... when you go to undo something it'll give you the error above.

**Plugins being used on the server:**

Plugins (19) (Custom plugins redacted): CoreProtect, Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsProtect, FastAsyncWorldEdit, InfiniteAnnouncements, LuckPerms, Multiverse-Core, OreAnnouncer, PlaceholderAPI, ProtocolLib, SmoothSleep, spark, Vault, WorldEdit

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.15.2](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by aurorasmiles** [comment]
Is this still an issue with the latest version?

**Comment by aurorasmiles** [comment]
No answer, assuming this is fixed

**Comment by dordsor21** [comment]
Please provide a debugpaste or log of some sort.

**Comment by hyperspacepilot** [comment]
[11:36:53] [Server thread/INFO]: Flauschiii issued server command: //pos2
[11:36:53] [Craft Scheduler Thread - 181/ERROR]: [WorldEdit] An unexpected error occurred while handling a FAWE command
java.lang.NullPointerException: The world was unloaded and the reference is unavailable
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:787) ~[patched_1.12.2.jar:git-Paper-1620]
	at com.sk89q.worldedit.bukkit.BukkitWorld.getWorld(BukkitWorld.java:212) ~[?:?]
	at com.sk89q.worldedit.bukkit.BukkitWorld.getMaxY(BukkitWorld.java:434) ~[?:?]
	at com.sk89q.worldedit.regions.CuboidRegion.recalculate(CuboidRegion.java:140) ~[?:?]
	at com.sk89q.worldedit.regions.CuboidRegion.setPos2(CuboidRegion.java:130) ~[?:?]
	at com.sk89q.worldedit.regions.selector.CuboidRegionSelector.selectSecondary(CuboidRegionSelector.java:149) ~[?:?]
	at com.sk89q.worldedit.command.SelectionCommands.pos2(SelectionCommands.java:147) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_282]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_282]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_282]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_282]
	at com.sk89q.worldedit.util.command.parametric.ParametricCallable.call(ParametricCallable.java:265) ~[?:?]
	at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:133) ~[?:?]
	at com.sk89q.worldedit.extension.platform.CommandManager$2.get(CommandManager.java:413) ~[?:?]
	at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandTask(CommandManager.java:436) ~[?:?]
	at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandOnCurrentThread(CommandManager.java:417) ~[?:?]
	at com.sk89q.worldedit.extension.platform.CommandManager$3$1.run(CommandManager.java:535) ~[?:?]
	at com.boydti.fawe.object.FawePlayer.lambda$runAction$3(FawePlayer.java:345) ~[?:?]
	at com.boydti.fawe.object.task.SimpleAsyncNotifyQueue.operate(SimpleAsyncNotifyQueue.java:25) ~[?:?]
	at com.boydti.fawe.object.task.AsyncNotifyQueue$1.run(AsyncNotifyQueue.java:15) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[patched_1.12.2.jar:git-Paper-1620]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.12.2.jar:git-Paper-1620]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.12.2.jar:git-Paper-1620]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_282]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_282]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
[11:37:18] [Server thread/INFO]: Flauschiii lost connection: Disconnected
[11:37:18] [Server thread/ERROR]: Could not pass event PlayerQuitEvent to FastAsyncWorldEdit v19.11.13-5505943-1282-22.3.5
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1620]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1620]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1620]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.PlayerList.disconnect(PlayerList.java:429) ~[patched_1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1167) ~[patched_1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.NetworkManager.handleDisconnection(NetworkManager.java:361) ~[patched_1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:184) ~[patched_1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:948) ~[patched_1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1620]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
Caused by: java.lang.NullPointerException: The world was unloaded and the reference is unavailable
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:787) ~[patched_1.12.2.jar:git-Paper-1620]
	at com.sk89q.worldedit.bukkit.BukkitWorld.getWorld(BukkitWorld.java:212) ~[?:?]
	at com.sk89q.worldedit.bukkit.BukkitWorld.getName(BukkitWorld.java:217) ~[?:?]
	at com.boydti.fawe.bukkit.FaweBukkit.getWorldName(FaweBukkit.java:477) ~[?:?]
	at com.sk89q.worldedit.LocalSession.saveHistoryNegativeIndex(LocalSession.java:253) ~[?:?]
	at com.sk89q.worldedit.LocalSession.save(LocalSession.java:301) ~[?:?]
	at com.sk89q.worldedit.session.SessionManager.save(SessionManager.java:229) ~[?:?]
	at com.sk89q.worldedit.session.SessionManager.remove(SessionManager.java:281) ~[?:?]
	at com.sk89q.worldedit.WorldEdit.removeSession(WorldEdit.java:218) ~[?:?]
	at com.boydti.fawe.object.FawePlayer.unregister(FawePlayer.java:660) ~[?:?]
	at com.boydti.fawe.bukkit.FaweBukkit.onPlayerQuit(FaweBukkit.java:604) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor241.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1620]
	... 12 more

**Comment by NotMyFault** [comment]
1.12 is outdated and not the "latest version". If this issue occurs on supported versions, like 1.16 to 1.19, feel free to raise a new issue.

**Comment by hyperspacepilot** [comment]
This is the same problem on a 1.18 server with a version very close to the newest:

[21:09:34] [Server thread/INFO]: Fruchtiii issued server command: //paste
[21:09:34] [ForkJoinPool-7-worker-569/WARN]: java.lang.NullPointerException: The world was unloaded and the reference is unavailable
[21:09:34] [ForkJoinPool-7-worker-569/WARN]: 	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:907)
[21:09:34] [ForkJoinPool-7-worker-569/WARN]: 	at FastAsyncWorldEdit-Bukkit-2.1.1.jar//com.sk89q.worldedit.bukkit.BukkitWorld.getWorld(BukkitWorld.java:185)
[21:09:34] [ForkJoinPool-7-worker-569/WARN]: 	at FastAsyncWorldEdit-Bukkit-2.1.1.jar//com.sk89q.worldedit.bukkit.BukkitWorld.getName(BukkitWorld.java:206)
[21:09:34] [ForkJoinPool-7-worker-569/WARN]: 	at FastAsyncWorldEdit-Bukkit-2.1.1.jar//com.sk89q.worldedit.LocalSession.saveHistoryNegativeIndex(LocalSession.java:309)
[21:09:34] [ForkJoinPool-7-worker-569/WARN]: 	at FastAsyncWorldEdit-Bukkit-2.1.1.jar//com.sk89q.worldedit.LocalSession.loadSessionHistoryFromDisk(LocalSession.java:235)
[21:09:34] [ForkJoinPool-7-worker-569/WARN]: 	at FastAsyncWorldEdit-Bukkit-2.1.1.jar//com.sk89q.worldedit.LocalSession.remember(LocalSession.java:535)
[21:09:34] [ForkJoinPool-7-worker-569/WARN]: 	at FastAsyncWorldEdit-Bukkit-2.1.1.jar//com.sk89q.worldedit.LocalSession.remember(LocalSession.java:437)
[21:09:34] [ForkJoinPool-7-worker-569/WARN]: 	at FastAsyncWorldEdit-Bukkit-2.1.1.jar//com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandTask(PlatformCommandManager.java:803)
[21:09:34] [ForkJoinPool-7-worker-569/WARN]: 	at FastAsyncWorldEdit-Bukkit-2.1.1.jar//com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandOnCurrentThread(PlatformCommandManager.java:732)
[21:09:34] [ForkJoinPool-7-worker-569/WARN]: 	at FastAsyncWorldEdit-Bukkit-2.1.1.jar//com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommand$13(PlatformCommandManager.java:702)
[21:09:34] [ForkJoinPool-7-worker-569/WARN]: 	at FastAsyncWorldEdit-Bukkit-2.1.1.jar//com.sk89q.worldedit.extension.platform.AbstractPlayerActor.lambda$runAction$1(AbstractPlayerActor.java:672)
[21:09:34] [ForkJoinPool-7-worker-569/WARN]: 	at FastAsyncWorldEdit-Bukkit-2.1.1.jar//com.fastasyncworldedit.core.util.task.AsyncNotifyQueue.lambda$run$0(AsyncNotifyQueue.java:28)
[21:09:34] [ForkJoinPool-7-worker-569/WARN]: 	at FastAsyncWorldEdit-Bukkit-2.1.1.jar//com.fastasyncworldedit.core.util.task.AsyncNotifyQueue.lambda$call$1(AsyncNotifyQueue.java:45)
[21:09:34] [ForkJoinPool-7-worker-569/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1428)
[21:09:34] [ForkJoinPool-7-worker-569/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[21:09:34] [ForkJoinPool-7-worker-569/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[21:09:34] [ForkJoinPool-7-worker-569/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[21:09:34] [ForkJoinPool-7-worker-569/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[21:09:34] [ForkJoinPool-7-worker-569/WARN]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

**Comment by dordsor21** [comment]
That's not a remotely up to date FAWE version creating that error though? It's been fixed since build 168 (we're on 215). The bug will not be fixed in legacy versions ad they are unsupported
