### ISSUE TITLE
//rotate //paste with a multiple chunk selection causes error

### ISSUE THREAD

**Issue by zeronerve** [IntellectualSites/FastAsyncWorldEdit#453]
When we copy, rotate and paste large areas (across multiple chunks) we get the error, below. But a small selection inside 1 chunk works fine. This is inside a PS 5.10.4 plot.

[11:54:02 WARN]: java.lang.NullPointerException [11:54:02 WARN]: at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:57) [11:54:02 WARN]: at java.base/jdk.internal.reflect.UnsafeShortFieldAccessorImpl.set(UnsafeShortFieldAccessorImpl.java:75) [11:54:02 WARN]: at java.base/java.lang.reflect.Field.set(Field.java:780) [11:54:02 WARN]: at com.boydti.fawe.bukkit.adapter.mc1_15_2.BukkitGetBlocks_1_15_2.call(BukkitGetBlocks_1_15_2.java:287) [11:54:02 WARN]: at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.call(ChunkHolder.java:424) [11:54:02 WARN]: at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.call(ChunkHolder.java:412) [11:54:02 WARN]: at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.call(ChunkHolder.java:31) [11:54:02 WARN]: at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) [11:54:02 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [11:54:02 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [11:54:02 WARN]: at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by zeronerve** [comment]
Using build 214

**Comment by dordsor21** [comment]
Use latest build
