### ISSUE TITLE
All //anvil commands throw an exception.

### ISSUE THREAD

**Issue by jeuxjeux20** [IntellectualSites/FastAsyncWorldEdit#455]
# Bug report for FastAsyncWorldEdit 1.15.2

**FastAsyncWorldEdit Configuration Files:** 
`/fawe debugpaste` gives me a path that doesn't exist.

`latest.log`: https://gist.github.com/jeuxjeux20/3f290f0cea34a8d6536b2e460b741a38
`config.yml` & `config-legacy.yml`: https://gist.github.com/jeuxjeux20/fc527dd116d146a7a6ad070a299032e9

**FastAsyncWorldEdit Version Number:** 
```
 ------------------ Platforms ------------------
* Bukkit-Official(1.15-217;4f2b0e6)

---------------- Capabilities ----------------
GAME_HOOKS: Bukkit-Official
CONFIGURATION: Bukkit-Official
USER_COMMANDS: Bukkit-Official
PERMISSIONS: Bukkit-Official
WORLDEDIT_CUI: Bukkit-Official
WORLD_EDITING: Bukkit-Official
```

**Spigot/Paper Version Number:** 
`git-Spigot-a03b1fd-bbe3d58 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)`

**Description of the problem:**
Upon doing any `//anvil` command on any world, an exception gets thrown:
```
[11:01:09] [Craft Scheduler Thread - 0/ERROR]: An unexpected error while handling a WorldEdit command
java.lang.IllegalStateException: No injected value for folder (type Key{type=java.lang.String, annotationWrapper=NullAnnotationWrapper})
	at org.enginehub.piston.internal.RegistrationUtil.lambda$requireOptional$0(RegistrationUtil.java:37) ~[?:?]
	at java.util.Optional.orElseThrow(Optional.java:401) ~[?:?]
	at org.enginehub.piston.internal.RegistrationUtil.requireOptional(RegistrationUtil.java:36) ~[?:?]
	at com.boydti.fawe.command.AnvilCommandsRegistration.extract$folder(AnvilCommandsRegistration.java:654) ~[?:?]
	at com.boydti.fawe.command.AnvilCommandsRegistration.cmd$deleteallunvisited(AnvilCommandsRegistration.java:369) ~[?:?]
	at org.enginehub.piston.CommandManager.execute(CommandManager.java:157) ~[?:?]
	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommandOnCurrentThread$15(PlatformCommandManager.java:679) ~[?:?]
	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandTask(PlatformCommandManager.java:695) ~[?:?]
	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandOnCurrentThread(PlatformCommandManager.java:681) ~[?:?]
	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommand$13(PlatformCommandManager.java:651) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:81) [spigot.jar:git-Spigot-a03b1fd-bbe3d58]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot.jar:git-Spigot-a03b1fd-bbe3d58]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
```
**How to replicate**:
1. Go to any world
2. Run a `//anvil` command, such as `//anvil deleteallunvisited` (run this command in a test world!).

**Plugins being used on the server:**
`Plugins (9): LuckPerms, PlugMan, FastAsyncWorldEdit, Vault, AutoReload, Multiverse-Core, ProtocolLib, LoupsGarous, WorldEdit`
(Note: `LoupsGarous` is a plugin I made and not publicly available, just in case you may try to search its name on google, there are other plugins with the same name :smile:) 

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.15.2](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
No, bad stalebot.

**Comment by NotMyFault** [comment]
Anvil commands are not implemented at the moment (and probably won't come back anytime soon) as they've caused many irreversible issues in versions prior to 1.13.
