### ISSUE TITLE
Error by copying great areas

### ISSUE THREAD

**Issue by therealatsuga** [IntellectualSites/FastAsyncWorldEdit#480]
# Bug report for FastAsyncWorldEdit 1.15.2

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 
Please see below, there are to many IP's and so on I would have to clear

**[REQUIRED] FastAsyncWorldEdit Version Number:** 
Bukkit Official 1.15-246

**[REQUIRED] Spigot/Paper Version Number:** 
Paper 305

**[REQUIRED] Description of the problem:**
[08:39:24 INFO]: atsuga issued server command: //copy
[08:39:25 ERROR]: An unexpected error while handling a WorldEdit command
java.lang.IllegalStateException: Asynchronous ChunkMapDistance::addPriorityTicket!
at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[patched_1.15.2.jar:git-Paper-305]
at net.minecraft.server.v1_15_R1.ChunkMapDistance.addPriorityTicket(ChunkMapDistance.java:202) ~[patched_1.15.2.jar:git-Paper-305]
at net.minecraft.server.v1_15_R1.ChunkMapDistance.markHighPriority(ChunkMapDistance.java:198) ~[patched_1.15.2.jar:git-Paper-305]
at net.minecraft.server.v1_15_R1.ChunkProviderServer.markHighPriority(ChunkProviderServer.java:441) ~[patched_1.15.2.jar:git-Paper-305]
at org.bukkit.craftbukkit.v1_15_R1.CraftWorld.getChunkAtAsync(CraftWorld.java:2477) ~[patched_1.15.2.jar:git-Paper-305]
at org.bukkit.World.getChunkAtAsync(World.java:702) ~[patched_1.15.2.jar:git-Paper-305]
at com.boydti.fawe.bukkit.adapter.mc1_15_2.BukkitAdapter_1_15_2.ensureLoaded(BukkitAdapter_1_15_2.java:149) ~[?:?]
at com.boydti.fawe.bukkit.adapter.mc1_15_2.BukkitGetBlocks_1_15_2.ensureLoaded(BukkitGetBlocks_1_15_2.java:239) ~[?:?]
at com.boydti.fawe.bukkit.adapter.mc1_15_2.BukkitGetBlocks_1_15_2.getChunk(BukkitGetBlocks_1_15_2.java:637) ~[?:?]
at com.boydti.fawe.bukkit.adapter.mc1_15_2.BukkitGetBlocks_1_15_2.getSections(BukkitGetBlocks_1_15_2.java:623) ~[?:?]
at com.boydti.fawe.bukkit.adapter.mc1_15_2.BukkitGetBlocks_1_15_2.hasSection(BukkitGetBlocks_1_15_2.java:646) ~[?:?]
at com.boydti.fawe.bukkit.adapter.mc1_15_2.BukkitGetBlocks_1_15_2.trim(BukkitGetBlocks_1_15_2.java:657) ~[?:?]
at com.boydti.fawe.beta.implementation.chunk.ChunkHolder$4.getFullBlock(ChunkHolder.java:303) ~[?:?]
at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.getFullBlock(ChunkHolder.java:481) ~[?:?]
at com.boydti.fawe.beta.implementation.IChunkExtent.getFullBlock(IChunkExtent.java:50) ~[?:?]
at com.sk89q.worldedit.extent.InputExtent.getFullBlock(InputExtent.java:65) ~[?:?]
at com.sk89q.worldedit.extent.PassthroughExtent.getFullBlock(PassthroughExtent.java:191) ~[?:?]
at com.sk89q.worldedit.extent.PassthroughExtent.getFullBlock(PassthroughExtent.java:191) ~[?:?]
at com.boydti.fawe.object.function.block.SimpleBlockCopy.apply(SimpleBlockCopy.java:21) ~[?:?]
at com.sk89q.worldedit.function.visitor.RegionVisitor.resume(RegionVisitor.java:66) ~[?:?]
at com.sk89q.worldedit.function.operation.Operations.completeBlindly(Operations.java:76) ~[?:?]
at com.sk89q.worldedit.function.operation.ForwardExtentCopy.resume(ForwardExtentCopy.java:397) ~[?:?]
at com.sk89q.worldedit.function.operation.Operations.completeLegacy(Operations.java:57) ~[?:?]
at com.sk89q.worldedit.command.ClipboardCommands.copy(ClipboardCommands.java:150) ~[?:?]
at com.sk89q.worldedit.command.ClipboardCommandsRegistration.cmd$_copy(ClipboardCommandsRegistration.java:273) ~[?:?]
at org.enginehub.piston.CommandManager.execute(CommandManager.java:157) ~[?:?]
at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommandOnCurrentThread$15(PlatformCommandManager.java:679) ~[?:?]
at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandTask(PlatformCommandManager.java:695) ~[?:?]
at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandOnCurrentThread(PlatformCommandManager.java:681) ~[?:?]
at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommand$13(PlatformCommandManager.java:651) ~[?:?]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-305]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.2.jar:git-Paper-305]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.2.jar:git-Paper-305]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]

**How to replicate**:
Try to copy more then 4-5 Chunks

**Plugins being used on the server:**

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.15.2](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by TheoRetisch1** [comment]
I'm glad someone else is experiencing the same problem. I also tried to report it in #435, but nobody could reproduce the bug :/. You could try if you can copy the same area with //lazycopy :)

**Comment by aurorasmiles** [comment]
Copying works fine for me. Your configuration files would be really useful here.

**Comment by therealatsuga** [comment]
https://athion.net/ISPaster/paste/view/aff988f50ba940049ed8b95c2c567419

It is the lobby, there is no need for much performance. I just wanted to create a schematica to save it.

**Comment by dordsor21** [comment]
Try the latest paper build. This is not technically a FAWE issue. If it persists on latest paper, do not make an issue there as they will ignore it because you're using FAWE, and some of the people at paper are a bit petty like that. Let me know, give the new error, and I shall look into it.
