### ISSUE TITLE
//undo not working

### ISSUE THREAD

**Issue by Fchen48** [IntellectualSites/FastAsyncWorldEdit#505]
# Bug report for FastAsyncWorldEdit 1.15.2

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 

https://athion.net/ISPaster/paste/view/3810eb4351e34be3af2f4f8b5452648f

**[REQUIRED] FastAsyncWorldEdit Version Number:** 

1.15.2-258

**[REQUIRED] Spigot/Paper Version Number:** 

This server is running Paper version git-Paper-350 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
Previous version: git-Paper-155 (MC: 1.15.2)
You are running the latest version

**[REQUIRED] Description of the problem:**

I copy some object, paste it somewhere else (on the same map), don't get happy with the position and want to undo the paste and FAWE says nothing left to undo. 
Server restart doesn't fix the problem.

**How to replicate**:

Copy something, paste it, try to undo.

**Plugins being used on the server:**

ActivityTracking, BuildingUtilities, EthyriaCore, EthyriaEssentials, EthyriaPermission, EthyriaPermissionResolver, EthyriaWorlds, FastAsyncWorldEdit, goBrush, goPaint, PlotSquared, ProtocolLib, Speedboost, VoxelSniper, WeBrush*, WorldEdit

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.15.2](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by aurorasmiles** [comment]
Seems like an issue with the latest build. Use 257 in the meantime, it works fine there @Fchen48

**Comment by aurorasmiles** [comment]
Assuming this is related:
`[10:44:42 INFO]: AuroraRainbow issued server command: //paste
[10:44:43 WARN]: [WorldEdit] Plugin WorldEdit v1.15-258;56f29a3 generated an exception while executing task 4231
java.lang.NullPointerException: null
        at com.boydti.fawe.util.MainUtil$1.run(MainUtil.java:77) ~[?:?]
        at com.boydti.fawe.util.MainUtil$1.run(MainUtil.java:74) ~[?:?]
        at com.boydti.fawe.object.RunnableVal.accept(RunnableVal.java:35) ~[?:?]
        at com.boydti.fawe.util.MainUtil$2.visitFile(MainUtil.java:89) ~[?:?]
        at com.boydti.fawe.util.MainUtil$2.visitFile(MainUtil.java:85) ~[?:?]
        at java.nio.file.Files.walkFileTree(Files.java:2670) ~[?:1.8.0_242]
        at java.nio.file.Files.walkFileTree(Files.java:2742) ~[?:1.8.0_242]
        at com.boydti.fawe.util.MainUtil.traverse(MainUtil.java:85) ~[?:?]
        at com.boydti.fawe.util.MainUtil.getTotalSize(MainUtil.java:74) ~[?:?]
        at com.sk89q.worldedit.LocalSession.loadHistoryChangeSets(LocalSession.java:255) ~[?:?]
        at com.sk89q.worldedit.LocalSession.loadSessionHistoryFromDisk(LocalSession.java:227) ~[?:?]
        at com.sk89q.worldedit.LocalSession.remember(LocalSession.java:502) ~[?:?]
        at com.sk89q.worldedit.LocalSession.remember(LocalSession.java:409) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandTask(PlatformCommandManager.java:743) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandOnCurrentThread(PlatformCommandManager.java:681) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommand$13(PlatformCommandManager.java:651) ~[?:?]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.15.2.jar:git-Paper-350]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.2.jar:git-Paper-350]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.2.jar:git-Paper-350]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
[10:44:47 INFO]: AuroraRainbow issued server command: //undo
`

**Comment by MicleBrick** [comment]
getting this issue too, was about to post a report but found this, so I'll just post it here

# Bug report for FastAsyncWorldEdit 1.15.2

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 
https://athion.net/ISPaster/paste/view/c4e20ed4bec245bd845f253170a85d54

**[REQUIRED] FastAsyncWorldEdit Version Number:** 

![image](https://user-images.githubusercontent.com/6323125/84566378-80e09180-ad3e-11ea-93bc-e425e6e83c0d.png)

**[REQUIRED] Spigot/Paper Version Number:** 
![image](https://user-images.githubusercontent.com/6323125/84566382-8a69f980-ad3e-11ea-9c85-6ec02a12ede1.png)

**[REQUIRED] Description of the problem:**
Fresh installed FAWE, getting a nullpointerexception on MainUtils.java line 77 that appears to be preventing history from working

**How to replicate**:
It seems to happen on a fresh install for me, tried removing WorldEdit & FastAsyncWorldEdit folders but it still happened

**Comment by aurorasmiles** [comment]
Yes, please use build 257 in the meantime

**Comment by MicleBrick** [comment]
thanks, that worked

**Comment by aurorasmiles** [comment]
We reverted the changes in the meantime, and the latest build now works correctly again
