### ISSUE TITLE
(1.16) NullPointerException using //fixlighting, //setblocklight 'Temporarily not working'

### ISSUE THREAD

**Issue by RickyB98** [IntellectualSites/FastAsyncWorldEdit#531]
# Bug report for FastAsyncWorldEdit 1.15.2

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** https://athion.net/ISPaster/paste/view/28d34bb1feab44908018f2f4e7ce76ec

**[REQUIRED] FastAsyncWorldEdit Version Number:** 
[17:53:16 INFO]: FastAsyncWorldEdit-293 created by Empire92
[17:53:16 INFO]: FAWE version:
- Date Jul 6, 2020 12:00:00 AM
- Commit f929219f
- Build 293
- Platform Bukkit
[17:53:16 INFO]: Wiki: https://wiki.intellectualsites.com/FastAsyncWorldEdit/index
[17:53:16 INFO]: ------------------ Platforms ------------------
* Bukkit-Official(1.16-293;6d6de61)
[17:53:16 INFO]: ---------------- Capabilities ----------------
GAME_HOOKS: Bukkit-Official
CONFIGURATION: Bukkit-Official
USER_COMMANDS: Bukkit-Official
PERMISSIONS: Bukkit-Official
WORLDEDIT_CUI: Bukkit-Official
WORLD_EDITING: Bukkit-Official

**[REQUIRED] Spigot/Paper Version Number:** 
[17:53:50 INFO]: This server is running Paper version git-Paper-79 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
[17:53:50 INFO]: Checking version, please wait...
[17:53:51 INFO]: Previous version: git-Paper-313 (MC: 1.15.2)
[17:53:51 INFO]: You are 7 version(s) behind

**[REQUIRED] Description of the problem:** //fixlighting throws NullPointerException, below is the stacktrace. Also, //setblocklight is 'Temporarily not working' with no exceptions thrown.

[17:50:45 INFO]: RickyB98 issued server command: //fixlighting
[17:50:45 ERROR]: An unexpected error while handling a WorldEdit command
java.lang.NullPointerException: null
at com.boydti.fawe.bukkit.adapter.mc1_16_1.BukkitGetBlocks_1_16_1.getEmmittedLight(BukkitGetBlocks_1_16_1.java:145) ~[?:?]
at com.boydti.fawe.beta.implementation.chunk.ChunkHolder$1.getEmmittedLight(ChunkHolder.java:236) ~[?:?]
at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.getEmmittedLight(ChunkHolder.java:824) ~[?:?]
at com.boydti.fawe.beta.implementation.lighting.NMSRelighter.updateBlockLight(NMSRelighter.java:199) ~[?:?]
at com.boydti.fawe.beta.implementation.lighting.NMSRelighter.fixBlockLighting(NMSRelighter.java:333) ~[?:?]
at com.boydti.fawe.FaweAPI.fixLighting(FaweAPI.java:388) ~[?:?]
at com.sk89q.worldedit.command.RegionCommands.fixLighting(RegionCommands.java:151) ~[?:?]
at com.sk89q.worldedit.command.RegionCommandsRegistration.cmd$_fixlighting(RegionCommandsRegistration.java:600) ~[?:?]
at org.enginehub.piston.CommandManager.execute(CommandManager.java:157) ~[?:?]
at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommandOnCurrentThread$15(PlatformCommandManager.java:681) ~[?:?]
at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandTask(PlatformCommandManager.java:697) ~[?:?]
at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandOnCurrentThread(PlatformCommandManager.java:683) ~[?:?]
at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommand$13(PlatformCommandManager.java:653) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.1.jar:git-Paper-79]
at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.1.jar:git-Paper-79]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.1.jar:git-Paper-79]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

**How to replicate**: pretty much just run //fixlighting or //setblocklight - the latter was giving some other message when CoreProtect integration was enabled, but I disabled it and I still can't make it work.

**Plugins being used on the server:** BuycraftX, ChatControl, Citizens, CoreProtect, Essentials, EssentialsAntiBuild, EssentialsProtect, EssentialsSpawn, FastAsyncWorldEdit, goBrush, goPaint, GriefPrevention, LuckPerms, PlaceholderAPI, PlugMan, ProtocolLib, Vault, ViaBackwards, ViaVersion, VoxelSniper, WorldBorder, WorldEdit, WorldGuard

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.15.2](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by ronsuper** [comment]
Error also occurs on spigot 1.16.1:

[16:29:50] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-05da6fa-75a2fb8 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)


NullPointer:
[16:39:54] [Server thread/INFO]: user issued server command: //fixlighting
[16:40:17] [Craft Scheduler Thread - 7/ERROR]: An unexpected error while handling a WorldEdit command
java.lang.NullPointerException: null
        at com.boydti.fawe.bukkit.adapter.mc1_16_1.BukkitGetBlocks_1_16_1.getEmmittedLight(BukkitGetBlocks_1_16_1.java:145) ~[?:?]
        at com.boydti.fawe.beta.implementation.chunk.ChunkHolder$2.getEmmittedLight(ChunkHolder.java:344) ~[?:?]
        at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.getEmmittedLight(ChunkHolder.java:824) ~[?:?]
        at com.boydti.fawe.beta.implementation.chunk.ChunkHolder$4.getEmmittedLight(ChunkHolder.java:591) ~[?:?]
        at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.getEmmittedLight(ChunkHolder.java:824) ~[?:?]
        at com.boydti.fawe.beta.implementation.lighting.NMSRelighter.updateBlockLight(NMSRelighter.java:199) ~[?:?]
        at com.boydti.fawe.beta.implementation.lighting.NMSRelighter.fixBlockLighting(NMSRelighter.java:333) ~[?:?]
        at com.boydti.fawe.FaweAPI.fixLighting(FaweAPI.java:385) ~[?:?]
        at com.sk89q.worldedit.command.RegionCommands.fixLighting(RegionCommands.java:151) ~[?:?]
        at com.sk89q.worldedit.command.RegionCommandsRegistration.cmd$_fixlighting(RegionCommandsRegistration.java:600) ~[?:?]
        at org.enginehub.piston.CommandManager.execute(CommandManager.java:157) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommandOnCurrentThread$15(PlatformCommandManager.java:682) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandTask(PlatformCommandManager.java:698) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandOnCurrentThread(PlatformCommandManager.java:684) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommand$13(PlatformCommandManager.java:654) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:81) [spigot.jar:git-Spigot-05da6fa-75a2fb8]
        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot.jar:git-Spigot-05da6fa-75a2fb8]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by MissPotato** [comment]
This is still happening on version 302, with paperMC version 98.

**Comment by MattBDev** [comment]
" //setblocklight is 'Temporarily not working' with no exceptions thrown." Literally not a bug. No matter what we do with this command people keep trying to report it as a bug. It doesn't work and we don't have a timeline on when it will be back.

**Comment by MissPotato** [comment]
I think the issue is more so that //setblocklight is reporting that it's "Temporarily not working" 

While //fixlighting is just throwing a null error which doesn't tell the user what's going on, and it actually tries to do something on the server as the server freezes during the execution.

**Comment by RickyB98** [comment]
A more eloquent explanation than 'Temporarily not working' might achieve the goal of stopping us dumb users reporting this as an error. Additionally, no indication is present in the documentation about the known missing functionality for the latest versions.

The fixlighting command bug, on the other hand, should still be taken into consideration.
