### ISSUE TITLE
Null Pointer Exception

### ISSUE THREAD

**Issue by SemperEtAnte** [IntellectualSites/FastAsyncWorldEdit#565]
I trying to make a copy of a region (via plugin). But got this error:

```
java.lang.NullPointerException: null
        at com.boydti.fawe.bukkit.adapter.mc1161.FAWEWorldNativeAccess1161.setBlock(FAWEWorldNativeAccess1161.java:176) ~[?:?]
        at com.sk89q.worldedit.bukkit.BukkitWorld.setBlock(BukkitWorld.java:513) ~[?:?]
        at com.sk89q.worldedit.world.AbstractWorld.setBlock(AbstractWorld.java:59) ~[?:?]
        at com.boydti.fawe.object.extent.BlockTranslateExtent.setBlock(BlockTranslateExtent.java:32) ~[?:?]
        at com.boydti.fawe.object.function.block.SimpleBlockCopy.apply(SimpleBlockCopy.java:20) ~[?:?]
        at com.sk89q.worldedit.function.visitor.RegionVisitor.resume(RegionVisitor.java:66) ~[?:?]
        at com.sk89q.worldedit.function.operation.Operations.completeBlindly(Operations.java:76) ~[?:?]
        at com.sk89q.worldedit.function.operation.ForwardExtentCopy.resume(ForwardExtentCopy.java:397) ~[?:?]
        at com.sk89q.worldedit.function.operation.Operations.completeLegacy(Operations.java:57) ~[?:?]
        at ru.SemperAnte.FreeServer.VillageUpgrade.VillageUtils.fillRegion(VillageUtils.java:120) ~[?:?]
        at ru.SemperAnte.FreeServer.VillageUpgrade.VillageUtils.upgradeVillageLevel(VillageUtils.java:85) ~[?:?]
        at ru.SemperAnte.FreeServer.VillageUpgrade.Command.CommandManager.lambda$upgrade$3(CommandManager.java:84) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.1.jar:git-Paper-133]
        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.1.jar:git-Paper-133]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.1.jar:git-Paper-133]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
        at java.lang.Thread.run(Thread.java:832) [?:?]
```
Code of plugin:
```
            Region old = new CuboidRegion(world, oldStart, oldEnd);
            clip = es.lazyCopy(old);
            clip.paste(world, start.add(10, 0, 10), true, true, false);
            es.flushQueue();
```
And was trying to write:
```
            ForwardExtentCopy copy = new ForwardExtentCopy(es, old, world, start.add(10, 0, 10));
            copy.setCopyingEntities(true);
            copy.setCopyingBiomes(false);
            Operations.completeLegacy(copy);
```

**Comment by dordsor21** [comment]
funky queue stuff that shouldn't be possible anymore
