### ISSUE TITLE
Any world edit commands throwing this error

### ISSUE THREAD

**Issue by TheCyberShocker** [IntellectualSites/FastAsyncWorldEdit#580]
[21:43:13 INFO]: smudgge issued server command: //cyl sand 10
[21:43:13 WARN]: java.lang.NullPointerException
[21:43:13 WARN]: at com.sk89q.worldedit.bukkit.BukkitWorld.get(BukkitWorld.java:589)
[21:43:13 WARN]: at com.sk89q.worldedit.bukkit.BukkitWorld.get(BukkitWorld.java:78)
[21:43:13 WARN]: at com.boydti.fawe.beta.implementation.cache.ChunkCache.newChunk(ChunkCache.java:43)
[21:43:13 WARN]: at com.boydti.fawe.beta.implementation.cache.ChunkCache.get(ChunkCache.java:37)
[21:43:13 WARN]: at com.boydti.fawe.beta.implementation.cache.ChunkCache.get(ChunkCache.java:12)
[21:43:13 WARN]: at com.boydti.fawe.beta.implementation.queue.SingleThreadQueueExtent.getCachedGet(SingleThreadQueueExtent.java:78)
[21:43:13 WARN]: at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.newWrappedGet(ChunkHolder.java:707)
[21:43:13 WARN]: at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.getOrCreateGet(ChunkHolder.java:677)
[21:43:13 WARN]: at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.call(ChunkHolder.java:737)
[21:43:13 WARN]: at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.call(ChunkHolder.java:729)
[21:43:13 WARN]: at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.call(ChunkHolder.java:31)
[21:43:13 WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[21:43:13 WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[21:43:13 WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[21:43:13 WARN]: at java.lang.Thread.run(Thread.java:748)
[21:43:13 WARN]: java.lang.NullPointerException
[21:43:13 WARN]: at com.sk89q.worldedit.bukkit.BukkitWorld.get(BukkitWorld.java:589)
[21:43:13 WARN]: at com.sk89q.worldedit.bukkit.BukkitWorld.get(BukkitWorld.java:78)
[21:43:13 WARN]: at com.boydti.fawe.beta.implementation.cache.ChunkCache.newChunk(ChunkCache.java:43)
[21:43:13 WARN]: at com.boydti.fawe.beta.implementation.cache.ChunkCache.get(ChunkCache.java:37)
[21:43:13 WARN]: at com.boydti.fawe.beta.implementation.cache.ChunkCache.get(ChunkCache.java:12)
[21:43:13 WARN]: at com.boydti.fawe.beta.implementation.queue.SingleThreadQueueExtent.getCachedGet(SingleThreadQueueExtent.java:78)
[21:43:13 WARN]: at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.newWrappedGet(ChunkHolder.java:707)
[21:43:13 WARN]: at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.getOrCreateGet(ChunkHolder.java:677)
[21:43:13 WARN]: at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.call(ChunkHolder.java:737)
[21:43:13 WARN]: at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.call(ChunkHolder.java:729)
[21:43:13 WARN]: at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.call(ChunkHolder.java:31)
[21:43:13 WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[21:43:13 WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[21:43:13 WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[21:43:13 WARN]: at java.lang.Thread.run(Thread.java:748)
[21:43:13 WARN]: java.util.concurrent.ExecutionException: java.lang.NullPointerException
[21:43:13 WARN]: at java.util.concurrent.FutureTask.report(FutureTask.java:122)
[21:43:13 WARN]: at java.util.concurrent.FutureTask.get(FutureTask.java:192)
[21:43:13 WARN]: at com.boydti.fawe.beta.implementation.queue.SingleThreadQueueExtent.pollSubmissions(SingleThreadQueueExtent.java:278)
[21:43:13 WARN]: at com.boydti.fawe.beta.implementation.queue.SingleThreadQueueExtent.flush(SingleThreadQueueExtent.java:332)
[21:43:13 WARN]: at com.boydti.fawe.beta.IQueueExtent.commit(IQueueExtent.java:113)
[21:43:13 WARN]: at com.sk89q.worldedit.extent.PassthroughExtent.commit(PassthroughExtent.java:209)
[21:43:13 WARN]: at com.sk89q.worldedit.extent.PassthroughExtent.commit(PassthroughExtent.java:209)
[21:43:13 WARN]: at com.sk89q.worldedit.EditSession.flushQueue(EditSession.java:1035)
[21:43:13 WARN]: at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandTask(PlatformCommandManager.java:745)
[21:43:13 WARN]: at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandOnCurrentThread(PlatformCommandManager.java:684)
[21:43:13 WARN]: at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommand$13(PlatformCommandManager.java:654)
[21:43:13 WARN]: at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99)
[21:43:13 WARN]: at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[21:43:13 WARN]: at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[21:43:13 WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[21:43:13 WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[21:43:13 WARN]: at java.lang.Thread.run(Thread.java:748)
[21:43:13 WARN]: Caused by: java.lang.NullPointerException
[21:43:13 WARN]: at com.sk89q.worldedit.bukkit.BukkitWorld.get(BukkitWorld.java:589)
[21:43:13 WARN]: at com.sk89q.worldedit.bukkit.BukkitWorld.get(BukkitWorld.java:78)
[21:43:13 WARN]: at com.boydti.fawe.beta.implementation.cache.ChunkCache.newChunk(ChunkCache.java:43)
[21:43:13 WARN]: at com.boydti.fawe.beta.implementation.cache.ChunkCache.get(ChunkCache.java:37)
[21:43:13 WARN]: at com.boydti.fawe.beta.implementation.cache.ChunkCache.get(ChunkCache.java:12)
[21:43:13 WARN]: at com.boydti.fawe.beta.implementation.queue.SingleThreadQueueExtent.getCachedGet(SingleThreadQueueExtent.java:78)
[21:43:13 WARN]: at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.newWrappedGet(ChunkHolder.java:707)
[21:43:13 WARN]: at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.getOrCreateGet(ChunkHolder.java:677)
[21:43:13 WARN]: at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.call(ChunkHolder.java:737)
[21:43:13 WARN]: at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.call(ChunkHolder.java:729)
[21:43:13 WARN]: at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.call(ChunkHolder.java:31)
[21:43:13 WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[21:43:13 WARN]: ... 3 more
[21:43:13 WARN]: java.lang.NullPointerException
[21:43:13 WARN]: at com.sk89q.worldedit.bukkit.BukkitWorld.get(BukkitWorld.java:589)
[21:43:13 WARN]: at com.sk89q.worldedit.bukkit.BukkitWorld.get(BukkitWorld.java:78)
[21:43:13 WARN]: at com.boydti.fawe.beta.implementation.cache.ChunkCache.newChunk(ChunkCache.java:43)
[21:43:13 WARN]: at com.boydti.fawe.beta.implementation.cache.ChunkCache.get(ChunkCache.java:37)
[21:43:13 WARN]: at com.boydti.fawe.beta.implementation.cache.ChunkCache.get(ChunkCache.java:12)
[21:43:13 WARN]: at com.boydti.fawe.beta.implementation.queue.SingleThreadQueueExtent.getCachedGet(SingleThreadQueueExtent.java:78)
[21:43:13 WARN]: at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.newWrappedGet(ChunkHolder.java:707)
[21:43:13 WARN]: at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.getOrCreateGet(ChunkHolder.java:677)
[21:43:13 WARN]: at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.call(ChunkHolder.java:737)
[21:43:13 WARN]: at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.call(ChunkHolder.java:729)
[21:43:13 WARN]: at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.call(ChunkHolder.java:31)
[21:43:13 WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[21:43:13 WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[21:43:13 WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[21:43:13 WARN]: at java.lang.Thread.run(Thread.java:748)
[21:43:13 WARN]: java.util.concurrent.ExecutionException: java.lang.NullPointerException
[21:43:13 WARN]: at java.util.concurrent.FutureTask.report(FutureTask.java:122)
[21:43:13 WARN]: at java.util.concurrent.FutureTask.get(FutureTask.java:192)
[21:43:13 WARN]: at com.boydti.fawe.beta.implementation.queue.SingleThreadQueueExtent.pollSubmissions(SingleThreadQueueExtent.java:278)
[21:43:13 WARN]: at com.boydti.fawe.beta.implementation.queue.SingleThreadQueueExtent.flush(SingleThreadQueueExtent.java:332)
[21:43:13 WARN]: at com.boydti.fawe.beta.IQueueExtent.commit(IQueueExtent.java:113)
[21:43:13 WARN]: at com.sk89q.worldedit.extent.PassthroughExtent.commit(PassthroughExtent.java:209)
[21:43:13 WARN]: at com.sk89q.worldedit.extent.PassthroughExtent.commit(PassthroughExtent.java:209)
[21:43:13 WARN]: at com.sk89q.worldedit.EditSession.flushQueue(EditSession.java:1035)
[21:43:13 WARN]: at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandTask(PlatformCommandManager.java:745)
[21:43:13 WARN]: at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandOnCurrentThread(PlatformCommandManager.java:684)
[21:43:13 WARN]: at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommand$13(PlatformCommandManager.java:654)
[21:43:13 WARN]: at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99)
[21:43:13 WARN]: at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[21:43:13 WARN]: at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[21:43:13 WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[21:43:13 WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[21:43:13 WARN]: at java.lang.Thread.run(Thread.java:748)
[21:43:13 WARN]: Caused by: java.lang.NullPointerException
[21:43:13 WARN]: at com.sk89q.worldedit.bukkit.BukkitWorld.get(BukkitWorld.java:589)
[21:43:13 WARN]: at com.sk89q.worldedit.bukkit.BukkitWorld.get(BukkitWorld.java:78)
[21:43:13 WARN]: at com.boydti.fawe.beta.implementation.cache.ChunkCache.newChunk(ChunkCache.java:43)
[21:43:13 WARN]: at com.boydti.fawe.beta.implementation.cache.ChunkCache.get(ChunkCache.java:37)
[21:43:13 WARN]: at com.boydti.fawe.beta.implementation.cache.ChunkCache.get(ChunkCache.java:12)
[21:43:13 WARN]: at com.boydti.fawe.beta.implementation.queue.SingleThreadQueueExtent.getCachedGet(SingleThreadQueueExtent.java:78)
[21:43:13 WARN]: at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.newWrappedGet(ChunkHolder.java:707)
[21:43:13 WARN]: at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.getOrCreateGet(ChunkHolder.java:677)
[21:43:13 WARN]: at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.call(ChunkHolder.java:737)
[21:43:13 WARN]: at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.call(ChunkHolder.java:729)
[21:43:13 WARN]: at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.call(ChunkHolder.java:31)
[21:43:13 WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[21:43:13 WARN]: ... 3 more
[21:43:13 WARN]: java.util.concurrent.ExecutionException: java.lang.NullPointerException
[21:43:13 WARN]: at java.util.concurrent.FutureTask.report(FutureTask.java:122)
[21:43:13 WARN]: at java.util.concurrent.FutureTask.get(FutureTask.java:192)
[21:43:13 WARN]: at com.boydti.fawe.beta.implementation.queue.SingleThreadQueueExtent.pollSubmissions(SingleThreadQueueExtent.java:278)
[21:43:13 WARN]: at com.boydti.fawe.beta.implementation.queue.SingleThreadQueueExtent.flush(SingleThreadQueueExtent.java:332)
[21:43:13 WARN]: at com.boydti.fawe.beta.IQueueExtent.commit(IQueueExtent.java:113)
[21:43:13 WARN]: at com.sk89q.worldedit.extent.PassthroughExtent.commit(PassthroughExtent.java:209)
[21:43:13 WARN]: at com.sk89q.worldedit.extent.PassthroughExtent.commit(PassthroughExtent.java:209)
[21:43:13 WARN]: at com.sk89q.worldedit.EditSession.flushQueue(EditSession.java:1035)
[21:43:13 WARN]: at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandTask(PlatformCommandManager.java:745)
[21:43:13 WARN]: at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandOnCurrentThread(PlatformCommandManager.java:684)
[21:43:13 WARN]: at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommand$13(PlatformCommandManager.java:654)
[21:43:13 WARN]: at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99)
[21:43:13 WARN]: at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[21:43:13 WARN]: at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[21:43:13 WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[21:43:13 WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[21:43:13 WARN]: at java.lang.Thread.run(Thread.java:748)
[21:43:13 WARN]: Caused by: java.lang.NullPointerException
[21:43:13 WARN]: at com.sk89q.worldedit.bukkit.BukkitWorld.get(BukkitWorld.java:589)
[21:43:13 WARN]: at com.sk89q.worldedit.bukkit.BukkitWorld.get(BukkitWorld.java:78)
[21:43:13 WARN]: at com.boydti.fawe.beta.implementation.cache.ChunkCache.newChunk(ChunkCache.java:43)
[21:43:13 WARN]: at com.boydti.fawe.beta.implementation.cache.ChunkCache.get(ChunkCache.java:37)
[21:43:13 WARN]: at com.boydti.fawe.beta.implementation.cache.ChunkCache.get(ChunkCache.java:12)
[21:43:13 WARN]: at com.boydti.fawe.beta.implementation.queue.SingleThreadQueueExtent.getCachedGet(SingleThreadQueueExtent.java:78)
[21:43:13 WARN]: at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.newWrappedGet(ChunkHolder.java:707)
[21:43:13 WARN]: at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.getOrCreateGet(ChunkHolder.java:677)
[21:43:13 WARN]: at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.call(ChunkHolder.java:737)
[21:43:13 WARN]: at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.call(ChunkHolder.java:729)
[21:43:13 WARN]: at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.call(ChunkHolder.java:31)
[21:43:13 WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[21:43:13 WARN]: ... 3 more
[21:43:13 WARN]: java.util.concurrent.ExecutionException: java.lang.NullPointerException
[21:43:13 WARN]: at java.util.concurrent.FutureTask.report(FutureTask.java:122)
[21:43:13 WARN]: at java.util.concurrent.FutureTask.get(FutureTask.java:192)
[21:43:13 WARN]: at com.boydti.fawe.beta.implementation.queue.SingleThreadQueueExtent.pollSubmissions(SingleThreadQueueExtent.java:278)
[21:43:13 WARN]: at com.boydti.fawe.beta.implementation.queue.SingleThreadQueueExtent.flush(SingleThreadQueueExtent.java:332)
[21:43:13 WARN]: at com.boydti.fawe.beta.IQueueExtent.commit(IQueueExtent.java:113)
[21:43:13 WARN]: at com.sk89q.worldedit.extent.PassthroughExtent.commit(PassthroughExtent.java:209)
[21:43:13 WARN]: at com.sk89q.worldedit.extent.PassthroughExtent.commit(PassthroughExtent.java:209)
[21:43:13 WARN]: at com.sk89q.worldedit.EditSession.flushQueue(EditSession.java:1035)
[21:43:13 WARN]: at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandTask(PlatformCommandManager.java:745)
[21:43:13 WARN]: at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandOnCurrentThread(PlatformCommandManager.java:684)
[21:43:13 WARN]: at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommand$13(PlatformCommandManager.java:654)
[21:43:13 WARN]: at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99)
[21:43:13 WARN]: at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[21:43:13 WARN]: at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[21:43:13 WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[21:43:13 WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[21:43:13 WARN]: at java.lang.Thread.run(Thread.java:748)
[21:43:13 WARN]: Caused by: java.lang.NullPointerException
[21:43:13 WARN]: at com.sk89q.worldedit.bukkit.BukkitWorld.get(BukkitWorld.java:589)
[21:43:13 WARN]: at com.sk89q.worldedit.bukkit.BukkitWorld.get(BukkitWorld.java:78)
[21:43:13 WARN]: at com.boydti.fawe.beta.implementation.cache.ChunkCache.newChunk(ChunkCache.java:43)
[21:43:13 WARN]: at com.boydti.fawe.beta.implementation.cache.ChunkCache.get(ChunkCache.java:37)
[21:43:13 WARN]: at com.boydti.fawe.beta.implementation.cache.ChunkCache.get(ChunkCache.java:12)
[21:43:13 WARN]: at com.boydti.fawe.beta.implementation.queue.SingleThreadQueueExtent.getCachedGet(SingleThreadQueueExtent.java:78)
[21:43:13 WARN]: at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.newWrappedGet(ChunkHolder.java:707)
[21:43:13 WARN]: at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.getOrCreateGet(ChunkHolder.java:677)
[21:43:13 WARN]: at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.call(ChunkHolder.java:737)
[21:43:13 WARN]: at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.call(ChunkHolder.java:729)
[21:43:13 WARN]: at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.call(ChunkHolder.java:31)
[21:43:13 WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[21:43:13 WARN]: ... 3 more
[21:43:13 WARN]: java.lang.NullPointerException
[21:43:13 WARN]: at com.sk89q.worldedit.bukkit.BukkitWorld.get(BukkitWorld.java:589)
[21:43:13 WARN]: at com.sk89q.worldedit.bukkit.BukkitWorld.get(BukkitWorld.java:78)
[21:43:13 WARN]: at com.boydti.fawe.beta.implementation.cache.ChunkCache.newChunk(ChunkCache.java:43)
[21:43:13 WARN]: at com.boydti.fawe.beta.implementation.cache.ChunkCache.get(ChunkCache.java:37)
[21:43:13 WARN]: at com.boydti.fawe.beta.implementation.cache.ChunkCache.get(ChunkCache.java:12)
[21:43:13 WARN]: at com.boydti.fawe.beta.implementation.queue.SingleThreadQueueExtent.getCachedGet(SingleThreadQueueExtent.java:78)
[21:43:13 WARN]: at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.newWrappedGet(ChunkHolder.java:707)
[21:43:13 WARN]: at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.getOrCreateGet(ChunkHolder.java:677)
[21:43:13 WARN]: at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.call(ChunkHolder.java:737)
[21:43:13 WARN]: at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.call(ChunkHolder.java:729)
[21:43:13 WARN]: at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.call(ChunkHolder.java:31)
[21:43:13 WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[21:43:13 WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[21:43:13 WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[21:43:13 WARN]: at java.lang.Thread.run(Thread.java:748)

**Comment by TheCyberShocker** [comment]
This is on 1.16.1 version

**Comment by MattBDev** [comment]
What was the reason for this being closed? Was it fixed?

**Comment by PierreSchwang** [comment]
Could be related to my issue:
```[15:09:23] [ForkJoinPool.commonPool-worker-13/WARN]: java.lang.NullPointerException
[15:09:23] [ForkJoinPool.commonPool-worker-13/WARN]: 	at com.boydti.fawe.beta.implementation.blocks.CharBlocks$Section.get(CharBlocks.java:167)
[15:09:23] [ForkJoinPool.commonPool-worker-13/WARN]: 	at com.boydti.fawe.beta.implementation.blocks.CharBlocks.get(CharBlocks.java:132)
[15:09:23] [ForkJoinPool.commonPool-worker-13/WARN]: 	at com.boydti.fawe.beta.implementation.blocks.CharBlocks.getBlock(CharBlocks.java:123)
[15:09:23] [ForkJoinPool.commonPool-worker-13/WARN]: 	at com.boydti.fawe.beta.implementation.chunk.ChunkHolder$1.getBlock(ChunkHolder.java:242)
[15:09:23] [ForkJoinPool.commonPool-worker-13/WARN]: 	at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.getBlock(ChunkHolder.java:982)
[15:09:23] [ForkJoinPool.commonPool-worker-13/WARN]: 	at com.boydti.fawe.beta.implementation.lighting.NMSRelighter.fixSkyLighting(NMSRelighter.java:972)
[15:09:23] [ForkJoinPool.commonPool-worker-13/WARN]: 	at com.boydti.fawe.beta.implementation.lighting.NMSRelighter.fixSkyLighting(NMSRelighter.java:897)
[15:09:23] [ForkJoinPool.commonPool-worker-13/WARN]: 	at com.boydti.fawe.beta.implementation.lighting.NMSRelighter.fixLightingSafe(NMSRelighter.java:781)
[15:09:23] [ForkJoinPool.commonPool-worker-13/WARN]: 	at com.boydti.fawe.beta.implementation.lighting.NMSRelighter.removeAndRelight(NMSRelighter.java:102)
[15:09:23] [ForkJoinPool.commonPool-worker-13/WARN]: 	at com.sk89q.worldedit.EditSession.flushQueue(EditSession.java:1113)
[15:09:23] [ForkJoinPool.commonPool-worker-13/WARN]: 	at com.sk89q.worldedit.EditSession.flushSession(EditSession.java:1083)
[15:09:23] [ForkJoinPool.commonPool-worker-13/WARN]: 	at com.sk89q.worldedit.EditSession.close(EditSession.java:1072)
[15:09:23] [ForkJoinPool.commonPool-worker-13/WARN]: 	at xxxxxx.paste.FawePasteService.lambda$paste$0(FawePasteService.java:45)
[15:09:23] [ForkJoinPool.commonPool-worker-13/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800)
[15:09:23] [ForkJoinPool.commonPool-worker-13/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1792)
[15:09:23] [ForkJoinPool.commonPool-worker-13/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[15:09:23] [ForkJoinPool.commonPool-worker-13/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
[15:09:23] [ForkJoinPool.commonPool-worker-13/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
[15:09:23] [ForkJoinPool.commonPool-worker-13/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
[15:09:23] [ForkJoinPool.commonPool-worker-13/WARN]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

<table>
<tr>
	<td>Server</td>
	<td>1.16.5 Fork (Rev git-Paper-ff0fa5f) » https://github.com/gommehdnet/cheetah-1.16</td>
<tr>
	<td>FastAsyncWorldEdit</td>
	<td>Build 688</td>
</table>

Code-Snippet which produced the error:
```java
CompletableFuture.runAsync(() -> {
            World world = BukkitAdapter.adapt(pasteOrigin.getWorld());
            try (EditSession session = new EditSessionBuilder(world).world(world).fastmode(true).build()) {
                schematic.getBlocks().forEach(session::smartSetBlock);
                Operations.complete(session.commit());
                future.set(null);
            } catch (Exception e) {		// Source
                future.setException(e);
            }
        });
```
