### ISSUE TITLE
help?

### ISSUE THREAD

**Issue by xAlexanderYo** [IntellectualSites/FastAsyncWorldEdit#626]
7:55:48 [INFO ] Enabling FastAsyncWorldEdit v19.03.29-d13b946-1257-22.0.14
> java.lang.NoSuchFieldException: modifiers
        at java.base/java.lang.Class.getDeclaredField(Class.java:2489)
        at com.boydti.fawe.config.Config.setAccessible(Config.java:451)
        at com.boydti.fawe.config.Config.save(Config.java:288)
        at com.boydti.fawe.config.Config.<init>(Config.java:27)
        at com.boydti.fawe.config.Settings.<init>(Settings.java:8)
        at com.boydti.fawe.config.Settings.<clinit>(Settings.java:10)
        at com.boydti.fawe.nukkit.core.NukkitWorldEdit.onEnable(NukkitWorldEdit.java:80)
        at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89)
        at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:117)
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:436)
        at cn.nukkit.Server.enablePlugin(Server.java:746)
        at cn.nukkit.Server.enablePlugins(Server.java:735)
        at cn.nukkit.Server.<init>(Server.java:571)
        at cn.nukkit.Nukkit.main(Nukkit.java:112)
java.lang.NullPointerException
        at com.boydti.fawe.nukkit.core.NukkitWorldEdit.onEnable(NukkitWorldEdit.java:80)
        at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89)
        at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:117)
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:436)
        at cn.nukkit.Server.enablePlugin(Server.java:746)
        at cn.nukkit.Server.enablePlugins(Server.java:735)
        at cn.nukkit.Server.<init>(Server.java:571)
        at cn.nukkit.Nukkit.main(Nukkit.java:112)

**Comment by SirYwell** [comment]
You're using an outdated, unsupported version of FAWE but most likely a Java version that isn't compatible with your FAWE build (try Java 8). Please note that this bug tracker is meant for issues with the current and supported version of FAWE.
