### ISSUE TITLE
ConcurrentModificationException when pasting schematic

### ISSUE THREAD

**Issue by bertek41** [IntellectualSites/FastAsyncWorldEdit#668]
**[REQUIRED] FastAsyncWorldEdit Configuration Files** 

https://athion.net/ISPaster/paste/view/b35939f84d824387811cbf2df03a7028

**Required Information**
- FAWE Version Number: FastAsyncWorldEdit-1.16-387
- Spigot/Paper Version Number:  git-Paper-204 (MC: 1.16.3)
- Minecraft Version: 1.16.3

**Describe the bug**
I loaded schematic and pasted it and received this error:
```
[16:38:57] [Server thread/INFO]: YasinSubasi issued server command: /schematic load spawn
[16:39:05] [Server thread/INFO]: YasinSubasi issued server command: //paste
[16:39:05] [pool-46-thread-2/WARN]: java.util.ConcurrentModificationException
[16:39:05] [pool-46-thread-2/WARN]: 	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1134)
[16:39:05] [pool-46-thread-2/WARN]: 	at org.bukkit.craftbukkit.v1_16_R2.block.data.CraftBlockData.newData(CraftBlockData.java:550)
[16:39:05] [pool-46-thread-2/WARN]: 	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.createBlockData(CraftServer.java:2121)
[16:39:05] [pool-46-thread-2/WARN]: 	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.createBlockData(CraftServer.java:2114)
[16:39:05] [pool-46-thread-2/WARN]: 	at org.bukkit.Bukkit.createBlockData(Bukkit.java:1575)
[16:39:05] [pool-46-thread-2/WARN]: 	at com.sk89q.worldedit.bukkit.adapter.impl.FAWE_Spigot_v1_16_R2.getMaterial(FAWE_Spigot_v1_16_R2.java:111)
[16:39:05] [pool-46-thread-2/WARN]: 	at com.sk89q.worldedit.bukkit.BukkitBlockRegistry.getMaterial(BukkitBlockRegistry.java:71)
[16:39:05] [pool-46-thread-2/WARN]: 	at com.sk89q.worldedit.world.block.BlockState.getMaterial(BlockState.java:368)
[16:39:05] [pool-46-thread-2/WARN]: 	at com.sk89q.worldedit.bukkit.adapter.impl.FAWE_Spigot_v1_16_R2.init(FAWE_Spigot_v1_16_R2.java:96)
[16:39:05] [pool-46-thread-2/WARN]: 	at com.sk89q.worldedit.bukkit.adapter.impl.FAWE_Spigot_v1_16_R2.adaptToChar(FAWE_Spigot_v1_16_R2.java:287)
[16:39:05] [pool-46-thread-2/WARN]: 	at com.boydti.fawe.bukkit.adapter.mc1_16_2.BukkitGetBlocks_1_16_2.ordinal(BukkitGetBlocks_1_16_2.java:703)
[16:39:05] [pool-46-thread-2/WARN]: 	at com.boydti.fawe.bukkit.adapter.mc1_16_2.BukkitGetBlocks_1_16_2.update(BukkitGetBlocks_1_16_2.java:662)
[16:39:05] [pool-46-thread-2/WARN]: 	at com.boydti.fawe.beta.implementation.blocks.CharBlocks$2.get(CharBlocks.java:23)
[16:39:05] [pool-46-thread-2/WARN]: 	at com.boydti.fawe.beta.implementation.blocks.CharBlocks.load(CharBlocks.java:103)
[16:39:05] [pool-46-thread-2/WARN]: 	at com.boydti.fawe.object.changeset.AbstractChangeSet.processSet(AbstractChangeSet.java:163)
[16:39:05] [pool-46-thread-2/WARN]: 	at com.boydti.fawe.beta.implementation.processors.BatchProcessorHolder.processSet(BatchProcessorHolder.java:26)
[16:39:05] [pool-46-thread-2/WARN]: 	at com.boydti.fawe.beta.implementation.processors.BatchProcessorHolder.processSet(BatchProcessorHolder.java:26)
[16:39:05] [pool-46-thread-2/WARN]: 	at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.call(ChunkHolder.java:793)
[16:39:05] [pool-46-thread-2/WARN]: 	at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.call(ChunkHolder.java:781)
[16:39:05] [pool-46-thread-2/WARN]: 	at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.call(ChunkHolder.java:33)
[16:39:05] [pool-46-thread-2/WARN]: 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[16:39:05] [pool-46-thread-2/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[16:39:05] [pool-46-thread-2/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[16:39:05] [pool-46-thread-2/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[16:39:08] [Craft Scheduler Thread - 66/WARN]: java.util.concurrent.ExecutionException: java.util.ConcurrentModificationException
[16:39:08] [Craft Scheduler Thread - 66/WARN]: 	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
[16:39:08] [Craft Scheduler Thread - 66/WARN]: 	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
[16:39:08] [Craft Scheduler Thread - 66/WARN]: 	at com.boydti.fawe.beta.implementation.queue.SingleThreadQueueExtent.pollSubmissions(SingleThreadQueueExtent.java:288)
[16:39:08] [Craft Scheduler Thread - 66/WARN]: 	at com.boydti.fawe.beta.implementation.queue.SingleThreadQueueExtent.flush(SingleThreadQueueExtent.java:342)
[16:39:08] [Craft Scheduler Thread - 66/WARN]: 	at com.boydti.fawe.beta.IQueueExtent.commit(IQueueExtent.java:113)
[16:39:08] [Craft Scheduler Thread - 66/WARN]: 	at com.sk89q.worldedit.extent.PassthroughExtent.commit(PassthroughExtent.java:209)
[16:39:08] [Craft Scheduler Thread - 66/WARN]: 	at com.sk89q.worldedit.extent.PassthroughExtent.commit(PassthroughExtent.java:209)
[16:39:08] [Craft Scheduler Thread - 66/WARN]: 	at com.sk89q.worldedit.EditSession.flushQueue(EditSession.java:1045)
[16:39:08] [Craft Scheduler Thread - 66/WARN]: 	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandTask(PlatformCommandManager.java:749)
[16:39:08] [Craft Scheduler Thread - 66/WARN]: 	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandOnCurrentThread(PlatformCommandManager.java:684)
[16:39:08] [Craft Scheduler Thread - 66/WARN]: 	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommand$13(PlatformCommandManager.java:654)
[16:39:08] [Craft Scheduler Thread - 66/WARN]: 	at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99)
[16:39:08] [Craft Scheduler Thread - 66/WARN]: 	at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[16:39:08] [Craft Scheduler Thread - 66/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[16:39:08] [Craft Scheduler Thread - 66/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[16:39:08] [Craft Scheduler Thread - 66/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[16:39:08] [Craft Scheduler Thread - 66/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[16:39:08] [Craft Scheduler Thread - 66/WARN]: Caused by: java.util.ConcurrentModificationException
[16:39:08] [Craft Scheduler Thread - 66/WARN]: 	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1134)
[16:39:08] [Craft Scheduler Thread - 66/WARN]: 	at org.bukkit.craftbukkit.v1_16_R2.block.data.CraftBlockData.newData(CraftBlockData.java:550)
[16:39:08] [Craft Scheduler Thread - 66/WARN]: 	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.createBlockData(CraftServer.java:2121)
[16:39:08] [Craft Scheduler Thread - 66/WARN]: 	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.createBlockData(CraftServer.java:2114)
[16:39:08] [Craft Scheduler Thread - 66/WARN]: 	at org.bukkit.Bukkit.createBlockData(Bukkit.java:1575)
[16:39:08] [Craft Scheduler Thread - 66/WARN]: 	at com.sk89q.worldedit.bukkit.adapter.impl.FAWE_Spigot_v1_16_R2.getMaterial(FAWE_Spigot_v1_16_R2.java:111)
[16:39:08] [Craft Scheduler Thread - 66/WARN]: 	at com.sk89q.worldedit.bukkit.BukkitBlockRegistry.getMaterial(BukkitBlockRegistry.java:71)
[16:39:08] [Craft Scheduler Thread - 66/WARN]: 	at com.sk89q.worldedit.world.block.BlockState.getMaterial(BlockState.java:368)
[16:39:08] [Craft Scheduler Thread - 66/WARN]: 	at com.sk89q.worldedit.bukkit.adapter.impl.FAWE_Spigot_v1_16_R2.init(FAWE_Spigot_v1_16_R2.java:96)
[16:39:08] [Craft Scheduler Thread - 66/WARN]: 	at com.sk89q.worldedit.bukkit.adapter.impl.FAWE_Spigot_v1_16_R2.adaptToChar(FAWE_Spigot_v1_16_R2.java:287)
[16:39:08] [Craft Scheduler Thread - 66/WARN]: 	at com.boydti.fawe.bukkit.adapter.mc1_16_2.BukkitGetBlocks_1_16_2.ordinal(BukkitGetBlocks_1_16_2.java:703)
[16:39:08] [Craft Scheduler Thread - 66/WARN]: 	at com.boydti.fawe.bukkit.adapter.mc1_16_2.BukkitGetBlocks_1_16_2.update(BukkitGetBlocks_1_16_2.java:662)
[16:39:08] [Craft Scheduler Thread - 66/WARN]: 	at com.boydti.fawe.beta.implementation.blocks.CharBlocks$2.get(CharBlocks.java:23)
[16:39:08] [Craft Scheduler Thread - 66/WARN]: 	at com.boydti.fawe.beta.implementation.blocks.CharBlocks.load(CharBlocks.java:103)
[16:39:08] [Craft Scheduler Thread - 66/WARN]: 	at com.boydti.fawe.object.changeset.AbstractChangeSet.processSet(AbstractChangeSet.java:163)
[16:39:08] [Craft Scheduler Thread - 66/WARN]: 	at com.boydti.fawe.beta.implementation.processors.BatchProcessorHolder.processSet(BatchProcessorHolder.java:26)
[16:39:08] [Craft Scheduler Thread - 66/WARN]: 	at com.boydti.fawe.beta.implementation.processors.BatchProcessorHolder.processSet(BatchProcessorHolder.java:26)
[16:39:08] [Craft Scheduler Thread - 66/WARN]: 	at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.call(ChunkHolder.java:793)
[16:39:08] [Craft Scheduler Thread - 66/WARN]: 	at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.call(ChunkHolder.java:781)
[16:39:08] [Craft Scheduler Thread - 66/WARN]: 	at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.call(ChunkHolder.java:33)
[16:39:08] [Craft Scheduler Thread - 66/WARN]: 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[16:39:08] [Craft Scheduler Thread - 66/WARN]: 	... 3 more
```
**To Reproduce**
1. Load schematic
2. Paste it
3. See error

If you want i can add schematic here.

**Comment by aurorasmiles** [comment]
Please provide the schematic that caused this error

**Comment by bertek41** [comment]
[spawn.zip](https://github.com/IntellectualSites/FastAsyncWorldEdit/files/5326375/spawn.zip)

> Please provide the schematic that caused this error

**Comment by dordsor21** [comment]
Is this still an issue on the latest FAWE/Paper?
