### ISSUE TITLE
Setting fast-placement: false produces error

### ISSUE THREAD

**Issue by Mintaka3a** [IntellectualSites/FastAsyncWorldEdit#726]
**[REQUIRED] FastAsyncWorldEdit Configuration Files** 

[22:26:40 ERROR]: An unexpected error while handling a WorldEdit command
java.lang.IllegalStateException: Asynchronous block remove!
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[patched_1.16.3.jar:git-Paper-246]
        at net.minecraft.server.v1_16_R2.BlockBase.remove(BlockBase.java:84) ~[patched_1.16.3.jar:git-Paper-246]
        at net.minecraft.server.v1_16_R2.BlockBase$BlockData.remove(BlockBase.java:561) ~[patched_1.16.3.jar:git-Paper-246]
        at net.minecraft.server.v1_16_R2.Chunk.setType(Chunk.java:505) ~[patched_1.16.3.jar:git-Paper-246]
        at net.minecraft.server.v1_16_R2.World.a(World.java:395) ~[patched_1.16.3.jar:git-Paper-246]
        at net.minecraft.server.v1_16_R2.World.setTypeAndData(World.java:358) ~[patched_1.16.3.jar:git-Paper-246]
        at org.bukkit.craftbukkit.v1_16_R2.block.CraftBlock.setTypeAndData(CraftBlock.java:199) ~[patched_1.16.3.jar:git-Paper-246]
        at org.bukkit.craftbukkit.v1_16_R2.block.CraftBlock.setBlockData(CraftBlock.java:184) ~[patched_1.16.3.jar:git-Paper-246]
        at com.sk89q.worldedit.bukkit.BukkitWorld.setBlock(BukkitWorld.java:465) ~[?:?]
        at com.sk89q.worldedit.world.AbstractWorld.setBlock(AbstractWorld.java:59) ~[?:?]
        at com.sk89q.worldedit.bukkit.BukkitWorld.setBlock(BukkitWorld.java:533) ~[?:?]
        at com.boydti.fawe.wrappers.WorldWrapper.setBlock(WorldWrapper.java:172) ~[?:?]
        at com.sk89q.worldedit.extent.AbstractDelegateExtent.setBlock(AbstractDelegateExtent.java:159) ~[?:?]
        at com.boydti.fawe.object.HistoryExtent.setBlock(HistoryExtent.java:60) ~[?:?]
        at com.sk89q.worldedit.extent.AbstractDelegateExtent.setBlock(AbstractDelegateExtent.java:159) ~[?:?]
        at com.boydti.fawe.object.extent.FaweRegionExtent.setBlock(FaweRegionExtent.java:81) ~[?:?]
        at com.sk89q.worldedit.extent.AbstractDelegateExtent.setBlock(AbstractDelegateExtent.java:159) ~[?:?]
        at com.boydti.fawe.beta.implementation.processors.LimitExtent.setBlock(LimitExtent.java:596) ~[?:?]
        at com.sk89q.worldedit.EditSession.setBlock(EditSession.java:927) ~[?:?]
        at com.sk89q.worldedit.extent.AbstractDelegateExtent.setBlock(AbstractDelegateExtent.java:153) ~[?:?]
        at com.boydti.fawe.object.extent.PositionTransformExtent.setBlock(PositionTransformExtent.java:79) ~[?:?]
        at com.boydti.fawe.object.function.block.SimpleBlockCopy.apply(SimpleBlockCopy.java:20) ~[?:?]
        at com.sk89q.worldedit.function.visitor.RegionVisitor.resume(RegionVisitor.java:66) ~[?:?]
        at com.sk89q.worldedit.function.operation.Operations.completeBlindly(Operations.java:76) ~[?:?]
        at com.sk89q.worldedit.function.operation.ForwardExtentCopy.resume(ForwardExtentCopy.java:396) ~[?:?]
        at com.sk89q.worldedit.function.operation.Operations.completeLegacy(Operations.java:57) ~[?:?]
        at com.sk89q.worldedit.EditSession.stackCuboidRegion(EditSession.java:1529) ~[?:?]
        at com.sk89q.worldedit.command.RegionCommands.stack(RegionCommands.java:585) ~[?:?]
        at com.sk89q.worldedit.command.RegionCommandsRegistration.cmd$_stack(RegionCommandsRegistration.java:894) ~[?:?]
        at org.enginehub.piston.CommandManager.execute(CommandManager.java:157) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommandOnCurrentThread$16(PlatformCommandManager.java:688) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandTask(PlatformCommandManager.java:704) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandOnCurrentThread(PlatformCommandManager.java:690) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$null$13(PlatformCommandManager.java:660) ~[?:?]
        at com.sk89q.worldedit.extension.platform.AbstractPlayerActor.lambda$runAction$1(AbstractPlayerActor.java:697) ~[?:?]
        at com.boydti.fawe.object.task.AsyncNotifyQueue.lambda$run$0(AsyncNotifyQueue.java:27) ~[?:?]
        at com.boydti.fawe.object.task.AsyncNotifyQueue.lambda$call$1(AsyncNotifyQueue.java:44) ~[?:?]
        at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1448) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?]

**/fawe debugpaste**:

**Required Information**
- FAWE Version Number (`/version FastAsyncWorldEdit`):     1.16-427.jar
- Spigot/Paper Version Number (`/version`):     
- Minecraft Version: [e.g. 1.16.3]     1.16.3

**Describe the bug**
Changing fast-placement from true to false in config.yml results in the above java exception on all block placement commands.

**To Reproduce**
Modify config.yml file to disable fast placement.
Restart server.
Left click and right click a block with //wand tool.
Issue //stack 10 l command.
Java exception shown on console and no new blocks appear.

**Plugins being used on the server**

**Checklist**:

- [] I included all information required in the sections above
- [] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.3](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [] I made sure the bug/error is not caused by any other plugin

**Comment by MattBDev** [comment]
Did not follow the template at all.
