### ISSUE TITLE
ver #369 Using //set Failed

### ISSUE THREAD

**Issue by TNTobsidian** [IntellectualSites/FastAsyncWorldEdit#755]
**[REQUIRED] FastAsyncWorldEdit Configuration Files** 

https://athion.net/ISPaster/paste/view/7e1a586572834db58b2d282dae065cf9

**/fawe debugpaste**:

**Required Information**
- FAWE Version Number (`/version FastAsyncWorldEdit`): FastAsyncWorldEdit version 1.16-369;aed6807
- Spigot/Paper Version Number (`/version`): This server is running CraftBukkit version git-Spigot-a19903d-167ff59 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
- Minecraft Version: [e.g. 1.16.4]     1.16.3(Mine Version)

**Describe the bug**

**See below**

**To Reproduce**
1. Run  to '...'

**Plugins being used on the server**

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.4](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [X] I made sure the bug/error is not caused by any other plugin

My Minecraft Version: 1.16.3
Plugin List: BeesEverywhere, InventoryRollback, LuckPerms, MultiWorld, GroupManager, UltimateTag, DeathSwap, Skins, ViaVersion, Vault, ViaBackwards, BlockShuffle, dynmap, FastAsyncWorldEdit (WorldEdit), AuthMe, AdvancedBan, CoreProtect

Bug: When I try to use //set to replace blocks, it wasn't responding and I check my console and see the error message
`[20:10:19] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 12738ms or 254 ticks behind
[20:11:01] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 11876ms or 237 ticks behind
[20:11:42] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 11283ms or 225 ticks behind
[20:12:21] [Server thread/INFO]: TNTobsidian issued server command: //set grass_block
[20:12:21] [ForkJoinPool-8-worker-0/WARN]: java.lang.NullPointerException
[20:12:21] [ForkJoinPool-8-worker-0/WARN]:  at com.sk89q.worldedit.bukkit.BukkitWorld.get(BukkitWorld.java:594)
[20:12:21] [ForkJoinPool-8-worker-0/WARN]:  at com.sk89q.worldedit.bukkit.BukkitWorld.get(BukkitWorld.java:76)
[20:12:21] [ForkJoinPool-8-worker-0/WARN]:  at com.boydti.fawe.beta.implementation.cache.ChunkCache.newChunk(ChunkCache.java:43)
[20:12:21] [ForkJoinPool-8-worker-0/WARN]:  at com.boydti.fawe.beta.implementation.cache.ChunkCache.get(ChunkCache.java:37)
[20:12:21] [ForkJoinPool-8-worker-0/WARN]:  at com.boydti.fawe.beta.implementation.cache.ChunkCache.get(ChunkCache.java:12)
[20:12:21] [ForkJoinPool-8-worker-0/WARN]:  at com.boydti.fawe.beta.implementation.queue.SingleThreadQueueExtent.getCachedGet(SingleThreadQueueExtent.java:78)`

AND MORE but I'm not going to paste it all here.
**To Reproduce**
1.Choose point 1
2.Choose point 2
3.command //set grass_block
4.not responding and console see the error message

**Comment by N0tMyFaultOG** [comment]
Update Fawe, use Paper and allocate more ram
