### ISSUE TITLE
bug report with //naturalize

### ISSUE THREAD

**Issue by bananasmoothii** [IntellectualSites/FastAsyncWorldEdit#758]
everything is in the log, I made a big selection "top-to-bottom" before
![version](https://user-images.githubusercontent.com/45853225/99906213-23317780-2cd6-11eb-8483-549854276115.PNG)
![version2](https://user-images.githubusercontent.com/45853225/99906228-42c8a000-2cd6-11eb-9b12-20f8ef8129ac.PNG)

```
22.11 15:14:14 [Server] INFO Bananasmoothii issued server command: //set #voronoi[40][stone,air]
22.11 15:14:54 [Server] WARN laserelpp moved too quickly! -14.187770267238193,22.91133311519576,-22.754193082424294
22.11 15:15:28 [Server] INFO Bananasmoothii issued server command: //naturalize
22.11 15:15:28 [Server] ERROR An unexpected error while handling a WorldEdit command
22.11 15:15:28 [Server] INFO java.lang.ArrayIndexOutOfBoundsException: 16
22.11 15:15:28 [Server] INFO at com.boydti.fawe.beta.implementation.blocks.CharBlocks.get(CharBlocks.java:118) ~[?:?]
22.11 15:15:28 [Server] INFO at com.boydti.fawe.beta.implementation.blocks.CharBlocks.getBlock(CharBlocks.java:112) ~[?:?]
22.11 15:15:28 [Server] INFO at com.boydti.fawe.beta.implementation.chunk.ChunkHolder$2.getBlock(ChunkHolder.java:353) ~[?:?]
22.11 15:15:28 [Server] INFO at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.getBlock(ChunkHolder.java:848) ~[?:?]
22.11 15:15:28 [Server] INFO at com.boydti.fawe.beta.implementation.chunk.ChunkHolder$4.getBlock(ChunkHolder.java:572) ~[?:?]
22.11 15:15:28 [Server] INFO at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.getBlock(ChunkHolder.java:848) ~[?:?]
22.11 15:15:28 [Server] INFO at com.boydti.fawe.beta.implementation.IChunkExtent.getBlock(IChunkExtent.java:65) ~[?:?]
22.11 15:15:28 [Server] INFO at com.sk89q.worldedit.extent.InputExtent.getBlock(InputExtent.java:53) ~[?:?]
22.11 15:15:28 [Server] INFO at com.sk89q.worldedit.extent.PassthroughExtent.getBlock(PassthroughExtent.java:181) ~[?:?]
22.11 15:15:28 [Server] INFO at com.sk89q.worldedit.extent.PassthroughExtent.getBlock(PassthroughExtent.java:181) ~[?:?]
22.11 15:15:28 [Server] INFO at com.sk89q.worldedit.function.mask.BlockTypeMask.test(BlockTypeMask.java:122) ~[?:?]
22.11 15:15:28 [Server] INFO at com.sk89q.worldedit.function.block.Naturalizer.isGround(Naturalizer.java:66) ~[?:?]
22.11 15:15:28 [Server] INFO at com.sk89q.worldedit.function.visitor.LayerVisitor.resume(LayerVisitor.java:99) ~[?:?]
22.11 15:15:28 [Server] INFO at com.sk89q.worldedit.function.operation.Operations.completeBlindly(Operations.java:76) ~[?:?]
22.11 15:15:28 [Server] INFO at com.sk89q.worldedit.EditSession.naturalizeCuboidBlocks(EditSession.java:1480) ~[?:?]
22.11 15:15:28 [Server] INFO at com.sk89q.worldedit.command.RegionCommands.naturalize(RegionCommands.java:371) ~[?:?]
22.11 15:15:28 [Server] INFO at com.sk89q.worldedit.command.RegionCommandsRegistration.cmd$_naturalize(RegionCommandsRegistration.java:779) ~[?:?]
22.11 15:15:28 [Server] INFO at org.enginehub.piston.CommandManager.execute(CommandManager.java:157) ~[?:?]
22.11 15:15:28 [Server] INFO at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommandOnCurrentThread$16(PlatformCommandManager.java:688) ~[?:?]
22.11 15:15:28 [Server] INFO at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandTask(PlatformCommandManager.java:704) ~[?:?]
22.11 15:15:28 [Server] INFO at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandOnCurrentThread(PlatformCommandManager.java:690) ~[?:?]
22.11 15:15:28 [Server] INFO at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$null$13(PlatformCommandManager.java:660) ~[?:?]
22.11 15:15:28 [Server] INFO at com.sk89q.worldedit.extension.platform.AbstractPlayerActor.lambda$runAction$1(AbstractPlayerActor.java:697) ~[?:?]
22.11 15:15:28 [Server] INFO at com.boydti.fawe.object.task.AsyncNotifyQueue.lambda$run$0(AsyncNotifyQueue.java:27) ~[?:?]
22.11 15:15:28 [Server] INFO at com.boydti.fawe.object.task.AsyncNotifyQueue.lambda$call$1(AsyncNotifyQueue.java:44) ~[?:?]
22.11 15:15:28 [Server] INFO at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424) ~[?:1.8.0_265]
22.11 15:15:28 [Server] INFO at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_265]
22.11 15:15:28 [Server] INFO at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_265]
22.11 15:15:28 [Server] INFO at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_265]
22.11 15:15:28 [Server] INFO at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175) ~[?:1.8.0_265]
```

**Comment by aurorasmiles** [comment]
Please update FAWE
