### ISSUE TITLE
Player Quit Error

### ISSUE THREAD

**Issue by TaskID** [IntellectualSites/FastAsyncWorldEdit#779]
**/fawe debugpaste**: Don't want to paste it since I'd share a lot of IP-Addresses and I can't remove them in the Incendo Paste.
Here is the split up paste without log (stack trace later as a spoiler):
information: https://pastebin.com/YBdP8hLM
config: https://pastebin.com/1Dp2N5yZ
config-legacy: https://pastebin.com/tAZELuqP

**Required Information**
- FAWE Version Number: 1.16-449;cc5b3ec
- Spigot/Paper Version Number: git-Paper-318 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
- Minecraft Version: 1.16.4 

**Describe the bug**
The bug occurs when disconnecting from the server. I use CloudNet 2 and because in the stack trace there was something from CloudNet, I first thought it was a CloudNet error. So I asked on the CloudNet Discord and a CloudNet developer said it's a FAWE error.
<details>
    <summary>Stack Trace</summary>
[23:09:42] [Server thread/INFO]: TaskID lost connection: Disconnected
[23:09:42] [Server thread/ERROR]: Could not pass event PlayerQuitEvent to FastAsyncWorldEdit v1.16-449;cc5b3ec
java.lang.NullPointerException: null
	at de.dytanic.cloudnet.bridge.internal.util.CloudPermissible.recalculatePermissions(CloudPermissible.java:90) ~[?:?]
	at org.bukkit.permissions.PermissibleBase.removeAttachment(PermissibleBase.java:161) ~[patched_1.16.4.jar:git-Paper-318]
	at org.bukkit.craftbukkit.v1_16_R3.entity.CraftHumanEntity.removeAttachment(CraftHumanEntity.java:236) ~[patched_1.16.4.jar:git-Paper-318]
	at com.sk89q.worldedit.bukkit.BukkitPermissionAttachmentManager.removeAttachment(BukkitPermissionAttachmentManager.java:31) ~[?:?]
	at com.sk89q.worldedit.bukkit.BukkitPlayer.unregister(BukkitPlayer.java:416) ~[?:?]
	at com.boydti.fawe.bukkit.FaweBukkit.onPlayerQuit(FaweBukkit.java:271) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1920.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.4.jar:git-Paper-318]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.4.jar:git-Paper-318]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Paper-318]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Paper-318]
	at net.minecraft.server.v1_16_R3.PlayerList.disconnect(PlayerList.java:513) ~[patched_1.16.4.jar:git-Paper-318]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1677) ~[patched_1.16.4.jar:git-Paper-318]
	at net.minecraft.server.v1_16_R3.NetworkManager.handleDisconnection(NetworkManager.java:500) ~[patched_1.16.4.jar:git-Paper-318]
	at net.minecraft.server.v1_16_R3.ServerConnection.c(ServerConnection.java:165) ~[patched_1.16.4.jar:git-Paper-318]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1381) ~[patched_1.16.4.jar:git-Paper-318]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.4.jar:git-Paper-318]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1209) ~[patched_1.16.4.jar:git-Paper-318]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:997) ~[patched_1.16.4.jar:git-Paper-318]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[patched_1.16.4.jar:git-Paper-318]
	at java.lang.Thread.run(Thread.java:834) [?:?]
</details>

**To Reproduce**
1. Disconnect (it happens at every disconnect)

**Plugins being used on the server**
PlotSquared, Multiverse, CloudNetAPI (I'm using CloudNet 2)

**Checklist**:

- [x] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.4](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
> Server thread/ERROR]: Could not pass event PlayerQuitEvent to FastAsyncWorldEdit v1.16-449;cc5b3ec java.lang.NullPointerException: null at de.dytanic.cloudnet.bridge.internal.util.CloudPermissible.recalculatePermissions(CloudPermissible.java:90) ~[?:?] at

Not a Fawe issue.
