### ISSUE TITLE
FAWE (Is it up to date?)

### ISSUE THREAD

**Issue by PirataGu** [IntellectualSites/FastAsyncWorldEdit#811]
Hi! I'm having this problem when I try to load the plugin... I am using 1.16.4 paper

**" [INFO] .... [FastAsyncWorldEdit] Enabling FastAsyncWorldEdit v1.16-488;7236f1d

[ERROR] .... Error occurred while enabling FastAsyncWorldEdit v1.16-488;7236f1d (Is it up to date?)

org.yaml.snakeyaml.error.YAMLException: java.nio.charset.MalformedInputException: Input length = 1

at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:218) ~[patched_1.16.4.jar:git-Paper-342]

at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:176) ~[patched_1.16.4.jar:git-Paper-342]

at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:171) ~[patched_1.16.4.jar:git-Paper-342]

at org.yaml.snakeyaml.reader.StreamReader.peek(StreamReader.java:126) ~[patched_1.16.4.jar:git-Paper-342]

at org.yaml.snakeyaml.scanner.ScannerImpl.scanToNextToken(ScannerImpl.java:1177) ~[patched_1.16.4.jar:git-Paper-342]

at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:287) ~[patched_1.16.4.jar:git-Paper-342]

at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:227) ~[patched_1.16.4.jar:git-Paper-342]

at org.yaml.snakeyaml.parser.ParserImpl$ParseImplicitDocumentStart.produce(ParserImpl.java:195) ~[patched_1.16.4.jar:git-Paper-342]

at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158) ~[patched_1.16.4.jar:git-Paper-342]

at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148) ~[patched_1.16.4.jar:git-Paper-342]

at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:118) ~[patched_1.16.4.jar:git-Paper-342]

at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:150) ~[patched_1.16.4.jar:git-Paper-342]

at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:472) ~[patched_1.16.4.jar:git-Paper-342]

at org.yaml.snakeyaml.Yaml.load(Yaml.java:424) ~[patched_1.16.4.jar:git-Paper-342]

at com.sk89q.util.yaml.YAMLProcessor.load(YAMLProcessor.java:117) ~[?:?]

at com.sk89q.wepif.PermissionsResolverManager.loadConfig(PermissionsResolverManager.java:199) ~[?:?]

at com.sk89q.wepif.PermissionsResolverManager.<init>(PermissionsResolverManager.java:103) ~[?:?]

at com.sk89q.wepif.PermissionsResolverManager.initialize(PermissionsResolverManager.java:66) ~[?:?]

at com.sk89q.worldedit.bukkit.WorldEditPlugin.onEnable(WorldEditPlugin.java:144) ~[?:?]

at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.4.jar:git-Paper-342]

at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.4.jar:git-Paper-342]

at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.4.jar:git-Paper-342]

at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.4.jar:git-Paper-342]

at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.4.jar:git-Paper-342]

at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:207) ~[patched_1.16.4.jar:git-Paper-342]

at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:936) ~[patched_1.16.4.jar:git-Paper-342]

at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[patched_1.16.4.jar:git-Paper-342]

at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

Caused by: java.nio.charset.MalformedInputException: Input length = 1

at java.nio.charset.CoderResult.throwException(CoderResult.java:281) ~[?:1.8.0_212]

at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:339) ~[?:1.8.0_212]

at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178) ~[?:1.8.0_212]

at java.io.InputStreamReader.read(InputStreamReader.java:184) ~[?:1.8.0_212]

at org.yaml.snakeyaml.reader.UnicodeReader.read(UnicodeReader.java:125) ~[patched_1.16.4.jar:git-Paper-342]

at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:183) ~[patched_1.16.4.jar:git-Paper-342]

... 27 more "**

**Comment by N0tMyFaultOG** [comment]
Don't delete the template.

**Comment by aurorasmiles** [comment]
Also your config is most likely broken

**Comment by PirataGu** [comment]
How do I fix it? Can you help me ?

**Comment by aurorasmiles** [comment]
Delete it

**Comment by PirataGu** [comment]
I've done it more than 10 times but I'll try again

**Comment by PirataGu** [comment]
I'm still having the problem...

**Comment by aurorasmiles** [comment]
Great, don't delete the template when you open an issue. For support use our discord
