### ISSUE TITLE
StripNbt fail and stop session

### ISSUE THREAD

**Issue by jewome62** [IntellectualSites/FastAsyncWorldEdit#832]
**/fawe debugpaste**: https://athion.net/ISPaster/paste/view/e5b8511cb1184724824b1ac00be94b92

**Required Information**
- FAWE Version Number (`/version FastAsyncWorldEdit`):  1.16-511;91de441
- Spigot/Paper Version Number (`/version`): Tuinity based on Paper 339 (bug reproducted on Paper too)
- Minecraft Version: 1.16.4

**Describe the bug**
when copy paste with block with possibility have nbt tags
the paste is stop with exception.
Structure copied:
![image](https://user-images.githubusercontent.com/472429/103801597-3dd56b00-504e-11eb-9e59-a9ccdcb9ca0b.png)
Structure pasted:
![image](https://user-images.githubusercontent.com/472429/103801618-462da600-504e-11eb-8c2d-fc96ad41f0a7.png)

**To Reproduce**
1. Configure into `config.yml` some `strip-nbt`
Example:
```yaml
    strip-nbt: 
    - "minecraft:repeating_command_block"
    - "minecraft:chain_command_block"
    - "minecraft:command_block"
```
2. reboot server
3. Copy selection with block with nbt tag (chest, beacon, etc)
4. Paste
5. See no full paste and error into console

```yaml
[18:31:33 INFO]: Nortu98 issued server command: //paste
[18:31:33 ERROR]: An unexpected error while handling a WorldEdit command
java.lang.UnsupportedOperationException: null
        at java.util.Collections$UnmodifiableMap.remove(Collections.java:1460) ~[?:?]
        at com.boydti.fawe.object.extent.StripNBTExtent.stripBlockNBT(StripNBTExtent.java:60) ~[?:?]
        at com.boydti.fawe.object.extent.StripNBTExtent.setBlock(StripNBTExtent.java:40) ~[?:?]
        at com.sk89q.worldedit.EditSession.setBlock(EditSession.java:931) ~[?:?]
        at com.sk89q.worldedit.extent.clipboard.Clipboard.paste(Clipboard.java:340) ~[?:?]
        at com.sk89q.worldedit.command.ClipboardCommands.place(ClipboardCommands.java:480) ~[?:?]
        at com.sk89q.worldedit.command.ClipboardCommands.paste(ClipboardCommands.java:403) ~[?:?]
        at com.sk89q.worldedit.command.ClipboardCommandsRegistration.cmd$_paste(ClipboardCommandsRegistration.java:333) ~[?:?]
        at org.enginehub.piston.CommandManager.execute(CommandManager.java:157) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommandOnCurrentThread$16(PlatformCommandManager.java:693) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandTask(PlatformCommandManager.java:709) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandOnCurrentThread(PlatformCommandManager.java:695) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$null$13(PlatformCommandManager.java:665) ~[?:?]
        at com.sk89q.worldedit.extension.platform.AbstractPlayerActor.lambda$runAction$1(AbstractPlayerActor.java:697) ~[?:?]
        at com.boydti.fawe.object.task.AsyncNotifyQueue.lambda$run$0(AsyncNotifyQueue.java:27) ~[?:?]
        at com.boydti.fawe.object.task.AsyncNotifyQueue.lambda$call$1(AsyncNotifyQueue.java:44) ~[?:?]
        at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1448) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?]
```

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.4](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by dordsor21** [comment]
update

**Comment by jewome62** [comment]
@dordsor21 You can reopen, same on build 515
https://athion.net/ISPaster/paste/view/5fb731841b984f2497ab5369602efd6a

**Comment by dordsor21** [comment]
Fixed now

**Comment by jewome62** [comment]
@dordsor21 
Build 516 : Same behavious but stack trace change 
https://athion.net/ISPaster/paste/view/a8ed7bd4158f402e8f3551f69202caec

```
[19:10:21 INFO]: Nortu98 issued server command: //paste
[19:10:22 ERROR]: An unexpected error while handling a WorldEdit command
java.lang.UnsupportedOperationException: This class is immutable.
        at com.sk89q.worldedit.world.block.BaseBlock.setNbtData(BaseBlock.java:167) ~[?:?]
        at com.boydti.fawe.object.extent.StripNBTExtent.stripBlockNBT(StripNBTExtent.java:63) ~[?:?]
        at com.boydti.fawe.object.extent.StripNBTExtent.setBlock(StripNBTExtent.java:41) ~[?:?]
        at com.sk89q.worldedit.EditSession.setBlock(EditSession.java:930) ~[?:?]
        at com.sk89q.worldedit.extent.clipboard.Clipboard.paste(Clipboard.java:340) ~[?:?]
        at com.sk89q.worldedit.command.ClipboardCommands.place(ClipboardCommands.java:480) ~[?:?]
        at com.sk89q.worldedit.command.ClipboardCommands.paste(ClipboardCommands.java:403) ~[?:?]
        at com.sk89q.worldedit.command.ClipboardCommandsRegistration.cmd$_paste(ClipboardCommandsRegistration.java:333) ~[?:?]
        at org.enginehub.piston.CommandManager.execute(CommandManager.java:157) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommandOnCurrentThread$16(PlatformCommandManager.java:693) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandTask(PlatformCommandManager.java:709) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandOnCurrentThread(PlatformCommandManager.java:695) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$null$13(PlatformCommandManager.java:665) ~[?:?]
        at com.sk89q.worldedit.extension.platform.AbstractPlayerActor.lambda$runAction$1(AbstractPlayerActor.java:697) ~[?:?]
        at com.boydti.fawe.object.task.AsyncNotifyQueue.lambda$run$0(AsyncNotifyQueue.java:27) ~[?:?]
        at com.boydti.fawe.object.task.AsyncNotifyQueue.lambda$call$1(AsyncNotifyQueue.java:44) ~[?:?]
        at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1448) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?]
```

**Comment by jewome62** [comment]
That's work on build 517
