### ISSUE TITLE
Lighting Issue

### ISSUE THREAD

**Issue by jewome62** [IntellectualSites/FastAsyncWorldEdit#857]
**/fawe debugpaste**: https://athion.net/ISPaster/paste/view/6d785daa2ddc43bcb9f18ba926461913

**Required Information**
- FAWE Version Number (`/version FastAsyncWorldEdit`):   1.16-560;6895fe3   
- Spigot/Paper Version Number (`/version`):  git-Paper-355 (MC: 1.16.4)
- Minecraft Version: [e.g. 1.16.4]   1.16.4

**Describe the bug**
Replace air by other blocks (with air under selection) cause lighting bug and stacktrace
![image](https://user-images.githubusercontent.com/472429/104818499-500e9080-5828-11eb-9115-9bcf54d3074c.png)

```
[18:20:48 INFO]: White_Invader issued server command: //re 0 1:3
[18:20:56 INFO]: White_Invader issued server command: //undo
[18:20:56 WARN]: java.lang.NullPointerException
[18:20:56 WARN]:        at com.boydti.fawe.beta.implementation.blocks.CharBlocks$Section.get(CharBlocks.java:165)
[18:20:56 WARN]:        at com.boydti.fawe.beta.implementation.blocks.CharBlocks.get(CharBlocks.java:131)
[18:20:56 WARN]:        at com.boydti.fawe.beta.implementation.blocks.CharGetBlocks.getFullBlock(CharGetBlocks.java:15)
[18:20:56 WARN]:        at com.sk89q.worldedit.extent.InputExtent.getOpacity(InputExtent.java:158)
[18:20:56 WARN]:        at com.boydti.fawe.beta.implementation.chunk.ChunkHolder$1.getOpacity(ChunkHolder.java:281)
[18:20:56 WARN]:        at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.getOpacity(ChunkHolder.java:1031)
[18:20:56 WARN]:        at com.boydti.fawe.beta.implementation.lighting.NMSRelighter.smoothSkyLight(NMSRelighter.java:1134)
[18:20:56 WARN]:        at com.boydti.fawe.beta.implementation.lighting.NMSRelighter.fixSkyLighting(NMSRelighter.java:1102)
[18:20:56 WARN]:        at com.boydti.fawe.beta.implementation.lighting.NMSRelighter.fixSkyLighting(NMSRelighter.java:913)
[18:20:56 WARN]:        at com.boydti.fawe.beta.implementation.lighting.NMSRelighter.fixLightingSafe(NMSRelighter.java:790)
[18:20:56 WARN]:        at com.boydti.fawe.beta.implementation.lighting.NMSRelighter.removeAndRelight(NMSRelighter.java:110)
[18:20:56 WARN]:        at com.sk89q.worldedit.EditSession.flushQueue(EditSession.java:1105)
[18:20:56 WARN]:        at com.sk89q.worldedit.EditSession.setBlocks(EditSession.java:1026)
[18:20:56 WARN]:        at com.sk89q.worldedit.LocalSession.undo(LocalSession.java:578)
[18:20:56 WARN]:        at com.sk89q.worldedit.command.HistoryCommands.undo(HistoryCommands.java:86)
[18:20:56 WARN]:        at com.sk89q.worldedit.command.HistoryCommandsRegistration.cmd$undo(HistoryCommandsRegistration.java:146)
[18:20:56 WARN]:        at org.enginehub.piston.CommandManager.execute(CommandManager.java:157)
[18:20:56 WARN]:        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommandOnCurrentThread$16(PlatformCommandManager.java:693)
[18:20:56 WARN]:        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandTask(PlatformCommandManager.java:709)
[18:20:56 WARN]:        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandOnCurrentThread(PlatformCommandManager.java:695)
[18:20:56 WARN]:        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$null$13(PlatformCommandManager.java:665)
[18:20:56 WARN]:        at com.sk89q.worldedit.extension.platform.AbstractPlayerActor.lambda$runAction$1(AbstractPlayerActor.java:697)
[18:20:56 WARN]:        at com.boydti.fawe.object.task.AsyncNotifyQueue.lambda$run$0(AsyncNotifyQueue.java:27)
[18:20:56 WARN]:        at com.boydti.fawe.object.task.AsyncNotifyQueue.lambda$call$1(AsyncNotifyQueue.java:44)
[18:20:56 WARN]:        at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1448)
[18:20:56 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[18:20:56 WARN]:        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
[18:20:56 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
[18:20:56 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
[18:20:56 WARN]:        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

```
**To Reproduce**
1. Select region with pos1 pos2 with air under
2. replace air by block
3. see lighting bug and stacktrace

**Plugins being used on the server**
`Plugins (43): AdvancedPortals, AdvancedTeleport, AntiAFK*, Arceon, ArmorStandTools, BKCommonLib, BlocksHub, Bruhshes, Builders-Utilities, BungeeTabListPlus, CoreProtect, CreativeNbtControl, DisableJoinMessage*, DKBans, DKBansConsoleCommandExtension, FastAsyncWorldEdit (WorldEdit), FlySpeed*, ForceField*, ForceGameMode*, goBrush, goPaint, HackedCore*, HackedServer*, HeadDatabase, ImageOnMap, LuckPerms, Multiverse-Core, NoDamage, PacketListenerApi*, PermBridge*, PlaceholderAPI, PremiumVanish, ProtocolLib, Skript, spark, SpawnJoin*, TpSpawnQuit*, Vault, ViewDistanceTweaks, VIPJoinSlots*, VoidGenerator, WorldBorder, WorldGuard`

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.4](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by arturek1666** [comment]
The issue still shows in:
FastAsyncWorldEdit-1.16-626.jar
Mobs not getting damage on sunlight :) 
And when using worldedit just like he explained still shows.
