### ISSUE TITLE
Error when using //copy

### ISSUE THREAD

**Issue by Thomas-Lecuppre** [IntellectualSites/FastAsyncWorldEdit#886]
As the chat say :
(FAWE) Please report this error : [See console]
(FAWE) java.lang.NullPointerException : null

And the console say :

[20:36:01] [Server thread/INFO]: MeuhSly_ issued server command: //copy
[20:36:01] [ForkJoinPool-9-worker-2/ERROR]: An unexpected error while handling a WorldEdit command
java.lang.NullPointerException: null
at com.sk89q.worldedit.bukkit.BukkitWorld.get(BukkitWorld.java:557) ~[?:?]
at com.sk89q.worldedit.bukkit.BukkitWorld.get(BukkitWorld.java:79) ~[?:?]
at com.boydti.fawe.beta.implementation.cache.ChunkCache.newChunk(ChunkCache.java:43) ~[?:?]
at com.boydti.fawe.beta.implementation.cache.ChunkCache.get(ChunkCache.java:37) ~[?:?]
at com.boydti.fawe.beta.implementation.cache.ChunkCache.get(ChunkCache.java:12) ~[?:?]
at com.boydti.fawe.beta.implementation.queue.SingleThreadQueueExtent.getCachedGet(SingleThreadQueueExtent.java:88) ~[?:?]
at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.newWrappedGet(ChunkHolder.java:894) ~[?:?]
at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.getOrCreateGet(ChunkHolder.java:864) ~[?:?]
at com.boydti.fawe.beta.implementation.chunk.ChunkHolder$4.getFullBlock(ChunkHolder.java:674) ~[?:?]
at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.getFullBlock(ChunkHolder.java:979) ~[?:?]
at com.boydti.fawe.beta.implementation.IChunkExtent.getFullBlock(IChunkExtent.java:71) ~[?:?]
at com.sk89q.worldedit.extent.InputExtent.getFullBlock(InputExtent.java:67) ~[?:?]
at com.sk89q.worldedit.extent.PassthroughExtent.getFullBlock(PassthroughExtent.java:185) ~[?:?]
at com.sk89q.worldedit.extent.PassthroughExtent.getFullBlock(PassthroughExtent.java:185) ~[?:?]
at com.boydti.fawe.object.function.block.SimpleBlockCopy.apply(SimpleBlockCopy.java:20) ~[?:?]
at com.sk89q.worldedit.function.visitor.RegionVisitor.resume(RegionVisitor.java:66) ~[?:?]
at com.sk89q.worldedit.function.operation.Operations.completeBlindly(Operations.java:76) ~[?:?]
at com.sk89q.worldedit.function.operation.ForwardExtentCopy.resume(ForwardExtentCopy.java:396) ~[?:?]
at com.sk89q.worldedit.function.operation.Operations.completeLegacy(Operations.java:57) ~[?:?]
at com.sk89q.worldedit.command.ClipboardCommands.copy(ClipboardCommands.java:166) ~[?:?]
at com.sk89q.worldedit.command.ClipboardCommandsRegistration.cmd$_copy(ClipboardCommandsRegistration.java:273) ~[?:?]
at org.enginehub.piston.CommandManager.execute(CommandManager.java:157) ~[?:?]
at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommandOnCurrentThread$16(PlatformCommandManager.java:693) ~[?:?]
at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandTask(PlatformCommandManager.java:709) ~[?:?]
at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandOnCurrentThread(PlatformCommandManager.java:695) ~[?:?]
at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$null$13(PlatformCommandManager.java:665) ~[?:?]
at com.sk89q.worldedit.extension.platform.AbstractPlayerActor.lambda$runAction$1(AbstractPlayerActor.java:697) ~[?:?]
at com.boydti.fawe.object.task.AsyncNotifyQueue.lambda$run$0(AsyncNotifyQueue.java:27) ~[?:?]
at com.boydti.fawe.object.task.AsyncNotifyQueue.lambda$call$1(AsyncNotifyQueue.java:44) ~[?:?]
at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424) [?:1.8.0_252]
at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_252]
at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_252]
at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_252]
at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_252]

Thank's

**Comment by NotMyFault** [comment]
Don't delete the template.

**Comment by Thomas-Lecuppre** [comment]
I have deleted nothing, I put it on my server, launch it, and that's all.

**Comment by NotMyFault** [comment]
> I have deleted nothing, I put it on my server, launch it, and that's all.

Yes, you have deleted the entire issue template. That is not up for debate. Read the issue template and fill it out allowing us to look into your issue properly.
