### ISSUE TITLE
Commands do not work - java.lang.IllegalArgumentException: The handle can not be null

### ISSUE THREAD

**Issue by Vilican** [IntellectualSites/FastAsyncWorldEdit#889]
**[REQUIRED] FastAsyncWorldEdit Configuration Files** 

**/fawe debugpaste**: https://athion.net/ISPaster/paste/view/25ac41ded4644cb49d873f4b57387e71

**Required Information**
- FAWE Version Number (`/version FastAsyncWorldEdit`): version 1.16-586;bfc37f1
- Spigot/Paper Version Number (`/version`): This server is running CraftBukkit version 2991-Spigot-018b9a0-f3f3094 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
- Minecraft Version: [e.g. 1.16.5]: 1.16.5

**Describe the bug**
After doing //set command, nothing happens and this is logged:

```
[14:50:14] [Server thread/INFO]: Vilican issued server command: //set air
[14:50:15] [pool-146-thread-3/WARN]: java.lang.IllegalArgumentException: The handle can not be null
[14:50:15] [pool-146-thread-3/WARN]: 	at com.bergerkiller.bukkit.common.wrappers.BasicWrapper.setHandle(BasicWrapper.java:21)
[14:50:15] [pool-146-thread-3/WARN]: 	at com.bergerkiller.bukkit.common.wrappers.LongHashSet.<init>(LongHashSet.java:24)
[14:50:15] [pool-146-thread-3/WARN]: 	at com.bergerkiller.bukkit.lightcleaner.lighting.LightingAutoClean.schedule(LightingAutoClean.java:77)
[14:50:15] [pool-146-thread-3/WARN]: 	at com.bergerkiller.bukkit.lightcleaner.impl.FastAsyncWorldEditHandler$1.processSet(FastAsyncWorldEditHandler.java:53)
[14:50:15] [pool-146-thread-3/WARN]: 	at com.boydti.fawe.beta.implementation.processors.MultiBatchProcessor.processSet(MultiBatchProcessor.java:117)
[14:50:15] [pool-146-thread-3/WARN]: 	at com.boydti.fawe.beta.implementation.processors.MultiBatchProcessor.processSet(MultiBatchProcessor.java:97)
[14:50:15] [pool-146-thread-3/WARN]: 	at com.boydti.fawe.beta.implementation.processors.BatchProcessorHolder.processSet(BatchProcessorHolder.java:26)
[14:50:15] [pool-146-thread-3/WARN]: 	at com.boydti.fawe.beta.implementation.processors.BatchProcessorHolder.processSet(BatchProcessorHolder.java:26)
[14:50:15] [pool-146-thread-3/WARN]: 	at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.call(ChunkHolder.java:928)
[14:50:15] [pool-146-thread-3/WARN]: 	at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.call(ChunkHolder.java:916)
[14:50:15] [pool-146-thread-3/WARN]: 	at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.call(ChunkHolder.java:33)
[14:50:15] [pool-146-thread-3/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[14:50:15] [pool-146-thread-3/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[14:50:15] [pool-146-thread-3/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[14:50:15] [pool-146-thread-3/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[14:50:15] [pool-146-thread-3/WARN]: java.lang.IllegalArgumentException: The handle can not be null
[14:50:15] [pool-146-thread-3/WARN]: 	at com.bergerkiller.bukkit.common.wrappers.BasicWrapper.setHandle(BasicWrapper.java:21)
[14:50:15] [pool-146-thread-3/WARN]: 	at com.bergerkiller.bukkit.common.wrappers.LongHashSet.<init>(LongHashSet.java:24)
[14:50:15] [pool-146-thread-3/WARN]: 	at com.bergerkiller.bukkit.lightcleaner.lighting.LightingAutoClean.schedule(LightingAutoClean.java:77)
[14:50:15] [pool-146-thread-3/WARN]: 	at com.bergerkiller.bukkit.lightcleaner.impl.FastAsyncWorldEditHandler$1.processSet(FastAsyncWorldEditHandler.java:53)
[14:50:15] [pool-146-thread-3/WARN]: 	at com.boydti.fawe.beta.implementation.processors.MultiBatchProcessor.processSet(MultiBatchProcessor.java:117)
[14:50:15] [pool-146-thread-3/WARN]: 	at com.boydti.fawe.beta.implementation.processors.MultiBatchProcessor.processSet(MultiBatchProcessor.java:97)
[14:50:15] [pool-146-thread-3/WARN]: 	at com.boydti.fawe.beta.implementation.processors.BatchProcessorHolder.processSet(BatchProcessorHolder.java:26)
[14:50:15] [pool-146-thread-3/WARN]: 	at com.boydti.fawe.beta.implementation.processors.BatchProcessorHolder.processSet(BatchProcessorHolder.java:26)
[14:50:15] [pool-146-thread-3/WARN]: 	at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.call(ChunkHolder.java:928)
[14:50:15] [pool-146-thread-3/WARN]: 	at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.call(ChunkHolder.java:916)
[14:50:15] [pool-146-thread-3/WARN]: 	at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.call(ChunkHolder.java:33)
[14:50:15] [pool-146-thread-3/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[14:50:15] [pool-146-thread-3/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[14:50:15] [pool-146-thread-3/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[14:50:15] [pool-146-thread-3/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[14:50:15] [ForkJoinPool-7-worker-1/WARN]: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: The handle can not be null
[14:50:15] [ForkJoinPool-7-worker-1/WARN]: 	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
[14:50:15] [ForkJoinPool-7-worker-1/WARN]: 	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
[14:50:15] [ForkJoinPool-7-worker-1/WARN]: 	at com.boydti.fawe.beta.implementation.queue.SingleThreadQueueExtent.pollSubmissions(SingleThreadQueueExtent.java:302)
[14:50:15] [ForkJoinPool-7-worker-1/WARN]: 	at com.boydti.fawe.beta.implementation.queue.SingleThreadQueueExtent.flush(SingleThreadQueueExtent.java:385)
[14:50:15] [ForkJoinPool-7-worker-1/WARN]: 	at com.boydti.fawe.beta.IQueueExtent.commit(IQueueExtent.java:112)
[14:50:15] [ForkJoinPool-7-worker-1/WARN]: 	at com.sk89q.worldedit.extent.PassthroughExtent.commit(PassthroughExtent.java:207)
[14:50:15] [ForkJoinPool-7-worker-1/WARN]: 	at com.sk89q.worldedit.extent.PassthroughExtent.commit(PassthroughExtent.java:207)
[14:50:15] [ForkJoinPool-7-worker-1/WARN]: 	at com.sk89q.worldedit.EditSession.flushQueue(EditSession.java:1082)
[14:50:15] [ForkJoinPool-7-worker-1/WARN]: 	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandTask(PlatformCommandManager.java:760)
[14:50:15] [ForkJoinPool-7-worker-1/WARN]: 	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandOnCurrentThread(PlatformCommandManager.java:695)
[14:50:15] [ForkJoinPool-7-worker-1/WARN]: 	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$null$13(PlatformCommandManager.java:665)
[14:50:15] [ForkJoinPool-7-worker-1/WARN]: 	at com.sk89q.worldedit.extension.platform.AbstractPlayerActor.lambda$runAction$1(AbstractPlayerActor.java:697)
[14:50:15] [ForkJoinPool-7-worker-1/WARN]: 	at com.boydti.fawe.object.task.AsyncNotifyQueue.lambda$run$0(AsyncNotifyQueue.java:27)
[14:50:15] [ForkJoinPool-7-worker-1/WARN]: 	at com.boydti.fawe.object.task.AsyncNotifyQueue.lambda$call$1(AsyncNotifyQueue.java:44)
[14:50:15] [ForkJoinPool-7-worker-1/WARN]: 	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
[14:50:15] [ForkJoinPool-7-worker-1/WARN]: 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[14:50:15] [ForkJoinPool-7-worker-1/WARN]: 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[14:50:15] [ForkJoinPool-7-worker-1/WARN]: 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[14:50:15] [ForkJoinPool-7-worker-1/WARN]: 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
[14:50:15] [ForkJoinPool-7-worker-1/WARN]: Caused by: java.lang.IllegalArgumentException: The handle can not be null
[14:50:15] [ForkJoinPool-7-worker-1/WARN]: 	at com.bergerkiller.bukkit.common.wrappers.BasicWrapper.setHandle(BasicWrapper.java:21)
[14:50:15] [ForkJoinPool-7-worker-1/WARN]: 	at com.bergerkiller.bukkit.common.wrappers.LongHashSet.<init>(LongHashSet.java:24)
[14:50:15] [ForkJoinPool-7-worker-1/WARN]: 	at com.bergerkiller.bukkit.lightcleaner.lighting.LightingAutoClean.schedule(LightingAutoClean.java:77)
[14:50:15] [ForkJoinPool-7-worker-1/WARN]: 	at com.bergerkiller.bukkit.lightcleaner.impl.FastAsyncWorldEditHandler$1.processSet(FastAsyncWorldEditHandler.java:53)
[14:50:15] [ForkJoinPool-7-worker-1/WARN]: 	at com.boydti.fawe.beta.implementation.processors.MultiBatchProcessor.processSet(MultiBatchProcessor.java:117)
[14:50:15] [ForkJoinPool-7-worker-1/WARN]: 	at com.boydti.fawe.beta.implementation.processors.MultiBatchProcessor.processSet(MultiBatchProcessor.java:97)
[14:50:15] [ForkJoinPool-7-worker-1/WARN]: 	at com.boydti.fawe.beta.implementation.processors.BatchProcessorHolder.processSet(BatchProcessorHolder.java:26)
[14:50:15] [ForkJoinPool-7-worker-1/WARN]: 	at com.boydti.fawe.beta.implementation.processors.BatchProcessorHolder.processSet(BatchProcessorHolder.java:26)
[14:50:15] [ForkJoinPool-7-worker-1/WARN]: 	at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.call(ChunkHolder.java:928)
[14:50:15] [ForkJoinPool-7-worker-1/WARN]: 	at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.call(ChunkHolder.java:916)
[14:50:15] [ForkJoinPool-7-worker-1/WARN]: 	at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.call(ChunkHolder.java:33)
[14:50:15] [ForkJoinPool-7-worker-1/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[14:50:15] [ForkJoinPool-7-worker-1/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[14:50:15] [ForkJoinPool-7-worker-1/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[14:50:15] [ForkJoinPool-7-worker-1/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```

**To Reproduce**
1. Select blocks with a wand
2. Do //set air
3. Error is logged

**Plugins being used on the server**
MySQLWhitelist, ColoredSigns, QuickSleep, FastChunkPregenerator, LoginSecurity, Websend, PlaceholderAPI, WhoIs, NametagEdit, InfiniteDispenserX, ProtocolLib, DeathMessagesPrime, AdvancedPortals, SkinsRestorer, HubThat, Maintenance, PermissionsEx, RandomTeleport, PexTabCompleter, ServerRestorer, Vault, MyCommand, ConsoleChat, dynmap, Essentials, BKCommonLib, HolographicDisplays, SuperLobby, FastAsyncWorldEdit (WorldEdit), Parkour, WorldGuard, WorldGuardExtraFlags, Dynmap-WorldGuard, ActionHealth, Skywars, BedWars, MobArena, LightCleaner, CommandSigns, Multiverse-Core, Multiverse-Inventories, BentoBox, Multiverse-NetherPortals, Multiverse-Portals

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.5](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by LaurenceBarnes** [comment]
What version of Light Cleaner/BKCommonLib are you using?

**Comment by NotMyFault** [comment]
Not a Fawe issue.

**Comment by bergerkiller** [comment]
I'll look at it

**Comment by bergerkiller** [comment]
Continue here: https://github.com/bergerhealer/Light-Cleaner/issues/42
I need more information
