### ISSUE TITLE
//copy error 

### ISSUE THREAD

**Issue by cmuagab** [IntellectualSites/FastAsyncWorldEdit#895]
**/fawe debugpaste**: https://athion.net/ISPaster/paste/view/38d969ae7a214fa9a3522eeb5ebd7963

**Required Information**
- FAWE Version Number: 1.16-590;a49ebb4     
- Spigot/Paper Version Number (`/version`):  1.16.4-R0.1-SNAPSHOT   
- Minecraft Version: 1.16.4   

**Describe the bug**
NPE on command //copy
`[20:19:03] [ForkJoinPool-7-worker-0/ERROR]: An unexpected error while handling a WorldEdit command
java.lang.NullPointerException: null
        at com.sk89q.worldedit.bukkit.BukkitWorld.get(BukkitWorld.java:557) ~[?:?]
        at com.sk89q.worldedit.bukkit.BukkitWorld.get(BukkitWorld.java:79) ~[?:?]
        at com.boydti.fawe.beta.implementation.cache.ChunkCache.newChunk(ChunkCache.java:43) ~[?:?]
        at com.boydti.fawe.beta.implementation.cache.ChunkCache.get(ChunkCache.java:37) ~[?:?]
        at com.boydti.fawe.beta.implementation.cache.ChunkCache.get(ChunkCache.java:12) ~[?:?]
        at com.boydti.fawe.beta.implementation.queue.SingleThreadQueueExtent.getCachedGet(SingleThreadQueueExtent.java:88) ~[?:?]
        at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.newWrappedGet(ChunkHolder.java:894) ~[?:?]
        at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.getOrCreateGet(ChunkHolder.java:864) ~[?:?]
        at com.boydti.fawe.beta.implementation.chunk.ChunkHolder$4.getFullBlock(ChunkHolder.java:674) ~[?:?]
        at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.getFullBlock(ChunkHolder.java:979) ~[?:?]
        at com.boydti.fawe.beta.implementation.IChunkExtent.getFullBlock(IChunkExtent.java:71) ~[?:?]
        at com.sk89q.worldedit.extent.InputExtent.getFullBlock(InputExtent.java:67) ~[?:?]
        at com.sk89q.worldedit.extent.PassthroughExtent.getFullBlock(PassthroughExtent.java:185) ~[?:?]
        at com.sk89q.worldedit.extent.PassthroughExtent.getFullBlock(PassthroughExtent.java:185) ~[?:?]
        at com.boydti.fawe.object.function.block.SimpleBlockCopy.apply(SimpleBlockCopy.java:20) ~[?:?]
        at com.sk89q.worldedit.function.visitor.RegionVisitor.resume(RegionVisitor.java:66) ~[?:?]
        at com.sk89q.worldedit.function.operation.Operations.completeBlindly(Operations.java:76) ~[?:?]
        at com.sk89q.worldedit.function.operation.ForwardExtentCopy.resume(ForwardExtentCopy.java:396) ~[?:?]
        at com.sk89q.worldedit.function.operation.Operations.completeLegacy(Operations.java:57) ~[?:?]
        at com.sk89q.worldedit.command.ClipboardCommands.copy(ClipboardCommands.java:166) ~[?:?]
        at com.sk89q.worldedit.command.ClipboardCommandsRegistration.cmd$_copy(ClipboardCommandsRegistration.java:273) ~[?:?]
        at org.enginehub.piston.CommandManager.execute(CommandManager.java:157) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommandOnCurrentThread$16(PlatformCommandManager.java:693) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandTask(PlatformCommandManager.java:709) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandOnCurrentThread(PlatformCommandManager.java:695) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$null$13(PlatformCommandManager.java:665) ~[?:?]
        at com.sk89q.worldedit.extension.platform.AbstractPlayerActor.lambda$runAction$1(AbstractPlayerActor.java:697) ~[?:?]
        at com.boydti.fawe.object.task.AsyncNotifyQueue.lambda$run$0(AsyncNotifyQueue.java:27) ~[?:?]
        at com.boydti.fawe.object.task.AsyncNotifyQueue.lambda$call$1(AsyncNotifyQueue.java:44) ~[?:?]
        at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424) [?:1.8.0_275]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_275]
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_275]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_275]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175) [?:1.8.0_275]
`

**To Reproduce**
After selecting two point, run //copu

**Plugins being used on the server**
Only ViaVersion & ProtocolLib

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.5](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- X[] I made sure the bug/error is not caused by any other plugin

**Comment by aurorasmiles** [comment]
1.16.4 is not supported with your version, please upgrade to 1.16.5
