### ISSUE TITLE
fawe explodes when symlinks are used (linux)

### ISSUE THREAD

**Issue by TauCubed** [IntellectualSites/FastAsyncWorldEdit#968]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

FAWE fails to list all schematics when a symlink is present in the FastAsyncWorldEdit schematics folder.

### To Reproduce

Create symbolic link pointing to some other folder within schematics (~/common/schematics --> ../someserver/plugins/FastAsyncWorldEdit/schematics/com)
run the in-game command: /schematic list

### Expected behaviour

FAWE would follow symlinks or at the very least not prevent me from seeing other schematics in the folder because of a symlink merely existing.

### Screenshots / Videos

https://i.imgur.com/DaQrPVb.png
https://i.imgur.com/ids9utw.png

### Error log (if applicable)

https://haste.athion.net/okugurivit.bash

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/29c74ae0b44c4aafa5a7102fd313a83f

### Fawe Version

FAWE version:  - Date Mar 12, 2021, 12:00:00 AM  - Commit f9b89cbb  - Build 621

This is definitely a FAWE issue as (normal) worldedit handles the symlinks properly: https://i.imgur.com/ids9utw.png

**Comment by ian-otto** [comment]
+1 I am also experiencing this issue.

It seems to be related to (I'm assuming?) a security feature implemented [here](https://github.com/IntellectualSites/FastAsyncWorldEdit/blob/8b69d8a8e2eee74df81beb21cc0d8b250582d0c7/worldedit-core/src/main/java/com/sk89q/worldedit/command/UtilityCommands.java#L800) which prevents the user from escaping the plugin schematic folder. [Implementation of the subdirectory check here](https://github.com/IntellectualSites/FastAsyncWorldEdit/blob/8b69d8a8e2eee74df81beb21cc0d8b250582d0c7/worldedit-core/src/main/java/com/boydti/fawe/util/MainUtil.java#L706)

Stacktrace when running /schem list:
```
[18:53:26 ERROR]: An unexpected error while handling a WorldEdit command
java.lang.RuntimeException: org.enginehub.piston.exception.StopExecutionException: Invalid path
        at com.sk89q.worldedit.command.UtilityCommands.lambda$entryToComponent$3(UtilityCommands.java:802) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
        at com.sk89q.worldedit.command.UtilityCommands.entryToComponent(UtilityCommands.java:813) ~[?:?]
        at com.sk89q.worldedit.command.SchematicCommands.list(SchematicCommands.java:537) ~[?:?]
        at com.sk89q.worldedit.command.SchematicCommandsRegistration.cmd$list(SchematicCommandsRegistration.java:322) ~[?:?]
        at org.enginehub.piston.CommandManager.execute(CommandManager.java:157) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommandOnCurrentThread$16(PlatformCommandManager.java:693) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandTask(PlatformCommandManager.java:709) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandOnCurrentThread(PlatformCommandManager.java:695) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$null$13(PlatformCommandManager.java:665) ~[?:?]
```

**Comment by anonyco** [comment]
**Proposal:**

I propose that FAWE searches a per-user directory for schematics (in addition to its local config folder): `~/.config/FastAsyncWorldEdit/schematics`

FAWE will still default to saving schematics in its present local config folder. If FAWE's the local config folder doesn't have a schematics folder but the per-user directory exists, then FAWE will save its schematics in the per-user directory.

I know this isn't perfect but it'll be easy to implement and a lot better than the behavior we have now.
